infiniflow/ragflow

api/apps/conversation_app.py
api/apps/llm_app.py
api/db/services/__init__.py
docs/CONTRIBUTING.md

fix set_api_key bug

---

README.md
README_zh.md

Issue link:#[[Link the issue here](https://github.com/infiniflow/ragflow/issues/190)]

for issue https://github.com/infiniflow/ragflow/issues/190

---

web/src/global.ts
web/src/hooks/loginHooks.ts
web/src/locales/config.ts
web/src/locales/en.json
web/src/locales/zh.json
web/src/pages/add-knowledge/components/knowledge-dataset/knowledge-upload-file/index.less
web/src/pages/add-knowledge/components/knowledge-dataset/knowledge-upload-file/index.tsx
web/src/pages/login/index.tsx

feat: enlarge the size of the next button for uploading files
feat: add locale config to global.ts

feat: enlarge the size of the next button for uploading files and add locale config to global.ts

---

deepdoc/parser/excel_parser.py
rag/app/manual.py
rag/app/one.py
rag/app/table.py

Issue link:#[[Link the issue here](https://github.com/infiniflow/ragflow/issues/196)]

To avoid assertion while no rows in excel

---

rag/svr/task_broker.py

Issue link:#[[Link the issue here](https://github.com/infiniflow/ragflow/issues/198)]

Let task continue dispaching while meeting unexpected doc formats

---

api/apps/chunk_app.py
api/db/services/knowledgebase_service.py
rag/app/manual.py
rag/app/qa.py
rag/nlp/query.py

Issue link:#[[Link the issue here](https://github.com/infiniflow/ragflow/issues/209)]

fix bug about reload knowledgebase configuration reloading

---

web/src/components/chunk-method-modal/index.tsx
web/src/components/similarity-slider/index.tsx
web/src/hooks/commonHooks.tsx
web/src/hooks/routeHook.ts
web/src/locales/config.ts
web/src/locales/en.json
web/src/locales/zh.json
web/src/pages/add-knowledge/components/knowledge-file/index.tsx
web/src/pages/add-knowledge/components/knowledge-file/parsing-action-cell/index.tsx
web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx
web/src/pages/add-knowledge/components/knowledge-file/rename-modal/index.tsx
web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx
web/src/pages/add-knowledge/components/knowledge-setting/hooks.ts
web/src/pages/add-knowledge/components/knowledge-setting/index.tsx
web/src/pages/add-knowledge/components/knowledge-sidebar/index.tsx
web/src/pages/add-knowledge/components/knowledge-testing/testing-control/index.tsx
web/src/pages/add-knowledge/components/knowledge-testing/testing-result/index.tsx
web/src/pages/add-knowledge/index.tsx
web/src/pages/knowledge/knowledge-card/index.tsx

fix: #209 after saving the knowledge base configuration, jump to the dataset page
feat: translate ConfigurationForm
feat: translate KnowledgeTesting
feat: translate document list page
feat: translate knowledge list page
Issue link: #209
- [ x ] Bug Fix (non-breaking change which fixes an issue)

fix: #209 after saving the knowledge base configuration, jump to the dataset page

---

api/db/services/knowledgebase_service.py

fix KB config reload bug

---

web/src/components/chunk-method-modal/index.tsx

…k token number needs to be displayed. #217
For any type of file, if the parsing method is general, the chunk token number needs to be displayed. #217
Issue link: #217

For any type of file, if the parsing method is general, the chunk token number needs to be displayed. #217

---

README_zh.md

doc: fix typo

---

README.md
README_ja.md
README_zh.md

I created Japanese translated README.

docs: Add Japanese README

---

README.md
README_ja.md
README_zh.md

Fix broken link of discord invitation
Issue link:#227

Fix broken link of discord invitation

---

README_zh.md

use `docker compose up -f docker-compose-CN.yml -d`
will cause
update to `docker compose -f docker-compose-CN.yaml up -d`
Issue link:None

docs: fix a bash command

---

api/apps/document_app.py
api/apps/user_app.py
api/db/init_data.py
api/settings.py
docker/docker-compose-CN.yml
docker/docker-compose-base.yml
docker/docker-compose.yml
docker/entrypoint.sh
docker/service_conf.yaml
rag/app/naive.py
rag/app/table.py
rag/llm/chat_model.py
rag/nlp/__init__.py
rag/nlp/search.py

Issue link:#[[Link the issue here](https://github.com/infiniflow/ragflow/issues/226)]

fix docker compose issue

---

api/db/init_data.py

Issue link:#[[Link the issue here](https://github.com/infiniflow/ragflow/issues/242)]

fix bug about field misspell

---

api/apps/user_app.py

fix user registration issue

---

web/src/app.tsx
web/src/layouts/components/header/index.tsx
web/src/locales/en.ts
web/src/locales/zh.ts
web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx
web/src/pages/add-knowledge/index.tsx
web/src/pages/chat/index.tsx
web/src/pages/user-setting/model.ts

Fixed an issue where refreshing the login page caused the language settings to become invalid.
Issue link: #249

Fixed an issue where refreshing the login page caused the language settings to become invalid.  #249

---

README.md
README_ja.md
README_zh.md
api/apps/conversation_app.py
api/apps/document_app.py
api/apps/llm_app.py
api/apps/user_app.py
api/db/init_data.py
docker/docker-compose-CN.yml
docs/ollama.md
rag/llm/__init__.py
rag/llm/chat_model.py
rag/llm/cv_model.py
rag/llm/embedding_model.py
rag/svr/task_executor.py

Support Ollama

---

README.md
README_ja.md
README_zh.md
api/apps/conversation_app.py

Support new feature about Ollama

---

README.md
README_ja.md
README_zh.md
docs/ollama.md

Refine Ollama docs

---

rag/llm/chat_model.py

remove presence_penalty for chatglm

---

api/settings.py

set database logger level

---

web/src/locales/en.ts
web/src/locales/zh.ts
web/src/pages/login/index.less
web/src/pages/user-setting/setting-model/ollama-modal/index.tsx

add ollama.md link to OllamaModal
Issue link:#221

feat: add ollama.md link to OllamaModal

---

api/apps/conversation_app.py
rag/llm/chat_model.py
rag/nlp/query.py

resolve issure to call ZH?IPUAI

---

web/src/hooks/chatHooks.ts
web/src/locales/en.ts
web/src/locales/zh.ts
web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
web/src/pages/chat/hooks.ts
web/src/pages/chat/index.tsx
web/src/pages/chat/model.ts

historical chats appear in the new user's chat box
Issue link:#256

fix: historical chats appear in the new user's chat box #256

---

rag/nlp/query.py
rag/svr/task_executor.py
rag/utils/minio_conn.py

fix #258 task_executor occupy cpu too much

---

rag/app/laws.py

continue add layout model for 'laws'

---

rag/nlp/__init__.py

fix es exception

---

api/db/db_models.py
web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx

Update default language to English

Update default language to English

---

README.md
README_ja.md
README_zh.md
api/db/db_models.py
api/settings.py
api/utils/log_utils.py
rag/app/book.py
rag/app/laws.py
rag/llm/chat_model.py

refine log format

---

api/apps/conversation_app.py

fix bug #314

---

docs/xinference.md
rag/llm/cv_model.py

Support Xinference

---

api/db/services/llm_service.py

fix wrong log printting

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/chat/chat-configuration-modal/prompt-engine.tsx
web/src/pages/chat/index.tsx

Show original text source in conversation messages
Issue link: #337

feat: add quote item to PromptEngine

---

api/apps/chunk_app.py
api/apps/conversation_app.py

add quota config in dialog conf

---

README.md
docs/faq.md

Updated README and FAQ

---

api/apps/__init__.py

issue 341_Update __init__.py

---

api/apps/conversation_app.py
api/db/init_data.py

add new model gpt-3-turbo

---

docker/docker-compose-CN.yml
docker/docker-compose.yml

add hf_endpoint as env variable

---

README.md
README_ja.md
README_zh.md

Fix broken discord link

---

docker/docker-compose.yml

update HF_ENDPOINT in docker-compose.yml
Issue link:#350

update HF_ENDPOINT in docker-compose.yml

---

api/apps/document_app.py

enlarge max file number per user limit

---

README.md
README_ja.md
README_zh.md
api/apps/chunk_app.py
api/apps/document_app.py
api/apps/llm_app.py
api/db/init_data.py
api/db/services/dialog_service.py
api/db/services/llm_service.py
api/db/services/task_service.py
rag/llm/__init__.py
rag/llm/embedding_model.py
rag/nlp/search.py
rag/svr/task_executor.py
requirements.txt

Add bce-embedding and fastembed

---

docs/faq.md

Added FAQ why document parsing gets stuck

---

README.md
README_ja.md
README_zh.md
docker/docker-compose-CN.yml
docker/docker-compose.yml

change version number in readme

---

api/apps/document_app.py
api/db/services/llm_service.py

fix bug for fasetembed

---

README.md
README_ja.md
README_zh.md
docs/faq.md

Fix document bug

---

rag/app/naive.py
rag/nlp/search.py

fix gb2312 encoding issue

---

docs/faq.md

Added FAQs

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts

feat: modify the description of qa
Issue link: #405

feat: modify the description of qa

---

rag/app/table.py
rag/utils/es_conn.py

fix bulk error for table method

---

api/apps/api_app.py
api/db/db_models.py
deepdoc/parser/pdf_parser.py
deepdoc/vision/layout_recognizer.py
deepdoc/vision/ocr.py
deepdoc/vision/recognizer.py
deepdoc/vision/table_structure_recognizer.py
rag/llm/embedding_model.py

make sure the models will not be load twice

---

deepdoc/parser/pdf_parser.py

rm page number exception for pdf parser

---

deepdoc/parser/pdf_parser.py

fix divide by zero bug

---

README.md
README_ja.md
README_zh.md
api/apps/api_app.py
api/apps/user_app.py
api/db/services/api_service.py
api/db/services/task_service.py
deepdoc/parser/excel_parser.py
rag/app/book.py
rag/app/laws.py
rag/app/naive.py
rag/app/one.py
rag/app/qa.py
rag/app/table.py
rag/nlp/__init__.py
rag/nlp/huqie.py
rag/nlp/search.py
rag/svr/task_broker.py
rag/svr/task_executor.py

Fit a lot of encodings for text file.

---

README.md
README_ja.md
README_zh.md
docs/conversation_api.md

refine docs for chat bot api.

---

README.md
README_ja.md
README_zh.md
docs/conversation_api.md

Refine conversaion docs

---

docker/docker-compose.yml

Fix duplicate ports in docker-compose

fix: 🐛 Fix duplicate ports in docker-compose

---

docs/faq.md

Adjust the structure of FAQ

---

rag/app/naive.py

parse markdown files as txt
support markdown files

feat: support markdown files

---

rag/llm/chat_model.py

fix ollama issuet push

---

rag/app/laws.py

…e alert
.doc file is not support yet, fix the regular expression ,then right message can by alert

.doc file is not support yet. fix regular expression ，then message can be alert

---

docker/.env

enlarge docker memory usage

---

docker/entrypoint.sh
rag/app/paper.py

fix bug #502

---

rag/app/book.py
rag/app/naive.py

fix bug of table in docx

---

web/src/hooks/fileManagerHooks.ts
web/src/layouts/components/header/index.tsx
web/src/pages/file-manager/action-cell/index.tsx
web/src/pages/file-manager/file-toolbar.tsx
web/src/pages/file-manager/file-upload-modal/index.tsx
web/src/pages/file-manager/folder-create-modal/index.tsx
web/src/pages/file-manager/hooks.ts
web/src/pages/file-manager/index.tsx
web/src/pages/file-manager/model.ts
web/src/services/fileManagerService.ts
web/src/utils/api.ts

feat: create folder
feat: ensure that all files in the current folder can be correctly requested after renaming the folder
#345

feat: create folder #345

---

docs/faq.md

_Add an entry in Debugging section._

Add an entry in Debugging section

---

.gitignore

Ignore temporal files to help Mac developers.
- [* ] Other (please describe):

Add .DS_Store and docker/ragflow-logs to the git ignore list

---

README.md
README_ja.md
README_zh.md

Add disk requirements on the README

Add disk requirements on the README

---

README.md
README_ja.md
README_zh.md

Added release badge

---

README.md
README_ja.md
README_zh.md

Updated badge

---

api/apps/api_app.py
api/db/services/knowledgebase_service.py
docs/conversation_api.md

Add upload file by knowledge base name API.

Add upload file by knowledge base name API.

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/question.yml
.github/ISSUE_TEMPLATE/subtask.yml
README.md
README_ja.md
README_zh.md

Updated badge link

---

api/db/init_data.py

fix youdao bug

---

api/apps/document_app.py
api/apps/file_app.py
api/apps/kb_app.py

fix rename bug

---

api/db/services/dialog_service.py
docs/conversation_api.md

make cites in conversation API configurable

---

conf/service_conf.yaml
docker/service_conf.yaml

remove default redis configuration

---

deepdoc/parser/pdf_parser.py

fix exception in pdf parser

---

docs/faq.md

Updated FAQ: Range of input length

---

rag/app/table.py
rag/utils/redis_conn.py

refine redis connection

---

api/apps/document_app.py
docker/entrypoint.sh

refine document upload

---

web/src/components/file-upload-modal/index.less
web/src/components/file-upload-modal/index.tsx
web/src/hooks/documentHooks.ts
web/src/hooks/llmHooks.ts
web/src/pages/add-knowledge/components/knowledge-file/document-toolbar.tsx
web/src/pages/add-knowledge/components/knowledge-file/hooks.ts
web/src/pages/add-knowledge/components/knowledge-file/index.tsx
web/src/pages/add-knowledge/components/knowledge-file/model.ts
web/src/pages/file-manager/model.ts
web/src/pages/user-setting/setting-model/index.less
web/src/pages/user-setting/setting-model/index.tsx
web/src/utils/commonUtil.ts
web/src/utils/documentUtils.ts

fix:  #567 use modal to upload files in the knowledge base

fix:  #567 use modal to upload files in the knowledge base

---

api/utils/file_utils.py
rag/llm/embedding_model.py

refine docker layers

---

web/src/components/chunk-method-modal/hooks.ts
web/src/components/chunk-method-modal/index.less
web/src/components/chunk-method-modal/index.tsx
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/add-knowledge/components/knowledge-file/index.less
web/src/pages/add-knowledge/components/knowledge-file/index.tsx
web/src/pages/add-knowledge/components/knowledge-file/model.ts
web/src/pages/add-knowledge/components/knowledge-file/parsing-action-cell/index.tsx
web/src/pages/chat/chat-overview-modal/index.tsx
web/src/pages/chat/index.tsx

#607
fix: omit long file names
fix: change the parsing method from tag to select
fix: replace icon for new chat
fix: change the OK button text of the Chat Bot API modal to close

fix: omit long file names

---

api/apps/dialog_app.py
api/utils/file_utils.py
rag/app/qa.py
rag/llm/chat_model.py
rag/llm/embedding_model.py

fix disable and enable llm setting in dialog

---

web/src/interfaces/database/chat.ts
web/src/pages/chat/chat-configuration-modal/index.tsx
web/src/pages/chat/chat-configuration-modal/model-setting.tsx

fix: fixed the issue that ModelSetting  could not be saved #614

fix: fixed the issue that ModelSetting  could not be saved #614

---

api/utils/file_utils.py
deepdoc/parser/pdf_parser.py
deepdoc/vision/__init__.py
rag/utils/minio_conn.py
requirements.txt

remove PyMuPDF

---

requirements.txt

This commit resolves an issue where the 'ollama' package was inadvertently omitted from the requirements.txt file. The package has now been added to ensure all dependencies are correctly installed for the project.

Fix missing 'ollama' package in requirements.txt

---

api/db/services/document_service.py
rag/svr/task_broker.py
rag/svr/task_executor.py

remove redis

---

docs/faq.md

Updated faq.md

---

web/src/hooks/documentHooks.ts
web/src/pages/add-knowledge/components/knowledge-file/hooks.ts
web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.less
web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx
web/src/pages/file-manager/index.less

fix: add spin to parsing status icon of dataset table
#648

fix: add spin to parsing status icon of dataset table

---

api/apps/file_app.py
rag/nlp/__init__.py

fix file encoding detection bug

---

README.md
README_ja.md
README_zh.md
docker/entrypoint.sh

refine doc for v0.5.0

---

rag/svr/task_executor.py
requirements.txt

remove unused dependency

---

deepdoc/parser/pdf_parser.py

fix coordinate error

---

rag/llm/embedding_model.py
rag/utils/__init__.py

truncate text to fitin embedding model

---

rag/nlp/search.py

fix disabled doc is still retreivalable

---

rag/svr/task_executor.py

let index be batchly.

---

api/apps/user_app.py

fix: typo in user_app.py

---

api/apps/document_app.py

fix bug of get file

---

api/apps/chunk_app.py
api/apps/dialog_app.py
api/apps/document_app.py
api/apps/file_app.py
api/apps/kb_app.py
api/apps/llm_app.py

Refactor method name

---

README.md
README_ja.md
README_zh.md
docs/quickstart.md

Miscellaneous updates

---

rag/svr/task_executor.py
web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx

Refactor message output format

---

api/apps/llm_app.py
api/db/init_data.py
api/db/services/llm_service.py
api/settings.py
rag/llm/__init__.py
rag/svr/task_executor.py

support gpt-4o

---

api/apps/api_app.py

api_app.py
/document/upload 
add two non mandatory parameters
parser_id: [naive,qaresume,manual,table,paper,book,laws,presentation,picture,one]
run: 1

Updated document upload method

---

api/db/services/file_service.py
api/db/services/task_service.py

fix bugs in searching file using keywords

---

rag/svr/task_executor.py

fix a string format error

---

docs/conversation_api.md

Updated conversation_api.md document/upload parameter description

Updated conversation_api.md document/upload

---

api/utils/file_utils.py
rag/app/naive.py

Support for code files parse

---

api/db/services/document_service.py

Knowledge base search is case sensitive

---

api/apps/api_app.py
api/apps/conversation_app.py
api/apps/system_app.py
api/db/services/dialog_service.py
api/db/services/document_service.py
api/db/services/llm_service.py
api/utils/api_utils.py
rag/llm/chat_model.py
rag/svr/task_executor.py
rag/utils/es_conn.py
rag/utils/minio_conn.py
rag/utils/redis_conn.py

add stream chat

---

api/db/init_data.py
api/db/services/llm_service.py

Add 2 embeding models from OpenAI

---

Dockerfile
Dockerfile.cuda
docker/entrypoint.sh

use smaller docker images

---

api/apps/user_app.py
api/settings.py
conf/service_conf.yaml

The back-end code adds Feishu oauth

feat: add feishu oauth

---

api/utils/file_utils.py

fix too large thumbnail issue

---

api/db/init_data.py

fix data init error

---

web/package-lock.json
web/package.json
web/src/locales/config.ts

Default language will be given according to the browse setting and also can be configured #801

Default language will be given according to the browse setting and also can be configured #801

---

api/db/services/dialog_service.py

add doc ids in API: completion

---

docs/conversation_api.md

refine doc about API: completion

---

api/db/services/dialog_service.py
rag/llm/chat_model.py
rag/llm/rpc_server.py
rag/nlp/query.py

fix english query bug

---

rag/llm/chat_model.py

add locally deployed llm

---

README.md

Some nitpicking editorial updates.

Updated Launch service from source

---

web/src/pages/chat/chat-overview-modal/index.tsx
web/src/pages/chat/embed-modal/index.tsx

fix: the site domain name in the Chat Bot API is hardcoded. #776

fix: the site domain name in the Chat Bot API is hardcoded. #776

---

docs/guides/deploy_local_llm.md

fixed a format issue for docusaurus publication

---

docs/guides/llm_api_key_setup.md

Fixed a format issue

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts

feat: remove the space before promptText #882

feat: remove the space before promptText

---

api/apps/system_app.py
api/db/services/document_service.py
api/db/services/llm_service.py
api/db/services/task_service.py
rag/llm/chat_model.py
rag/raptor.py
rag/svr/task_executor.py
rag/utils/redis_conn.py

add raptor

---

deepdoc/vision/postprocess.py

Fix some syntax errors, re not import

---

requirements.txt
requirements_dev.txt

The fasttext library is missing, and it is used in the operators.py file.

---

api/apps/chunk_app.py

syntax error

---

api/apps/api_app.py
api/apps/chunk_app.py
api/db/services/document_service.py
deepdoc/vision/postprocess.py
rag/llm/chat_model.py
rag/raptor.py
requirements.txt
requirements_dev.txt

fix raptor bugs

---

Dockerfile.cuda

Remove duplicated FROM in Dockerfile.cuda.

Remove duplicated FROM.

---

Dockerfile.arm
requirements_arm.txt

Add Dockerfile and requirements.txt for arm

---

README.md
docs/quickstart.md

minor editorial updates for clarity

---

requirements_arm.txt

Complete the requirements for ARM

Add umap-learn, fasttext and volcengine in requirements_arm.txt

---

web/src/interfaces/database/knowledge.ts
web/src/pages/user-setting/sidebar/index.tsx

fix: fixed the issue of 404 error in the user settings page of the demo site #947

fix: fixed the issue of 404 error in the user settings page of the demo site

---

docs/references/api.md

Fixed a docusaurus display issue

---

web/.umirc.ts
web/package-lock.json
web/package.json
web/src/locales/zh-traditional.ts
web/src/pages/flow/canvas/context-menu/index.tsx
web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/elk-hooks.ts
web/src/pages/flow/elk-utils.ts
web/src/pages/flow/header/index.less
web/src/pages/flow/header/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/index.tsx
web/src/pages/flow/mock.tsx
web/src/pages/flow/utils.ts

feat: add FlowHeader and delete edge #918

feat: add FlowHeader and delete edge

---

api/db/services/dialog_service.py

limit the system context length of conversation messages.

---

web/src/components/rerank.tsx
web/src/components/similarity-slider/index.tsx
web/src/constants/knowledge.ts
web/src/hooks/llmHooks.ts
web/src/interfaces/database/chat.ts
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/add-knowledge/components/knowledge-testing/index.tsx
web/src/pages/add-knowledge/components/knowledge-testing/testing-control/index.tsx
web/src/pages/chat/chat-configuration-modal/hooks.ts
web/src/pages/chat/chat-configuration-modal/index.tsx
web/src/pages/chat/chat-configuration-modal/model-setting.tsx
web/src/pages/chat/chat-configuration-modal/prompt-engine.tsx
web/src/pages/user-setting/setting-model/system-model-setting-modal/index.tsx

Vector similarity weight is displayed incorrectly #965
feat: add rerank models to the project #724 #162

feat: add rerank models to the project #724 #162

---

api/apps/chunk_app.py
api/apps/dialog_app.py
api/apps/llm_app.py
api/apps/user_app.py
api/db/__init__.py
api/db/db_models.py
api/db/init_data.py
api/db/services/dialog_service.py
api/db/services/llm_service.py
api/db/services/user_service.py
api/settings.py
rag/llm/__init__.py
rag/llm/embedding_model.py
rag/llm/rerank_model.py
rag/nlp/query.py
rag/nlp/rag_tokenizer.py
rag/nlp/search.py

feat: add rerank models to the project #724 #162

add rerank model

---

web/src/pages/chat/index.less
web/src/pages/chat/index.tsx

fix: if the conversation name is too long, it will overflow the current item. #607

fix: if the conversation name is too long, it will overflow the current item. #607

---

api/apps/llm_app.py
api/db/services/llm_service.py
rag/llm/__init__.py
rag/llm/embedding_model.py
rag/llm/rerank_model.py
rag/nlp/query.py
rag/nlp/search.py
rag/nlp/term_weight.py

fix jina adding issure and term weight refinement

---

api/utils/file_utils.py
deepdoc/parser/__init__.py
deepdoc/parser/html_parser.py
rag/app/book.py
rag/app/laws.py
rag/app/naive.py
rag/app/one.py
requirements.txt
requirements_arm.txt
requirements_dev.txt

Add support for HTML file

---

api/apps/dialog_app.py
api/utils/file_utils.py
deepdoc/parser/html_parser.py
rag/app/book.py

fix create dialog bug

---

deepdoc/parser/pdf_parser.py

fix bug in pdf parser

---

rag/llm/rerank_model.py

fix bge rerank normalize issue

---

rag/llm/chat_model.py

fix tk_count undefine issue

---

api/db/services/dialog_service.py

fix ollama bug

---

rag/llm/__init__.py
rag/llm/rerank_model.py

fix bug 994 ,991

---

api/db/services/llm_service.py

fix chunk modification bug

---

api/db/init_data.py
rag/llm/__init__.py
rag/llm/chat_model.py

Adding the Minimax model

---

api/db/init_data.py
rag/llm/rerank_model.py

Fix: bug #991

---

api/apps/file_app.py
api/db/services/file_service.py

Add backend API support for moving files into other directory

Add API for moving files

---

api/db/init_data.py
api/db/services/file_service.py

refine file select code

---

api/apps/api_app.py
rag/llm/rerank_model.py

refine API request data processing

---

api/apps/dialog_app.py
web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
web/src/pages/chat/chat-configuration-modal/index.tsx

fix: fixed the problem that the api will be called directly after selecting the chat assistant picture #1033

fix: fixed the problem that the api will be called directly after selecting the chat assistant picture

---

.gitignore
sdk/python/README.md
sdk/python/hello_ragflow.py
sdk/python/pyproject.toml
sdk/python/ragflow/__init__.py
sdk/python/ragflow/ragflow.py
sdk/python/setup.py
sdk/python/test/test_basic.py
sdk/python/test/test_sdkbase.py

Add create_dataset method, test for it, and update SDK->sdk.

Update SDK->sdk, and add create_dataset

---

sdk/python/ragflow/ragflow.py
sdk/python/test/test_basic.py

Added delete_dataset method and test for it.

added delete_dataset method

---

rag/llm/rerank_model.py

refine rerank

---

web/package.json
web/src/components/similarity-slider/index.tsx
web/src/constants/chat.ts
web/src/hooks/flow-hooks.ts
web/src/interfaces/database/flow.ts
web/src/pages/chat/chat-configuration-modal/index.tsx
web/src/pages/chat/chat-configuration-modal/model-setting.tsx
web/src/pages/chat/constants.ts
web/src/pages/chat/utils.ts
web/src/pages/flow/begin-form/index.tsx
web/src/pages/flow/constant.ts
web/src/pages/flow/flow-drawer/index.tsx
web/src/pages/flow/generate-form/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/interface.ts
web/src/pages/flow/list/flow-card/index.tsx
web/src/pages/flow/list/index.tsx
web/src/pages/flow/retrieval-form/index.tsx
web/src/pages/flow/store.ts
web/src/pages/flow/utils.ts
web/src/utils/form.ts
web/src/utils/registerServer.ts

feat: fetch flow #918 
feat: save graph

feat: fetch flow

---

api/apps/api_app.py
api/apps/canvas_app.py
api/apps/conversation_app.py
api/apps/dialog_app.py
api/db/services/canvas_service.py
api/db/services/dialog_service.py
deepdoc/parser/pdf_parser.py
rag/llm/rerank_model.py
rag/nlp/query.py

add self-rag

---

web/src/hooks/flow-hooks.ts
web/src/pages/flow/constant.ts
web/src/pages/flow/header/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/mock.tsx
web/src/pages/flow/utils.ts
web/src/services/flow-service.ts
web/src/utils/api.ts
web/src/utils/form.ts

feat: run flow

---

rag/llm/rerank_model.py

fix: bug similarity() in YoudaoRerank

---

api/apps/api_app.py
rag/llm/embedding_model.py

fix bug in api

---

web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/constant.tsx
web/src/pages/flow/flow-sider/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/mock.tsx

feat: watch graph change

---

api/utils/log_utils.py

fix: logger formater is not work

---

docs/guides/deploy_local_llm.md
docs/references/api.md

[doc] Updated default value of quote in 'get answers'

---

README.md
README_ja.md
README_zh.md

add preview gif

---

web/src/components/operate-dropdown/index.less
web/src/components/operate-dropdown/index.tsx
web/src/hooks/flow-hooks.ts
web/src/hooks/logicHooks.ts
web/src/interfaces/database/flow.ts
web/src/pages/chat/utils.ts
web/src/pages/flow/chat/box.tsx
web/src/pages/flow/chat/drawer.tsx
web/src/pages/flow/chat/hooks.ts
web/src/pages/flow/chat/index.less
web/src/pages/flow/header/index.less
web/src/pages/flow/header/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/list/flow-card/index.tsx
web/src/pages/flow/list/hooks.ts
web/src/pages/flow/mock.tsx
web/src/pages/flow/utils.ts
web/src/pages/knowledge/knowledge-card/index.tsx
web/src/utils/api.ts

feat: add OperateDropdown
feat: send debug message #918

feat: add OperateDropdown and send debug message #918

---

api/apps/document_app.py
api/utils/web_utils.py
requirements.txt
web/src/hooks/documentHooks.ts
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/add-knowledge/components/knowledge-file/document-toolbar.tsx
web/src/pages/add-knowledge/components/knowledge-file/hooks.ts
web/src/pages/add-knowledge/components/knowledge-file/index.tsx
web/src/pages/add-knowledge/components/knowledge-file/model.ts
web/src/pages/add-knowledge/components/knowledge-file/web-crawl-modal.tsx
web/src/services/kbService.ts
web/src/utils/api.ts

Knowledge base management supports crawling information from web pages and generating PDF documents

Supports obtaining PDF documents from web pages

---

web/src/pages/add-knowledge/components/knowledge-file/document-toolbar.tsx

fix: hide web crawl menu item #1107

fix: hide web crawl menu item

---

web/package-lock.json
web/package.json
web/src/pages/flow/chat/drawer.tsx
web/src/pages/flow/hooks.ts

feat: generate uuid with human-id #918

feat: generate uuid with human-id #918

---

README.md
docs/guides/configure_knowledge_base.md
docs/guides/llm_api_key_setup.md
docs/guides/manage_files.md
docs/guides/start_chat.md
docs/quickstart.mdx

Updated the doc for configuring api key

---

web/src/hooks/logicHooks.ts
web/src/interfaces/database/base.ts
web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/chat/box.tsx
web/src/pages/flow/chat/drawer.tsx
web/src/pages/flow/chat/hooks.ts
web/src/pages/flow/header/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/index.tsx
web/src/utils/request.ts

feat: catch errors when sending messages #918

feat: catch errors when sending messages #918

---

web/src/pages/chat/hooks.ts
web/src/pages/chat/shared-hooks.ts
web/src/pages/flow/canvas/node/index.tsx
web/src/pages/flow/chat/hooks.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/flow-sider/index.tsx
web/src/pages/flow/operator-icon/index.less
web/src/pages/flow/operator-icon/index.tsx

feat: add icon to graph nodes #918

feat: add icon to graph nodes #918

---

docs/guides/llm_api_key_setup.md

[doc] Minor editorial updates.

---

web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/canvas/node/index.less
web/src/pages/flow/canvas/node/index.tsx

feat: set the anchor points of all nodes to be enterable and exitable #918

feat: set the anchor points of all nodes to be enterable and exitable #918

---

README.md
README_ja.md
README_zh.md

Update discord link

---

web/src/pages/flow/canvas/node/index.less
web/src/pages/flow/canvas/node/index.tsx

feat: when a node of the graph is selected, the border of the node is highlighted. #918

feat: when a node of the graph is selected, the border of the node is highlighted. #918

---

rag/llm/cv_model.py

fix multi-modual bug

---

web/src/components/operate-dropdown/index.tsx
web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/canvas/node/index.less
web/src/pages/flow/canvas/node/index.tsx
web/src/pages/flow/constant.tsx
web/src/pages/flow/flow-sider/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/mock.tsx
web/src/pages/flow/store.ts
web/src/pages/flow/utils.ts

feat: add delete menu to graph node #918

feat: add delete menu to graph node #918

---

api/apps/canvas_app.py
api/apps/file_app.py
api/db/services/canvas_service.py
api/db/services/task_service.py
docker/docker-compose-CN-oc9.yml
docker/docker-compose-CN.yml
docker/docker-compose.yml
rag/app/picture.py
rag/llm/cv_model.py
rag/llm/embedding_model.py

fix file preview in file management

fix file preview in file management

---

api/db/db_models.py
graph/canvas.py
graph/component/__init__.py
graph/component/answer.py
graph/component/base.py
graph/component/begin.py
graph/component/categorize.py
graph/component/cite.py
graph/component/generate.py
graph/component/message.py
graph/component/relevant.py
graph/component/retrieval.py
graph/component/rewrite.py
graph/component/switch.py
graph/settings.py
graph/test/client.py
graph/test/dsl_examples/categorize.json
graph/test/dsl_examples/customer_service.json
graph/test/dsl_examples/headhunter_zh.json
graph/test/dsl_examples/retrieval_and_generate.json
graph/test/dsl_examples/retrieval_categorize_and_generate.json
graph/test/dsl_examples/retrieval_relevant_and_generate.json
graph/test/dsl_examples/retrieval_relevant_rewrite_and_generate.json

support graph

---

api/db/init_data.py
rag/llm/__init__.py
rag/llm/chat_model.py
rag/llm/embedding_model.py

add support for mistral

---

rag/app/qa.py
rag/nlp/__init__.py
requirements.txt
requirements_arm.txt
requirements_dev.txt

Support extracting questions and answers from PDF files

Add pdf support for QA parser

---

README.md
README_ja.md
README_zh.md

refine doc about supporting PDF for Q&A

---

rag/llm/__init__.py

- Fix a bug for VolcEngine
- After testing, the current VolcEngine configuration also supports the Doubao series

Fix VolcEngine BUG

---

requirements.txt

due to security problem, need updagre to fix, see bellow
Name| version | CVE | upgrade version
-- | -- | -- | --
PyMySQL | 1.1.0 | CVE-2024-36039 | 1.1.1
Werkzeug | 3.0.1 | CVE-2024-34069 | 3.0.3
aiohttp | 3.9.3 | CVE-2024-30251 | 3.9.4
pillow | 10.2.0 | CVE-2024-28219 | 10.3.0

upgrade version fix security bug

---

docs/guides/llm_api_key_setup.md
docs/references/api.md

[doc] RAGFlow's api key never expires

---

docs/references/ragflow_api.md
sdk/python/test/test_dataset.py

This PR added ragflow_api.md and more tests for API.

added api documentation and added more tests

---

docs/references/ragflow_api.md

Remove the visibilty of RAGFlow API

---

api/apps/dataset_api.py
api/db/services/knowledgebase_service.py

fixed: duplicate name

---

graph/README.md
graph/README_zh.md
graph/canvas.py
graph/component/base.py
graph/component/categorize.py
graph/settings.py
graph/test/client.py
graph/test/dsl_examples/customer_service.json

add README to graph

---

api/apps/chunk_app.py
api/db/services/document_service.py

fix: using embd which user configured at knowledgebase

---

api/apps/chunk_app.py

fix bug: [1159](https://github.com/infiniflow/ragflow/issues/1159)
using embd which user configured at knowledgebase when create new chunk in database

fix:failed to Create new Chunk in database #1159

---

rag/app/manual.py
rag/app/qa.py
rag/nlp/__init__.py

Add docx support for manual parser

Add docx support for manual parser

---

docs/references/ragflow_api.md

polished doc for dataset API

---

rag/app/naive.py

refine code to prevent exception

---

web/src/pages/user-setting/setting-team/index.tsx

Grey out the team function #1221

feat: grey out the team function #1221

---

web/src/components/chunk-method-modal/hooks.ts

Let json files support naive parsing methods #1245

Let json files support naive parsing methods #1245

---

rag/app/qa.py

Place pdf's image at the correct position in QA parser

Place pdf's image at the correct position in QA parser

---

web/.husky/pre-commit
web/package-lock.json
web/package.json
web/src/hooks/documentHooks.ts

feat: format code before submitting it #1251

feat: format code before submitting it #1251 

---

rag/app/naive.py
rag/app/qa.py
rag/nlp/__init__.py

Support displaying images in chunks of docx files when using general parser

Support displaying images in the chunks of docx files when using general parser

---

web/src/pages/chat/chat-container/index.less
web/src/pages/chat/hooks.ts
web/src/pages/chat/share/index.less
web/src/pages/chat/shared-hooks.ts

feat: modify the background color of chat messages #1215

feat: modify the background color of chat messages 

---

web/src/pages/flow/canvas/node/index.less
web/src/pages/flow/canvas/node/index.tsx

feat: change nodes to circular #918

feat: change nodes to circular #918

---

web/src/pages/flow/canvas/node/categorize-handle.tsx
web/src/pages/flow/canvas/node/index.less
web/src/pages/flow/canvas/node/index.tsx
web/src/pages/flow/categorize-form/dynamic-categorize.tsx
web/src/pages/flow/categorize-form/hooks.ts
web/src/pages/flow/categorize-form/index.tsx
web/src/pages/flow/constant.tsx
web/src/pages/flow/store.ts

feat: add CategorizeHandle #918

feat: add CategorizeHandle #918

---

docs/quickstart.mdx

docs: update quickstart.mdx

---

requirements.txt

Fix dependency conflict

---

deepdoc/parser/pdf_parser.py

Fix occasional errors in pdf table recognition

Fix occasional errors in pdf table recognition

---

deepdoc/parser/__init__.py
deepdoc/parser/markdown_parser.py
deepdoc/parser/md_parser.py
rag/app/naive.py

Support extracting table for markdown file in general parser

Support table for markdown file in general parser

---

sdk/python/README.md

Update sdk readme

---

rag/llm/embedding_model.py
rag/llm/rerank_model.py

Fix ragflow may encounter an OOM (Out Of Memory) when there are a lot of conversations. 
#1288

Fix ragflow may encounter an OOM (Out Of Memory) when there are a lot of conversations

---

rag/llm/rerank_model.py

fix mem leak for local reranker

---

web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/canvas/node/begin-node.tsx
web/src/pages/flow/canvas/node/categorize-node.tsx
web/src/pages/flow/canvas/node/dropdown.tsx
web/src/pages/flow/constant.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/mock.tsx
web/src/pages/flow/utils.ts

feat: restrict classification operators cannot be connected to Answer and other classification #918

feat: restrict classification operators cannot be connected to Answer and other classification #918

---

README.md
README_ja.md
README_zh.md

Update README to introduce new features

Introduce new features

---

web/src/pages/flow/categorize-form/hooks.ts
web/src/pages/flow/categorize-form/index.tsx
web/src/pages/flow/constant.tsx
web/src/pages/flow/interface.ts
web/src/pages/flow/mock.tsx
web/src/pages/flow/store.ts
web/src/pages/flow/utils.ts

feat: clear the selection box to delete the corresponding edge. #918
feat: fix the problem of form entries being deleted when adding a new line #918

feat: fix the problem of form entries being deleted when adding a new line #918 and clear the selection box to delete the corresponding edge

---

web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/utils.ts

feat: limit there to be only one line between two nodes #918

feat: limit there to be only one line between two nodes #918

---

rag/app/laws.py
rag/nlp/__init__.py

Optimize docx handle method in laws parser

Optimize docx handle method in laws parser

---

web/src/pages/flow/headhunter_zh.json
web/src/pages/flow/hooks.ts
web/src/pages/flow/list/hooks.ts
web/src/pages/flow/store.ts
web/src/pages/flow/utils.test.ts
web/src/pages/flow/utils.ts

feat: get the operator type from id #918

feat: get the operator type from id #918

---

graph/test/dsl_examples/headhunter_zh.json
web/src/pages/flow/canvas/node/categorize-node.tsx
web/src/pages/flow/canvas/node/index.less
web/src/pages/flow/headhunter_zh.json
web/src/pages/flow/utils.test.ts
web/src/pages/flow/utils.ts

feat: construct the edge of the classification operator from dsl #918

feat: construct the edge of the classification operator from dsl #918

---

api/apps/chunk_app.py
api/db/services/dialog_service.py
rag/app/laws.py
rag/nlp/__init__.py

upgrade laws parser of docx

---

web/src/pages/flow/answer-form/index.tsx
web/src/pages/flow/canvas/node/begin-node.tsx
web/src/pages/flow/canvas/node/categorize-node.tsx
web/src/pages/flow/canvas/node/index.tsx
web/src/pages/flow/categorize-form/dynamic-categorize.tsx
web/src/pages/flow/categorize-form/hooks.ts
web/src/pages/flow/flow-drawer/index.tsx
web/src/pages/flow/headhunter_zh.json
web/src/pages/flow/hooks.ts
web/src/pages/flow/interface.ts
web/src/pages/flow/mock.tsx
web/src/pages/flow/store.ts
web/src/pages/flow/utils.ts

feat: modify the name of an operator #918

feat: modify the name of an operator #918

---

docs/references/ragflow_api.md

Adds the documentation for three newly added API methods for content management.

Doc: added doc for three doc methods

---

web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/canvas/node/index.less
web/src/pages/flow/flow-drawer/index.tsx
web/src/pages/flow/headhunter_zh.json
web/src/pages/flow/utils.ts

feat: customize edge arrow #918

feat: customize edge arrow #918

---

web/src/hooks/flow-hooks.ts
web/src/hooks/logicHooks.ts
web/src/interfaces/database/base.ts
web/src/interfaces/database/flow.ts
web/src/locales/en.ts
web/src/locales/zh.ts
web/src/pages/flow/hooks.ts
web/src/pages/flow/list/create-flow-modal.tsx
web/src/pages/flow/list/hooks.ts
web/src/pages/flow/list/index.less
web/src/pages/flow/list/index.tsx

feat: add CreateFlowModal #918

feat: add CreateFlowModal #918

---

docs/guides/deploy_local_llm.md

It adds the setup guide for using Intel IPEX-LLM with Ollama to docs/guide/deploy_local_llm.md

Add Intel IPEX-LLM setup under deploy_local_llm

---

web/src/locales/en.ts
web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/canvas/node/categorize-handle.tsx
web/src/pages/flow/canvas/node/relevant-node.tsx
web/src/pages/flow/categorize-form/dynamic-categorize.tsx
web/src/pages/flow/categorize-form/hooks.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/form-hooks.ts
web/src/pages/flow/interface.ts
web/src/pages/flow/relevant-form/hooks.ts
web/src/pages/flow/relevant-form/index.tsx
web/src/pages/flow/store.ts

feat: add RelevantForm #918

---

api/apps/dataset_api.py
api/utils/api_utils.py
sdk/python/ragflow/ragflow.py
sdk/python/test/test_document.py

Adds the API method of updating documents.

API: create update_doc method

---

web/src/hooks/flow-hooks.ts
web/src/pages/flow/canvas/node/index.tsx
web/src/pages/flow/chat/hooks.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/header/index.tsx

feat:  call the reset api before opening the run drawer each time #918

feat:  call the reset api before opening the run drawer each time #918

---

graph/test/dsl_examples/retrieval_relevant_rewrite_and_generate.json
web/src/pages/flow/list/create-flow-modal.tsx
web/src/pages/flow/list/hooks.ts
web/src/pages/flow/list/index.less
web/src/pages/flow/retrieval-form/index.tsx
web/src/pages/flow/retrieval_relevant_rewrite_and_generate.json
web/src/pages/flow/utils.test.ts

feat: build nodes and edges from chat bot dsl #918

feat: build nodes and edges from chat bot dsl #918

---

api/apps/canvas_app.py
api/db/init_data.py
graph/canvas.py
graph/component/base.py
graph/component/keyword.py
graph/templates/HR_callout_zh.json
graph/templates/customer_service.json
graph/templates/general_chat_bot.json
graph/templates/interpreter.json
graph/test/dsl_examples/retrieval_relevant_rewrite_and_generate.json
rag/llm/chat_model.py

add keyword extraction in graph

---

web/src/hooks/flow-hooks.ts
web/src/layouts/components/header/index.tsx
web/src/locales/en.ts
web/src/pages/flow/categorize-form/index.tsx
web/src/pages/flow/constant.tsx
web/src/pages/flow/generate-form/index.tsx
web/src/pages/flow/relevant-form/index.tsx
web/src/pages/flow/rewrite-question-form/index.tsx

feat: add graph tab to header #918

feat: add graph tab to header #918

---

web/src/pages/flow/canvas/index.tsx
web/src/pages/flow/constant.tsx
web/src/pages/flow/list/index.less

feat: click on a blank area of ​​the canvas to hide the form drawer #918

feat: click on a blank area of ​​the canvas to hide the form drawer #918

---

web/src/hooks/flow-hooks.ts
web/src/pages/flow/list/create-flow-modal.tsx
web/src/pages/flow/list/flow-card/index.less
web/src/pages/flow/list/flow-card/index.tsx
web/src/pages/flow/list/graph-avatar.tsx
web/src/pages/flow/list/hooks.ts

feat: add GraphAvatar to graph list #918

feat: add GraphAvatar to graph list #918

---

web/src/pages/flow/chat/hooks.ts
web/src/pages/flow/header/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/utils.ts

feat: save graph data before opening the debug drawer #918

feat: save graph data before opening the debug drawer #918

---

web/src/locales/en.ts
web/src/locales/zh.ts
web/src/pages/flow/flow-sider/index.tsx
web/src/pages/flow/relevant-form/hooks.ts
web/src/pages/flow/store.ts

feat: after deleting the edge, set the corresponding field in the node's form field to undefined #918

feat: after deleting the edge, set the corresponding field in the node's form field to undefined #918

---

api/apps/canvas_app.py
graph/canvas.py
graph/component/base.py
graph/component/categorize.py
graph/component/generate.py
graph/component/message.py
graph/component/relevant.py
graph/component/retrieval.py
graph/component/switch.py

be more specific for error message

---

graph/component/duckduckgosearch.py

fix duckduckgosearch.py bug

---

web/src/pages/flow/constant.tsx
web/src/pages/flow/hooks.ts

feat: node cannot connect to itself #918

feat: node cannot connect to itself #918

---

rag/llm/chat_model.py

fix botocore 

---

web/package-lock.json
web/package.json
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/canvas/node/categorize-node.tsx
web/src/pages/flow/store.ts

feat: when Categorize establishes a connection with other operators, it adds the target node to the to field. #918
feat: modify the Chinese text of loop #918

feat: when Categorize establishes a connection with other operators, it adds the target node to the to field. #918

---

README.md
README_ja.md
README_zh.md
docs/guides/configure_knowledge_base.md
docs/guides/manage_files.md
docs/quickstart.mdx
graph/canvas.py
graph/component/categorize.py
graph/component/generate.py

update docs for release 0.8.0

---

graph/component/categorize.py
rag/nlp/term_weight.py

examples empty in categorize

---

web/src/interfaces/database/flow.ts
web/src/pages/flow/canvas/edge/index.tsx

feat: highlight the nodes that the workflow passes through #918

feat: highlight the nodes that the workflow passes through #918

---

web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/categorize-form/dynamic-categorize.tsx

feat: translate graph of header #918

feat: translate graph of header #918

---

web/src/assets/svg/llm/bedrock.svg
web/src/pages/user-setting/setting-model/index.tsx

feat: add bedrock icon

---

web/src/locales/zh-traditional.ts
web/src/locales/zh.ts

feat: translate the to field #918

feat: translate the to field #918

---

graph/canvas.py
graph/component/baidu.py
graph/component/duckduckgosearch.py
graph/component/message.py
graph/templates/HR_callout_zh.json

fix no resualt bugs

---

deepdoc/parser/pdf_parser.py

fix pdf_parser content confusion

---

deepdoc/parser/pdf_parser.py

After checking the language of the pdf, the line will hardcode the language into Chinese

fix: Delete hardcode

---

deepdoc/parser/pdf_parser.py

fix bug about divided by zero

---

rag/llm/__init__.py

add Gemini key

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/duckduckgo-form/index.tsx

feat: translate text from DuckDuckGo #918

feat: translate text from DuckDuckGo #918

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/generate-form/index.tsx

fix: add message_history_window_size to  GenerateForm #1472

fix: add message_history_window_size to  GenerateForm #1472

---

api/db/services/dialog_service.py
api/ragflow_server.py
graph/component/base.py

fix ollama max token issue

---

api/db/db_models.py
api/ragflow_server.py
rag/llm/__init__.py

refine db connection

---

graph/component/duckduckgo.py

fix duckduckgo.py

---

web/src/pages/flow/constant.tsx
web/src/pages/flow/duckduckgo-form/index.tsx
web/src/pages/flow/hooks.ts

fix: fixed the issue where parameters of DuckDuckGo could not be saved to the backend after being dragged to the canvas #918

fix: fixed the issue where parameters of DuckDuckGo could not be saved to the backend after being dragged to the canvas #918

---

web/src/pages/flow/hooks.ts

fix: fixed the issue that the llm field in the KeywordExtract form had no default value

fix: fixed the issue that the llm field in the KeywordExtract form had no default value

---

web/src/pages/user-setting/setting-model/api-key-modal/index.tsx
web/src/pages/user-setting/setting-model/volcengine-model/index.tsx

fix: Add Model Providers:Azure-OpenAI error #1402

fix: Add Model Providers:Azure-OpenAI error #1402

---

graph/component/__init__.py
graph/component/wikipedia.py
graph/test/dsl_examples/keyword_wikipedia_and_generate.json
requirements.txt
requirements_arm.txt
requirements_dev.txt

Add component Wikipedia

---

graph/component/wikipedia.py

Set wikipedia lang

---

docs/guides/configure_knowledge_base.md
docs/guides/llm_api_key_setup.md
docs/quickstart.mdx
docs/references/faq.md

Added supported LLMs

---

graph/canvas.py
graph/component/base.py
graph/component/generate.py

fix bugs about multi input for generate

---

api/db/init_data.py
rag/llm/__init__.py

fix minimax bug

---

web/src/pages/add-knowledge/components/knowledge-chunk/model.ts

fix: Hundreds of chunks list can't choose page #1238

fix: Hundreds of chunks list can't choose page #1238

---

api/db/services/dialog_service.py

hide referece when disable cite

---

api/apps/api_app.py
api/db/init_data.py

fix minimax init error

---

web/src/assets/svg/llm/open-router.svg

feat: replace open-router.svg #1467

feat: replace open-router.svg #1467

---

web/src/pages/user-setting/interface.ts
web/src/pages/user-setting/setting-model/api-key-modal/index.tsx
web/src/pages/user-setting/setting-model/hooks.ts

fix: add group id field to ApiKeyModal #1353

fix: add group id field to ApiKeyModal #1353

---

graph/component/base.py

fix emmpty input in graph

---

graph/component/base.py
graph/component/generate.py

refine generate

---

web/src/pages/add-knowledge/components/knowledge-chunk/index.tsx
web/src/pages/add-knowledge/components/knowledge-chunk/model.ts

fix: display total items on chunk list page #900

fix: display total items on chunk list page #900

---

docker/docker-compose-gpu.yml

add docker-compose-gpu.yml to support gpu
#1558

add docker-compose-gpu.yml to support gpu

---

web/src/assets/svg/pubmed.svg
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/flow-drawer/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/pubmed-form/index.tsx
web/src/pages/user-setting/setting-model/api-key-modal/index.tsx

feat: modify the translation of baiduDescription #918
feat: add PubMed operator #918

feat: add PubMed operator #918

---

web/package-lock.json
web/package.json
web/src/app.tsx
web/src/components/knowledge-base-item.tsx
web/src/hooks/flow-hooks.ts
web/src/hooks/knowledge-hooks.ts
web/src/locales/en.ts
web/src/pages/add-knowledge/components/knowledge-setting/model.ts
web/src/pages/file-manager/connect-to-knowledge-modal/index.tsx
web/src/pages/knowledge/hooks.ts
web/src/pages/knowledge/index.tsx
web/src/pages/knowledge/knowledge-card/index.tsx
web/src/pages/knowledge/knowledge-creating-modal/index.tsx

fix: after logging out and entering the knowledge base page again, the data before still exists #1306

fix: after logging out and entering the knowledge base page again, the data before still exists #1306

---

rag/llm/embedding_model.py

fix embeding model for Azure

---

api/apps/chunk_app.py

fix function create to slove the problem of creating a chunk and increasing the chunk number by 2.

fix function create to slove chunk number wrong

---

docs/guides/llm_api_key_setup.md
docs/quickstart.mdx

update quickstart and llm_api_key_setup document

update quickstart and llm_api_key_setup document

---

docker/docker-compose-gpu-CN-oc9.yml
docker/docker-compose-gpu-CN.yml

add docker-compose-gpu-CN.yml and docker-compose-gpu-CN-oc9.yml to support gpu
#1558

add docker-compose-gpu-CN.yml and docker-compose-gpu-CN-oc9.yml to support gpu

---

web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-card/index.less
web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-card/index.tsx

fix: the content in the chunk card will overflow #1628

fix: the content in the chunk card will overflow #1628

---

web/src/components/message-item/index.tsx
web/src/components/new-document-link.tsx
web/src/pages/add-knowledge/components/knowledge-testing/testing-result/select-files.tsx
web/src/pages/document-viewer/index.tsx
web/src/pages/file-manager/action-cell/index.tsx
web/src/utils/documentUtils.ts

fix: reference file with 'docx' type can not open #844

fix: reference file with 'docx' type can not open #844

---

README_zh.md

Add information form

---

web/src/hooks/file-manager-hooks.ts
web/src/hooks/logic-hooks.ts
web/src/pages/file-manager/file-toolbar.tsx
web/src/pages/file-manager/index.tsx

fix: fetch file list by react-query #1306

fix: fetch file list by react-query #1306 

---

deepdoc/parser/docx_parser.py

fix bug of ragflowdocxpparser

---

README.md
README_ja.md
README_zh.md

refine readme, update updates

---

api/apps/system_app.py
rag/utils/redis_conn.py

fix redis no such key

---

api/apps/__init__.py
api/utils/commands.py

add password reset function by extending the Flask command. #1200

add password reset function by extending the Flask command

---

rag/app/qa.py

fix: Misspelled Variable Name

---

deepdoc/parser/pdf_parser.py
requirements.txt
requirements_arm.txt
requirements_dev.txt

pypdf and PyPDF2 possible Infinite Loop when a comment isn't followed by a character #59

pypdf2 to pypdf

---

graph/component/base.py

fix graph bug about second retrieval

---

web/.umirc.ts

fix: Fixed an issue where the project could not be built #1306

fix: Fixed an issue where the project could not be built #1306

---

web/src/hooks/file-manager-hooks.ts
web/src/hooks/flow-hooks.ts
web/src/layouts/components/right-toolbar/index.tsx

fix: Set the default language to English #1306

fix: Set the default language to English #1306

---

rag/llm/chat_model.py
rag/llm/cv_model.py
rag/llm/embedding_model.py

refactor some llm api using openai api format

refactor some llm api using openai api format

---

web/src/pages/user-setting/setting-password/index.tsx

fix: Limit the length of the new password input box to no less than 8 #1634

fix: Limit the length of the new password input box to no less than 8 #1634

---

rag/llm/embedding_model.py

fix embedding_model

---

rag/nlp/__init__.py

fix bug of regx

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/arxiv-form/index.tsx
web/src/pages/flow/canvas/node/index.tsx
web/src/pages/flow/constant.tsx
web/src/pages/flow/flow-drawer/index.tsx
web/src/pages/flow/hooks.ts

fix: alter Arxiv to ArXiv #918

fix: alter Arxiv to ArXiv #918

---

web/src/hooks/llm-hooks.ts
web/src/hooks/logic-hooks.ts
web/src/interfaces/database/base.ts
web/src/pages/add-knowledge/components/knowledge-setting/hooks.ts
web/src/pages/add-knowledge/components/knowledge-testing/testing-control/index.tsx
web/src/pages/chat/chat-configuration-modal/index.tsx
web/src/pages/chat/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/user-setting/setting-model/hooks.ts
web/src/pages/user-setting/setting-model/index.tsx

fix: fetch llm list by @tanstack/react-query #1306

fix: fetch llm list by @tanstack/react-query #1306

---

docker/.env
docker/docker-compose-admin-tool.yml
docker/docker-compose.yml
docker/init-kibana.sh
docker/service_conf.yaml

Add Kibana component for Elasticsearch

Add Kibana component for Elasticsearch

---

rag/llm/chat_model.py

fix OpenAI llm return bug

---

api/apps/llm_app.py

#1726   fix add local vision llm  error when cannot download test pic

fix add local vision llm  error when cannot download test pic

---

web/src/hooks/chunk-hooks.ts
web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-card/index.less
web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-toolbar/index.tsx
web/src/pages/add-knowledge/components/knowledge-chunk/components/document-preview/preview.tsx
web/src/pages/add-knowledge/components/knowledge-chunk/hooks.ts
web/src/pages/add-knowledge/components/knowledge-chunk/index.tsx
web/src/pages/force-graph.tsx
web/src/routes.ts

fix: Fetch chunk list by @tanstack/react-query #1306

fix: Fetch chunk list by @tanstack/react-query #1306

---

rag/llm/chat_model.py

fix MiniMax chat bug

---

api/utils/commands.py

support reset the user email from old to new
#1723

support reset the user email

---

rag/llm/chat_model.py

fix: ERROR: 'CompletionUsage' object has no attribute 'get'

---

rag/llm/cv_model.py

refactor stepfun cv model

---

requirements.txt
requirements_arm.txt
requirements_dev.txt

fix jina module not find bug

---

web/src/pages/add-knowledge/components/knowledge-chunk/components/document-preview/preview.tsx

fix: TypeError: Cannot read properties of undefined (reading 'viewport' #1761

fix: TypeError: Cannot read properties of undefined (reading 'viewport' #1761

---

web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/force-graph.tsx
web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/indented-tree.tsx
web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/index.tsx
web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/modal.tsx
web/src/pages/add-knowledge/components/knowledge-chunk/index.tsx

feat: Add IndentedTree #162

---

README.md
README_ja.md
README_zh.md

readme update

---

Dockerfile
Dockerfile.arm
Dockerfile.cuda
Dockerfile.scratch
Dockerfile.scratch.oc9
graphrag/leiden.py

refine dockerfile

---

web/src/components/llm-select/index.tsx
web/src/components/llm-setting-items/index.tsx
web/src/pages/add-knowledge/components/knowledge-file/model.ts
web/src/pages/flow/hooks.ts

fix: Fixed the issue that the related form value does not change after selecting the freedom field of the model #1804

fix: Fixed the issue that the related form value does not change after selecting the freedom field of the model #1804

---

api/db/services/document_service.py
conf/llm_factories.json
graphrag/mind_map_prompt.py
rag/app/knowledge_graph.py
rag/utils/redis_conn.py

refine mindmap prompt

---

graphrag/index.py
rag/nlp/__init__.py

remove duplicated key in mind map

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/force-graph.tsx
web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/indented-tree.tsx
web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/modal.tsx

feat: Translate ForceGraph #162

feat: Translate ForceGraph #162

---

rag/app/naive.py

be better chunks before graphrag

---

README.md
README_ja.md
README_zh.md
api/db/services/document_service.py
docs/guides/configure_knowledge_base.md
docs/guides/manage_files.md
docs/quickstart.mdx

refine docs for 0.9.0 release

---

graphrag/index.py

refine context length

---

api/db/services/document_service.py
graphrag/community_reports_extractor.py
graphrag/graph_extractor.py
graphrag/index.py
rag/nlp/search.py

refine loginfo about graprag progress

---

rag/settings.py

try to process the large file will throw a File size exceeds error

fix: align limitation with env

---

docs/guides/llm_api_key_setup.md

Fixed a broken link

---

web/src/pages/add-knowledge/components/knowledge-setting/hooks.ts

fix: Embedding error in file parsing #1835

fix: Embedding error in file parsing #1835

---

graphrag/index.py

add callback to entity extraction

---

graphrag/index.py

refine mindmap

---

rag/llm/chat_model.py
rag/llm/embedding_model.py

fix LocalAI add bug

---

api/apps/llm_app.py
graphrag/index.py

fix add slef base url openai error

---

agent/templates/HR_callout_zh.json
agent/templates/customer_service.json
agent/templates/general_chat_bot.json
agent/templates/interpreter.json
agent/templates/websearch_assistant.json

fix: The size of operators created from agent templates is displayed incorrectly #1863

fix: The size of operators created from agent templates is displayed incorrectly #1863

---

requirements.txt
requirements_arm.txt
requirements_dev.txt

#1824  #1822 remove jina pack in requirement file to fix package conflict

remove jina pack in requirement file to fix package conflict

---

conf/llm_factories.json

add support for gpt-4o-mini

---

api/apps/llm_app.py

fix code injection in https://github.com/infiniflow/ragflow/issues/1860, developers can have a check to see if the fix works as expected.
Vulnerability Fix

fix code injection

---

graphrag/index.py

less text, better extraction

---

README.md
README_ja.md

1. Update the change line to Unix style
2. Update version info.

Update version and format

---

api/apps/llm_app.py
rag/llm/chat_model.py

Enhance the robustness of the code

Enhance the robustness of the code

---

conf/llm_factories.json

model type only support single value

fix: model type only support single value

---

api/apps/conversation_app.py
api/apps/document_app.py
api/db/services/dialog_service.py
api/db/services/document_service.py
api/db/services/file_service.py
graphrag/index.py
graphrag/mind_map_extractor.py
graphrag/mind_map_prompt.py

add function: upload and parse

---

api/db/services/file_service.py

fix no modual error

---

api/db/init_data.py

rm qwen-v1-max

---

api/utils/file_utils.py
deepdoc/parser/txt_parser.py
rag/app/naive.py

add sql to naive parser

---

web/src/components/chunk-method-modal/index.tsx
web/src/components/delimiter.tsx
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx

feat: Add delimiter field to naive parsing method #1909

feat: Add delimiter field to naive parsing method #1909

---

web/src/hooks/chunk-hooks.ts
web/src/pages/add-knowledge/components/knowledge-chunk/hooks.ts

fix: Chunks cannot be deleted #1912

fix: Chunks cannot be deleted #1912

---

api/apps/api_app.py
api/apps/document_app.py
api/db/services/file_service.py

fix api argument error

---

web/src/components/api-service/chat-overview-modal/index.tsx
web/src/components/api-service/hooks.ts
web/src/hooks/chat-hooks.ts

fix: Error on chat api，<BadRequestKeyError '400: Bad Request'> #1918

fix: Error on chat api，<BadRequestKeyError '400: Bad Request'> #1918

---

graphrag/index.py

boost paralal of graphrag

---

deepdoc/parser/txt_parser.py

fix parameter error

---

web/src/components/chunk-method-modal/hooks.ts
web/src/components/chunk-method-modal/index.tsx
web/src/components/edit-tag/index.less
web/src/components/max-token-number.tsx
web/src/hooks/logic-hooks.ts
web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx
web/src/pages/add-knowledge/components/knowledge-setting/hooks.ts

feat: After selecting the parsing method as knowledge graph, the delimiter and chunk token number are displayed. #1594

feat: After selecting the parsing method as knowledge graph, the delimiter and chunk token number are displayed. #1594

---

api/apps/api_app.py

Type of change
Bug Fix (Import necessary class for retrieval API )
New Feature (Add multi-KB search to retrieval API)

Fix retrieval API error  and add multi-kb search

---

web/src/pages/user-setting/setting-model/constant.ts

fix prefXCloud logo bug

---

api/apps/document_app.py
api/db/services/api_service.py
graphrag/mind_map_extractor.py
rag/app/naive.py

fix mind map bug

---

api/apps/document_app.py
rag/svr/task_executor.py

refine error log while chunking

---

api/db/init_data.py

refine llm init

---

graphrag/index.py

fix empty graph issue

---

api/db/services/dialog_service.py
rag/nlp/search.py

add doc ids to chat

---

api/apps/document_app.py

add interface to get doc infos by doc ids

---

conf/llm_factories.json

Removed extraneous spaces and corrected a misspelling of a model name.

 Correct the incorrect description of the pre-installed models on the SILICONFLOW platform.

---

web/src/components/file-icon/index.less
web/src/components/file-icon/index.tsx
web/src/components/message-input/index.less
web/src/components/message-input/index.tsx
web/src/components/message-item/index.tsx

feat: Add FileIcon #1880

---

rag/llm/chat_model.py

#1942  fix add Bedrock llm error

fix add Bedrock llm error

---

api/apps/user_app.py

Refactor code, improve performance

Refactor user register

---

api/apps/api_app.py
api/apps/document_app.py
api/db/services/document_service.py
api/db/services/file_service.py

refine upload & parse

---

api/apps/user_app.py
api/utils/api_utils.py

1. Refactor error message
2. Update function name

Refactor user registration

---

api/apps/user_app.py

1. Rename the variable
2. Refactor error message
3. Format the code

Refactor user register & login

---

rag/llm/embedding_model.py

#1958   fix OpenAI Embedding length error

 fix OpenAI Embedding length error

---

agent/component/__init__.py
agent/component/exesql.py
agent/test/dsl_examples/exesql.json
api/apps/canvas_app.py
requirements.txt
requirements_arm.txt

Add component ExeSQL

---

web/src/components/indented-tree/indented-tree.tsx

fix: Opening file whose type is Knowledge Graph appear error with tsx #1975

fix: Opening file whose type is Knowledge Graph appear error with tsx #1975

---

rag/llm/chat_model.py

fix 01.ai url error

---

web/src/components/api-service/hooks.ts
web/src/components/message-input/index.tsx
web/src/constants/chat.ts
web/src/pages/chat/share/large.tsx
web/src/pages/chat/shared-hooks.ts

feat: Hide the upload button in the external agent's chat box  #1880

feat: Hide the upload button in the external agent's chat box  #1880

---

graphrag/mind_map_extractor.py

fix empty mind map issue

---

api/apps/api_app.py

Supports use API to get doc info by doc ids
feat: Supports use API to get doc info by doc ids

Add API to get doc info by doc ids

---

agent/component/base.py
agent/component/generate.py
agent/component/retrieval.py

fix mutiple retrieval component content

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/switch-form/index.tsx

feat: Add complex dynamic form to SwitchForm #1739

feat: Add complex dynamic form to SwitchForm #1739

---

agent/component/generate.py

Fix generate param empty_response

---

rag/svr/task_executor.py

turn down es bulk size

---

web/src/pages/flow/canvas/node/hooks.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/interface.ts
web/src/pages/flow/store.ts
web/src/pages/flow/utils.ts

feat: Build the positions of the Switch handle #1739

feat: Build the positions of the Switch handle #1739

---

README_ja.md
README_zh.md

- Fix zh and ja document types to allow users to read better

doc: fix zh and ja document type

---

web/src/pages/flow/canvas/node/hooks.ts
web/src/pages/flow/categorize-form/dynamic-categorize.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/store.ts
web/src/pages/flow/switch-form/index.tsx
web/src/pages/flow/utils.ts

feat: Build the edges of Switch  by form data #1739

feat: Build the edges of Switch  by form data #1739

---

web/src/pages/flow/canvas/node/categorize-handle.tsx
web/src/pages/flow/canvas/node/categorize-node.tsx
web/src/pages/flow/constant.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/store.ts
web/src/pages/flow/switch-form/index.tsx

feat: Update Switch form data #1739

feat: Update Switch form data #1739

---

api/apps/canvas_app.py
api/apps/system_app.py
rag/svr/task_executor.py

add taskexecutor status check

---

docs/quickstart.mdx

How to make your changes to vm.max_map_count persistent on macOS

---

web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/switch-form/index.tsx
web/src/pages/flow/utils.ts

feat: Delete Answer and Relevant from RestrictedUpstreamMap of Switch #1739

feat: Delete Answer and Relevant from RestrictedUpstreamMap of Switch #1739

---

graphrag/graph_extractor.py

show error log of KG extraction

---

graphrag/graph_extractor.py
rag/nlp/query.py

filter out + in es query

---

agent/canvas.py
agent/component/exesql.py
api/apps/canvas_app.py

Fix component exesql bug

---

agent/component/exesql.py

Refactor component exesql

---

README.md
README_ja.md
README_ko.md
README_zh.md

Add Korean translation for the `README.md` file.
This translation aims to accurately convey the meaning of the original document.

[Doc] Add Korean translation for README.md

---

rag/app/one.py

#2021 add support for markdown file in one parse way

add support for markdown file in one parse way

---

web/src/hooks/flow-hooks.ts

feat: Fixed the issue where the test database connection was successful but the prompt message showed that there was no error status #1739

feat: Fixed the issue where the test database connection was successful but the prompt message showed that there was no error status #1739

---

rag/app/one.py
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts

Add Explanation for entering the API key when adding an LLM

Add Explanation for entering the API key when adding an LLM

---

web/src/components/message-input/index.tsx
web/src/hooks/chat-hooks.ts
web/src/hooks/document-hooks.ts
web/src/pages/chat/chat-container/index.tsx
web/src/pages/chat/hooks.ts
web/src/pages/chat/share/large.tsx
web/src/services/chat-service.ts
web/src/services/knowledge-service.ts
web/src/utils/api.ts

feat: Create a conversation before uploading files in it #1880

feat: Create a conversation before uploading files in it #1880

---

web/src/pages/flow/switch-form/index.tsx

feat: Remove Typography from SwitchForm #1739

feat: Remove Typography from SwitchForm #1739

---

api/db/services/document_service.py

fix uploading docx for mind map

---

api/apps/system_app.py
api/db/services/document_service.py
rag/svr/task_executor.py

support monitoring task executor

---

web/src/components/line-chart/index.tsx
web/src/hooks/user-setting-hooks.ts
web/src/interfaces/database/user-setting.ts
web/src/pages/user-setting/setting-system/index.less
web/src/pages/user-setting/setting-system/index.tsx
web/src/pages/user-setting/setting-system/task-bar-chat.tsx

fix: Add Task Executor to system panel #2061

fix: Add Task Executor to system panel #2061

---

README.md
README_ja.md
README_ko.md
README_zh.md
docs/guides/configure_knowledge_base.md
docs/guides/manage_files.md
docs/quickstart.mdx

update doc for release

---

api/apps/api_app.py
api/apps/canvas_app.py
api/apps/conversation_app.py

add message id to conversions

---

api/apps/conversation_app.py

add inferface for message thumbup

---

api/apps/conversation_app.py

add thumb up api

---

rag/svr/task_executor.py

Most 'index failure' error is caused by ES.

Provide detailed error information.

---

rag/svr/task_executor.py

alter way of alerting info of empty task

---

graphrag/graph_extractor.py

fix callback function error

---

api/apps/conversation_app.py
api/db/services/dialog_service.py

add prompt to message

---

api/apps/user_app.py

fix no tts issue

---

conf/llm_factories.json

update groq llm

---

api/apps/conversation_app.py
api/db/services/user_service.py
conf/llm_factories.json

add tts api 

---

web/src/locales/zh-traditional.ts
web/src/locales/zh.ts

add fish audio zh and zh-traditional

add fish audio zh and zh-traditional

---

web/src/components/message-item/index.tsx
web/src/hooks/chat-hooks.ts
web/src/hooks/logic-hooks.ts
web/src/interfaces/database/chat.ts

feat: Pop-up prompt message after modifying the dialog settings #2088

feat: Pop-up prompt message after modifying the dialog settings #2088

---

web/src/pages/user-setting/setting-model/index.less
web/src/pages/user-setting/setting-model/index.tsx

feat: Align the cards on the Model Providers page #2111

feat: Align the cards on the Model Providers page #2111

---

api/db/services/dialog_service.py
docker/entrypoint.sh
rag/svr/task_executor.py
rag/utils/redis_conn.py

make task resumable

---

api/apps/api_app.py
api/apps/conversation_app.py
rag/utils/redis_conn.py

remove alter log

---

requirements_arm.txt

Fix building on ARM architecture.
Fix building on ARM architecture.
- https://github.com/infiniflow/ragflow/issues/2137
- https://github.com/infiniflow/ragflow/issues/610
- https://github.com/infiniflow/ragflow/issues/434
- https://github.com/infiniflow/ragflow/issues/253

fix: build on ARM #2137

---

graphrag/search.py

fix: Use wrong variable in graph rag step.

fix(graphrag): variable refernence error

---

web/src/components/message-item/feedback-modal.tsx
web/src/components/message-item/group-button.tsx
web/src/components/message-item/hooks.ts
web/src/components/message-item/index.tsx
web/src/hooks/chat-hooks.ts
web/src/interfaces/request/chat.ts
web/src/pages/chat/hooks.ts
web/src/services/chat-service.ts
web/src/utils/api.ts
web/src/utils/chat.ts

feat: Submit Feedback #2088

---

deepdoc/parser/txt_parser.py

optimize text parser

---

agent/component/switch.py

Fix Logical operator

---

api/apps/canvas_app.py

alter message id

---

web/src/components/message-item/group-button.tsx
web/src/components/message-item/index.tsx
web/src/hooks/chat-hooks.ts
web/src/pages/chat/chat-container/index.tsx
web/src/pages/chat/hooks.ts
web/src/pages/chat/markdown-content/index.tsx
web/src/pages/chat/share/large.tsx
web/src/pages/chat/shared-hooks.ts
web/src/pages/flow/chat/box.tsx
web/src/pages/flow/chat/hooks.ts
web/src/utils/chat.ts

feat: Send message with uuid #2088

feat: Send message with uuid #2088

---

api/apps/conversation_app.py
api/db/services/task_service.py

fix delete message error

---

Dockerfile.arm

Fix the issue about `No module named 'graspologic'` #2157

---

api/apps/llm_app.py
rag/llm/chat_model.py
rag/llm/embedding_model.py

Fix some security vulnerabilities

Fix some security vulnerabilities.

---

rag/llm/__init__.py

fix anthropic bug

---

web/src/components/message-item/group-button.tsx
web/src/components/message-item/index.tsx
web/src/hooks/logic-hooks.ts
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/chat/chat-container/index.tsx
web/src/pages/chat/hooks.ts
web/src/utils/chat.ts

feat: Regenerate chat message #2088

feat: Regenerate chat message #2088

---

web/src/components/message-item/group-button.tsx
web/src/components/message-item/index.tsx
web/src/hooks/chat-hooks.ts
web/src/hooks/flow-hooks.ts
web/src/hooks/logic-hooks.ts
web/src/pages/chat/chat-container/index.tsx
web/src/pages/chat/hooks.ts
web/src/pages/chat/share/large.tsx
web/src/pages/chat/shared-hooks.ts
web/src/pages/chat/utils.ts
web/src/pages/flow/chat/box.tsx
web/src/pages/flow/chat/hooks.ts
web/src/utils/chat.ts

feat: Select derived messages from backend #2088

feat: Select derived messages from backend #2088

---

rag/svr/task_executor.py

ignore when save image fail

---

api/apps/tenant_app.py
api/db/services/user_service.py

feat: add api of tenant app

---

web/src/hooks/logic-hooks.ts
web/src/pages/chat/hooks.ts

fix: After sending the message for the first time, the returned content is not streamed out #2067 #1832

fix: After sending the message for the first time, the returned content is not streamed out #2067 #1832

---

agent/component/pubmed.py

Fix component PubMed

---

agent/component/pubmed.py

Fix component PubMed 

---

rag/llm/tts_model.py

fix re sub bug

---

web/package-lock.json
web/package.json
web/src/components/message-item/group-button.tsx
web/src/components/message-item/hooks.ts
web/src/hooks/logic-hooks.ts

feat: Play audio #2088

---

api/apps/tenant_app.py

feat: add tenant api of create & delete user

---

docs/guides/deploy_local_llm.mdx

Minor editorial updates

---

rag/nlp/query.py

enable 3 char words to finegrind tokenize

---

api/apps/kb_app.py

Add Authorization checks 
#2203

Add Authorization checks

---

rag/nlp/query.py

make term similarity robust

---

rag/llm/cv_model.py

fix zhipuCV bug

---

api/apps/llm_app.py
rag/llm/cv_model.py

fix tts add bug

---

web/src/components/message-item/group-button.tsx
web/src/components/message-item/hooks.ts
web/src/components/message-item/index.tsx
web/src/hooks/file-manager-hooks.ts
web/src/hooks/logic-hooks.ts
web/src/interfaces/database/chat.ts
web/src/utils/common-util.ts

feat: Supports pronunciation while outputting text #2088

feat: Supports pronunciation while outputting text #2088

---

agent/component/generate.py

Fix bug : bad escape \x at position xxx (line xx, column xx) in agent

---

web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx

feat: Comment out tts item #2088

feat: Comment out tts item #2088

---

agent/component/qweather.py

Fix component qweather

---

api/apps/llm_app.py
rag/llm/sequence2txt_model.py

fix QWenSeq2txt bug

---

agent/component/__init__.py
agent/component/yahoofinance.py
requirements.txt
requirements_arm.txt

Add component yahoo finance 

---

web/src/layouts/components/header/index.tsx
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/search/index.tsx
web/src/routes.ts

feat: Add SearchPage #2247

---

web/src/pages/flow/list/agent-template-modal.tsx

feat: Make agent template support HTML #1842

feat: Make agent template support HTML #1842

---

web/src/hooks/knowledge-hooks.ts
web/src/pages/search/index.less
web/src/pages/search/index.tsx

feat: Add Sider to SearchPage #2247

feat: Add Sider to SearchPage #2247

---

web/src/global.less
web/src/pages/search/index.less

feat: Set the global scroll bar style #2247

feat: Set the global scroll bar style #2247

---

web/src/pages/search/index.less
web/src/pages/search/index.tsx
web/src/pages/search/sidebar.tsx

feat: Add sidebar to SearchPage #2247

feat: Add sidebar to SearchPage #2247

---

agent/templates/DB Assistant.json
agent/templates/HR_callout_zh.json
agent/templates/customer_service.json
agent/templates/general_chat_bot.json
agent/templates/interpreter.json
agent/templates/text2sql.json
agent/templates/websearch_assistant.json

Fine tweaks to template descriptions

---

agent/component/__init__.py
agent/component/wencai.py
requirements.txt
requirements_arm.txt

Add component WenCai

---

agent/component/__init__.py
agent/component/jin10.py

Add component Jin10

---

agent/component/jin10.py
graphrag/claim_extractor.py
graphrag/community_reports_extractor.py
graphrag/entity_resolution.py
graphrag/graph_extractor.py
graphrag/mind_map_extractor.py

Fix graphrag : "role" user

---

agent/component/retrieval.py

Fix agent retrieval nothing
- [✓] Bug Fix (non-breaking change which fixes an issue)

Fix agent retrieval nothing

---

web/src/components/message-item/index.tsx
web/src/hooks/knowledge-hooks.ts
web/src/hooks/logic-hooks.ts
web/src/layouts/components/header/index.tsx
web/src/pages/chat/markdown-content/index.tsx
web/src/pages/search/hooks.ts
web/src/pages/search/index.less
web/src/pages/search/index.tsx

feat: Search for the answers you want based on the selected knowledge base #2247

feat: Search for the answers you want based on the selected knowledge base #2247

---

README.md
README_ko.md
README_zh.md
SECURITY.md
docker/docker-compose-admin-tool.yml
docker/entrypoint.sh
docker/init-kibana.sh

Added kibana to make elastic management easier.
PR #1710 did this. 
PR #1714 revert this.
This PR did again and fix some bugs.

Added kibana

---

agent/component/__init__.py
agent/component/akshare.py
requirements.txt
requirements_arm.txt

Add component AkShare

---

web/src/layouts/components/header/index.tsx

feat: Show chat tab #2247

---

rag/svr/task_executor.py

reduce interval of task executor heart beat

---

api/db/services/dialog_service.py

add elapsed time of conversation

---

docker/.env

fix: es CVE-2024-37288
https://discuss.elastic.co/t/kibana-8-15-1-security-update-esa-2024-27-esa-2024-28/366119

Update .env For CVE-2024-37288

---

api/apps/file_app.py

fix minio error

---

web/src/hooks/logic-hooks.ts
web/src/layouts/components/header/index.tsx
web/src/pages/chat/hooks.ts
web/src/pages/search/hooks.ts
web/src/pages/search/index.less
web/src/pages/search/index.tsx

feat: Click on the relevant question tag to continue searching for answers #2247

feat: Click on the relevant question tag to continue searching for answers #2247

---

web/src/layouts/components/header/index.tsx

feat: Hide search tab #2247

---

api/apps/file_app.py
api/db/services/file2document_service.py

fix error for files from filemanager

---

api/apps/sdk/assistant.py
api/apps/sdk/dataset.py
api/apps/sdk/session.py
sdk/python/ragflow/modules/chat_assistant.py
sdk/python/ragflow/modules/session.py
sdk/python/ragflow/ragflow.py
sdk/python/test/t_assistant.py
sdk/python/test/t_session.py

SDK for session

---

rag/benchmark.py
requirements.txt
requirements_arm.txt

Add benchmark ndcg@10

---

docker/nginx/ragflow.conf
web/.umirc.ts
web/src/pages/search/hooks.ts
web/src/pages/search/index.less
web/src/pages/search/index.tsx

feat: Dynamically change the background image on the search homepage every day #2247

feat: Dynamically change the background image on the search homepage every day #2247

---

api/apps/llm_app.py

add model types to factories API

---

api/apps/llm_app.py

add default model types

---

web/src/components/highlight-markdown/index.less

fix: Make markdown support line breaks #2315

fix: Make markdown support line breaks #2315

---

agent/canvas.py
agent/component/categorize.py

fix categorize error

---

web/.umirc.ts

fix: 123.60.95.134 redirect attack #2350

fix: 123.60.95.134 redirect attack #2350

---

agent/templates/DB Assistant.json
agent/templates/text2sql.json

Update templates:Text2sql and DB Description

---

web/.umirc.ts

feat: Proxy the api address to the local nginx address #2350

feat: Proxy the api address to the local nginx address #2350

---

web/src/hooks/chat-hooks.ts

feat: Catch errors in getting mindmap #2247

feat: Catch errors in getting mindmap #2247

---

agent/templates/text2sql.json

fix json error

---

api/apps/chunk_app.py
api/apps/conversation_app.py
api/db/services/dialog_service.py
api/db/services/llm_service.py
graphrag/search.py
rag/nlp/search.py

add search TAB backend api

---

api/apps/sdk/doc.py
sdk/python/ragflow/__init__.py
sdk/python/ragflow/modules/base.py
sdk/python/ragflow/modules/dataset.py
sdk/python/ragflow/modules/document.py
sdk/python/ragflow/ragflow.py
sdk/python/test/ragflow.txt
sdk/python/test/t_document.py

update sdk document

---

web/src/pages/search/index.less
web/src/pages/search/index.tsx
web/src/pages/search/sidebar.tsx

feat: Cover the entire search page with a background image #2247

feat: Cover the entire search page with a background image #2247

---

web/src/interfaces/database/knowledge.ts
web/src/pages/search/index.less
web/src/pages/search/index.tsx
web/src/pages/search/sidebar.tsx

feat: Use Tree to display the knowledge base list on the search page #2247

feat: Use Tree to display the knowledge base list on the search page #2247

---

api/apps/chunk_app.py
api/apps/conversation_app.py
api/db/services/dialog_service.py
graphrag/mind_map_extractor.py
rag/llm/embedding_model.py
rag/nlp/search.py

debug backend API for TAB 'search'

---

agent/component/yahoofinance.py
requirements.txt
requirements_arm.txt

Fix volcengine yfinance confliction

---

rag/benchmark.py

Add RAGFlow benchmark

---

web/src/components/highlight-markdown/index.tsx
web/src/components/image/index.less
web/src/components/image/index.tsx
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/search/index.less
web/src/pages/search/index.tsx

feat: Wrap the searched chunk with a Popover #2247

feat: Wrap the searched chunk with a Popover #2247

---

web/src/interfaces/database/knowledge.ts
web/src/pages/search/index.tsx

feat: Click on the chunk on the search page to locate the corresponding file location #2247

feat: Click on the chunk on the search page to locate the corresponding file location #2247

---

requirements.txt
requirements_arm.txt

fix pip install error

---

web/src/components/highlight-markdown/index.tsx
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/search/index.less
web/src/pages/search/index.tsx

feat: Modify the style of the answer card on the search page #2247

feat: Modify the style of the answer card on the search page #2247

---

web/src/interfaces/database/knowledge.ts
web/src/pages/search/index.less
web/src/pages/search/index.tsx

feat: When the mindmap data is empty, it will not be displayed on the search page #2247

feat: When the mindmap data is empty, it will not be displayed on the search page #2247

---

rag/nlp/__init__.py
rag/nlp/search.py
rag/utils/__init__.py

make highlight friendly to English

---

graphrag/mind_map_extractor.py

fix empty children in mindmap

---

rag/nlp/query.py
rag/nlp/search.py

boost highlight performace

---

agent/component/rewrite.py

refine the warning message for rewrite component

---

rag/llm/embedding_model.py

fix batch size error for qianwen embedding

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts

feat: Add html to the description text of the parsing method general #336

feat: Add html to the description text of the parsing method general #336

---

api/apps/sdk/doc.py

fix duplicate function name

---

README.md
README_ja.md
README_ko.md
README_zh.md
docs/guides/configure_knowledge_base.md
docs/guides/manage_files.md
docs/quickstart.mdx

prepare document for release

---

web/src/components/message-item/hooks.ts
web/src/interfaces/database/chat.ts
web/src/pages/chat/chat-container/index.tsx
web/src/pages/chat/context.ts
web/src/pages/chat/hooks.ts

feat: After the voice in the new conversation window is played, jump to the tab of the conversation #1877

feat: After the voice in the new conversation window is played, jump to the tab of the conversation #1877

---

docs/guides/agentic_rag/agent_introduction.md

Update and rename agentic_rag_introduction.md to agent_introduction.md

---

web/src/hooks/chat-hooks.ts
web/src/pages/chat/hooks.ts

feat: When voice is turned on, the page will not display an empty reply message when the answer is empty #1877

feat: When voice is turned on, the page will not display an empty reply message when the answer is empty #1877

---

api/apps/file2document_app.py
api/db/services/file_service.py

fix ppt file from filemanager error

---

sdk/python/ragflow/modules/chunk.py

rename create_timestamp_flt to create_timestamp_float

---

api/apps/file2document_app.py
api/db/services/file_service.py

fix parser for pptx of which files are from filemanager

---

api/apps/llm_app.py

Add VolcEngine to create api_key format error
When constructing the json string, there was an extra "," at the end, which caused a formatting error. This commit fixed the problem.

fix(Add model api): Add VolcEngine to create api_key format error

---

api/apps/conversation_app.py
api/apps/llm_app.py
rag/llm/tts_model.py

refine TTS

---

api/apps/api_app.py
api/apps/dataset_api.py
api/apps/document_app.py
api/apps/file_app.py
api/apps/sdk/doc.py
api/db/services/file2document_service.py
rag/svr/task_executor.py

https://github.com/infiniflow/ragflow/issues/2496

Storage: Rename all the variables about get file to storage from minio.

---

api/apps/llm_app.py

BugFix: Fixed api_key generation error for VolcEngine with python's f-string syntax

BugFix: Fixed api_key generation error for VolcEngine

---

api/apps/llm_app.py
rag/llm/chat_model.py

refactor add LLM

---

rag/llm/chat_model.py

rm key set in xinference

---

api/apps/__init__.py
api/apps/apis/datasets.py
api/apps/apis/documents.py
api/apps/services/dataset_service.py
sdk/python/ragflow/ragflow.py

1. Fixed swagger docs error in nginx external port
2. Add retrieval api
3. Add documentation for SDK API

fix(API): fixed swagger docs error in nginx external port

---

rag/app/naive.py
rag/llm/chat_model.py

make excel parsing configurable

---

rag/llm/cv_model.py
rag/llm/embedding_model.py
rag/llm/rerank_model.py
rag/llm/sequence2txt_model.py

refine xinference

---

web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/chat/chat-configuration-modal/prompt-engine.tsx

feat: Refine reteival of multi-turn conversation #2362

feat: Refine reteival of multi-turn conversation #2362

---

web/src/hooks/user-setting-hooks.ts

fix: Initial language is English, but the UI is in Chinese #2514

fix: Initial language is English, but the UI is in Chinese #2514

---

agent/component/rewrite.py

fix component rewrite bug

---

api/db/services/dialog_service.py

refine markdown prompt

---

rag/nlp/search.py

refine using rerank model

---

docs/references/faq.md

Streaming output is supported, dialogue share is not

---

api/apps/llm_app.py

add an API of delete llm supplier

---

api/apps/canvas_app.py
api/apps/llm_app.py

refine multi-turn chat in agent

---

web/src/assets/svg/yahoo-finance.svg
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/flow-drawer/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/yahoo-finance-form/index.tsx

feat: Add component YahooFinance #1739

feat: Add component YahooFinance #1739

---

api/apps/llm_app.py
api/settings.py
deepdoc/parser/pdf_parser.py
rag/llm/embedding_model.py
rag/llm/rerank_model.py

add lighten control

---

rag/nlp/rag_tokenizer.py

Fix tokenizer bug

---

web/src/hooks/user-setting-hooks.tsx
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts

feat: If the model is not set, a pop-up window will remind the user  #2295

feat: If the model is not set, a pop-up window will remind the user  #2295

---

Dockerfile.scratch
poetry.lock

remove onnx copy command from dockerfile

---

agent/component/__init__.py
agent/component/concentrator.py

Add component Concentrator

---

agent/component/concentrator.py
agent/test/dsl_examples/categorize.json
agent/test/dsl_examples/concentrator_message.json

Update dsl_examples and Fix component concentrator

---

conf/service_conf.yaml

Fix soft link. Close #2587

---

api/settings.py

fix AzureOpenAI  issue`

---

agent/component/wencai.py
agent/templates/investment_advisor.json

Remove WenCai imageurl and update investment_advisor prompt

---

api/apps/dataset_api.py
api/apps/document_app.py

force eml file to be parsed by EMAIL

---

rag/llm/chat_model.py

Update Yichat base_url

---

graphrag/leiden.py

remove repeat func

---

api/db/services/llm_service.py
graphrag/index.py
rag/app/knowledge_graph.py
rag/llm/chat_model.py
rag/utils/__init__.py

- Fix typo
- Remove unused import
- Format code

style: fix typo and format code

---

web/src/assets/svg/plus-circle-fill.svg
web/src/hooks/chat-hooks.ts
web/src/pages/chat/index.tsx

fix:  Fixed the issue where the conversation list was not displayed on the conversation page #2625

fix:  Fixed the issue where the conversation list was not displayed on the conversation page #2625

---

rag/svr/task_executor.py

- fix typo
- fix string format
- format import

handle nits in task_executor

---

rag/settings.py

Fix logger error: AttributeError: 'Logger' object has no attribute 'basicConfig'

Fix logger error

---

api/apps/sdk/doc.py
sdk/python/ragflow/modules/chunk.py
sdk/python/test/t_document.py

change chunk.status to chunk.available

---

graphrag/utils.py

The default value of Python function parameters cannot be mutable. Modifying this parameter inside the function will permanently change the default value

Fix mutable default argument

---

api/db/services/task_service.py

Refactoring large integers to improve readability

---

agent/templates/general_chat_bot.json

refine general purpose chat bot

---

deepdoc/parser/utils.py
rag/app/book.py
rag/app/laws.py
rag/app/one.py
rag/app/qa.py
rag/app/table.py

rename get_txt to get_text

---

agent/templates/general_chat_bot.json

fix template error

---

web/src/pages/user-setting/setting-model/ollama-modal/index.tsx

change url of local llm deploy guide 

---

web/src/pages/flow/qweather-form/index.tsx

fix: Filter the timePeriod options based on the userType parameter #1739

fix: Filter the timePeriod options based on the userType parameter #1739

---

README.md
README_ja.md
README_ko.md
README_zh.md

Updated CN readme

---

Dockerfile.scratch.oc9
docker/docker-compose-CN-oc9.yml
docker/docker-compose-gpu-CN-oc9.yml

added back oc9

---

README_ja.md

Translated Japanese README

---

Dockerfile
Dockerfile.slim
README_zh.md
download_deps.py

Fixed huggingface url. Close #2665

Fixed huggingface url

---

web/src/hooks/logic-hooks.ts

fix: Fixed an issue where quotes in messages could not be displayed #2677

fix: Fixed an issue where quotes in messages could not be displayed #2677

---

.github/workflows/tests.yml

added tests.yml

---

.github/workflows/tests.yml

fix tests.yml

---

README.md
README_ja.md
README_ko.md
README_zh.md

refine readme

---

graphrag/mind_map_extractor.py

format mind_map_extractor code

format mind_map_extractor code

---

graphrag/entity_resolution.py

Refactoring entity_resolution

---

rag/llm/chat_model.py

fix error in exception

---

.github/workflows/tests.yml
Dockerfile
Dockerfile.slim

Updated Dockerfile

---

.github/workflows/tests.yml
Dockerfile
Dockerfile.slim
README.md
README_ja.md
README_ko.md
README_zh.md
docs/guides/develop/build_docker_image.md
download_deps.py

Updated Dockefile to use cache

Updated Dockefile to use cache

---

.github/workflows/tests.yml
Dockerfile
Dockerfile.slim
docker/.env
download_deps.py

Fix Dockerfile for arm64

---

Dockerfile.slim

Fix Dockerfile.slim

---

Dockerfile
Dockerfile.slim

Fix poetry cache

---

.github/workflows/tests.yml
Dockerfile
Dockerfile.slim
download_deps.py

build multi-arch image

---

api/utils/api_utils.py

Redeclared 'get_json_result' defined above without usage
line 99 VS line 218

remove redeclared get_json_result func

---

agent/component/generate.py

fix re.escape problem

---

deepdoc/vision/operators.py

chore: update operators.py

---

api/db/services/llm_service.py
rag/llm/__init__.py
rag/llm/sequence2txt_model.py
rag/llm/tts_model.py
web/src/pages/user-setting/setting-model/ollama-modal/index.tsx

support sequence2txt and tts model in Xinference

---

api/db/services/dialog_service.py

Add query parts to lamp

---

web/.umirc.ts
web/src/assets/svg/tushare.svg
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/flow-drawer/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/tushare-form/index.tsx

feat: Add component  TuShare  #1739

feat: Add component  TuShare  #1739

---

api/settings.py

Fix LIGHTEN. Close #2723

---

rag/nlp/search.py

expand rerank range

---

rag/app/naive.py

Fix docx images

---

README.md
README_ja.md
README_ko.md
README_zh.md

Docs:fix user guide links

---

README.md
README_ja.md
README_ko.md
README_zh.md
docs/quickstart.mdx

Fix README description

---

Dockerfile
Dockerfile.slim
README.md
docker/.env
docs/quickstart.mdx

1. Fix typo
2. Update comments.

Fix README and some comments

---

rag/llm/chat_model.py

fix bedrock issue

---

deepdoc/parser/pdf_parser.py

when use slim image, remove ```torch``` denpendency.
- [✓] Bug Fix (non-breaking change which fixes an issue)

fix: torch dependency start error

---

README.md
README_ja.md
README_ko.md
README_zh.md
docs/quickstart.mdx

Updated instructions on downloading RAGFlow Slim and RAGFlow all-in-one.

---

web/src/routes.ts

(cherry picked from commit 8d11a070b2fc88285a7cff1ab85ebefee84b6c64)
fix document preview error in file manager.

fix: document preview

---

api/db/init_data.py
rag/llm/rerank_model.py

reduce rerank batch size

---

README.md
README_ja.md
README_ko.md
README_zh.md

Fixed broken links.

---

api/apps/llm_app.py
api/settings.py
rag/nlp/__init__.py

fix LIGHTEN issue

---

api/apps/document_app.py
api/db/services/document_service.py
api/db/services/file_service.py
web/src/pages/chat/markdown-content/index.tsx

1. fix white screen issue when chat response
2. thumbnail bug when document not support

fix chat and thumbnail bug

---

agent/component/retrieval.py
agent/component/rewrite.py

refine components retrieval and rewrite

---

api/apps/sdk/doc.py
api/apps/sdk/session.py
api/db/services/dialog_service.py
api/db/services/document_service.py
api/http_api.md
api/python_api_reference.md
sdk/python/ragflow/modules/chat.py
sdk/python/ragflow/modules/session.py
sdk/python/test/t_session.py

Refactor API for document and session.

Refactor API for document and session

---

agent/canvas.py
rag/nlp/query.py

refine token similarity

---

web/src/components/message-history-window-size-item.tsx

feat: Fix translation issue of message_history_window_size #1739

feat: Fix translation issue of message_history_window_size #1739

---

api/apps/sdk/chat.py
api/apps/sdk/dataset.py
api/apps/sdk/doc.py
api/apps/sdk/session.py
api/http_api.md
api/python_api_reference.md
sdk/python/ragflow/modules/base.py
sdk/python/ragflow/modules/dataset.py
sdk/python/ragflow/modules/document.py
sdk/python/ragflow/ragflow.py
sdk/python/test/t_document.py

Refactor Document API

---

api/http_api.md
api/python_api_reference.md

Updated chat APIs

---

api/apps/document_app.py
rag/app/qa.py

let presentation do raptor

---

web/src/pages/flow/constant.tsx
web/src/pages/flow/hooks.ts

feat: Generate operator names in an auto-incremental manner #1739

feat: Generate operator names in an auto-incremental manner #1739

---

api/apps/sdk/session.py
api/apps/system_app.py
api/db/db_models.py

refine API token application

---

api/apps/api_app.py
api/apps/system_app.py
api/utils/api_utils.py

refactor api util

---

api/apps/system_app.py

add rm token

---

web/.umirc.ts
web/src/components/api-service/chat-overview-modal/api-content.tsx
web/src/components/highlight-markdown/index.less
web/tsconfig.json

feat: Configure the root directory alias #1739

feat: Configure the root directory alias #1739

---

api/python_api_reference.md

Updated file management-related APIs

Draft: Updated file management-related APIs

---

api/python_api_reference.md

Miscellaneous minor updates

---

web/src/components/message-input/index.tsx
web/src/hooks/document-hooks.ts
web/src/pages/chat/hooks.ts
web/src/pages/chat/markdown-content/index.less
web/src/pages/chat/markdown-content/index.tsx
web/src/services/knowledge-service.ts

fix: Fixed the issue of error reporting when uploading files in the chat box #2897

fix: Fixed the issue of error reporting when uploading files in the chat box #2897

---

api/python_api_reference.md

DRAFT: Miscellaneous proofedits on Python APIs

---

conf/llm_factories.json

add zhipu glm-4-9b

---

api/apps/sdk/chat.py
api/apps/sdk/dataset.py
api/apps/sdk/doc.py
api/apps/sdk/session.py
api/db/db_models.py
api/utils/api_utils.py
sdk/python/ragflow/modules/base.py
sdk/python/ragflow/modules/chat.py
sdk/python/ragflow/modules/dataset.py
sdk/python/ragflow/modules/document.py
sdk/python/ragflow/ragflow.py
sdk/python/test/t_document.py

Fix some issues in API

---

api/db/services/document_service.py

fix thumbnail issue

---

deepdoc/parser/pdf_parser.py

bigger resolution for OCR

---

api/http_api_reference.md
api/python_api_reference.md
web/src/components/api-service/chat-overview-modal/api-content.tsx

DRAFT: Miscellaneous updates to HTTP API reference

---

api/utils/file_utils.py

fix thumbnail_img NoneType error

Fix thumbnail_img NoneType error

---

agent/component/crawler.py
agent/component/invoke.py

add component invoke

---

rag/app/manual.py
rag/app/naive.py
rag/app/qa.py

make titles in markdown not be splited with following content

---

api/http_api_reference.md
api/python_api_reference.md

DRAFT: Updated python and http api references

---

api/apps/chunk_app.py
rag/llm/rerank_model.py

fix SILICONFLOW rerank error

---

agent/component/generate.py

fix generate string join issue

---

web/src/components/auto-keywords-item.tsx
web/src/components/chunk-method-modal/hooks.ts
web/src/components/chunk-method-modal/index.tsx
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx

feat: Added auto_keywords and auto_questions fields to the parsing configuration page #2687

feat: Added auto_keywords and auto_questions fields to the parsing configuration page #2687

---

rag/svr/task_executor.py

refactor auto keywords and auto question

---

api/http_api_reference.md
api/python_api_reference.md

Updated HTTP API Reference (document, chat assistant, session, chat)

---

api/apps/sdk/dataset.py
api/apps/sdk/doc.py
api/utils/api_utils.py
sdk/python/ragflow/ragflow.py
sdk/python/test/common.py
sdk/python/test/conftest.py
sdk/python/test/t_chat.py
sdk/python/test/t_dataset.py
sdk/python/test/t_document.py
sdk/python/test/t_session.py
sdk/python/test/test_sdkbase.py

Test Cases

---

api/http_api_reference.md

Remove defaults to 'None'

---

web/src/components/auto-keywords-item.tsx

feat: Limit the maximum value of auto keywords to 30 #2687

feat: Limit the maximum value of auto keywords to 30 #2687

---

api/http_api_reference.md
api/python_api_reference.md

Miscellaneous updates to HTTP and PYthon APIs

---

api/http_api_reference.md
api/python_api_reference.md

Miscellaneous updates to HTTP API Reference

---

api/apps/sdk/chat.py
api/apps/sdk/doc.py
sdk/python/ragflow/modules/chat.py
sdk/python/ragflow/ragflow.py
sdk/python/test/t_chat.py
sdk/python/test/t_session.py

Fix some issues in API and test

Fix some issues in API and test

---

rag/llm/chat_model.py

make gemini robust

---

api/http_api_reference.md

Minor editorial updates to the HTTP API reference

---

conf/llm_factories.json

add model moonshot-v1-auto

---

agent/component/baidufanyi.py

fix baidufanyi param error

---

api/apps/sdk/dify_retrieval.py
api/apps/sdk/doc.py
api/http_api_reference.md
sdk/python/ragflow/modules/chat.py
sdk/python/ragflow/modules/chunk.py
sdk/python/ragflow/modules/dataset.py
sdk/python/ragflow/modules/document.py
sdk/python/ragflow/modules/session.py
sdk/python/ragflow/ragflow.py

Turn resource to plural form

---

agent/component/retrieval.py
agent/templates/DB Assistant.json
agent/templates/HR_callout_zh.json
agent/templates/customer_service.json
agent/templates/general_chat_bot.json
agent/templates/interpreter.json
agent/templates/investment_advisor.json
agent/templates/medical_consultation.json
agent/templates/text2sql.json
agent/templates/websearch_assistant.json

agent template upgrade

---

web/package-lock.json
web/package.json
web/src/assets/svg/invoke-ai.svg
web/src/locales/en.ts
web/src/locales/zh-traditional.ts
web/src/locales/zh.ts
web/src/pages/flow/constant.tsx
web/src/pages/flow/flow-drawer/index.tsx
web/src/pages/flow/form/invoke-form/dynamic-variables.tsx
web/src/pages/flow/form/invoke-form/hooks.ts
web/src/pages/flow/form/invoke-form/index.less
web/src/pages/flow/form/invoke-form/index.tsx
web/src/pages/flow/hooks.ts
web/src/pages/flow/interface.ts

feat: Add component Invoke #2908

feat: Add component Invoke #2908

---

rag/app/qa.py
rag/llm/chat_model.py

refactor error message of qwen

---

rag/llm/chat_model.py

fix local variable ans

---

api/apps/sdk/dify_retrieval.py

Modify the response of metadata in Dify retrieval api
resolve   #2914

fix: modify the response of metadata in Dify retrieval api
