web/src/hooks/knowledgeHook.ts
fix: all documents in the knowledge base cannot be selected if they have not been parsed. 
Issue link: #214
=> fix: all documents in the knowledge base cannot be selected if they have not been parsed. #214

docs/llm_api_key_setup.md
fix a broken url for moonshot 
`https://platform.moonshot.cn/docs/docs` to `https://platform.moonshot.cn/docs`
Issue link:None
=> docs: fix a broken url

docker/docker-compose-CN.yml, docker/docker-compose-base.yml, docker/docker-compose.yml
- remove version top-level element in the compose.yml file
when use command `docker compose -f docker-compose-CN.yml up -d` ,it will waring,[maybe it appear after v25,5](https://github.com/mailcow/mailcow-dockerized/issues/5797#issuecomment-2011349228)
ref to https://docs.docker.com/compose/intro/history/#docker-compose-cli-versioning
> Version one of the Docker Compose command-line binary was first released in 2014. It was written in Python, and is invoked with docker-compose. Typically, Compose V1 projects include a top-level version element in the compose.yml file, with values ranging from 2.0 to 3.8, which refer to the specific [file formats](https://docs.docker.com/compose/intro/history/#compose-file-format-versioning).
> Version two of the Docker Compose command-line binary was …
=> remove version top-level element in the compose.yml file

docs/ollama.md, docs/xinference.md
make `<xxxx>` visiable
it was misinterpreted as part of the HTML tags
Issue link:None
=> make `<xxxx>` visiable

README.md, docs/faq.md
=> Added some debugging FAQs

rag/app/table.py
When handling some excel file, following error might occur, looks like some clmns item could be in type 'int':
[INFO] [2024-04-17 16:01:40,644] [_internal._log] [line:96]: 172.29.0.6 - - [17/Apr/2024 16:01:40] "GET /v1/document/list?kb_id=615d3698fc6711ee85920242ac140006&page=1&page_size=10 HTTP/1.1" 200 - Traceback (most recent call last):
File "/ragflow/rag/svr/task_executor.py", line 130, in build
cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/ragflow/rag/app/table.py", line 198, in chunk
py_clmns = [
^
File "/ragflow/rag/app/table.py", line 200, in <listcomp>
re.sub(
File "/root/miniconda3/envs/py11/lib/python3.11/re/__init__.py", line 185, in sub
return _compile(pattern, …
=> Update table.py to convert clmns to string

api/apps/__init__.py, api/utils/file_utils.py, conf/mapping.json, conf/service_conf.yaml, docker/docker-compose.yml, docker/service_conf.yaml, rag/app/naive.py, rag/settings.py, rag/svr/task_broker.py, rag/svr/task_executor.py, rag/utils/redis_conn.py
=> add redis to accelerate access of minio

rag/app/book.py, rag/app/laws.py, rag/app/naive.py, rag/app/one.py
=> remove doc from supported processing types

api/utils/file_utils.py, rag/app/book.py, rag/app/laws.py, rag/app/naive.py, rag/app/one.py, requirements.txt
Add `.doc` file parser, using tika.
```
pip install tika
```
```
from tika import parser
from io import BytesIO
def extract_text_from_doc_bytes(doc_bytes):
file_like_object = BytesIO(doc_bytes)
parsed = parser.from_buffer(file_like_object)
return parsed["content"]
```
=> Add `.doc` file parser.

README.md, README_ja.md, README_zh.md, docs/faq.md
=> Updated minimum RAM capacity

docs/faq.md
=> there's no need to connect to Redis in order to use Redis

docker/docker-compose-base.yml
Since Kibana service is not currently being used, the associated volume 'kibanadata' has been commented out in the Docker Compose file. This change helps to prevent the allocation of unnecessary resources and simplifies the configuration.
=> chore: disable Kibana volume storage in Docker Compose

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/file-manager/action-cell/index.tsx
#345
feat: add Tooltip to action icon of FileManager
=> feat: add Tooltip to action icon of FileManager

api/apps/file2document_app.py, api/apps/file_app.py, api/apps/user_app.py, api/db/services/file_service.py
=> fix bug of file management

api/apps/file_app.py, api/db/services/file2document_service.py, api/db/services/file_service.py, api/db/services/task_service.py, rag/svr/task_broker.py, rag/svr/task_executor.py
=> fix bug about fetching file from minio

docker/.env, docs/faq.md
=> refine document by using latest as version number

api/apps/chunk_app.py, api/db/services/task_service.py, deepdoc/parser/docx_parser.py, deepdoc/parser/pdf_parser.py, deepdoc/parser/resume/entities/corporations.py, deepdoc/parser/resume/step_two.py, deepdoc/vision/table_structure_recognizer.py, rag/app/book.py, rag/app/laws.py, rag/app/manual.py, rag/app/naive.py, rag/app/one.py, rag/app/paper.py, rag/app/presentation.py, rag/app/qa.py, rag/app/resume.py, rag/app/table.py, rag/nlp/__init__.py, rag/nlp/query.py, rag/nlp/rag_tokenizer.py, rag/nlp/search.py, rag/nlp/term_weight.py, rag/svr/cache_file_svr.py, rag/svr/task_broker.py
=> refine code

requirements.txt
This commit resolves an issue where the 'redis' package was inadvertently omitted from the requirements.txt file. The package has now been added to ensure all dependencies are correctly installed for the project.
=> Fix: missing 'redis' package in requirements.txt

api/db/init_data.py, rag/llm/__init__.py, rag/llm/chat_model.py
=> add support for deepseek

Dockerfile, Dockerfile.cuda, Dockerfile.scratch, Dockerfile.scratch.oc9
=> update docker file to support low version npm package

rag/svr/task_executor.py
=> make sure  the error will be recorded.

api/apps/llm_app.py, api/db/services/task_service.py
=> make sure to raise exception if redis is not there

README.md
=> Minor editorial updates

api/apps/document_app.py, api/apps/file_app.py, api/db/__init__.py, api/db/db_models.py, api/db/services/document_service.py, api/db/services/file2document_service.py, api/db/services/file_service.py, docker/entrypoint.sh, rag/svr/task_executor.py, requirements_dev.txt
Let file in knowledgebases visible in file manager.
#162
=> let file in knowledgebases visible in file manager

web/src/interfaces/database/file-manager.ts, web/src/pages/file-manager/file-toolbar.tsx
#764 fix: hide the add button when the folder is a knowledge base
=> fix: hide the add button when the folder is a knowledge base

web/src/components/pdf-previewer/hooks.ts, web/src/components/pdf-previewer/index.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/components/document-preview/preview.tsx, web/src/pages/add-knowledge/components/knowledge-testing/testing-control/index.tsx, web/src/pages/document-viewer/file-error/index.tsx
fix: remove Top K in retrieval testing  #770
fix: if the document parsing fails, the error message returned by the backend is displayed.
=> fix: remove Top K in retrieval testing  #770 and if the document parsing fails, the error message returned by the backend is displayed

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/file-manager/hooks.ts
fix: .knowledgebase folder can be deleted bug 
fix:  change "Add file to knowledge base" to "Link file to knowledge base" bug
#783 #784
=> fix: .knowledgebase folder can be deleted bug and change "Add file to knowledge base" to "Link file to knowledge base" bug

docs/manage_files.md
Added guide with instructions on managing files in RAGFlow.
=> Added file management guide

api/apps/document_app.py, api/apps/file_app.py
=> fix: can't capitalize file or folder name

docs/configure_knowledge_base.md, docs/quickstart.md
=> Initial draft of configure knowledge base

api/apps/api_app.py, rag/llm/chat_model.py
=> fix stream chat for ollama

web/src/components/chunk-method-modal/index.tsx, web/src/components/layout-recognize.tsx, web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx, web/src/pages/chat/chat-container/index.less, web/src/pages/chat/chat-container/index.tsx, web/src/pages/chat/share/index.less, web/src/pages/chat/share/large.tsx
fix: thumbnails are too large in the chat box #818
=> fix: thumbnails are too large in the chat box #818

api/apps/document_app.py, api/apps/file2document_app.py, api/apps/file_app.py, api/apps/kb_app.py, api/db/services/document_service.py
=> fix doc number miss-match issue

api/apps/api_app.py, api/apps/conversation_app.py, rag/llm/chat_model.py
=> fix zhipuAI stream issue

api/db/init_data.py, api/db/services/document_service.py, api/db/services/knowledgebase_service.py
=> correct mismatched kb doc number

api/apps/api_app.py, api/apps/conversation_app.py, api/db/services/dialog_service.py
=> fix bug of chat without stream

api/apps/kb_app.py
=> fix bug about removing KB.

api/db/db_models.py, web/src/constants/knowledge.ts
=> The default max tokens of 215 is too small, answers are often cut off.I will modify it to 512 to address this issue.

deepdoc/parser/excel_parser.py, rag/app/one.py, rag/utils/minio_conn.py
=> fix minio helth bug

web/src/components/chunk-method-modal/index.tsx, web/src/components/parse-configuration/index.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx, web/src/pages/add-knowledge/components/knowledge-setting/hooks.ts
Implements RAPTOR for better chunking #882
=> Implements RAPTOR for better chunking #882

web/src/components/parse-configuration/index.tsx, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
Implements RAPTOR for better chunking #882
=> feat: RAPTOR is not displayed when the parsing method is picture.

deepdoc/parser/pdf_parser.py
When pdfparser call `_naive_vertical_merge` method，there is a "not concating feature " value  by computing difference between `b` and `b_`'s layoutno ,but actually is `b` and `b`. I think it's a bug, so fix it. Please check again.
=> fixbug for computing 'not concating feature'

web/src/interfaces/database/flow.ts, web/src/pages/flow/canvas/index.tsx, web/src/pages/flow/canvas/node/index.less, web/src/pages/flow/canvas/node/index.tsx, web/src/pages/flow/hooks.ts, web/src/pages/flow/interface.ts, web/src/pages/flow/mock.tsx, web/src/pages/flow/utils.ts
feat: build react flow nodes and edges from mock data #918
=> feat: build react flow nodes and edges from mock data #918

README.md, README_ja.md, README_zh.md, docs/guides/configure_knowledge_base.md, docs/references/faq.md
=> Expanded list of locally deployed embedding models

deepdoc/parser/pdf_parser.py, rag/app/naive.py, rag/nlp/rag_tokenizer.py, requirements.txt, requirements_dev.txt
=> fix #917 #915

docker/README.md, docs/guides/llm_api_key_setup.md, docs/quickstart.md, docs/references/api.md
=> Expanded the supported LLM list

rag/utils/redis_conn.py
After being idle for a while (When Redis Queue exceeds the SVR_QUEUE_RETENTION(60*60) expiration time), new tasks need to be cancel and redo.
When use xgroup_create to create a consumer group, set the ID to "$", meaning that only messages added to the stream after the group is created will be visible to new consumers. If the application scenario requires processing messages that already exist in the queue, you might need to change this ID to "0", so that the new consumer group can read all messages from the beginning.
=> Fix:After being idle for a while, new tasks need to be cancel and redo

api/db/init_data.py, rag/llm/chat_model.py
=> set ollama keep_alive

README.md, README_ja.md, README_zh.md, deepdoc/parser/__init__.py, deepdoc/parser/docx_parser.py, deepdoc/parser/excel_parser.py, deepdoc/parser/pdf_parser.py, deepdoc/parser/ppt_parser.py, deepdoc/parser/resume/__init__.py, deepdoc/parser/resume/entities/corporations.py, deepdoc/parser/resume/entities/degrees.py, deepdoc/parser/resume/entities/industries.py, deepdoc/parser/resume/entities/regions.py, deepdoc/parser/resume/entities/schools.py, deepdoc/parser/resume/step_one.py, deepdoc/parser/resume/step_two.py, deepdoc/vision/__init__.py, deepdoc/vision/postprocess.py
=> Update readme and add license

conf/service_conf.yaml, docker/.env, docker/docker-compose-base.yml, docker/service_conf.yaml, rag/utils/es_conn.py
Using password authentication to access ElasticSearch is essential, especially in a production environment. 
This PR will enable password access support.
=> feat: Support Password Access for ElasticSearch

web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
feat: modify the chinese translation of self-rag #1069
=> feat: modify the chinese translation of self-rag #1069

README.md, README_ja.md, README_zh.md
=> documentaion for self-rag

web/src/components/message-item/index.less, web/src/components/message-item/index.tsx, web/src/hooks/logicHooks.ts, web/src/interfaces/database/flow.ts, web/src/pages/flow/canvas/edge/index.tsx, web/src/pages/flow/chat/box.tsx, web/src/pages/flow/chat/hooks.ts, web/src/pages/flow/chat/index.less, web/src/pages/flow/hooks.ts, web/src/pages/flow/store.ts
=> feat: add FlowChatBox #918 

README.md, README_ja.md, README_zh.md, docs/guides/deploy_local_llm.md, docs/quickstart.mdx, docs/references/api.md
=> Updated Ollama part of local deployment

rag/llm/embedding_model.py
I implemented infinity, a fast vector embeddings engine.
=> infinity: Update embedding_model.py

Dockerfile, Dockerfile.arm, Dockerfile.scratch, Dockerfile.scratch.oc9, requirements_arm.txt
=> Fix Docker image building failure on MacOS (ARM architecture)

api/apps/dataset_api.py, sdk/python/ragflow/ragflow.py, sdk/python/test/test_dataset.py
This PR have completed both HTTP API and Python SDK for 'delete_dataset". In addition, there are tests for it.
=> delete_dataset method and tests created

deepdoc/parser/docx_parser.py, rag/app/qa.py, rag/nlp/query.py, rag/nlp/search.py
=> fix too long query exception

rag/app/qa.py
Add docx support for QA parser
=> Add docx support for QA parser

deepdoc/parser/__init__.py, deepdoc/parser/json_parser.py, rag/app/naive.py, rag/nlp/__init__.py
=> feat: support json file

web/src/pages/chat/chat-container/index.less, web/src/pages/chat/chat-container/index.tsx, web/src/pages/chat/hooks.ts, web/src/pages/chat/share/index.less, web/src/pages/chat/share/large.tsx, web/src/pages/chat/shared-hooks.ts
Optimized the chat interface (including the chat API after sharing)
1. Change the background color of the dialog box between the assistant and the user (use the theme color of the interface)
2. Add rounded corners to the dialog box
3. When the input box is empty, you can't click the send button(because some models will report an error when sending empty data)
Color reference(can be a bit subjective)：
=> Optimized the chat interface (including the chat API after sharing)

rag/app/qa.py, requirements.txt, requirements_arm.txt, requirements_dev.txt
Support displaying tables in the chunks of pdf file when using QA parser
=> Support displaying tables in the chunks of pdf file when using QA parser

web/src/components/llm-select/index.tsx, web/src/pages/flow/categorize-form/index.tsx, web/src/pages/flow/constant.tsx, web/src/pages/flow/flow-drawer/index.tsx
=> feat: add LLMSelect

web/src/components/llm-select/index.tsx, web/src/layouts/components/right-toolbar/index.tsx, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/canvas/node/index.tsx, web/src/pages/flow/categorize-form/dynamic-categorize.tsx, web/src/pages/flow/categorize-form/hooks.ts, web/src/pages/flow/categorize-form/index.tsx, web/src/pages/flow/constant.tsx
feat: add DynamicCategorize #918
=> feat: add DynamicCategorize #918

web/src/components/llm-select/index.tsx, web/src/components/llm-setting-items/index.tsx, web/src/pages/chat/chat-configuration-modal/model-setting.tsx, web/src/pages/flow/categorize-form/hooks.ts, web/src/pages/flow/categorize-form/index.tsx, web/src/pages/flow/flow-drawer/index.tsx, web/src/pages/flow/generate-form/index.tsx, web/src/pages/flow/hooks.ts, web/src/pages/flow/interface.ts, web/src/pages/flow/store.ts, web/src/pages/flow/utils.ts
feat: build categorize list from object #918
=> feat: build categorize list from object #918

api/apps/documents_api.py, sdk/python/ragflow/ragflow.py, sdk/python/test/test_document.py
Adds the functionality of deleting documentation
=> API: completed delete_doc api

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/constant.tsx, web/src/pages/flow/flow-drawer/index.tsx, web/src/pages/flow/relevant-form/index.tsx, web/src/pages/flow/rewrite-question-form/index.tsx
=> feat: add RelevantForm #918

web/src/hooks/flow-hooks.ts, web/src/pages/flow/canvas/index.tsx, web/src/pages/flow/chat/drawer.tsx, web/src/pages/flow/chat/hooks.ts
feat: pull the message list after sending the message successfully #918
=> feat: pull the message list after sending the message successfully #918

web/src/components/operate-dropdown/index.tsx, web/src/pages/flow/canvas/node/dropdown.tsx
feat: deleting a node does not require a confirmation box to pop up #918
=> feat: deleting a node does not require a confirmation box to pop up #918

api/db/services/dialog_service.py
During knowledge Q&A conversations, the user-defined rerank model's top_k parameter was not used
#1395
=> fix: use user-defined rerank model's top_k parameter when knowledge Q&A conversation

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/list/create-flow-modal.tsx, web/src/pages/flow/list/index.tsx
feat: translate graph list #918
=> feat: translate graph list #918

web/package-lock.json, web/package.json, web/src/pages/flow/canvas/node/categorize-node.tsx, web/src/pages/flow/canvas/node/index.tsx, web/src/pages/flow/canvas/node/popover.tsx, web/src/pages/flow/canvas/node/relevant-node.tsx, web/src/pages/flow/hooks.ts, web/src/pages/flow/utils.ts
feat: display the debugging results of each operator in a pop-up window #918
=> feat: display the debugging results of each operator in a pop-up window #918

README.md, README_ja.md, README_zh.md, graph/canvas.py, graph/component/baidu.py, graph/component/duckduckgosearch.py, graph/component/message.py, graph/templates/HR_callout_zh.json
=> fix no resualt bugs

docs/references/ragflow_api.md
The correct URL is http://<host_address>/v1/api , not http://<host_address>/api/v1 .
=> API doc: Correct Base URL and Dataset URL.

deepdoc/parser/pdf_parser.py
=> fix pdf_paser char content confusion

api/apps/dataset_api.py, sdk/python/ragflow/ragflow.py, sdk/python/test/test_data/lol.txt, sdk/python/test/test_document.py
Make the document start parsing.
=> API: start parsing

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/canvas/node/categorize-node.tsx, web/src/pages/flow/categorize-form/dynamic-categorize.tsx, web/src/pages/flow/categorize-form/hooks.ts, web/src/pages/flow/form-hooks.ts
feat: validate the name field of the categorize operator for duplicate names and nulls #918
=> feat: validate the name field of the categorize operator for duplicate names and nulls #918

api/db/init_data.py, rag/llm/__init__.py, rag/llm/rerank_model.py, web/src/pages/user-setting/setting-model/ollama-modal/index.tsx
support xinference rerank model
#1455
=> feat: support xinference rerank model

api/apps/llm_app.py, rag/llm/rerank_model.py
=> fix bugs of rerank model with xinference

graph/component/baidu.py, graph/component/duckduckgosearch.py
=> Fix baidusearch and duckduckgosearch

api/apps/dataset_api.py, sdk/python/ragflow/ragflow.py, sdk/python/test/test_document.py
=> API: show status of parsing

rag/llm/rerank_model.py
fix the tokens error that occurred when adding the xinference model
#1522 
root@pc-gpu-86-41:~# curl -X 'POST' 'http://127.0.0.1:9997/v1/rerank' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{
"model": "bge-reranker-v2-m3",
"query": "A man is eating pasta.",
"return_documents":"true",
"return_len":"true",
"documents": [
"A man is eating food.",
"A man is eating a piece of bread.",
"The girl is carrying a baby.",
"A man is riding a horse.",
"A woman is playing violin."
]
}'
{"id":"610a8724-3e96-11ef-81ce-08bfb886c012","results":[{"index":0,"relevance_score":0.999574601650238,"document":{"text":"A man is eating food."}},{"index":1,"relevance_score":0.07814773917198181,"document":{"text":"A man is eating a piece of …
=> fix the tokens error that occurred when adding the xinference model

deepdoc/vision/ocr.py, deepdoc/vision/recognizer.py
=> remove dependency

requirements.txt
necessary for successful installation of the fasttext==0.9.2 module
Aiming to solve issue #1547 
- [ X] Bug Fix (non-breaking change which fixes an issue)
=> Update requirements.txt with pybind11 2.13.1

Dockerfile.cuda
Fix the `Dockerfile.cuda`, as the `/root/miniconda3/envs/py11/bin/pip` is not found in the base images.
`/root/miniconda3/envs/py11/bin/pip` is not found in the base images.
=> Update the Dockerfile.cuda

api/apps/chunk_app.py, api/db/services/document_service.py
This PR solves the problem that when you delete selected chunks, the chunks can be deleted but Chunk Number doesn't change. Now you delete one chunk, the Chunk Number is reduced by one, delete two chunks, the Chunk Number is reduced by two...
#900
=> fix delete selected chunks display wrong

api/utils/t_crypt.py
The encryption should first perform base64 encoding and then encrypt, to maintain consistency with the frontend
#1620
=> modify the encryption to first perform base64 encoding and then encrypt

deepdoc/parser/pdf_parser.py
_fix: When parsing the bold content in PDF, the result is duplicated._
the detail: [When using OCR to recognize Chinese titles, the structure appears to be duplicated](https://github.com/infiniflow/ragflow/issues/1718)
=> fix: When parsing the bold content in PDF, the result is duplicated.

web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/force-graph.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/index.less, web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/modal.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/util.ts
feat: alter style of ForceGraph #162
=> feat: Alter style of ForceGraph #162

web/src/components/chunk-method-modal/index.tsx, web/src/components/entity-types-item.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/index.tsx, web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx
feat: Hide KnowledgeGraphModal #162
=> feat: Hide KnowledgeGraphModal #162

web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/force-graph.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/util.ts
…returned by the interface is empty #162
feat: Fixed the issue where the page reports an error when the graph returned by the interface is empty #162
=> feat: Fixed the issue where the page reports an error when the graph returned by the interface is empty #162

graphrag/index.py, graphrag/mind_map_extractor.py, graphrag/mind_map_prompt.py
=> refine mindmap

web/src/pages/chat/hooks.ts
fix: Unable to create a new chat assistant after closing the edit modal #1833
=> fix: Unable to create a new chat assistant after closing the edit modal #1833

web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx
fix: Entity types are only displayed when the knowledge graph is selected #1594
=> fix: Entity types are only displayed when the knowledge graph is selected #1594

api/db/services/file_service.py, web/src/interfaces/database/file-manager.ts, web/src/pages/file-manager/move-file-modal/async-tree-select.tsx
feat: Do not display arrow icons on leaf node of folders #1826
=> feat: Do not display arrow icons on leaf node of folders #1826

api/db/services/dialog_service.py
The answer in the context carries reference markers and passes them to the large model, which may include the markers in the new answer, leading to abnormal reference points.
```
{'role': 'assistant', 'content': '设置在地下或半地下空间 ##0$$。'}
```
- Bug Fix (non-breaking change which fixes an issue)
=> fix: Reference markers in the context may be carried over into the next answer

web/src/components/message-input/index.less, web/src/components/message-input/index.tsx, web/src/hooks/document-hooks.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/chat/share/large.tsx, web/src/pages/chat/shared-hooks.ts, web/src/services/knowledge-service.ts, web/src/utils/api.ts, web/src/utils/register-server.ts
feat: Delete the files uploaded in the external dialog box #1880
=> feat: Delete the files uploaded in the external dialog box #1880

web/.umirc.ts, web/src/hooks/flow-hooks.ts, web/src/pages/flow/exesql-form/index.tsx, web/src/services/flow-service.ts, web/src/utils/api.ts
feat: Test the database connection of the ExeSQL operator #1739
=> feat: Test the database connection of the ExeSQL operator #1739

rag/utils/__init__.py
Fix return type annotation in truncate function
=> fix: Fix return type annotation in truncate function

rag/llm/chat_model.py
Bugfix: usage of Bedrock models require the system prompt (for models that support it) to be provided in the API in a different way, at least that was my experience with it just today. This PR fixes it.
https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html
=> Fix Bedrock system prompt

web/src/hooks/llm-hooks.ts
fix: Filter out disabled values ​​from the llm options #2072
=> fix: Filter out disabled values ​​from the llm options #2072

api/apps/api_app.py
=> Fix  API key validation api/conversation

conf/llm_factories.json
fix the max token of Tongyi-Qianwen text-embedding-v3 model to 8k
close #2117
=> fix the max token of Tongyi-Qianwen text-embedding-v3 model to 8k

agent/canvas.py, agent/component/exesql.py, agent/templates/DB Assistant.json
Fix exeSQL component 
Update DB Assistant template 
Fix canvas Message window size
=> Fix Text2SQL

api/apps/sdk/dataset.py, api/utils/api_utils.py, sdk/python/ragflow/modules/base.py, sdk/python/ragflow/modules/dataset.py, sdk/python/ragflow/ragflow.py, sdk/python/test/t_dataset.py
Complete implementation of dataset SDK.
#1102
=> complete implementation of dataset SDK

web/src/components/message-item/group-button.tsx, web/src/components/message-item/hooks.ts, web/src/components/message-item/index.tsx, web/src/pages/flow/chat/box.tsx
feat: Hide the delete button on the agent page #2088
=> feat: Hide the delete button on the agent page #2088

api/apps/sdk/dataset.py, sdk/python/ragflow/modules/dataset.py, sdk/python/ragflow/ragflow.py
Complete DataSet SDK implementation
#1102
=> Complete DataSet SDK implementation

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
feat: Add tts Switch to chat configuration modal  #2088
=> feat: Add tts Switch to chat configuration modal  #2088

api/apps/canvas_app.py
=> fix error response disformat usage

api/apps/conversation_app.py, api/db/services/dialog_service.py
=> add stream chat with TTS

api/apps/canvas_app.py, api/apps/conversation_app.py, api/apps/dialog_app.py, api/apps/document_app.py, api/apps/kb_app.py
Add Authorization checks
#2203
=> Add Authorization checks

README.md, README_ja.md, README_ko.md, README_zh.md
=> updates dead link

web/src/layouts/components/header/index.tsx, web/src/pages/search/hooks.ts, web/src/pages/search/index.less, web/src/pages/search/index.tsx, web/src/pages/search/sidebar.tsx
feat: The search box is displayed globally when the page is loaded for the first time #2247
=> feat: The search box is displayed globally when the page is loaded for the first time #2247

agent/component/retrieval.py
the setting was kept empty for Empty_response. In expectation, this case should get a response from the LLM if can't find the references from the knowledgebase.
=> fix: empty or contains only empty strings.

web/src/components/retrieval-documents/index.tsx, web/src/layouts/components/header/index.tsx, web/src/pages/search/hooks.ts, web/src/pages/search/index.less, web/src/pages/search/index.tsx
feat: Retrieval chunks by page #2247
=> feat: Retrieval chunks by page #2247

web/package-lock.json, web/package.json, web/src/components/indented-tree/indented-tree.tsx, web/src/hooks/chat-hooks.ts, web/src/pages/search/index.less, web/src/pages/search/index.tsx
feat: Catching errors with IndentedTree #2247
=> feat: Catching errors with IndentedTree #2247

api/db/db_models.py, api/db/services/api_service.py
Add a default value for do_refer in Dialog
=> Add a default value for do_refer in Dialog

web/src/pages/search/hooks.ts, web/src/pages/search/index.less, web/src/pages/search/index.tsx
feat: Use Spin to wrap the chunk list on the search page #2247
=> feat: Use Spin to wrap the chunk list on the search page #2247

deepdoc/parser/pdf_parser.py
[#1987](https://github.com/infiniflow/ragflow/issues/1987)
When scanning PDF files character by character, the parser excluded spaces if the string did not match regex. Text from [Russian documents](https://github.com/user-attachments/files/16659706/dogovor_oferta.pdf) needs spaces, but it does not match the regex because it uses different alphabet. That's why PDFs were parsed incorrectly and were almost unusable as source. Fixed that by adding Russian alphabet to regex.
There might be problems with other languages that use different alphabets. I additionally tested [PDF in Spanish](https://www.scusd.edu/sites/main/files/file-attachments/howtohelpyourchildsucceedinschoolspanish.pdf?1338307816) and old [a-zA-Z...] regex parses it correctly with spaces.
=> fix parsing spaces in russian language PDFs (#1987)

web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
feat: If the tts model is not set, the Text to Speech switch is not allowed to be turned on #1877
=> feat: If the tts model is not set, the Text to Speech switch is not allowed to be turned on #1877

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
_This PR addresses the need to describe the "Switch" component across different languages and corrects a misleading description for a placeholder message not exclusively tied to a specific assistant type. By providing clearer and more accurate descriptions, this PR aims to improve user understanding and usability of the Switch component and the "Message Resume Assistant..." placeholder in a multilingual context._
1. **Added Descriptions for "Switch" Component**: 
- Descriptions were added for the "Switch" component in three different locales:
- **English (EN)**: Provides a concise description of what the "Switch" component does, focusing on its ability to evaluate conditions and direct the flow of execution.
- **Simplified Chinese (ZH)**: Translated the English description into Simplified …
=> Add Multi-Language Descriptions for 'Switch' Component and Update Message Assistant Placeholder

api/db/init_data.py
Fixes the _superuser_ `admin@ragflow.io` not being accessible due to how entered passwords are used. Unless this is expected behavior?
=> fix `superuser` password not base64 encoded

api/apps/chunk_app.py, api/db/services/dialog_service.py, api/db/services/llm_service.py, rag/app/naive.py
=> fix duplicated llm name betweeen different suppliers

api/apps/sdk/doc.py, sdk/python/ragflow/modules/chunk.py, sdk/python/ragflow/modules/dataset.py, sdk/python/ragflow/modules/document.py, sdk/python/ragflow/ragflow.py, sdk/python/test/t_document.py
=> rename some attributes in document sdk

api/apps/sdk/doc.py, sdk/python/ragflow/modules/chunk.py, sdk/python/ragflow/modules/document.py
=> update document sdk

api/apps/llm_app.py
=> fix self deployed llm lost

web/src/components/llm-select/index.tsx, web/src/hooks/llm-hooks.ts
fix: Add model by ollama in model provider page, user can't choose the model in chat window. #2479
=> fix: Add model by ollama in model provider page, user can't choose the model in chat window. #2479

web/src/components/llm-select/index.tsx, web/src/components/llm-setting-items/index.tsx, web/src/hooks/llm-hooks.ts
fix: Merge models of the same category #2479
=> fix: Merge models of the same category #2479

web/src/components/chunk-method-modal/index.tsx, web/src/components/excel-to-html.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx
feat: Configurable for excel, html table or row based text #2516
=> feat: Configurable for excel, html table or row based text #2516

web/src/hooks/llm-hooks.ts, web/src/interfaces/request/llm.ts, web/src/pages/user-setting/setting-model/hooks.ts, web/src/pages/user-setting/setting-model/index.tsx, web/src/services/user-service.ts, web/src/utils/api.ts
feat: Delete Model Provider #2376
=> feat: Delete Model Provider #2376

api/db/init_data.py
=> deprecate init a super user

api/apps/sdk/session.py, deepdoc/parser/pdf_parser.py, rag/llm/rerank_model.py, sdk/python/ragflow/modules/assistant.py, sdk/python/ragflow/modules/session.py, sdk/python/test/t_session.py
Fix: renrank_model and pdf_parser bugs | Update: session API
#2575
#2559
=> Fix: renrank_model and  pdf_parser bugs |  Update: session API

api/apps/api_app.py
=> Support agent for aibot

agent/component/generate.py, agent/component/switch.py
=> fix generate bug

api/apps/api_app.py
If .eml file is uploaded, there is always General method chosen for email processing, even if parsing_method is defined in the request. This change solves this issue.
=> Bug fix - email processing could be run now from API

agent/component/base.py, agent/component/concentrator.py
=> refine get_input

deepdoc/parser/txt_parser.py, deepdoc/parser/utils.py, rag/app/book.py, rag/app/laws.py, rag/app/naive.py, rag/app/one.py, rag/app/qa.py, rag/app/table.py
Add get_txt function to reduce duplicate code
=> Add get_txt function

README_ko.md
=> Translated Korean README

web/src/pages/search/hooks.ts
fix: Search page search results are cleared after output #2677
=> fix: Search page search results are cleared after output #2677

graphrag/entity_resolution.py
Simplify the usage of dictionaries
=> Simplify the usage of dict

README.md, README_ja.md, README_ko.md
This PR updates README to reflect the migration from Compose V1 (`docker-compose`) to Compose V2 (`docker compose`):
The migration details and differences between Compose V1 and Compose V2 are based on the official Docker documentation:  
[Docker Docs: Migrate to Compose V2](https://docs.docker.com/compose/releases/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2)
=> docs: Migrate README to Compose V2 syntax

.github/workflows/tests.yml, Dockerfile, download_deps.py
=> Modified download_deps.py

rag/utils/azure_sas_conn.py
=> Update azure_sas_conn.py - fixing container_url typo

rag/llm/chat_model.py
=> solve knowledgegraph issue when calling gemini model

rag/llm/embedding_model.py
=> move import positions

agent/component/exesql.py
=> Fix component exesql

rag/llm/rerank_model.py
Fix xinference add rerank model bug, https://github.com/infiniflow/ragflow/issues/2294#issue-2510788135
=> fix xinference add rerank model bug

api/http_api.md
1. dataset: create/delete/list/get/update
2. files in dataset: upload/download/list/delete/get_info
=> HTTP API documents, part1

api/apps/document_app.py, api/contants.py, api/db/services/file_service.py, api/utils/file_utils.py
In MySQL, when the thumbnail base64 of a document is relatively large, the display of the document's thumbnail fails.
Now, I put the document thumbnail into MiniIO storage.
- [✓] Bug Fix (non-breaking change which fixes an issue)
=> fix: Large document thumbnail display failed

agent/component/categorize.py, agent/component/generate.py, agent/component/rewrite.py, api/apps/canvas_app.py
=> refine agent

web/src/pages/flow/flow-drawer/index.less, web/src/pages/flow/flow-drawer/index.tsx, web/src/pages/flow/form/categorize-form/index.tsx, web/src/pages/flow/form/generate-form/index.tsx, web/src/pages/flow/form/retrieval-form/index.tsx, web/src/pages/flow/form/switch-form/index.tsx
feat: Arrange the form of generate, categorize, switch, retrieval operators vertically #1739
=> feat: Arrange the form of generate, categorize, switch, retrieval operators vertically #1739

api/apps/llm_app.py, conf/llm_factories.json, rag/llm/chat_model.py, rag/llm/cv_model.py, rag/llm/embedding_model.py, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/user-setting/setting-model/azure-openai-modal/index.tsx, web/src/pages/user-setting/setting-model/hooks.ts, web/src/pages/user-setting/setting-model/index.tsx
#2701 #2712 #2749
-[x] Bug Fix (non-breaking change which fixes an issue)
=> support api-version and change default-model in adding azure-openai and openai

web/src/components/message-history-window-size-item.tsx, web/src/pages/flow/constant.tsx, web/src/pages/flow/form/categorize-form/index.tsx, web/src/pages/flow/form/generate-form/index.tsx
feat: Add message_history_window_size to CategorizeForm #1739
=> feat: Add message_history_window_size to CategorizeForm #1739

api/apps/user_app.py
Currently singing up to ragflow using a mail-adress with associated top-level domains that have more than 4 chars will fail due to a regex validation that enforces just this.
In our use case, we'd like to use e-mail addresses with `.swiss` top-level domains, which is a valid TLD associated with the country switzerland in the IANA root database.
This change makes the validation accept 5-letter TLDs.
=> Enhance email validation: Allow top-level domains with 5 letters

api/apps/canvas_app.py, api/apps/conversation_app.py, api/apps/system_app.py, api/apps/tenant_app.py, api/apps/user_app.py, api/db/__init__.py, api/db/services/document_service.py, api/db/services/user_service.py, api/ragflow_server.py, api/utils/__init__.py, rag/raptor.py
feat: API access key management https://github.com/infiniflow/ragflow/issues/2846
feat: Render markdown file with remark-loader https://github.com/infiniflow/ragflow/issues/2846
=> add API for tenant function

api/apps/sdk/doc.py, api/apps/sdk/session.py, api/db/services/document_service.py, api/http_api.md, api/python_api_reference.md, sdk/python/ragflow/modules/chunk.py, sdk/python/ragflow/modules/dataset.py, sdk/python/ragflow/modules/document.py, sdk/python/ragflow/modules/session.py, sdk/python/ragflow/ragflow.py, sdk/python/test/t_document.py
=> Refactor Chunk API

web/.umirc.ts, web/src/components/api-service/chat-overview-modal/api-content.tsx
feat: Load markdown file with "asset/source" #17339
=> feat: Load markdown file with "asset/source" #1739

api/apps/tenant_app.py, api/apps/user_app.py, api/db/services/knowledgebase_service.py
=> add team tag to kb

agent/component/exesql.py, api/apps/document_app.py, api/apps/kb_app.py, api/db/services/document_service.py, api/db/services/knowledgebase_service.py, api/settings.py
=> add owner check for team work

rag/llm/rerank_model.py
Resolve #2905 
due to the in-consistent of token size,  I make it safe to limit 500 in code, since there is no config param to control
my llama.cpp run set -ub to 1024:
${llama_path}/bin/llama-server --host 0.0.0.0 --port 9901 -ub 1024 -ngl 99 -m $gguf_file --reranking "$@"
Here is my test Ragflow use llama.cpp
```
lot update_slots: id  0 | task 458 | prompt done, n_past = 416, n_tokens = 416
slot      release: id  0 | task 458 | stop processing: n_past = 416, truncated = 0
slot launch_slot_: id  0 | task 459 | processing task
slot update_slots: id  0 | task 459 | tokenizing prompt, len = 2
slot update_slots: id  0 | task 459 | prompt tokenized, n_ctx_slot = 8192, n_keep = 0, n_prompt_tokens = 111
slot update_slots: id  0 | task 459 | kv cache rm [0, end)
slot update_slots: id  0 | task …
```
=> Resolves #2905 openai compatible model provider add llama.cpp rerank support

api/apps/conversation_app.py, api/db/services/llm_service.py, api/utils/file_utils.py, rag/llm/chat_model.py, rag/llm/sequence2txt_model.py
=> fix sequence2txt error and usage total token issue

rag/llm/chat_model.py
[Bug]: When use OpenAI chat model , raise ERROR: 'CompletionUsage' object has no attribute 'get' #2948
the detail of this PR is shown at https://github.com/infiniflow/ragflow/issues/2948
=> [Bug]: When use OpenAI chat model , raise ERROR: 'CompletionUsage' object has no attribute 'get' #2948

rag/llm/chat_model.py
the details is shown in https://github.com/infiniflow/ragflow/issues/2968
=> [Bug]: unnecessary auto-increment calculations in the tokens statistics of the chat model

api/apps/sdk/chat.py, api/apps/sdk/dataset.py, api/apps/sdk/doc.py, api/apps/sdk/session.py, api/db/services/knowledgebase_service.py, api/utils/api_utils.py, sdk/python/ragflow/modules/chat.py, sdk/python/ragflow/modules/chunk.py, sdk/python/ragflow/modules/dataset.py, sdk/python/ragflow/modules/document.py, sdk/python/ragflow/modules/session.py, sdk/python/ragflow/ragflow.py, sdk/python/test/t_chat.py, sdk/python/test/t_session.py
=> Fix some issues in API

docker/docker-compose-base.yml, docker/docker-compose.yml
1. The mysql_data path mapping in docker-compose-base.yml does not use local path,
making mysql container unable to start, 44a91525ac96a86ee02e95d1f5c383b3a94b9455 fixes it.
2. services running (e.g., ollama) running on the host could not be accessed from docker containers
=> allowing docker container to access service on host

api/apps/tenant_app.py
Not sure why MySQL is inserting empty string in this case, but when I use postgres I got `null value in column "invited_by" of relation "user_tenant" violates not-null constraint`
=> Fix non-null violation when inviting people to team

api/apps/sdk/chat.py, api/apps/sdk/dataset.py, api/apps/sdk/dify_retrieval.py, api/apps/sdk/doc.py, api/apps/sdk/session.py, api/http_api_reference.md
=> Turn resource to plural form

api/apps/sdk/doc.py, intergrations/chatgpt-on-wechat/plugins/README.md
=> remove file size check for sdk API

agent/component/__init__.py, agent/component/generate.py, agent/component/invoke.py, api/db/services/dialog_service.py, deepdoc/parser/html_parser.py, rag/nlp/search.py, rag/utils/es_conn.py
=> search between multiple indiices for team function

web/src/pages/flow/canvas/node/hooks.ts, web/src/pages/flow/form/categorize-form/dynamic-categorize.tsx, web/src/pages/flow/form/categorize-form/hooks.ts, web/src/pages/flow/interface.ts
feat: The order of the category operator form is messed up after refreshing the page #3088
=> feat: The order of the category operator form is messed up after refreshing the page #3088

Dockerfile, Dockerfile.slim
Added jdk to happify tika(https://pypi.org/project/tika/). The image size become ~400MB bigger. Close #2886
=> Added jdk to happify tika

.github/workflows/tests.yml, Dockerfile, Dockerfile.slim, download_deps.py
Added tika jar into image to avoid downloading. Close #3017
=> Added tika jar into image to avoid downloading

agent/canvas.py, agent/component/base.py, graphrag/search.py
=> fix es search parameter error

api/db/services/dialog_service.py
=> add keyword extraction time elapsed to the little lamp.

rag/llm/embedding_model.py
fix "TypeError: only length-1 arrays can be converted to Python scalars" while using cohere embedding model.
=> fix: TypeError: only length-1 arrays can be converted to Python scalars

docker/README.md
=> Updated Docker README

rag/benchmark.py, rag/nlp/term_weight.py
=> fix: term weight issue

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/header/index.tsx
[_Briefly describe what this PR aims to solve. Include background context that will help reviewers understand the purpose of the PR._](feat: Translate autosaved #3301)
=> feat: Translate autosaved #3301

web/src/pages/login-next/form.tsx, web/src/pages/login-next/hooks.ts, web/src/pages/login-next/index.tsx
feat: Switch the login page to the registration component by changing the routing parameters #3221
=> feat: Switch the login page to the registration component by changing the routing parameters #3221

api/db/services/dialog_service.py
=> Turn the relative date in question to absolute date

api/apps/sdk/session.py
This PR addresses the inconsistency in property naming within the codebase by renaming the 'chat' property to 'chat_id' in the session.py file. This change aims to align the naming convention with other parts of the application that refer to chat identifiers as 'chat_id', thereby improving code clarity and maintainability.
=> fix: standardize property name from 'chat' to 'chat_id'

api/constants.py, api/ragflow_server.py, api/utils/__init__.py, api/validation.py
Print configs at the RAGFlow startup phase.
```
2024-11-14 21:27:53,090 INFO     962231 Current configs, from /home/weilongma/Documents/development/ragflow/conf/service_conf.yaml:
2024-11-14 21:27:53,090 INFO     962231 ragflow: {'host': '0.0.0.0', 'http_port': 9380}
2024-11-14 21:27:53,090 INFO     962231 mysql: {'name': 'rag_flow', 'user': 'root', 'password': 'infini_rag_flow', 'host': 'mysql', 'port': 5455, 'max_connections': 100, 'stale_timeout': 30}
2024-11-14 21:27:53,090 INFO     962231 minio: {'user': 'rag_flow', 'password': 'infini_rag_flow', 'host': 'minio:9000'}
2024-11-14 21:27:53,090 INFO     962231 es: {'hosts': 'http://es01:1200', 'username': 'elastic', 'password': 'infini_rag_flow'}
2024-11-14 21:27:53,090 INFO     962231 redis: {'db': 1, 'password': 'infini_rag_flow', …
```
=> Print configs when startup RAGFlow server

graphrag/graph_extractor.py, rag/nlp/search.py
1. Fix error in viewing document chunk
￼
Viewing document chunk details in a BeartypeCallHintParamViolation error.
File "ragflow/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
rv = self.dispatch_request()
^^^^^^^^^^^^^^^^^^^^^^^
File "ragflow/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "ragflow/.venv/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
return current_app.ensure_sync(func)(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
=> fix(rag): fix error in viewing document chunk and cannot start task_executor server

graphrag/leiden.py
leiden alg throws exception for lack func cast definition
- Bug Fix (non-breaking change which fixes an issue)
=> [bug]import typing.cast for leiden.py

rag/app/laws.py
_Choosing Laws Chunk Method results in an error when parsing a document. The error is caused by a missing import in the `laws.py` file._
```
File "/ragflow/rag/svr/task_executor.py", line 445, in handle_task
do_handle_task(task)
File "/ragflow/rag/svr/task_executor.py", line 384, in do_handle_task
cks = build(r)
^^^^^^^^
File "/ragflow/rag/svr/task_executor.py", line 196, in build
cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/ragflow/rag/app/laws.py", line 161, in chunk
for txt, poss in pdf_parser(filename if not binary else binary,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/ragflow/rag/app/laws.py", line 124, in __call__ …
```
=> fix: laws.py added missing import logging

api/ragflow_server.py, rag/svr/task_executor.py
The beartype configuration of main(64f50992e0fc4dce73e79f8b951a02e31cb2d638) is:
```
from beartype import BeartypeConf
from beartype.claw import beartype_all  # <-- you didn't sign up for this
beartype_all(conf=BeartypeConf(violation_type=UserWarning))    # <-- emit warnings from all code
```
ragflow_server failed at a third-party package:
```
(ragflow-py3.10) zhichyu@iris:~/github.com/infiniflow/ragflow$ rm -rf logs/* && bash docker/launch_backend_service.sh 
Starting task_executor.py for task 0 (Attempt 1)
Starting ragflow_server.py (Attempt 1)
File "/home/zhichyu/github.com/infiniflow/ragflow/api/ragflow_server.py", line 22, in <module>
from api.utils.log_utils import initRootLogger
File "/home/zhichyu/github.com/infiniflow/ragflow/api/utils/__init__.p …
```
=> Removed beartype

web/src/pages/flow/canvas/node/popover.tsx, web/src/pages/flow/chat/hooks.ts
Feat: Display the input parameters of begin in the output result table  #3355
=> Feat: Display the input parameters of begin in the output result table  #3355

web/src/pages/flow/canvas/node/popover.tsx, web/src/pages/flow/hooks.tsx, web/src/pages/flow/utils.ts
Feat: When saving the canvas, other dls parameters passed from the backend are spliced ​​into the dsl parameters #3355
#3556
=> Feat: When saving the canvas, other dls parameters passed from the backend are spliced ​​into the dsl parameters #3355

docker/README.md, docs/configurations.md, docs/quickstart.mdx, docs/references/faq.md, docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Updated obsolete faqs

web/src/hooks/common-hooks.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/user-setting/setting-team/hooks.ts
Feat: Modify the prompt text for deleting team members #2834
=> Feat: Modify the prompt text for deleting team members #2834

rag/llm/rerank_model.py
When calling the Qwen rerank model, if the model does not return correctly, an exception should be raised to notify the user, rather than simply returning a value of 0, as this would be confusing to the user.
=> when qwen rerank model not return ok, raise exception to notice user

web/src/pages/profile-setting/index.tsx, web/src/pages/profile-setting/profile/index.tsx, web/src/pages/profile-setting/team/index.tsx, web/tailwind.config.js
Feat: Add TeamManagement component #3221
=> Feat: Add TeamManagement component #3221

web/src/components/ui/button.tsx, web/src/pages/profile-setting/model/index.tsx, web/src/pages/profile-setting/model/model-card.tsx, web/src/pages/profile-setting/team/index.tsx, web/src/routes.ts
Feat: Add ModelManagement page #3221
=> Feat: Add ModelManagement page #3221

docs/guides/deploy_local_llm.mdx, docs/guides/manage_team_members.md, docs/references/supported_models.mdx, docs/release_notes.md
=> Added release notes

api/apps/kb_app.py, api/db/services/knowledgebase_service.py, web/.umirc.ts, web/package-lock.json, web/package.json, web/src/hooks/knowledge-hooks.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/knowledge/index.less, web/src/pages/knowledge/index.tsx
Reverts infiniflow/ragflow#3703
=> Revert "Feat: Scrolling knowledge base list #3695"

docs/guides/upgrade_ragflow.mdx, docs/release_notes.md
=> Added release notes v0.12.0

api/apps/chunk_app.py, rag/llm/rerank_model.py, sdk/python/test/test_frontend_api/test_dataset.py
=> Fix error response

rag/utils/minio_conn.py
Don't log exception if object doesn't exist. Close #1483
=> Don't log exception if object doesn't exist

web/src/locales/zh.ts, web/src/utils/file-util.ts
The uploaded avatar has been compressed to preserve transparency while meeting the length requirements for the 'text' type. The current compressed size is 100x100 pixels.
=> Image compression

docs/configurations.md
=> Removed obsolete instructions

api/apps/sdk/session.py, api/db/db_models.py
Fix the bug that the agent could not find the context
#3682
=> Fix the bug that the agent could not find the context

api/apps/sdk/session.py
Fix the agent reference bug and the session prologue
#3285 #3819
=> Fix the agent reference bug and the session prologue

web/src/constants/knowledge.ts, web/src/pages/add-knowledge/components/knowledge-file/parsing-action-cell/index.tsx, web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx
Fix: Hide the download button if it is an empty file #3762
=> Fix: Hide the download button if it is an empty file #3762

web/src/components/editable-cell.tsx, web/src/pages/flow/canvas/node/hooks.ts, web/src/pages/flow/canvas/node/relevant-node.tsx
Fix: The right coordinates of Categorize and Switch operators are misplaced #3868
=> Fix: The right coordinates of Categorize and Switch operators are misplaced #3868

rag/llm/chat_model.py, rag/llm/embedding_model.py, rag/llm/rerank_model.py
=> Fix HuggingFace model error.

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/hooks.ts
Feat: Add question parameter to edit chunk modal #3873
=> Feat: Add question parameter to edit chunk modal #3873

.github/workflows/tests.yml, api/apps/api_app.py, api/apps/canvas_app.py, api/apps/chunk_app.py, api/apps/conversation_app.py, api/apps/dialog_app.py, api/apps/document_app.py, api/apps/file2document_app.py, api/apps/file_app.py, api/apps/kb_app.py, api/apps/llm_app.py, api/apps/sdk/agent.py, api/apps/sdk/chat.py, api/apps/sdk/dataset.py, api/apps/sdk/dify_retrieval.py, api/apps/sdk/doc.py, api/apps/sdk/session.py, api/apps/system_app.py, api/apps/tenant_app.py, api/apps/user_app.py, deepdoc/parser/pdf_parser.py, deepdoc/vision/ocr.py, deepdoc/vision/recognizer.py, graphrag/entity_embedding.py
=> Added static check at PR CI

api/db/services/dialog_service.py
This PR organize chunks in the prompt by document and indicate what is the name of the document in this way
```
Document: {doc_name} \nContains the following relevant fragments:
chunk1
chunk2
chunk3
Document: {doc_name} \nContains the following relevant fragments:
chunk4
chunk5
```
Maybe can be a baseline to add metadata to the documents.
This allow in my case to improve llm context about the orgin of the information.
=> organize chunks by document in the prompt

helm/templates/mysql.yaml
The initial Helm chart implementation added in #3815 suffers from an issue where the 5GB data volume for the SQL DB is filled up with [binlog](https://dev.mysql.com/doc/refman/8.4/en/binary-log.html) files after just a few days. Since the app uses a non-replicated SQL DB config I think it makes sense to disable the binlog in the SQL DB container. This is achieved by simply adding the required argument to the container startup command.
=> Disable SQL DB binlog in Helm chart

README.md, README_id.md, README_ja.md, README_ko.md, README_zh.md, docs/quickstart.mdx
=> Updated RAGFlow edition descriptions

api/apps/document_app.py, api/db/db_models.py, api/db/services/document_service.py, api/db/services/task_service.py, poetry.lock, pyproject.toml, rag/svr/task_executor.py
Try to reuse existing chunks. Close #3793
=> Try to reuse existing chunks

agent/canvas.py, api/apps/sdk/session.py, api/db/services/canvas_service.py, api/db/services/conversation_service.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/agent.py, sdk/python/ragflow_sdk/modules/session.py, sdk/python/test/test_sdk_api/t_agent.py
Fix bugs in agent api and update api document
=> Fix bugs in agent api and update api document

api/apps/dialog_app.py
The removed if statement is unnecessary and adds cognitive load for readers.
The original code:
```
vector_similarity_weight = req.get("vector_similarity_weight", 0.3)
if vector_similarity_weight is None:
vector_similarity_weight = 0.3
```
has been simplified to:
```
vector_similarity_weight = req.get("vector_similarity_weight", 0.3)
```
=> Remove Redundant None Check for vector_similarity_weight

web/src/components/theme-provider.tsx, web/src/pages/flow/canvas/index.tsx
Feat: Set the color of the canvas's control button #3851
=> Feat: Set the color of the canvas's control button #3851

api/db/services/task_service.py, conf/infinity_mapping.json, deepdoc/vision/__init__.py, deepdoc/vision/layout_recognizer.py, deepdoc/vision/operators.py
=> Upgrades Document Layout Analysis model.

rag/llm/embedding_model.py
=> Fix fastembed reloading issue.

api/db/services/dialog_service.py, api/db/services/llm_service.py
=> Refactor ask decorator

api/apps/sdk/chat.py, api/apps/sdk/session.py, api/db/services/canvas_service.py, api/utils/api_utils.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/agent.py, sdk/python/ragflow_sdk/modules/session.py
Update the  component of the agent API with parameters.
=> Update the  component of the agent API with parameters.

rag/utils/s3_conn.py
Fix the issue when retrieving AWS credentials from the S3 configuration from the settings module instead of getting from the environment variables.
=> Use s3 configuration from settings module

rag/llm/embedding_model.py
1. Change embedding model of knowledge base won't change the default embedding model. 
2. Retrieval test bug
=> Fix error of changing embedding model

api/db/services/task_service.py, rag/svr/task_executor.py
Added time to progress message
=> Added time to progress message

rag/nlp/search.py
stop rerank by model when search result is empty, otherwise rerank may raise an error (qwen).
=> fix: stop rerank by model when search result is empty

api/apps/sdk/session.py, api/db/db_models.py, api/db/services/api_service.py, api/db/services/conversation_service.py, docs/references/http_api_reference.md
=> Add user_id for third-party system to record sessions.

api/apps/sdk/chat.py
=> Fix chat listing error.

agent/component/exesql.py, rag/app/qa.py
Fix some bugs in text2sql.(#4279)(#4281)
- The incorrect results in parsing CSV files of the QA knowledge base in the text2sql scenario. Process CSV files using the csv library. Decouple CSV parsing from TXT parsing
- Most llm return results in markdown format ```sql query ```, Fix execution error caused by LLM output SQLmarkdown format.### Type of change
=> Fix some bugs in text2sql.(#4279)(#4281)

api/apps/sdk/chat.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/chat.py, sdk/python/ragflow_sdk/ragflow.py
Add top_k for create_chat and update_chat api #4157
=> Add top_k for create_chat and update_chat api

conf/llm_factories.json
OpenAI has deprecated the gpt-4-vision-preview model. This PR adds support for the newer gpt-4o and gpt-4o-mini models in the img2text feature.
This PR add addtional 4o/4o-mini entry for img2text besides original ones. Utilized [alias](https://platform.openai.com/docs/models#gpt-4o) model names (e.g., gpt-4o-2024-08-06) because the database schema uses the model name as the primary key.
=> Support OpenAI gpt-4o and gpt-4o-mini for img2text

web/src/components/list-filter-bar.tsx, web/src/components/rename-dialog/index.tsx, web/src/components/ui/dialog.tsx, web/src/components/ui/input.tsx, web/src/components/ui/select.tsx, web/src/components/ui/textarea.tsx, web/src/pages/dataset/setting/advanced-setting-form.tsx, web/src/pages/dataset/setting/basic-setting-form.tsx, web/src/pages/datasets/dataset-creating-dialog.tsx, web/src/pages/datasets/hooks.ts, web/src/pages/datasets/index.tsx, web/src/pages/profile-setting/model/model-card.tsx, web/src/pages/profile-setting/profile/index.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Add DatasetCreatingDialog #3221
=> Feat: Add DatasetCreatingDialog #3221

conf/service_conf.yaml, docker/service_conf.yaml.template, rag/svr/cache_file_svr.py, rag/utils/s3_conn.py
- Bring `STORAGE_IMPL` back in `rag/svr/cache_file_svr.py`
- Simplify storage connection when working with AWS S3
=> Improve storage engine

docs/references/agent_component_reference/begin.mdx, docs/references/agent_component_reference/generate.mdx, docs/references/agent_component_reference/interact.mdx
=> Added generate component description

web/src/components/edit-tag/index.tsx, web/src/components/entity-types-item.tsx, web/src/hooks/chunk-hooks.ts, web/src/hooks/knowledge-hooks.ts, web/src/hooks/logic-hooks.ts, web/src/interfaces/database/knowledge.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/tag-feature-item.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/hooks.ts, web/src/pages/add-knowledge/components/knowledge-chunk/utils.ts, web/src/services/knowledge-service.ts, web/src/utils/api.ts
Feat: Add TagFeatureItem #4368
=> Feat: Add TagFeatureItem #4368

rag/svr/task_executor.py
=> Error message: Infinity not support table parsing method

web/src/pages/user-setting/setting-model/system-model-setting-modal/index.tsx
Fix: Can not select GPT-4o / 4o mini as Chat Model #4421
=> Fix: Can not select GPT-4o / 4o mini as Chat Model #4421

deepdoc/vision/layout_recognizer.py, rag/svr/task_executor.py
=> Accelerate titles' embeddings.

deepdoc/vision/ocr.py
`eval(op_name)` -> `getattr(operators, op_name)`
Using `eval()` can lead to code injections and is entirely unnecessary here.
Best practice code improvement, preventing the possibility of code injection.
=> Remove use of eval() from ocr.py

deepdoc/vision/recognizer.py
`eval(op_type)` -> `getattr(operators, op_type)`
Using `eval()` can lead to code injections and is entirely unnecessary here.
Best practice code improvement, preventing the possibility of code injection.
=> Remove use of eval() from recognizer.py

docs/references/agent_component_reference/generate.mdx, docs/references/agent_component_reference/note.mdx, docs/references/agent_component_reference/template.mdx, web/src/locales/en.ts
=> Added descriptions of the Note and Template components

deepdoc/vision/postprocess.py
Remove usage of `eval()` from postprocess.py
The use of `eval()` is a potential security risk. While the use of `eval()` is guarded and thus not a security risk normally, `assert`s aren't run if `-O` or `-OO` is passed to the interpreter, and as such then the guard would not apply.  In any case there is no reason to use `eval()` here at all.
Potential security fix if somehow the passed `modul_name` could be user controlled.
=> Remove usage of eval() from postprocess.py

web/src/pages/add-knowledge/components/knowledge-sidebar/index.tsx
Fix: Capture the problem that the knowledge graph interface returns null and causes page errors #4543
=> Fix: Capture the problem that the knowledge graph interface returns null and causes page errors #4543

rag/llm/chat_model.py, rag/llm/embedding_model.py, rag/llm/rerank_model.py
=> Refactor for total_tokens.

Dockerfile, docker/docker-compose-macos.yml, docs/guides/develop/build_docker_image.mdx
https://github.com/infiniflow/ragflow/issues/4319
This pull request includes several changes to improve the Docker setup and documentation for the project. The most important changes include updating the Dockerfile to support modern versions of Rust, adding a new Docker Compose configuration for macOS, and updating the build instructions in the documentation.
Improvements to Docker setup:
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L80-R107): Added installation steps for a modern version of Rust and updated the logic for installing the correct ODBC driver based on the architecture.
* [`docker/docker-compose-macos.yml`](diffhunk://#diff-8e8587143bb2442c02f6dff4caa217ebbe3ba4ec8e7c23b2e568886a67b00eafR1-R56): Added a new Docker Compose …
=> Fix macOS startup

rag/llm/chat_model.py
ERROR: 'Stream' object has no attribute 'iter_lines' with reference to Claude/Anthropic chat streams
=> fix: err object has no attribute 'iter_lines'

docs/guides/develop/build_docker_image.mdx
I'm assuming that this was a mistake (but I could be missing something) [here](https://github.com/infiniflow/ragflow/pull/4658/files#:~:text=docker%20build%20%2D%2Dbuild%2Darg%20LIGHTEN%3D1%20%2Df%20Dockerfile%20%2Dt%20infiniflow/ragflow%3Anightly%2Dslim%20.) when the docker building instructions for the slim image was just changed away from an actual `docker build` command to the mac os `docker compose up` command. This is just reverting the change.
=> Reverted build slim image documentation

agent/component/exesql.py
resume content flow, instead of closed with errors.
=> Resume content flow ExecSQL

docs/guides/start_chat.md, docs/references/agent_component_reference/categorize.mdx, docs/references/agent_component_reference/generate.mdx, docs/references/agent_component_reference/keyword.mdx, docs/references/agent_component_reference/rewrite.mdx, docs/release_notes.md, web/src/locales/en.ts
=> Added a release notes

rag/nlp/search.py
Use `json.loads()` instead.
Using `eval()` can lead to code injections. I think this loads a JSON field, right? If yes, why is this done via `eval()` and not `json.loads()`?
=> Remove use of eval() from search.py

api/db/services/dialog_service.py
When calling the chat API with `stream=False`, the code attempts to access `msg[-1]["content"]` without verifying if the key exists. This causes a `KeyError` when the message structure does not contain `"content"`.  
This issue was discussed in [#4885](https://github.com/infiniflow/ragflow/issues/4885), where we analyzed the root cause. The error does not occur with `stream=True`, as the response is processed differently.  
- **Logging Fix:**  
- Before accessing `msg[-1]["content"]`, we check if the key exists.  
- If it does not exist, a default value (`"[content not available]"`) is used to prevent errors.  
- **Structural Fix in `msg` Construction:**  
- Ensured that every message in `msg` contains the `"content"` key, even if empty.  
- This fixes the issue at its root and ensures …
=> Fixes KeyError: 'content' when using stream=False

agent/component/rewrite.py, web/src/locales/en.ts, web/src/pages/flow/constant.tsx, web/src/pages/flow/flow-drawer/index.tsx, web/src/pages/flow/form/rewrite-question-form/index.tsx
Support specified language or language according to initial question
=> Rewrite Support specified language or language according to initial question

api/apps/__init__.py
Fix: When starting the backend service from source code on Windows, the "HTTP API" no longer returns 404.
=> Fix: Starting the source code on Windows, the 'HTTP API' returns 404

api/apps/sdk/session.py, docs/references/http_api_reference.md
Update the agent session API "POST /api/v1/agents/{agent_id}/sessions", to support uploading files while create a new session:
- currently, the API only supports requesting with a json body. If user wants to upload a doc or image when create session, like what is already supported on the web client, we need to update the API.
- if upload an image, ragflow will call image2text, and a user_id is needed for the image2text model. So we need to send user_id in the API request. As form-data is needed to upload files, not json body, seems we need to put the user_id in the url as an optional parameter (currently user_id is an optional in json body).
=> Update agent session API, to support uploading files while create a new session

conf/llm_factories.json, web/src/hooks/llm-hooks.tsx
The current design is not well-suited for multimodal models, as each model can only be configured for a single purpose—either chat or Img2txt. To work around this limitation, we use model aliases such as gpt-4o-mini and gpt-4o-mini-2024-07-18.
To fix this, this PR allows specifying the Img2txt model by tag instead of model_type.
=> Specify img2text model by tag

agent/component/exesql.py, api/db/services/dialog_service.py, graphrag/general/extractor.py
=> Remove <think> for exeSql component.

agent/component/rewrite.py, web/src/components/api-service/embed-modal/index.less, web/src/components/api-service/embed-modal/index.tsx, web/src/locales/config.ts, web/src/locales/en.ts
=> add option Embed into webpage

agent/component/invoke.py
Invoke component can be used to call third party services.
Tried GET/POST/PUT from web UI, and found PUT request failed like this:  (test api: api/v1/chats/<assistant_id>)
```
{"code":100,"data":null,"message":"AttributeError("'NoneType' object has no attribute 'get'")"}
```
Root cause: Invoke PUT with a 'data=args' parameter, which is a form-encoded data, however the default content type setting of request header is application/json. The test api could not deal with such case.
Fix: use the 'json' parameter of reqeusts.put(), same as Invoke POST. Do not use the 'data' parameter.
Another way is to use 'data=json.dumps(args)'.
=> Fix: PUT method does not work as expected with Invoke component

api/apps/sdk/session.py
API options like `stream` was ignored when no session_id was provided.
This PR fixes the issue.
Test command and expected result:
```
curl  --request POST \
--url http://:9222/api/v1/chats/2f2e1d30ee6111efafe211749b004925/completions \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ragflow-xxx' \
--data '{
"question":"Who are you",
"stream":false
}'
{"code":0,"data":"data:{\"code\": 0, \"message\": \"\", \"data\": {\"answer\": \"Hi! I'm your assistant, what can I do for you?\", \"reference\": {}, \"audio_binary\": null, \"id\": null, \"session_id\": \"82ceb0fcee7111efafe211749b004925\"}}\n\n"}
```
- [*] Bug Fix (non-breaking change which fixes an issue)
=> Fix: Option ineffective in Chat API

api/apps/dialog_app.py, api/apps/sdk/chat.py, api/apps/sdk/doc.py
Modify embedding model ID comparison to remove vendor suffixes, ensuring consistent model identification when working with multiple knowledge bases. This change affects dialog creation, chat operations, and document retrieval test functions.
resolve this bug: https://github.com/infiniflow/ragflow/issues/5166
=> Fix: Normalize embedding model ID comparison across datasets

sdk/python/ragflow_sdk/modules/session.py
add non-stream mode support to session.ask function
same as title,  I do not know why the stream=False is not work on the server side also, when stream=False, the response in the session._ask_chat is a fully connnected SSE string.
This is a quick fix on the sdk side to make the response format align with API docs
=> Fix session.ask return generator bug when stream=False on python sdk

api/settings.py, docker/service_conf.yaml.template
This pull request includes changes to the `api/settings.py` and `docker/service_conf.yaml.template` files to add support for default models in the LLM configuration (specially for LIGHTEN builds). The most important changes include adding default model configurations and updating the initialization settings to use these defaults.
For example:
With this configuration Bedrock will be enable by default with claude and titan embeddings.
```
user_default_llm:
factory: 'Bedrock'
api_key: '{}' 
base_url: ''
default_models:
chat_model: 'anthropic.claude-3-5-sonnet-20240620-v1:0'
embedding_model: 'amazon.titan-embed-text-v2:0'
rerank_model: ''
asr_model: ''
image2text_model: ''
```
=> Add configuration to choose default llm models

rag/llm/chat_model.py, rag/llm/embedding_model.py
This pull request includes changes to the initialization logic of the `ChatModel` and `EmbeddingModel` classes to enhance the handling of AWS credentials.
Use cases:
- Use env variables for credentials instead of managing them on the DB 
- Easy connection when deploying on an AWS machine
=> Add support to boto3 default connection

api/apps/chunk_app.py
As issue #3268  mentioned, "Chun not found!" exception will occur, especially during the teamwork of knowledge bases.
"tenants" are the people on current_user's team, including the team owner itself. The old one only checks the first "tenant", tenants[0], which will cause error when anyone editing the chunk that is not in tenants[0]'s knowledge base.
My modification won't introduce new errors while iterate all the tenant then retrieve knowledge bases of each.
=> Fix: 'Chunk not found!' error in team-sharing knowledge base.

api/apps/sdk/session.py
Added OpenAI-like completion api, related to #4672, #4705 
This function allows users to interact with a model to get responses based on a series of messages. 
If `stream` is set to True, the response will be streamed in chunks, mimicking the OpenAI-style API.
```bash
curl -X POST https://ragflow_address.com/api/v1/chats_openai/<chat_id>/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $RAGFLOW_API_KEY" \
-d '{
"model": "model",
"messages": [{"role": "user", "content": "Say this is a test!"}],
"stream": true
}'
```
Alternatively, you can use Python's `OpenAI` client:
```python
from openai import OpenAI
model = "model"
client = OpenAI(api_key="ragflow-api-key", base_url=f"http://ragflow_address/api/v1/chats_openai/<chat_id>")
completion = …
```
=> Added OpenAI-like completion api

agent/canvas.py
seems  no need use ABC here, there's no `abstractmethod` here
=> Fix: drop useless ABC method

web/src/pages/user-setting/setting-profile/index.tsx
Improve the language selection display on the profile settings page.
| before | after |
| --- | --- |
|![截屏2025-02-28 上午8 46 54](https://github.com/user-attachments/assets/0924275c-99d4-4ddd-8935-693286c0d07f)|![CleanShot 2025-02-28 at 09 58 21](https://github.com/user-attachments/assets/a96c9d73-8e16-40a8-aa80-d31fecc18edf)|
=> Fix: language selection display on the profile settings page

deepdoc/vision/operators.py, pyproject.toml, uv.lock
This patch drop useless fastext which is seems useless in the code base 
and its very kind of hard install
should close #4498
=> Refa: drop useless fasttext

api/apps/user_app.py
This pull request aims to fix a bug that prevents certain email addresses from signing up. The affected TLDs were returning 'invalid email address' errors:
.museum
.software
.photography
.technology
.marketing
.education
.international
.community
.construction
.government
.consulting
....
=> Fix email validation regex

helm/templates/ingress.yaml, helm/templates/ragflow.yaml, helm/values.yaml
Adds a new Kubernetes Service resource to the Helm chart which specifically targets the RAGFlow API. This feature useful for cases where you want to expose the RAGFlow HTTP API separately from the web interface, for example if RAGFlow is running behind an authenticating proxy it allows a route to bypass the proxy (e.g. by defining a separate ingress resource which forwards to the separate API-only k8s service added here) to provide RAGFlow API access. This is still secure since API access is already authenticated by API keys inside RAGFlow itself.
=> Add separate API service resource to Helm chart

Dockerfile, docker/entrypoint-parser.sh, docker/entrypoint.sh
Introduced jemalloc.
Python uses pymalloc (which is an reimplementation of gblibc malloc) to manage RES. It has pools for small objects to avoid returning memory to OS aggressively. My experience is: Replacing pymalloc with [jemalloc](https://github.com/jemalloc/jemalloc) can reduce RES and speedup task_executor.py.
=> Introduced jemalloc

web/src/pages/document-viewer/image/index.tsx, web/src/pages/document-viewer/index.tsx
the preview botton of image not work for me.
request url: `http://127.0.0.1:9222/document/af570920f80e11efb8e967fd67f0d8c7?ext=jpg&prefix=file`
response: `{"code":401,"data":null,"message":"<Unauthorized '401: Unauthorized'>"}`
=> Fix: image file can't preview

api/db/db_models.py
The `dialog_id` field was inconsistently defined:
- In the `migrate_db()` function, it was set to `null=True`.
- In the model class, it was defined as `null=False`.
This inconsistency caused an issue during the initial deployment where the database table did not allow `dialog_id` to be null. As a result, calling `APITokenService.save(**obj)` in `system_app.py` raised the following error:
```
peewee.IntegrityError: null value in column "dialog_id" violates not-null constraint
```
Error: peewee.IntegrityError: null value in column "dialog_id" violates not-null constraint
=> Fix: Resolve inconsistency in APIToken dialog_id field definition

rag/llm/rerank_model.py
vLLM provider with a reranking model does not work : as vLLM uses under the hood the [CoHereRerank provider](https://github.com/infiniflow/ragflow/blob/v0.17.0/rag/llm/__init__.py#L250) with a `base_url`, if this URL [is not passed to the Cohere client](https://github.com/infiniflow/ragflow/blob/v0.17.0/rag/llm/rerank_model.py#L379-L382) any attempt will endup on the Cohere SaaS (sending your private api key in the process) instead of your vLLM instance.
=> Fix: CoHereRerank not respecting base_url when provided

api/apps/sdk/chat.py
The `/api/v1/chats` API endpoint was broken, any GET request got the following response:
```
{"code":100,"data":null,"message":"TypeError(\"'int' object is not callable\")"}
```
With this log ragflow-server side:
```
2025-03-07 14:36:26,297 ERROR    20 'int' object is not callable
File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
rv = self.dispatch_request()
File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
File "/ragflow/api/utils/api_utils.py", line 303, in decorated_function
return func(*args, **kwargs)
File "/ragflow/api/apps/sdk/chat.py", line 323, in …
```
=> Fix: broken /api/v1/chats endpoint

api/ragflow_server.py, graphrag/general/extractor.py, graphrag/general/index.py, graphrag/general/smoke.py, graphrag/light/smoke.py, graphrag/utils.py, rag/raptor.py, rag/svr/task_executor.py, rag/utils/redis_conn.py
Refactor graphrag to remove redis lock
=> Refactor graphrag to remove redis lock

rag/svr/task_executor.py
Fix:signal.SIGUSR1 and signal.SIGUSR2 can't use in window. so don't bind signal.SIGUSR1 and signal.SIGUSR2 in the windows env
- [✓ ] Bug Fix (non-breaking change which fixes an issue)
=> Fix:signal.SIGUSR1 and signal.SIGUSR2 can't use in window. so don't bind signal.SIGUSR1 and signal.SIGUSR2 in the windows env

api/apps/document_app.py, api/apps/sdk/chat.py, api/apps/sdk/dataset.py, sdk/python/ragflow_sdk/ragflow.py, sdk/python/test/test_frontend_api/common.py, sdk/python/test/test_http_api/test_dataset_mangement/common.py
Fixes #5923 
Fixes the readonly variables from payload at
/datasets/<dataset_id> 
Now if user tries to modify readonly values then it will show " The input parameters are invalid. "
invalid_keys = {"id", "embd_id", "chunk_num", "doc_num", "parser_id", "create_date", "create_time", "created_by", "status","token_num","update_date","update_time"}
if any(key in req for key in invalid_keys):
return get_error_data_result(message="The input parameters are invalid.")
i have include those readonly keys in invalid_keys
=> Fix: HTTP API Updates Read-Only Dataset Fields During Modification #5923 

conf/llm_factories.json
AWS Bedrock has made deepseek-r1 available on its serverless inference.
This adds the R1 serverless model for use via the bedrock model abilities.
=> Feat: Add deepseek to llm_factories

web/src/components/tavily-item.tsx
Fix: Prevent password boxes other than login passwords from displaying passwords saved in the browser's password manager by default. #6033
=> Fix: Prevent password boxes other than login passwords from displaying passwords saved in the browser's password manager by default. #6033

api/apps/conversation_app.py
https://github.com/infiniflow/ragflow/issues/5546
up_down was using req.get("set") to retrieve the parameter, but according to the frontend code, it should be req.get("thumbup"). 
https://github.com/infiniflow/ragflow/blob/1842ca03345e8f204b69c45d4d1b8c21dcc3cd0d/web/src/interfaces/request/chat.ts#L3
https://github.com/infiniflow/ragflow/blob/1842ca03345e8f204b69c45d4d1b8c21dcc3cd0d/api/apps/conversation_app.py#L327
=> Fix: Correct parameter retrieval in thumbup api

docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/session.py
Add support for non-stream response with session.ask_without_stream and fix a typo mistake in python API doc
There are requirements for non-stream response, especially for commands exection, e.g. text2SQL. The commands have to be completed before the agent is triggered.
It's to fix the [Issue: 6206](https://github.com/infiniflow/ragflow/issues/6206)
=> Fix: add support for non-stream response with session.ask_without_stream

web/src/hooks/flow-hooks.ts
Blank and createFromNothing were not read from the i18n file when Agent was created
创建Agent的时候 Blank 和 createFromNothing  没从i18n文件中读取
=> Fix: read flow blank template strings from i18n file

rag/svr/task_executor.py
When using LLM for auto-tag, if there are no examples, the tag format generated by LLM may be wrong. This will cause Elasticsearch insert errors. Adding basic examples can avoid this problem.
=> Fix: Add a basic example when the example of content_tagging is empty

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
cover [stop parse documents](https://ragflow.io/docs/dev/http_api_reference#stop-parsing-documents) endpoints
=> Test: Added test cases for Stop Parse Documents HTTP API

rag/settings.py
Optimize setting configuration initialization to resolve Minio initialization error caused by using a specific storage.
Reproduction Scenario:
Using Aliyun OSS as the backend storage with the STORAGE_IMPL environment variable set to OSS.
The service_conf.yaml.template configuration file contains OSS-related configurations, while other storage configurations are commented out.
When the service starts, it still attempts to initialize the Minio storage. Since there is no Minio configuration in service_conf.yaml.template, it results in an error due to the missing configuration file.
Optimization Measures:
Automatically determine the required initialization configuration based on the environment variable.
Do not initialize configurations for unused resources.
=> Fix: optimize setting config initialization to resolve Minio initialization error

agent/component/base.py
Fix: Resolved a bug where sibling components in Canvas were not restricted to fetching data from the upstream when parallel components were present.
Issue: When parallel components existed in Canvas, sibling components incorrectly fetched data without being limited to the upstream scope, causing data retrieval issues.
Solution: Adjusted the data fetching logic to ensure sibling components only retrieve data from the upstream scope.
=> Fix: Resolved a bug where sibling components in Canvas were not restricted to fetching data from the upstream when parallel components were present.

docker/launch_backend_service.sh
- A new function `load_env_file` has been added to load environment variables from a .env file in the current script directory.
- If the .env file exists, the variables within it will be loaded; if it does not exist, a warning message will be output.
I found this issue while testing this pr: https://github.com/infiniflow/ragflow/pull/6327. The locally started server did not read the REGISTER_ENABLED variables in the .env. The result has always been the default True
Follow the tutorial in the README.md to start from source code. base's container that is es、redis，etc will load .env. Therefore, `launch_backend_service.sh` should also load .env to be consistent with the configuration of the docker container when it was started
=> Feat: Add the functionality to load environment variables from a .env file

agent/component/categorize.py, rag/llm/chat_model.py
=> Fix: change ollama default num_ctx.

web/src/components/ui/transfer-list.tsx
Feat: If the Transfer item is disabled, the item cannot be edited. #3221
=> Feat: If the Transfer item is disabled, the item cannot be edited. #3221

pyproject.toml
This PR resolves the issue of multiple top-level packages being detected in the Python project, which caused errors when using uv pip install. The problem occurred because the project had multiple directories files at the root level, leading to a flat-layout error.
To fix this, the pyproject.toml file was updated to explicitly list the packages using the [tool.setuptools] section. This ensures that the correct packages are included during installation, avoiding the flat-layout error.
Type of change
=> Fix: multiple top-level packages error in Python project

agent/component/template.py
###Address Problem:
The original implementation used re.sub(r"(\\\"|\")", "", content) which stripped all quotes from the processed content. While this worked for simple Jinja2-rendered templates, it caused formatting issues when :
-Quotes were required in the final output (e.g., JSON, Python Code strings) 
###Solution:
1. Selective JSON Serialization.
2. Removed Global Quote Removal
This PR addresses an issue in template processing where all quotation marks (" and \") were being removed from content, potentially corrupting string formatting in rendered outputs. **In fact, extra quotes is generated by json.dumps(v, ensure_ascii=False).**
=> Fix: Preserve quotes while handling variable substitution withTemplate component.

agent/component/keyword.py
For now, if you use thinking model (deepseek-r1:32b with ollama server in my case) in "Keyword" node, result contains all <think> block and so node return not only keywords
=> Remove thinking block from keyword node's result

api/db/db_models.py
Added the with_retry decorator in db_models.py to add a retry mechanism for database operations. Applied the retry mechanism to the lock and unlock methods of the PostgresDatabaseLock and MysqlDatabaseLock classes to enhance the reliability of lock operations.
resolve failed to acquire lock exception with retry mechanism
=> Fix: failed to acquire lock exception with retry mechanism for postgres and mysql

rag/utils/minio_conn.py
Prevent applications from failing to start due to calling non-existent or incorrect Minio connection configurations when using file storage outside of Minio
=> fix:  Remove unnecessary minio initialization

docker/docker-compose-base.yml
This PR updates the MySQL container configuration by setting the parameter --binlog_expire_logs_seconds to 604800 seconds (7 days). This change ensures that MySQL automatically purges binary logs older than 7 days, helping to conserve disk space and maintain precise log management.
=> Fix: binlog_expire_logs_seconds

api/apps/sdk/session.py
Fix #5418
Actually, the fix #4329 also works for agent flows with parameters, so this PR just relaxes the `else` branch of that. With this PR, it works fine on my side, may need more testing to make sure this does not break something.
I guess the real problem may be deeply hidden in the code which relates to conversation and canvas execution. After a few hours of debugging, I see the only difference between with and without parameters in `begin` component, is the `history` field of canvas data. When the `begin` component contains some parameters, the debug log shows:
```
025-03-29 19:50:38,521 DEBUG    356590 {
"component_name": "Begin",
"params": {"output_var_name": "output", "message_history_window_size": 22, "query": [{"type": "fileUrls", "key": "fileUrls", "name": "files", "optional": …
```
=> Fix agent completion requiring calling twice with parameters in begin component

agent/component/retrieval.py
Actually fix #6241 
Hello, I ran into the same problem as #6241. When I'm testing my agent flow in the web ui using `Run` button with a file input, the retrieval component always gave an empty output.
In the code I found that:
`web/src/pages/flow/debug-content/index.tsx`:
```tsx
const onOk = useCallback(async () => {
const values = await form.validateFields();
const nextValues = Object.entries(values).map(([key, value]) => {
const item = parameters[Number(key)];
let nextValue = value;
if (Array.isArray(value)) {
nextValue = ``;
value.forEach((x) => {
nextValue +=
x?.originFileObj instanceof File
? `${x.name}\n${x.response?.data}\n----\n`    // Here, the file content always ends in '\n'
: `${x.url}\n${x.result}\n----\n`;
});
}
return { ...item, value: nextValue };
});
ok(nextValues);
}, …
```
=> Don't split and strip input in retrieval component.

docker/README.md, docker/docker-compose.yml, docker/service_conf.yaml.template, rag/utils/s3_conn.py
- Added support for S3-compatible protocols.
- Enabled the use of knowledge base ID as a file prefix when storing files in S3.
- Updated docker/README.md to include detailed S3 and OSS configuration instructions.
=> Feat: extend S3 storage compatibility and add knowledge base ID prefix

graphrag/entity_resolution.py, graphrag/general/extractor.py, graphrag/utils.py
Using nightly version
Elasticsearch database
When clicking the "Entity Resolution" button in KnowledgeGraph, encountered the following errors:
graphrag/entity_resolution.py
```
list(sub_connect_graph.nodes) AttributeError
```
graphrag/general/extractor.py
```
node0_attrs[attr] = sorted(set(node0_attrs[attr].extend(node1_attrs[attr])))
TypeError: 'NoneType' object is not iterable
```
```
for attr in ["keywords", "source_id"]:  
KeyError I think attribute "keywords" is in edges not nodes
```
graphrag/utils.py
```
settings.docStoreConn.delete()  # Sync function called as async
```
Fixed AttributeError in entity_resolution.py by properly handling graph nodes
Fixed TypeError and KeyError in extractor.py by separate operations
Corrected async/sync mismatch in document deletion call
=> fix: Resolve KnowledgeGraph entity resolution errors (#6653)

graphrag/entity_resolution.py, graphrag/general/extractor.py
I'm really sorry, I found that in graphrag/general/extractor.py under def __call__, the line change.removed_nodes.extend(nodes[1:]) causes an AttributeError: 'set' object has no attribute 'extend'. Could you please merge the branch e666528 again? I made some modifications.
=> Hotfix ece5903

docs/references/http_api_reference.md
align default values in create chat assistant HTTP API dos with implementation.
llm.presence_penalty  0.2 -> 0.4
prompt.top_n  8->6
=> Docs(api): align default values in create chat assistant HTTP API dos with implementation

api/apps/sdk/chat.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py
=> Fix: Error message is incorrect when updating chat name #6850

api/db/services/common_service.py
Fixes #6548 
Add exception handling to prevent exceptions from propagating back to the web, which may lead to failure in displaying conversation content.
=> fix: add exception handling for get_by_id method

agent/canvas.py
Fix the issue where waiting tasks couldn't be processed when upstream components were "switch", "categorize", or "relevant" and the normal processing path couldn't continue.
=> Fix: handle waiting tasks when upstream is switch/categorize/relevant and normal path fails

api/apps/kb_app.py
Fix: remove deprecated KB updating `permission` field. #6911
=> Fix: remove deprecated `permission` field

rag/nlp/search.py
https://github.com/infiniflow/ragflow/issues/6741
Using nightly version
Commit version: [[6051abb](https://github.com/infiniflow/ragflow/commit/6051abb4a328176717fae3836e2ce933a980a894)]
The retrieval function in rag/nlp/search.py returns the original total chunks number
even after chunks are filtered by similarity_threshold. This creates inconsistency
between the actual returned chunks and the reported total.
Added code to count how many search results actually meet or exceed the configured similarity threshold
Positioned the calculation after the doc_ids conditional logic to ensure special cases are handled correctly
Updated the ranks["total"] value to store this filtered count instead of using the raw search result count
Using NumPy leverages optimized C-level batch operations to …
=> Fix: incorrect total chunks count in retrieval function after similarity filtering (#6741) 

rag/raptor.py
Sometimes, the **s** in **chunks (s, a)** is an empty string. This causes the condition **if s and len(a) > 0** in the line **chunks = [(s, a) for s, a in chunks if s and len(a) > 0]** to fail, which changes the length of the new chunks. As a result, the final assertion **assert len(chunks) - end == n_clusters, "{} vs. {}".format(len(chunks) - end, n_clusters)** fails and raises a confusing error like 7 vs. 8
=> fix bug [ERROR][Exception]: 8 vs. 9

sdk/python/test/test_http_api/test_session_management/conftest.py, sdk/python/test/test_http_api/test_session_management/test_update_session_with_chat_assistant.py
cover [Update chat assistant's sessions](https://ragflow.io/docs/dev/http_api_reference#update-chat-assistants-session) endpoints
=> Test: Added test cases for Update Session With Chat Assistant HTTP API

rag/app/presentation.py
Sometimes a slide may trigger a Proxy error (ArgumentException: Parameter is not valid) due to issues in the original file, and this error message can be confusing for users.
=> Make error messages during PPT processing clearer.

web/src/components/ui/tree-view.tsx
Fix: The selected state of the TreeView node cannot be seen on Mac #7000
=> Fix: The selected state of the TreeView node cannot be seen on Mac #7000

api/apps/document_app.py
https://github.com/infiniflow/ragflow/issues/6905
When deleting a document will check before removing it from storage
=> Fix: when remove document do not delete the file in storage if the source is not knowledge base

api/db/services/llm_service.py
https://github.com/infiniflow/ragflow/issues/6548
https://github.com/infiniflow/ragflow/pull/6861
Commit version: [[48730e0](https://github.com/infiniflow/ragflow/commit/48730e00a864606606a9d0778620d75411488740)]
Unexpected `pymysql.err.InterfaceError: (0, '') `when using Peewee + PyMySQL + PooledMySQLDatabase  after a long-running `chat streamly` operation.  
This is a common issue with Peewee + PyMySQL + connection pooling: you end up using a connection that was silently closed by the server, but Peewee doesn't realize it's dead.
**I found that the error only occurs during longer streaming outputs** and is unrelated to the database connection context, so it's likely because:
- The prolonged streaming response caused the database connection to time out
- The original database connection …
=> Fix: pymysql.err.InterfaceError: (0, '') during long time streaming chat responses (#6548) 

web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
The assistant message placeholder is incorrect, I have finished modifying both Chinese and traditional Chinese characters
=> Fix: Error in sending placeholder words in Chinese and Chinese-Traditional

api/apps/sdk/doc.py
https://github.com/infiniflow/ragflow/issues/7083
Internal due to when returning from ES, fields changed to str, so the bool conversion does not work as expected.
=> Fix: wrong “available” property when list chunk 

graphrag/entity_resolution.py, graphrag/general/community_reports_extractor.py, graphrag/general/extractor.py, graphrag/general/mind_map_extractor.py, graphrag/utils.py, rag/raptor.py, rag/svr/task_executor.py
Multiple files in the RAGFlow project contain closure trap issues when using lambda functions with `trio.open_nursery()`. This problem causes concurrent tasks created in loops to reference the same variable, resulting in all tasks processing the same data (the data from the last iteration) rather than each task processing its corresponding data from the loop.
When using a `lambda` to create a closure function and passing it to `nursery.start_soon()` within a loop, the lambda function captures a reference to the loop variable rather than its value. For example:
```python
async with trio.open_nursery() as nursery:
for d in docs:
nursery.start_soon(lambda: doc_keyword_extraction(chat_mdl, d, topn))
```
In this pattern, when concurrent tasks begin execution, `d` has already become the value …
=> fix(nursery): Fix Closure Trap Issues in Trio Concurrent Tasks

rag/svr/task_executor.py, rag/utils/redis_conn.py
If you deploy Ragflow using Kubernetes, the hostname will change during a rolling update. This causes the consumer name of the task executor to change, making it impossible to schedule tasks that were previously in a pending state.
To address this, I introduced a recovery task that scans these pending messages and re-publishes them, allowing the tasks to continue being processed.
=> feat: Recover pending tasks while pod restart.

rag/utils/s3_conn.py
Hello, I encountered a problem when trying to use a S3 backend (seaweedfs) for storage in RAGFlow: when calling `STORAGE_IMPL.get("bucket", "key")`, the actual request sent to S3 is `bucket/bucket/key`, causing a `NoSuchKey` error.
I compared the code in `s3_conn.py` to `minio_conn.py` and `oss_conn.py`, then decided to remove the `else` branch in `use_prefix_path` method, and it works. I didn't configure `prefix_path` or `bucket` in `s3` section of the `service_conf.yaml`.
I think this is a bug, but not sure.
=> Fix: don't modify S3 file name when not using prefix_path

helm/templates/redis.yaml
This PR changes Redis to be a statefulset. In some situation when we Redis pod gets rescheduled to another Node, it gets stuck in pending state due to the PVC attached to another Kubernetes node.
=> refactor: Update Redis configuration to use StatefulSet instead of deployment with pvc

api/apps/sdk/dataset.py, api/settings.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py, sdk/python/test/test_sdk_api/t_dataset.py
The knowledge_graph chunk method is deprecated and should no longer be used. #7184.
=> Refa: knowledge_graph chunk method is deprecated

docker/entrypoint.sh
Fix the entrypoint file from the docker container to solve #7249 
Here is the important part from the logs:
```
docker logs -f ragflow-server
...
usage: server.py [-h] [--base_url BASE_URL] [--host HOST] [--port PORT]
[--mode MODE] [--api_key API_KEY]
server.py: error: unrecognized arguments:
...
```
=> Fix: mcp server start

conf/llm_factories.json
With current config will get error "Fail to access model(gemma-7b-it) using this api key"
Since the model has been removed, according to Groq official document: https://console.groq.com/docs/models
- [ x] Bug Fix (non-breaking change which fixes an issue)
=> Update Groq AI Model Config

api/utils/api_utils.py
In the generate_confirmation_token method, a spelling error was found with 'tenent_id'. The correct spelling should be 'tenant_id'.
=> Fix: tenant_id spelling error.

graphrag/general/graph_extractor.py, graphrag/general/graph_prompt.py
当前graphrag的LOOP_PROMPT，会导致模型输出Y之后，继续补充了实体和关系，比较浪费时间。参照[graph rag](https://github.com/microsoft/graphrag/blob/main/graphrag/prompts/index/extract_graph.py)最新的代码，修改了LOOP_PROMPT，经过验证，修改后可以稳定的输出Y停止。
Currently, GraphRAG’s LOOP_PROMPT causes the model to keep appending entities and relationships even after outputting “Y,” which wastes time. Referring to the latest code in [graphRAG](https://github.com/microsoft/graphrag/blob/main/graphrag/prompts/index/extract_graph.py), I modified the LOOP_PROMPT, and after verification the updated prompt reliably outputs “Y” and stops.
=> perf: Optimize GraphRAG’s LOOP_PROMPT

api/apps/auth/README.md, api/apps/auth/__init__.py, api/apps/auth/oauth.py, api/apps/auth/oidc.py, api/apps/user_app.py, api/settings.py, conf/service_conf.yaml, docker/service_conf.yaml.template, docs/configurations.md
Add support for OAuth2 and OpenID Connect (OIDC) authentication, allowing OAuth/OIDC authentication using the specified routes:
- `/login/<channel>`: Initiates the OAuth flow for the specified channel
- `/oauth/callback/<channel>`: Handles the OAuth callback after successful authentication
The callback URL should be configured in your OAuth provider as:
```
https://your-app.com/oauth/callback/<channel>
```
For detailed instructions on configuring **service_conf.yaml.template**, see: `./api/apps/auth/README.md#usage`.
- Related issues
#3495
=> Feat: Add support for OAuth2 and OpenID Connect (OIDC) authentication

rag/svr/task_executor.py
Fix the redis lock will always timeout (change the logic order release lock first)
=> Fix: improve recover_pending_tasks timeout

api/db/services/document_service.py, graphrag/general/index.py, graphrag/utils.py, rag/utils/infinity_conn.py
When you removed any document in a knowledge base using knowledge graph, the graph's `removed_kwd` is set to "Y".  
However, in the function `graphrag.utils.get_gaph`, `rebuild_graph` method is passed and directly return `None` while `removed_kwd=Y`, making residual part of the graph abandoned (but old entity data still exist in db).
Besides, infinity instance actually pass deleting graph components' `source_id` when removing document. It may cause wrong graph after rebuild.
=> Fix: whole knowledge graph lost after removing any document in the knowledge base

agent/component/base.py, agent/component/retrieval.py, web/src/components/knowledge-base-item.tsx, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/flow/form/components/dynamic-input-variable.tsx, web/src/pages/flow/form/retrieval-form/index.tsx
Fix #6600
Hello, I have the same business requirement as #6600. My use case is: 
We have many departments (> 20 now and increasing), and each department has its own knowledge base. Because the agent workflow is the same, so I want to change the knowledge base on the fly, instead of creating agents for every department.
It now looks like this:
Knowledge bases can be selected from the dropdown, and passed through the variables in the table. All selected knowledge bases are used for retrieval.
=> Feat: Support passing knowledge base id as variable in retrieval component

api/utils/api_utils.py, api/utils/validation_utils.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py
change create dataset delimiter default value to r'\n'
=> Fix: change create dataset htto api delimiter default value to r'\n'

deepdoc/parser/figure_parser.py, rag/svr/task_executor.py
When parsing documents containing images, the current code uses a single-threaded approach to call the VL model, resulting in extremely slow parsing speed (e.g., parsing a Word document with dozens of images takes over 20 minutes). 
By switching to a multithreaded approach to call the VL model, the parsing speed can be improved to an acceptable level.
=> perf: optimze figure parser

agent/component/retrieval.py, web/src/components/knowledge-base-item.tsx, web/src/pages/flow/constant.tsx, web/src/pages/flow/debug-content/index.tsx
This is a follow-up of #7088 , adding a knowledge base type input to the `Begin` component, and a knowledge base selector to the agent flow debug input panel:
then you can select one or more knowledge bases when testing the agent:
Note: the lines changed in `agent/component/retrieval.py` after line 94 are modified by `ruff format` from the `pre-commit` hooks, no functional change.
=> Feat: Support knowledge base type input in agent flow debugger

api/apps/auth/README.md, api/apps/auth/oauth.py, api/apps/auth/oidc.py, api/apps/user_app.py, conf/service_conf.yaml, docker/service_conf.yaml.template
Add `/login/channels` route and improve auth logic to support frontend integration with third-party login providers:
- Add `/login/channels` route to provide authentication channel list with `display_name` and `icon`
- Optimize user info parsing logic by prioritizing `avatar_url` and falling back to `picture`
- Simplify OIDC token validation by removing unnecessary `kid` checks
- Ensure `client_id` is safely cast to string during `audience` validation
- Fix typo
---
- Related pull request: #7379
=> Feat: Add `/login/channels` route and improve auth logic for frontend third-party login integration

rag/svr/task_executor.py
Two Case when local  Es tag search has result which is filtered by score
1: Doc has empty tag,and not visi LLM
2: Code may use empty examples in Prompt for LLM search tag
=> Fix:local_es_tag

api/db/services/common_service.py, api/db/services/llm_service.py, conf/service_conf.yaml, docker/service_conf.yaml.template
1. The MySQL instance is configured with max_connections=1000,
but our connection pool was limited to max_connections: 100.
This mismatch caused connection pool exhaustion during performance testing.
2.  Increase stale_timeout to resolve #6548
=> Perf: Increase database connection pool size

helm/templates/redis.yaml, helm/values.yaml
Fixes bug & regression introduced by [PR #7187 - refactor: Update Redis configuration to use StatefulSet instead of deployment with pvc](https://github.com/infiniflow/ragflow/pull/7187):
1. Fixes bug #7403  - `redis.persistence.enabled` missing from `helm/values.yaml` causes helm error:
[ERROR] templates/: template: ragflow/templates/redis.yaml:55:24: executing "ragflow/templates/redis.yaml" at <.Values.redis.persistence.enabled>: nil pointer evaluating interface {}.enabled
2. Fixes regression: reverts hardcoded redis.storage.capacity value back to using variable `redis.storage.capacity` from `helm/values.yaml`.
=> Fix: helm template redis

deepdoc/parser/pdf_parser.py
When the PDF uses vector fonts, the rendered text in the captured page image often has missing strokes, leading to numerous OCR errors and incorrect characters. Similar issues also occur in the extracted chart images.
**Before**
**After**
You can use the following document for testing.
[Casio说明书.pdf](https://github.com/user-attachments/files/20119690/Casio.pdf)
=> feat: Enable antialiasing for PDF image extraction to improve OCR accuracy

helm/templates/elasticsearch.yaml, helm/templates/infinity.yaml, helm/templates/minio.yaml, helm/templates/mysql.yaml, helm/templates/redis.yaml
Modified the chart to retain persistent volumes by default when the chart is uninstalled, following established best practices in the Helm community (e.g., Bitnami charts)
Previously, deleting the helm chart would automatically remove all persistent data, which poses a risk of accidental data loss.
This change aligns with industry standards to safeguard data by requiring explicit action to remove persistence, rather than making deletion the default behavior.
Users who intentionally want to remove persistent data will need to do so manually or by setting appropriate flags during chart uninstallation.
=> Set helm resource-policy to be keep

rag/app/naive.py
Since `import markdown.markdown` has been changed to `import markdown` in `rag/app/naive.py`, previous code for converting markdown tables would call a markdown module instead of a callable function. This cause error.
=> Fix: markdown table conversion error

api/apps/sdk/agent.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/ragflow.py
Hello, we are using ragflow as a backend service, so we need to manage agents from our own frontend. So adding these http APIs to manage agents.
The code logic is copied and modified from the `rm` and `save` methods in `api/apps/canvas_app.py`.
btw, I found that the `save` method in `canvas_app.py` actually allows to modify an agent to an existing title, so I kept the behavior in the http api. I'm not sure if this is intentional.
=> Feat: Add http api to create, update, or delete agents.

graphrag/general/index.py, rag/svr/task_executor.py
Info of whether applying graph resolution and community extraction is storage in `task["kb_parser_config"]`. However, previous code get `graphrag_conf` from `task["parser_config"]`, making `with_resolution` and `with_community` are always false.
=> Fix: missing graph resolution and community extraction in graphrag tasks

api/apps/api_app.py, rag/nlp/search.py
=> FIX:ZeroDivisionError when using large page_size in client.retrieve()

pyproject.toml
For `uv package`/`uv pip install ".[full]"`, bug introduced in #6370:
* Removes erroneous (non-package) directories (`helm`, `flask_session`)
* Adds `mcp.server` package
* Resolves "warning: package would be ignored" ambiguity by changing `sdk` to `sdk.python.ragflow_sdk`
* Resolves "error: package directory 'intergrations' does not exist" by including `intergrations.chatgpt-on-wechat.plugins` explicitly
* Also rearranges packages in alphabetical order, for DX.
=> Fix: setuptools package definitions

pyproject.toml
TOML-table-based project.license is deprecated as per PEP 639, see: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files
The following error when building project (e.g. `uv build`)
```
SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details. …
```
=> Fix: Setuptools project.license as a TOML table deprecation

api/apps/conversation_app.py
Hello, when I input a very long line in the chat input box, it will fail with following error:
```
2025-05-17 16:11:26,004 ERROR    182558 value too long for type character varying(255)
File "/var/home/sfc/Projects/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3291, in execute_sql
cursor.execute(sql, params or ())
psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)
During handling of the above exception, another exception occurred:
File "/var/home/sfc/Projects/ragflow/api/apps/conversation_app.py", line 68, in set_conversation
ConversationService.save(**conv)
File "/var/home/sfc/Projects/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3128, in inner
return …
```
=> Fix: value too long error for chat name

rag/svr/task_executor.py
During the execution process, due to improper use of trio CapacityLimiter, the configuration parameter MAX_CONCURRENT_TASKS is invalid, causing the executor to take out a large number of tasks from the Redis queue at one time.
This behavior will cause the task executor to occupy too much memory and be killed by the OS when a large number of tasks exist at the same time. As a result, all executing tasks are suspended.
Added the task_manager method to the entry of /rag/svr/task_executor.py to make CapacityLimiter effective. Deleted the invalid async with statement.
After testing, the task executor execution meets expectations, that is: concurrent execution of up to $MAX_CONCURRENT_TASKS tasks.
=> fix: Fix the problem that concurrent execution limit in task executor fails and causes OOM (issue#7580)

api/apps/dialog_app.py
- Updated the dialog settings function to add a default prompt configuration for no dataset.
- The prompt configuration will be determined based on the presence of `kb_ids` in the request.
=> When creating an assistant, no dataset is specified, a different default system promt is used

api/apps/auth/oauth.py, api/apps/user_app.py
Add OAuth `state` parameter for CSRF protection:
- Updated `get_authorization_url()` to accept an optional state parameter
- Generated a unique state value during OAuth login and stored in session
- Verified state parameter in callback to ensure request legitimacy
This PR follows OAuth 2.0 security best practices by ensuring that the authorization request originates from the same user who initiated the flow.
=> Feat: Add OAuth `state` parameter for CSRF protection

web/src/components/image/index.tsx, web/src/pages/chat/markdown-content/index.less, web/src/pages/chat/markdown-content/index.tsx
Feat: The image displayed in the reply message can also be clicked to display the location of the source document where the slice is located #7623
=> Feat: The image displayed in the reply message can also be clicked to display the location of the source document where the slice is located #7623

deepdoc/parser/resume/entities/corporations.py, deepdoc/parser/resume/step_two.py, rag/nlp/__init__.py
This small PR resolves the regex library warnings showing in Python3.11:
```python
DeprecationWarning: 'count' is passed as positional argument
```
=> Fix: resolve regex library warnings

agent/component/exesql.py
Remove the backquotes in the sql generated by LLM to prevent it from causing execution errors.
=> Fix backquotes in text2sql causing execution errors

api/apps/api_app.py
**Issue Description:**
When using the `/api/retrieval` endpoint with a POST request and setting the `keyword` parameter to `true`, the system invokes the `model_instance` method from `TenantLLMService` to create a `chat_mdl` instance. Subsequently, it calls the `keyword_extraction` method to extract keywords.
However, within the `keyword_extraction` method, the `chat` function of the LLM attempts to access the `chat_mdl.max_length` attribute to validate input length. This results in the following error:
```
AttributeError: 'SILICONFLOWChat' object has no attribute 'max_length'
```
**Proposed Solution:**
Upon reviewing other parts of the codebase where `chat_mdl` instances are created, it appears that utilizing `LLMBundle` for instantiation is more appropriate. `LLMBundle` includes the …
=> fix: resolve “has no attribute 'max_length'” error in keyword_extraction

web/src/components/llm-select/llm-label.tsx, web/src/components/llm-select/next.tsx, web/src/pages/agent/agent-sidebar.tsx, web/src/pages/agent/canvas/node/begin-node.tsx, web/src/pages/agent/canvas/node/categorize-handle.tsx, web/src/pages/agent/canvas/node/categorize-node.tsx, web/src/pages/agent/canvas/node/email-node.tsx, web/src/pages/agent/canvas/node/generate-node.tsx, web/src/pages/agent/canvas/node/index.tsx, web/src/pages/agent/canvas/node/invoke-node.tsx, web/src/pages/agent/canvas/node/iteration-node.tsx, web/src/pages/agent/canvas/node/keyword-node.tsx, web/src/pages/agent/canvas/node/logic-node.tsx, web/src/pages/agent/canvas/node/message-node.tsx, web/src/pages/agent/canvas/node/node-header.tsx, web/src/pages/agent/canvas/node/relevant-node.tsx, web/src/pages/agent/canvas/node/retrieval-node.tsx, web/src/pages/agent/canvas/node/rewrite-node.tsx, web/src/pages/agent/canvas/node/switch-node.tsx, web/src/pages/agent/canvas/node/template-node.tsx
Feat: Use memo to wrap canvas nodes to improve fluency #3221
=> Feat: Use memo to wrap canvas nodes to improve fluency #3221

api/apps/sdk/session.py
SpringAI can only add session_id in metadata。so add new way to get session_id from "id" or "metadata.id"
=> agents openai API add new way to get session_id

api/db/services/document_service.py
When deleting knowledge base documents in RAGFlow, the current process only removes the block texts in Elasticsearch and the original files in MinIO, but it leaves behind many binary images and thumbnails generated during chunking. This pull request improves the deletion process by querying the block information in Elasticsearch to ensure a more thorough and complete cleanup.
=> fix: resolve residual image files issue after document deletion

api/ragflow_server.py
**Fix: Prevent Flask hot reload from hanging due to early thread startup**
When running the Flask server with `use_reloader=True` (enabled during debug mode), modifying a Python source file would trigger a reload detection (`Detected change in ...`), but the application would hang instead of restarting cleanly.
This was caused by the `update_progress` background thread being started **too early**, often within the main module scope. 
This issue was reported in [#7498](https://github.com/infiniflow/ragflow/issues/7498).
---
**Summary of changes:**
- Wrapped `update_progress` launch in a `threading.Timer` with delay to avoid premature thread execution.
- Marked thread as `daemon=True` to avoid blocking process exit.
- Added `WERKZEUG_RUN_MAIN` environment check to ensure background threads …
=> Fix: Prevent Flask hot reload from hanging due to early thread startup

rag/app/naive.py, rag/nlp/__init__.py
Fix unnecessary truncation in markdown parser. So that markdown can work perfectly like [this](https://github.com/infiniflow/ragflow/issues/7824#issuecomment-2921312576) in #7824, supporting multiple special delimiters.
=> Fix: Unnecessary truncation in markdown parser

rag/prompts.py
Fixed grammar errors and improved clarity in prompt templates throughout `rag/prompts.py`.
- **Fixed incomplete sentence**: `"If the user's latest question is completely, don't do anything"` → `"If the user's latest question is already complete, don't do anything"`
- **Improved phrasing**: `"of like [ID:i]"` → `"such as [ID:i]"`
- **Added missing articles**: `"give top 3"` → `"give the top 3"`
- **Fixed prepositions**: `"in language of"` → `"in the same language as"`
- **Corrected spelling**: `"Jappanese"` → `"Japanese"`
- **Standardized formatting**: Consistent role descriptions and punctuation
These changes improve prompt readability and should make instructions clearer for the underlying language models.
=> Fix: Grammar and clarity improvements in prompt templates

docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/session.py, web/src/interfaces/request/base.ts
The Unicode codepoint '，' (U+FF0C) is meant to be used in Chinese text, but this is English text. It looks like a comma followed by a space, but isn't. Of course I didn't change actual Chinese text.
Mixup of Unicode characters. This is probably unnoticed by most users, but I wonder if screen readers would read it out differently or if LLMs would trip up on it.
=> Don't use '，' (U+FF0C) but ', ' (U+2C U+20)

api/apps/__init__.py, api/apps/user_app.py, api/db/services/user_service.py, api/settings.py
There's a critical authentication bypass vulnerability that allows remote attackers to gain unauthorized access to user accounts without any credentials. The vulnerability stems from two security flaws: (1) the application uses a predictable `SECRET_KEY` that defaults to the current date, and (2) the authentication mechanism fails to properly validate empty access tokens left by logged-out users. When combined, these flaws allow attackers to forge valid JWT tokens and authenticate as any user who has previously logged out of the system.
The authentication flow relies on JWT tokens signed with a `SECRET_KEY` that, in default configurations, is set to `str(date.today())` (e.g., "2025-05-30"). When users log out, their `access_token` field in the database is set to an empty string but their …
=> Fix: Authentication Bypass via predictable JWT secret and empty token validation

agent/component/message.py
now Streamning logic is not match with none streaming logic, which may introduce down stream can not find upstream components.
=> Fix: set output for Message template

sdk/python/ragflow_sdk/modules/document.py
An exception is thrown only when the json file has only two keys, `code` and `message`. In other cases, response.content is returned normally.
=> Fix: Resolve JSON download errors in Document.download()

rag/svr/task_executor.py
Currently, as long as there are tasks in Redis, this loop will keep getting the tasks. This will lead to a single task executor with many tasks in the pending state. Then we need to wait for the pending tasks to get them back in the queue.
In first place, if we set the `MAX_CONCURRENT_TASKS` to X, then only X tasks should be picked from the queue, and others should be left in the queue for other `task_executors` or be picked after 1 of the spots in the current executor gets free. This PR ensures this behavior.
The additional changes were due to the Ruff linting in pre-commit. But I believe these are expected to keep the coding style.
=> fix: single task executor getting all tasks from Redis queue

sdk/python/ragflow_sdk/modules/chat.py
Previously when LLM.rerank_model was not configured:
- SDK would pass None as the value
- Database field with null=False constraint would reject it
- Caused storage failures for unset rerank_model cases
Now:
- SDK checks for None value before database operations
- Provides empty string as default when rerank_model is unset
=> Fix: Set default rerank_model to empty string in Chat class

sdk/python/ragflow_sdk/modules/chat.py
Previously when LLM.model_name was not configured:
- System incorrectly defaulted to 'deepseek-chat' model
- This caused permission errors for unauthorized tenants
Now:
- Use tenant's default chat_model configuration first
=> Fix: chat module  update LLM defaults

api/apps/auth/oidc.py
Issue: #8051
The current implementation assumes JWKS endpoints follow the standard `/.well-known/jwks.json` convention. This breaks authentication for OIDC providers that use non-standard JWKS paths, resulting in 404 errors during token validation.
Root Cause Analysis
- The OpenID Connect specification doesn't mandate a fixed path for JWKS endpoints
- Some identity providers (like certain Keycloak configurations) use custom endpoints
- Our previous approach constructed JWKS URLs by convention rather than discovery
Instead of constructing JWKS URLs by appending to the issuer URI, we now:
1. Properly leverage the `jwks_uri` from the OIDC discovery metadata
2. Honor the identity provider's actual configured endpoint
```python
jwks_url = f"{self.issuer}/.well-known/jwks.json"
jwks_cli = …
```
=> Fix: use jwks_uri from OIDC metadata for JWKS client

api/apps/kb_app.py
- Trim whitespace before checking for empty dataset names
- Change length check from >= to > DATASET_NAME_LIMIT for consistency
=> Fix: Improve dataset name validation in KB app

api/apps/kb_app.py
Validate that pagerank updates are only allowed when using elasticsearch as the document engine. Return an error if pagerank is set while using a different doc engine, preventing potential inconsistencies in document scoring.
#8208
=> Fix: Add pagerank validation for non-elasticsearch doc engines

graphrag/entity_resolution.py, graphrag/general/community_reports_extractor.py, rag/svr/task_executor.py
This PR investigates the cause of #7957.
TL;DR: Incorrect similarity calculations lead to too many candidates. Since candidate selection involves interaction with the LLM, this causes significant delays in the program.
What this PR does:
1. **Fix similarity calculation**:
When processing a 64 pages government document, the corrected similarity calculation reduces the number of candidates from over 100,000 to around 16,000. With a default batch size of 100 pairs per LLM call, this fix reduces unnecessary LLM interactions from over 1,000 calls to around 160, a roughly 10x improvement.
2. **Add concurrency and timeout limits**: 
Up to 5 entity types are processed in "parallel", each with a 180-second timeout. These limits may be configurable in future updates.
3. **Improve logging**:
The …
=> Refa: GraphRAG and explaining GraphRAG stalling behavior on large files

conf/service_conf.yaml, rag/utils/opendal_conn.py
This PR resolves the inconsistency in the opendal configuration where both ‎`schema` and ‎`scheme` were used as keys. The code and configuration file now consistently use ‎`scheme`, which helps prevent configuration errors and runtime issues. This change improves code clarity and maintainability.
- Updated both ‎`conf/service_conf.yaml` and ‎`rag/utils/opendal_conn.py` to use ‎`scheme` instead of ‎`schema`
- No breaking changes to other configuration fields
=> Fix: unify opendal config key from ‎`schema` to ‎`scheme`

test/libs/auth.py, test/testcases/test_http_api/test_dataset_mangement/test_delete_datasets.py, test/testcases/test_web_api/common.py, test/testcases/test_web_api/conftest.py, test/testcases/test_web_api/test_kb_app/conftest.py, test/testcases/test_web_api/test_kb_app/test_create_kb.py, test/testcases/test_web_api/test_kb_app/test_detail_kb.py, test/testcases/test_web_api/test_kb_app/test_list_kbs.py, test/testcases/test_web_api/test_kb_app/test_rm_kb.py, test/testcases/test_web_api/test_kb_app/test_update_kb.py
- Implement RAGFlowWebApiAuth class for web API authentication
- Add comprehensive test cases for KB CRUD operations
- Set up common fixtures and utilities in conftest.py
- Add helper functions in common.py for web API requests
The changes establish a complete testing framework for knowledge base management via web API endpoints.
=> Test: Add web API test suite for knowledge base operations

api/db/services/llm_service.py
Fix mixing different embedding models in document parsing.
=> Fix: avoid mixing different embedding models in document parsing

mcp/client/client.py, mcp/server/server.py
Add authorization header for MCP server based on [OAuth 2.1](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-1-12#section-5).
=> Feat: add authorization header for MCP server based on OAuth 2.1

api/apps/document_app.py
- Add validation for empty filenames in document_app.py and trim whitespace
=> Fix: Add validation for empty filenames in document_app.py

api/apps/document_app.py, api/apps/sdk/doc.py, api/constants.py, api/db/services/file_service.py
- Replace hardcoded 255-byte file name length checks with FILE_NAME_LEN_LIMIT constant
- Update error messages to show the actual limit value
- #8290
=> Refa: Implement centralized file name length limit using FILE_NAME_LEN_LIMIT constant

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docker/README.md, docs/configurations.md, docs/develop/build_docker_image.mdx, docs/faq.mdx, docs/guides/chat/start_chat.md, docs/guides/dataset/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/tracing.mdx, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, docs/references/glossary.mdx, helm/values.yaml, pyproject.toml, sdk/python/pyproject.toml, sdk/python/uv.lock, uv.lock
- Update Docker image version badges and references from v0.19.0 to v0.19.1
- Modify version mentions in all localized README files (id, ja, ko, pt_br, tzh, zh)
- Update version in docker/README.md and related documentation files
- Includes updates to Helm values and Python SDK dependencies
=> Docs: Update version references to v0.19.1 in READMEs and docs

rag/llm/embedding_model.py
image_version: v0.19.1
This PR fixes a bug in the HuggingFaceEmBedding API method that was causing AssertionError: assert len(vects) == len(docs) during the document embedding process.
The HuggingFaceEmbed.encode() method had an early return statement inside the for loop, causing it to return after processing only the first text input instead of processing all texts in the input list.
**Error Messenge**
```python
AssertionError: assert len(vects) == len(docs) # input chunks  != embedded  vectors from embedding api
File "/ragflow/rag/svr/task_executor.py", line 442, in embedding
```
**Buggy code(/ragflow/rag/llm/embedding_model.py)**
```python
class HuggingFaceEmbed(Base):
def __init__(self, key, model_name, base_url=None):
if not model_name:
raise ValueError("Model name cannot be None") …
```
=> fix a bug when using huggingface embedding api

test/testcases/test_http_api/common.py, test/testcases/test_http_api/test_file_management_within_dataset/test_list_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_upload_documents.py, test/testcases/test_web_api/common.py, test/testcases/test_web_api/conftest.py, test/testcases/test_web_api/test_document_app/conftest.py, test/testcases/test_web_api/test_document_app/test_create_document.py, test/testcases/test_web_api/test_document_app/test_list_documents.py, test/testcases/test_web_api/test_document_app/test_paser_documents.py, test/testcases/test_web_api/test_document_app/test_rm_documents.py, test/testcases/test_web_api/test_document_app/test_upload_documents.py
- Add new test suite for document app with create/list/parse/upload/remove tests
- Update API URLs to use version variable from config in HTTP and web API tests
=> Test: Add document app tests

rag/app/qa.py
Using the QA chunking method with a large PDF (e.g., 300+ pages) may lead to OOM in the ragflow-worker module.
=> Fix: Solve the OOM issue when passing large PDF files while using QA chunking method.

api/apps/sdk/session.py
stack：
```
2025-06-26 17:22:24,739 ERROR    1609 list index out of range
File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
rv = self.dispatch_request()
File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
File "/ragflow/api/utils/api_utils.py", line 298, in decorated_function
return func(*args, **kwargs)
File "/ragflow/api/apps/sdk/session.py", line 472, in list_session
print(conv["reference"][message_num])
IndexError: list index out of range
```
=> fix: list index out of range

api/apps/chunk_app.py, test/testcases/test_http_api/conftest.py, test/testcases/test_web_api/common.py, test/testcases/test_web_api/conftest.py, test/testcases/test_web_api/test_chunk_app/conftest.py, test/testcases/test_web_api/test_chunk_app/test_create_chunk.py, test/testcases/test_web_api/test_chunk_app/test_list_chunks.py, test/testcases/test_web_api/test_chunk_app/test_retrieval_chunks.py, test/testcases/test_web_api/test_chunk_app/test_rm_chunks.py, test/testcases/test_web_api/test_chunk_app/test_update_chunk.py
- Add comprehensive test suite for chunk operations including:
- Test files for create, list, retrieve, update, and delete chunks
- Authorization tests
- Batch operations tests
- Update test configurations and common utilities
- Validate `important_kwd` and `question_kwd` fields are lists in chunk_app.py
- Reorganize imports and clean up duplicate code
=> Test: Add tests for chunk API endpoints

docker/docker-compose-base.yml
- Ensure consistent Minio deployment by pinning the image to a specific release version (RELEASE.2025-06-13T11-33-47Z) for stability and reproducibility.
- #8672
=> Refa: Update Minio image to specific release version in docker-compose-base.yml

docker/docker-compose-base.yml, docker/docker-compose.yml
Suppress docker-compose warning like:
```bash
The "HF_ENDPOINT" variable is not set. Defaulting to a blank string.
The "MACOS" variable is not set. Defaulting to a blank string.
The "SANDBOX_EXECUTOR_MANAGER_IMAGE variable is not set. Defaulting to a blank string.
The "SANDBOX_EXECUTOR_MANAGER_PORT variable is not set. Defaulting to a blank string.
```
=> Fix: suppress docker-compose warning

web/src/pages/user-setting/setting-model/ollama-modal/index.tsx
'handleOk' was used before it was defined.eslint@typescript-eslint/no-use-before-define
=> Fix: EsLint Problem of index.tsx

test/testcases/test_web_api/common.py, test/testcases/test_web_api/conftest.py, test/testcases/test_web_api/test_dialog_app/conftest.py, test/testcases/test_web_api/test_dialog_app/test_create_dialog.py, test/testcases/test_web_api/test_dialog_app/test_delete_dialogs.py, test/testcases/test_web_api/test_dialog_app/test_dialog_edge_cases.py, test/testcases/test_web_api/test_dialog_app/test_get_dialog.py, test/testcases/test_web_api/test_dialog_app/test_list_dialogs.py, test/testcases/test_web_api/test_dialog_app/test_update_dialog.py
This commit introduces a comprehensive test suite for the dialog app, including tests for creating, updating, retrieving, listing, and deleting dialogs. Additionally, the common.py file has been updated to include necessary API endpoints and helper functions for dialog operations.
=> Test: Add dialog app test suite and update common.py with dialog endpoints

api/utils/api_utils.py, api/utils/validation_utils.py, test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py, test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py, test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py, test/testcases/test_sdk_api/test_dataset_mangement/test_create_dataset.py, test/testcases/test_sdk_api/test_dataset_mangement/test_update_dataset.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_update_document.py
Updated the default `chunk_token_num` value in `api_utils.py` and `validation_utils.py` to 512 to accommodate larger text chunks. Adjusted corresponding test cases in HTTP and SDK API tests to reflect this change.
=> Fix: Increase default `chunk_token_num` from 128 to 512 in parser config

api/apps/chunk_app.py
The rm function in chunk_app.py now takes the index name differently than other functions, so there will be situations where users can create and update a chunk but not delete it.
=> fix: use tenant_id of kb to get index name in rm chunk func

deepdoc/parser/markdown_parser.py, rag/app/naive.py
Fix context loss caused by separating markdown tables from original text. #6871, #8804.
=> Fix: fixed context loss caused by separating markdown tables from original text

web/src/pages/add-knowledge/components/knowledge-graph/util.ts
Fixed graphknowledge Tree structure not found for treeKey.
=> Fix: graphknowledge Tree structure not found for treeKey: combo (#7819)

rag/llm/chat_model.py
Correct the logging message from "OpenAI cat_with_tools" to "OpenAI chat_with_tools" in the `_exceptions` method of the `Base` class to accurately reflect the method name and improve error traceability.
=> Fix: fix typo in OpenAI error logging message

helm/templates/elasticsearch-config.yaml, helm/templates/env.yaml, helm/templates/opensearch-config.yaml, helm/templates/opensearch.yaml, helm/values.yaml
Adds OpenSearch support to the RAGFlow Helm chart based on https://github.com/infiniflow/ragflow/pull/7140 and the existing Elasticsearch support in the Helm chart.
=> Add OpenSearch support to Helm chart

api/utils/api_utils.py, api/utils/validation_utils.py, test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py, test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py, test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py, test/testcases/test_sdk_api/test_dataset_mangement/test_create_dataset.py, test/testcases/test_sdk_api/test_dataset_mangement/test_update_dataset.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_update_document.py
- Update `get_parser_config` to merge provided configs with defaults
- Add GraphRAG configuration defaults for all chunk methods
- Make raptor and graphrag fields non-nullable in ParserConfig schema
- Update related test cases to reflect config changes
- Ensure backward compatibility while adding new GraphRAG support
- #8396
=> Fix: Refactor parser config handling and add GraphRAG defaults

rag/utils/opendal_conn.py
Use `quote_plus` to escape password in opendal's mysql url to support special characters like `#`.
=> use quote_plus to escape password in opendal's mysql url

conf/llm_factories.json
Adds configurations for gemini-2.5-flash and Gemini 2.5-pro models, including tags, maximum token limits, and model types.
=> Fix: Adds newest Gemini models to fit google's standard API rate limits

api/utils/api_utils.py, test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_parse_documents.py
- Extended embedding model timeout from 3 to 10 seconds in api_utils.py
- Added more time for large file batches and concurrent parsing operations to prevent test flakiness
- Import from #8940
- https://github.com/infiniflow/ragflow/actions/runs/16422052652
=> Fix: Increase timeouts for document parsing and model checks

helm/templates/opensearch.yaml
Fix Kubernetes liveness probe on the OpenSearch container. The previous HTTP probe received an 401 response from the OpenSearch API which treated as a failure and caused the container to be restarted every 20 minutes.
=> Fix OpenSearch liveness probe

helm/templates/redis.yaml
Previous version created labels which were dependent on the specific Helm chart version such as:
```
volumeClaimTemplates:
- metadata:
name: redis-data
labels:
helm.sh/chart: ragflow-0.2.3-dev.0.opensearch-test.4
app.kubernetes.io/name: ragflow
app.kubernetes.io/instance: test-1
app.kubernetes.io/version: "9a04408"
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/component: redis
```
which causes `helm upgrade` commands to fail with
```
Upgrade "test-1" failed: cannot patch "test-1-ragflow-redis" with
kind StatefulSet: StatefulSet.apps "test-1-ragflow-redis" is
invalid: spec: Forbidden: updates to statefulset spec for fields
other than 'replicas', 'ordinals', 'template', 'updateStrategy',
'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are
forbidden
```
because the labels …
=> Ensure Redis volumeClaimTemplate labels are deterministic

api/utils/__init__.py
Obfuscates additional secrets values on ragflow_server startup to prevent leakage: 
* `secret` (azure)
* `client_secret` (oauth)
* `http_secret_key` (authentication)
* `sas_token` (azure)
=> fix: obfuscate additional server secrets values

docker/docker-compose-macos.yml
Mac OS build fails on M4. Docker compose requires platform to be specified to build correctly
=> adding platform: linux/amd64 to the mac build

docs/develop/mcp/mcp_client_example.md
- Fix incomplete curl command in section 5 'Tool calling', add missing closing braces and parentheses to complete the JSON payload
This resolves the incomplete bash script that was missing proper JSON structure closure.
=> docs: Complete tool calling bash script in MCP client example

rag/llm/chat_model.py, rag/llm/embedding_model.py
fix error 429 api rate limit when building knowledge graph for all chat model and Mistral embedding model.
=> Fix: fix error 429 api rate limit when building knowledge graph for all chat model and Mistral embedding model

api/apps/document_app.py
doc_ids is a list , should use request.args.getlist("doc_ids")
=> Fix : API /document/thumbnails using wrong method to get ''doc_ids'

api/db/services/document_service.py
```bash
File "/home/infiniflow/workspace/ragflow/api/db/services/document_service.py", line 635, in update_progress
info["progress_msg"] = "%d tasks are ahead in the queue..."%get_queue_length(priority)
File "/home/infiniflow/workspace/ragflow/api/db/services/document_service.py", line 686, in get_queue_length
return int(group_info.get("lag", 0))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
This issue can happen very rare. When a `stream` is first created, the `lag` value may be nil, which can cause this issue. However, once any message is synced, the `lag` will become `0` afterwards.
```bash
> XINFO GROUPS rag_flow_svr_queue
1)  1) "name"
2) "rag_flow_svr_task_broker"
3) "consumers"
4) (integer) 0 …
```
=> Fix: Redis stream lag can be nil

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docker/.env, docker/README.md, docs/configurations.md, docs/develop/build_docker_image.mdx, docs/faq.mdx, docs/guides/chat/start_chat.md, docs/guides/dataset/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/tracing.mdx, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, docs/references/glossary.mdx, helm/values.yaml, pyproject.toml, sdk/python/pyproject.toml, sdk/python/uv.lock, uv.lock
- Update version tags in README files (including translations) from v0.19.1 to v0.20.0
- Modify Docker image references and documentation to reflect new version
- Update version badges and image descriptions
- Maintain consistency across all language variants of README files
=> Docs: Update version references to v0.20.0 in READMEs and docs

api/apps/kb_app.py
The index name of the tag chunks is generated by the tenant id of the knowledge base, so it should use the tenant id instead of the current user id in the listing tags API.
=> Fix: list tags api by using tenant id instead of user id

rag/app/presentation.py
fix "out of memory" if slide.get_thumbnail() to a huge image
=> fix "out of memory" if slide.get_thumbnail() to a huge image

api/apps/conversation_app.py, api/apps/sdk/session.py
#9232
1.  When creating a new session, initialize an empty reference that includes both the app api and sdk API.
2. Fix the logic when retrieving references for historical messages: the number of dialogue messages and reference messages may differ, but it should match the number of assistant messages.
=> Fix: fix mismatch of assitant message and its reference

docker/.env, docker/service_conf.yaml.template, rag/utils/opendal_conn.py
Add missing env var `MYSQL_MAX_PACKET` to service_conf.yaml.template, and add default values to opendal config to fix npe.
=> fix: add missing env vars and default values of service_conf.yaml

sdk/python/ragflow_sdk/modules/chat.py
- The default dataset_ids "kb1" was removed from the Chat class. 
- The HTTP API response does not include the dataset_ids field.
=> Fix: Remove default dataset_ids from Chat class initialization

test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_update_chunk.py, test/testcases/test_sdk_api/test_dataset_mangement/test_update_dataset.py
- Modify error message assertion in chunk update test to check for document ownership
- Add GraphRAG configuration with `use_graphrag: False` in dataset update tests
- Fix actions: https://github.com/infiniflow/ragflow/actions/runs/16863637898/job/47767511582
=> Fix: Update test assertions and add GraphRAG config in dataset tests

api/apps/sdk/chat.py
- Root cause: accessing req.get("dataset_ids") returns None when the key is absent, causing KeyError.
- Fix: use req.get("dataset_ids", []) to default to empty list.
=> Fix: handle missing dataset_ids when creating chat assistant

test/testcases/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py, test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py
- Fix error message assertion in test_update_chunk.py to match new ownership validation
- Simplify dataset listing test cases by removing lambda assertions for sorting
- Fix actions: https://github.com/infiniflow/ragflow/actions/runs/16885465524/job/47831942553
=> Fix: Update test assertions and simplify test cases

agent/component/llm.py
Change return type of _generate_streamly from str to Generator[str, None, None] to properly type hint streaming responses.
=> Refa: Update LLM stream response type to Generator

docs/references/http_api_reference.md
Add `url`, `doc_type`, and `created_at` fields to the API response example in the documentation.
=> Docs: Update HTTP API reference with new response fields

rag/llm/cv_model.py
fix: preserve correct MIME & unify data URL handling for vision inputs (relates #9248)
- Updated image2base64() to return a full data URL (data:image/<fmt>;base64,...) with accurate MIME
- Removed hardcoded image/jpeg in Base._image_prompt(); pass through data URLs and default raw base64 to image/png
- Set AnthropicCV._image_prompt() raw base64 media_type default to image/png
- Ensures MIME type matches actual image content, fixing “cannot process base64 image” errors on vLLM/OpenAI-compatible backends
This PR fixes a compatibility issue where base64-encoded images sent to vision models (e.g., vLLM/OpenAI-compatible backends) were rejected due to mismatched MIME type or incorrect decoding.
Previously, the backend:
- Always converted raw base64 into data:image/jpeg;base64,... even if the …
=> fix: preserve correct MIME & unify data URL handling for vision inputs (relates #9248)

helm/templates/elasticsearch.yaml, helm/templates/infinity.yaml, helm/templates/minio.yaml, helm/templates/mysql.yaml, helm/templates/opensearch.yaml, helm/templates/ragflow.yaml, helm/templates/redis.yaml, helm/values.yaml
- Unified configuration format: All services now use the same image configuration structure for consistency.
- Private registry support: Added imagePullSecrets to enable pulling images from private registries.
-  Per-service flexibility: Each service can override image-related parameters independently.
=> Refactor:Standardize image conf and add private registry support

web/src/pages/agent/form/begin-form/index.tsx
There is a problem with the implementation of the Agent begin-form: although the enablePrologue switch and the prologue input box are hidden in Task mode, these values are still saved in the form data. If the user first enables the opening and sets the content in Conversational mode, and then switches to Task mode, these values will still be saved and may be used in some scenarios.
=> Fix the bug in enablePrologue under agent task mode

api/ragflow_server.py
Move stop_event.wait(6) into finally block so that even when an exception occurs, the loop still sleeps before retrying. This prevents busy looping and excessive error logs when Redis connection fails.
=> Fix: ensure update_progress loop always waits between iterations

pyproject.toml, uv.lock
Bump infinity-sdk dependency to the latest development version (0.6.0.dev5) in both pyproject.toml and uv.lock files to incorporate recent changes and fixes from the SDK.
=> Chore: Update infinity-sdk from 0.6.0.dev4 to 0.6.0.dev5

web/src/app.tsx, web/src/pages/next-chats/chat/app-settings/chat-settings.tsx, web/src/pages/next-chats/hooks/use-rename-chat.ts
Feat: Exclude operator_permission field from renaming chat fields #3221
=> Feat: Exclude operator_permission field from renaming chat fields #3221

api/db/services/canvas_service.py
Fix Multiple conversations cause the reference list to grow indefinitely due to Python's mutable default argument behavior.
Explicitly initialize reference as empty list when creating new sessions
=> Fix: grow reference list

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docker/.env, docker/README.md, docs/configurations.md, docs/develop/build_docker_image.mdx, docs/faq.mdx, docs/guides/agent/agent_component_reference/agent.mdx, docs/guides/agent/agent_component_reference/retrieval.mdx, docs/guides/chat/start_chat.md, docs/guides/dataset/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/tracing.mdx, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, docs/references/glossary.mdx, helm/values.yaml, pyproject.toml, sdk/python/pyproject.toml, sdk/python/uv.lock, uv.lock
- Update version tags in README files (including translations) from v0.20.3 to v0.20.4
- Modify Docker image references and documentation to reflect new version
- Update version badges and image descriptions
- Maintain consistency across all language variants of README files
=> Docs: Update version references to v0.20.4 in READMEs and docs

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md
Updates the installation step in README.md to explicitly include pre-commit alongside uv.
Applies the change to all localized versions: English, Chinese, Japanese, Korean, Indonesian, and Portuguese.
The installation instructions previously mentioned only uv, but pre-commit is also required for contributing.
Ensures consistency across all language versions and helps new contributors set up the environment correctly.
=> Clarify installation of pre-commit alongside uv in README

web/src/pages/user-setting/setting-model/index.tsx
This PR enhances the display of tags in the UI.
* Before: Model tags were shown as a single string with commas.
* After: Model tags are split by commas and displayed as individual <Tag> components , making them visually distinct and easier to read.
=> Improve model tag rendering by splitting comma-separated string into styled <Tag> components

api/utils/api_utils.py
- Add robust serialize_for_json() function to handle non-serializable objects
- Update server_error_response() to safely serialize exception data
- Update get_json_result() with fallback error handling
- Handles ModelMetaclass, functions, and other problematic objects
- Maintains proper JSON response format instead of server crashes
Fixes #9797
Currently, error responses and certain result objects may include types that are not JSON serializable (e.g., ModelMetaclass, functions). This causes server crashes instead of returning valid JSON responses.
This PR introduces a robust serializer that converts unsupported types into string representations, ensuring the server always returns a valid JSON response.
- [] Bug Fix (non-breaking change which fixes an issue)
=> Fix JSON serialization error for ModelMetaclass objects

rag/utils/infinity_conn.py, rag/utils/s3_conn.py
This PR fixes a critical bug in the knowledge base isolation feature where chat responses were referencing documents from incorrect knowledge bases. The issue was in the `infinity_conn.py` file where the `equivalent_condition_to_str()` function was incorrectly skipping `kb_id` filtering, causing documents from unintended knowledge bases to be included in search results.
=> Fix kb isolation infinity conn

agent/templates/sql_assistant.json
Updated SQL assistant template to wrap variables like 'sys.query' and 'Agent:WickedGoatsDivide@content' in curly braces for better template variable syntax consistency.
=> Fix(agent template): wrap template variables in curly braces

docs/guides/chat/start_chat.md, docs/guides/models/deploy_local_llm.mdx
=> Docs: Removed `/v1` from Ollama base URLs

web/src/locales/zh.ts
The original text for vectorSimilarityWeight in Chinese version was "相似度相似度权重," which is obviously a malformed phrase. It has now been changed to "向量相似度权重". Also, align it with the English version 'Vector similarity weight'.
=> Correct the text of `vectorSimilarityWeight` in zh.ts

rag/llm/__init__.py, web/src/pages/user-setting/setting-model/api-key-modal/index.tsx
issue:
[Bug]: anthropic model have not baseurl selecting,need add #8546
change:
This PR adds support for using Anthropic models through a third-party API by allowing a custom base_url.
It ensures compatibility with both the official Anthropic endpoint and external providers.
=> Feat: add support for Anthropic third-party API

conf/llm_factories.json
fix: Wrong Qwen models's ID
[Bug]: ERROR: litellm.NotFoundError: DashscopeException - The model Qwen/Qwen3-Omni-Flash does not exist or you do not have access to it. change: delete wrong qwen model id
=> fix: Wrong Qwen models's ID

rag/flow/parser/parser.py, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/data-flow/constant.tsx, web/src/pages/data-flow/form/parser-form/image-form-fields.tsx, web/src/pages/data-flow/form/parser-form/index.tsx, web/src/pages/data-flow/utils.ts
BugFix: ERROR: KeyError: 'llm_id'
Feat: The prompt of the describe picture in cv_model supports customization #10320
=> Fix bug of image parser and  prompt of parser supports customization

web/src/components/floating-chat-widget-markdown.less, web/src/components/floating-chat-widget-markdown.tsx, web/src/components/floating-chat-widget.tsx, web/src/components/pdf-drawer/index.tsx
These changes are intended to implement the remaining functionalities of the fullscreen widget.
The question arises: how to display document prieview of PDFs in this floating widget?
- simply enlarge the widget window
- implement zoom in/out
- render outside the iframe?
=> Fix: floating widget match style with original one
