infiniflow/ragflow

web/src/components/editable-cell.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/canvas/index.tsx, web/src/pages/flow/canvas/node/invoke-node.tsx, web/src/pages/flow/constant.tsx, web/src/pages/flow/flow-drawer/index.tsx, web/src/pages/flow/form/invoke-form/dynamic-variables.tsx, web/src/pages/flow/form/invoke-form/index.tsx
=> feat: Add InvokeNode #1908

agent/canvas.py, agent/component/generate.py
=> let 'Generate' take user's input as parameter

web/src/pages/flow/hooks.ts
feat: Allow the component id drop-down box to select the answer operator #3085
=> feat: Allow the component id drop-down box to select the answer operator #3085

api/http_api_reference.md, api/python_api_reference.md
=> Updated HTTP API reference and Python API reference based on test results

api/http_api_reference.md, api/python_api_reference.md
=> Updated parser_config description

api/apps/sdk/chat.py, api/apps/sdk/dataset.py, api/apps/sdk/doc.py, api/apps/sdk/session.py, api/utils/api_utils.py, sdk/python/ragflow/modules/chat.py, sdk/python/ragflow/ragflow.py
=> Fix bugs in API

api/http_api_reference.md, api/python_api_reference.md
=> Added chunk methods

README.md, README_ja.md, README_ko.md, README_zh.md, docs/guides/configure_knowledge_base.md, docs/guides/manage_files.md, docs/quickstart.mdx
=> docs updates for 0.13 release

api/http_api_reference.md, web/src/components/api-service/chat-overview-modal/api-content.tsx
=> Tried to fix a link issue

conf/llm_factories.json
=> add yi-lightning

docs/references/http_api_reference.md
=> Fixed a docusaurus display issue.

api/apps/conversation_app.py, api/apps/sdk/session.py
=> fix: remove useless test code

.github/workflows/tests.yml, api/apps/sdk/chat.py, api/apps/sdk/dataset.py, api/apps/sdk/doc.py, api/utils/api_utils.py, sdk/python/hello_ragflow.py, sdk/python/poetry.lock, sdk/python/pyproject.toml, sdk/python/test/conftest.py, sdk/python/test/t_chat.py, sdk/python/test/t_dataset.py, sdk/python/test/t_document.py, sdk/python/test/t_session.py
=> Add test for CI

docs/references/http_api_reference.md
=> Updated list_documents()

docs/guides/upgrade_ragflow.md, docs/quickstart.mdx, docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Moved the Upgrade Manuel out of FAQ

docs/guides/upgrade_ragflow.md
=> Reworded descriptions for development versions and latest version

docs/guides/start_chat.md
=> Updated screenshots for Starting an AI chat

pyproject.toml, sdk/python/pyproject.toml
=> Changed version to 0.13.0

docs/guides/start_chat.md
=> Updated obsolete screenshot.

README.md, README_ja.md, README_ko.md, README_zh.md, agent/component/base.py, agent/component/generate.py, agent/component/invoke.py, agent/templates/HR_callout_zh.json
=> Update gif for readme and add input param to every components

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/constant.tsx, web/src/pages/flow/form/akshare-form/index.tsx, web/src/pages/flow/form/arxiv-form/index.tsx, web/src/pages/flow/form/baidu-fanyi-form/index.tsx, web/src/pages/flow/form/baidu-form/index.tsx, web/src/pages/flow/form/bing-form/index.tsx, web/src/pages/flow/form/categorize-form/dynamic-categorize.tsx, web/src/pages/flow/form/categorize-form/index.tsx, web/src/pages/flow/form/components/dynamic-input-variable.tsx, web/src/pages/flow/form/components/index.less, web/src/pages/flow/form/crawler-form/index.tsx, web/src/pages/flow/form/deepl-form/index.tsx, web/src/pages/flow/form/duckduckgo-form/index.tsx, web/src/pages/flow/form/exesql-form/index.tsx, web/src/pages/flow/form/github-form/index.tsx, web/src/pages/flow/form/google-form/index.tsx, web/src/pages/flow/form/google-scholar-form/index.tsx, web/src/pages/flow/form/jin10-form/index.tsx, web/src/pages/flow/form/keyword-extract-form/index.tsx, web/src/pages/flow/form/pubmed-form/index.tsx, web/src/pages/flow/form/qweather-form/index.tsx, web/src/pages/flow/form/retrieval-form/index.tsx, web/src/pages/flow/form/tushare-form/index.tsx, web/src/pages/flow/form/wencai-form/index.tsx, web/src/pages/flow/form/wikipedia-form/index.tsx, web/src/pages/flow/form/yahoo-finance-form/index.tsx
feat: Add DynamicInputVariable to RetrievalForm #1739
=> feat: Add DynamicInputVariable to RetrievalForm #1739

docs/references/http_api_reference.md
=> Updated an obsolete response

docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Updated descriptions for knowledge graph

docker/README.md, docs/guides/upgrade_ragflow.md, docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Updated instructions on upgrading to RAGFlow dev

api/settings.py
=> set default LLM to new registered user

web/.umirc.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/form/invoke-form/dynamic-variables.tsx, web/src/pages/flow/form/invoke-form/hooks.ts, web/src/pages/flow/form/invoke-form/index.less, web/src/pages/flow/form/invoke-form/index.tsx
feat: Add tooltip to clean_html item #2908
=> feat: Add tooltip to clean_html item #2908

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/flow-id-modal/index.less, web/src/pages/flow/flow-id-modal/index.tsx, web/src/pages/flow/header/index.tsx
feat: Add agent interface document link to agent page #3189
=> feat: Add agent interface document link to agent page #3189

api/apps/sdk/session.py, api/db/services/canvas_service.py
=> add agent completion API

api/db/services/dialog_service.py
=> raise exception if embedding model not found

agent/canvas.py, api/apps/api_app.py, api/apps/canvas_app.py, api/db/services/dialog_service.py
=> add assistant to canvas chat history

rag/llm/__init__.py, rag/nlp/query.py, rag/nlp/term_weight.py
=> accelerate term weight calculation

api/db/services/document_service.py, api/db/services/knowledgebase_service.py
=> Remove dead code

web/package-lock.json, web/package.json, web/src/components/api-service/chat-overview-modal/api-content.tsx
fix: Fixed the issue of api markdown document display being messy #2346
=> fix: Fixed the issue of api markdown document display being messy #2346

docker/README.md, docs/guides/llm_api_key_setup.md, docs/guides/manage_files.md, docs/quickstart.mdx, docs/references/faq.md, docs/references/supported_models.mdx
=> Editorial updates to Docker README

rag/nlp/rag_tokenizer.py
=> accelerate tokenize

sdk/python/test/t_session.py
=> fix ci issue

web/src/pages/flow/canvas/node/dropdown.tsx, web/src/pages/flow/canvas/node/node-header.tsx, web/src/pages/flow/canvas/node/note-node.tsx, web/src/pages/flow/hooks.ts, web/src/pages/flow/store.ts, web/src/pages/flow/utils.ts
fix: The name of the copy operator is displayed the same as before ##3265
=> fix: The name of the copy operator is displayed the same as before ##3265

api/apps/sdk/chat.py, api/apps/sdk/dataset.py, api/apps/sdk/doc.py, api/utils/api_utils.py, docs/references/http_api_reference.md
Update authorization for team.
#3253 #3233
=> Update authorization for team

docker/README.md
=> Refactored Docker README

graphrag/mind_map_extractor.py
=> fix index of range

agent/component/switch.py
=> fix `switch` bug

web/src/pages/flow/canvas/index.tsx
feat: Support shortcut keys to delete nodes #3283
=> feat: Support shortcut keys to delete nodes #3283

rag/nlp/query.py
=> make language judgement robuster

web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
feat: Modify the name of the answer operator #1739
=> feat: Modify the name of the answer operator #1739

web/src/pages/flow/canvas/index.tsx, web/src/pages/flow/canvas/node/dropdown.tsx, web/src/pages/flow/hooks.ts, web/src/pages/flow/index.tsx, web/src/pages/flow/store.ts
feat: Support shortcut keys to copy nodes #3283
=> feat: Support shortcut keys to copy nodes #3283

docker/.env, docker/README.md, docker/service_conf.yaml
=> Updated .env and Docker README

docker/.env, docker/README.md
=> Added env. MACOS

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/canvas/index.tsx, web/src/pages/flow/canvas/node/relevant-node.tsx, web/src/pages/flow/header/index.less, web/src/pages/flow/header/index.tsx, web/src/pages/flow/hooks.ts, web/src/pages/flow/store.ts, web/src/pages/flow/utils.ts
feat: Automatically save agent page data #3301
=> feat: Automatically save agent page data #3301

rag/benchmark.py, rag/nlp/search.py
=> fix term weight issue

README.md, docker/.env, docker/README.md, docs/configurations.md, docs/quickstart.mdx
=> Added configuration guideline

graphrag/community_reports_extractor.py
=> fix: double brace issue

agent/templates/investment_advisor.json, agent/templates/medical_consultation.json, api/db/services/document_service.py, docs/configurations.md, docs/guides/configure_knowledge_base.md, web/src/locales/en.ts
=> Miscellaneous edits to RAGFlow's UI

README_id.md
Add Readme docs in Indonesia's native language (Bahasa Indonesia) for ragflow
=> feat: documentation updates to support Bahasa Indonesia

README.md, README_ja.md, README_ko.md, README_zh.md
Updates all readme to have a link to redirect to README_id.md for documentation in Bahasa Indonesia
=> feat: updates all readme to have a link to redirect to new locale

conf/llm_factories.json
=> add  new models for zhipu-ai

web/src/components/ui/segmented .tsx, web/src/pages/home/header.tsx, web/tailwind.config.js, web/tailwind.css
feat: Add background colors such as inverse-strong #3221
=> feat: Add background colors such as inverse-strong #3221

agent/component/base.py, agent/component/generate.py, api/apps/document_app.py, rag/nlp/query.py, rag/nlp/synonym.py
=> Refine english synonym

docs/guides/configure_knowledge_base.md, docs/quickstart.mdx, web/src/locales/en.ts
=> Updated RAGFlow's dataset configuration UI

api/apps/canvas_app.py
=> refine the error message

api/apps/document_app.py, rag/app/knowledge_graph.py
=> set DLA active for KG

.github/workflows/tests.yml, README.md, README_id.md, README_ko.md, README_zh.md, api/settings.py, conf/service_conf.yaml, docker/.env, docker/docker-compose-base.yml, docker/docker-compose.yml, docker/service_conf.yaml.template, docs/guides/develop/build_docker_image.mdx, rag/utils/es_conn.py, rag/utils/infinity_conn.py, sdk/python/test/t_chunk.py
Added doc for switching elasticsearch to infinity
=> Added doc for switching elasticsearch to infinity

api/db/init_data.py
=> adapt to lower case cohere

api/ragflow_server.py, api/validation.py
1. Validate the Python version should >= 3.11
2. Download nltk data
=> Add enviroment validation at server startup phase

api/apps/chunk_app.py, api/apps/document_app.py, api/db/services/file_service.py, api/db/services/knowledgebase_service.py, deepdoc/parser/txt_parser.py, rag/utils/es_conn.py
=> fix bug about fetching knowledge graph

api/validation.py, rag/nlp/rag_tokenizer.py
=> resolve halt while starting up

api/apps/system_app.py, api/db/runtime_config.py, api/ragflow_server.py, api/versions.py
=> Update version display on web UI

agent/component/base.py, agent/component/generate.py
=> make variables access robuster

docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Updated descriptions of agent APIs

agent/component/generate.py, rag/benchmark.py, rag/nlp/query.py
=> fix: synonym bug

Dockerfile, Dockerfile.slim, download_deps.py, rag/utils/__init__.py
Move the tiktoken of cl100k_base into docker image
issue: #3338
=> Move clk100k_base tokenizer to docker image

rag/nlp/query.py
=> fix: empty token bug

api/settings.py
=> Remove unused settings

rag/nlp/query.py
=> rm es query escape chars

api/ragflow_server.py, rag/svr/task_executor.py, rag/utils/redis_conn.py
Rework task executor heartbeat, and print in console.
=> Rework task executor heartbeat

api/apps/document_app.py, rag/nlp/query.py, rag/nlp/term_weight.py
=> Enlarge the term weight difference

api/db/services/document_service.py, rag/nlp/rag_tokenizer.py
=> refine the message of queuing a task

Dockerfile, Dockerfile.slim
=> fix tika-server issue

api/apps/system_app.py, api/db/services/task_service.py, rag/svr/task_executor.py, rag/utils/redis_conn.py
handle_task catch all exception
Report heartbeats
=> handle_task catch all exception

rag/svr/task_executor.py
Added current task into task executor's hearbeat
=> Added current task into task executor's hearbeat

docs/guides/agentic_rag/general_purpose_chatbot.md
=> Minor: Fixed a broken link

api/apps/system_app.py
=> Adjusted heartbeat format

api/apps/__init__.py, api/constants.py, api/settings.py, api/utils/api_utils.py
1. Remove unused code.
2. Move some codes from settings to constants
=> Remove unused code

web/src/interfaces/database/user-setting.ts, web/src/pages/user-setting/setting-system/index.tsx, web/src/pages/user-setting/setting-system/task-bar-chat.tsx, web/src/utils/date.ts
feat: Show task_executor heartbeat #3409
=> feat: Show task_executor heartbeat #3409

web/src/pages/user-setting/setting-system/task-bar-chat.tsx
feat: Capture task executor null value exception #3409
=> feat: Capture task executor null value exception #3409

docs/guides/upgrade_ragflow.mdx
=> minor format updates

web/src/layouts/components/header/index.tsx
feat:  "Open link in new tab" doesn't work for profile image #3018
=> feat:  "Open link in new tab" doesn't work for profile image #3018

README_ko.md, README_zh.md
1. Fix document error
2. Move start server out of if __main__ branch.
=> Refactor ragflow server

api/apps/api_app.py, api/apps/chunk_app.py, api/apps/sdk/dify_retrieval.py, api/apps/sdk/doc.py, api/apps/user_app.py, api/db/services/document_service.py, api/utils/log_utils.py, graphrag/graph_extractor.py, rag/benchmark.py, rag/nlp/search.py, rag/utils/es_conn.py, rag/utils/minio_conn.py, rag/utils/redis_conn.py
Fix logs. Use dict.pop instead of del.
=> Fix logs. Use dict.pop instead of del. Close #3473

web/src/layouts/components/header/index.less, web/src/layouts/components/header/index.tsx
feat: Let the top navigation bar open in a tab when you right click on it #3018
=> feat: Let the top navigation bar open in a tab when you right click on it #3018

rag/utils/es_conn.py, rag/utils/minio_conn.py
=> Fix elasticsearch status display

api/apps/llm_app.py, api/apps/sdk/session.py, api/db/db_models.py, rag/llm/embedding_model.py, web/src/interfaces/request/llm.ts, web/src/locales/en.ts, web/src/locales/es.ts, web/src/locales/id.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/user-setting/setting-model/Tencent-modal/index.tsx, web/src/pages/user-setting/setting-model/azure-openai-modal/index.tsx, web/src/pages/user-setting/setting-model/bedrock-modal/index.tsx, web/src/pages/user-setting/setting-model/fish-audio-modal/index.tsx, web/src/pages/user-setting/setting-model/google-modal/index.tsx, web/src/pages/user-setting/setting-model/hunyuan-modal/index.tsx, web/src/pages/user-setting/setting-model/index.tsx, web/src/pages/user-setting/setting-model/ollama-modal/index.tsx, web/src/pages/user-setting/setting-model/spark-modal/index.tsx, web/src/pages/user-setting/setting-model/volcengine-modal/index.tsx, web/src/pages/user-setting/setting-model/yiyan-modal/index.tsx
Add api for sessions and add max_tokens for tenant_llm
=> Add api for sessions and add max_tokens for tenant_llm

web/src/pages/flow/chat/hooks.ts, web/src/pages/flow/hooks.tsx
feat: Stream the greetings of the agent dialogue #3355
=> feat: Stream the greetings of the agent dialogue #3355

Dockerfile, Dockerfile.slim, download_deps.py, poetry.lock, pyproject.toml, rag/utils/doc_store_conn.py, sdk/python/poetry.lock, sdk/python/pyproject.toml
Changed requirement to python 3.10.
Changed image base to Ubuntu 22.04 since it contains python 3.10.
=> Changed requirement to python 3.10

agent/canvas.py, agent/component/base.py, agent/component/generate.py, agent/component/switch.py, api/apps/canvas_app.py, api/apps/document_app.py, api/db/services/dialog_service.py
=> add input variables to begin component

rag/nlp/synonym.py
=> fix synonym bug

rag/nlp/term_weight.py
=> smooth term weight

api/apps/sdk/session.py
=> fix: keyerror issue

deepdoc/parser/pdf_parser.py, rag/nlp/synonym.py, rag/utils/es_conn.py
Added kb_id filter to knn. Fix #3458
=> Added kb_id filter to knn. Fix #3458

conf/llm_factories.json, rag/llm/chat_model.py
=> Make spark model robuster to model name

api/apps/tenant_app.py
=> Fix: potential risk

agent/component/base.py
=> Fix set_output type hint

web/src/pages/flow/constant.tsx, web/src/pages/flow/form/generate-form/dynamic-parameters.tsx, web/src/pages/flow/run-drawer/index.tsx
Feat: merge the begin operator's url and file into one field #3355
=> Feat: merge the begin operator's url and file into one field #3355

api/ragflow_server.py, rag/svr/task_executor.py
Warning instead of exception on type mismatch.
=> Warning instead of exception on type mismatch

api/apps/tenant_app.py
=> Fix: authorization issue

agent/canvas.py, agent/component/base.py, agent/component/generate.py, agent/templates/interpreter.json, api/apps/canvas_app.py, api/apps/tenant_app.py
=> New: a new interpretor based on Andrew Ng theory.

api/settings.py
=> Ensure LIGHTEN work

graphrag/search.py
=> Fix: search issue for graphrag

rag/utils/es_conn.py
=> Cut down the attempt times of ES

sdk/python/ragflow_sdk/modules/agent.py
=> Fix a bug in agent api

docker/.env, docker/README.md, docs/configurations.md, docs/quickstart.mdx, docs/references/faq.md, docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Updated obsolete faqs

agent/component/base.py, agent/component/template.py, api/apps/canvas_app.py, api/apps/user_app.py
=> Fixs for translation agent

web/.npmrc, web/package-lock.json, web/package.json
=> Fix: Limit node version #3547

docker/.env, docker/README.md, docs/configurations.md, docs/quickstart.mdx, docs/references/faq.md, docs/references/http_api_reference.md, docs/references/python_api_reference.md
This reverts commit 13ff4638452e5055553f1458300a2866e3fdff65.
=> Revert "Updated obsolete faqs (#3554)"

.github/ISSUE_TEMPLATE/bug_report.yml
Add RAGFlow image version into bug report template
=> Added RAGFlow image version into bug report template

rag/svr/task_executor.py, rag/utils/es_conn.py
Added TRACE_MALLOC_DELTA and TRACE_MALLOC_FULL to debug task_executor.py heap. Relates to #3518
=> Added TRACE_MALLOC_DELTA and TRACE_MALLOC_FULL

api/apps/chunk_app.py, api/apps/user_app.py, rag/nlp/search.py, rag/utils/es_conn.py
=> Fix chunk enable/disable issue

api/apps/sdk/session.py
=> Fix agent api invokation issue

agent/templates/seo_blog.json
=> Add an agent template: SEO bloger

web/src/pages/user-setting/setting-team/user-table.tsx
Feat: Capitalize the first letter of the team's role #2834
=> Feat: Capitalize the first letter of the team's role #2834

README.md, README_id.md, README_ja.md, README_ko.md, README_zh.md, docs/guides/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx
=> Restore version info to v0.13.0

rag/app/one.py
=> Let 'One' applicable for tables in docx

README.md, README_id.md, README_ja.md, README_ko.md, README_zh.md, docs/guides/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, rag/llm/embedding_model.py
=> Update docs for v0.14.0

web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
rewrite some confusing statement to improve user experience
=> doc:rewrite some confusing statement 

.github/workflows/tests.yml, Dockerfile, Dockerfile.slim, rag/utils/infinity_conn.py
Handle infinity empty response. Close #3623
Show version in docker build log
=> Handle infinity empty response

README_id.md, conf/service_conf.yaml
=> Fix missing info in README and config error

api/apps/sdk/session.py
=> Fix a bug in completions

web/src/components/ui/badge.tsx, web/src/components/ui/button.tsx, web/src/pages/home/datasets.tsx, web/src/pages/profile-setting/plan/index.tsx, web/src/pages/profile-setting/plan/pricing-card.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Add PricingCard component #3221
=> Feat: Add PricingCard component #3221

api/apps/kb_app.py, api/apps/sdk/dataset.py
Add support for folder deletion.
=> Add support for folder deletion

docs/guides/upgrade_ragflow.mdx, docs/references/faq.md
=> Updated FAQ and Upgrade guide

docker/README.md, docs/configurations.md, web/src/locales/en.ts
=> Updated UI

agent/component/crawler.py
=> For security.

conf/mapping.json
=> Fixed es mapping

api/apps/kb_app.py, api/apps/sdk/dataset.py, rag/nlp/__init__.py
Fix the bug causing garbled text #3613
=> Fix the bug causing garbled text

web/package-lock.json, web/package.json, web/src/pages/profile-setting/components.tsx, web/src/pages/profile-setting/prompt/index.tsx, web/src/routes.ts, web/tailwind.config.js
Feat: add PromptManagement page #3221
=> Feat: add PromptManagement page #3221

rag/utils/es_conn.py
=> Fix es get NotFoundError

api/apps/kb_app.py, sdk/python/test/conftest.py, sdk/python/test/test_frontend_api/common.py, sdk/python/test/test_frontend_api/test_dataset.py
1. Read KB list path parameter, page_number and page_size, which type isn't int
2. Add cases on create / list / delete datasets.
=> Fix KB list bugs and add web api test

rag/llm/__init__.py, rag/llm/embedding_model.py
Fix a bug in VolcEngine  #3553
=> Fix a bug in VolcEngine

web/src/pages/datasets/index.tsx, web/src/routes.ts
=> Feat: Add Datasets page #3221

poetry.lock, pyproject.toml
=> Use polars-lts-cpu on arm64

rag/utils/es_conn.py
Fix enable/disable bug   #3628
=> Fix enable/disable bug

api/utils/file_utils.py, deepdoc/parser/resume/entities/schools.py, deepdoc/vision/t_ocr.py, deepdoc/vision/t_recognizer.py, rag/benchmark.py
Always open text file for write with UTF-8. Close #932
=> Always open text file for write with UTF-8

api/apps/kb_app.py, api/db/services/knowledgebase_service.py, web/.umirc.ts, web/package-lock.json, web/package.json, web/src/hooks/knowledge-hooks.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/knowledge/index.less, web/src/pages/knowledge/index.tsx
Feat: Scrolling knowledge base list #3695
=> Feat: Scrolling knowledge base list #3695

api/apps/chunk_app.py, api/apps/kb_app.py, api/apps/user_app.py, deepdoc/parser/docx_parser.py, deepdoc/parser/pdf_parser.py, deepdoc/parser/resume/entities/corporations.py, deepdoc/parser/resume/entities/schools.py, deepdoc/parser/resume/step_one.py, deepdoc/parser/resume/step_two.py, deepdoc/vision/table_structure_recognizer.py, rag/app/paper.py, rag/app/picture.py, rag/nlp/__init__.py, rag/nlp/query.py, rag/nlp/rag_tokenizer.py, rag/nlp/search.py, rag/nlp/term_weight.py, rag/utils/es_conn.py, rag/utils/infinity_conn.py
Edit chunk shall update instead of insert it. Close #3679
=> Edit chunk shall update instead of insert it

rag/app/picture.py
**Passing cv_mdl.describe() is not an RGB converted image**
=> Fix RGBA error

rag/nlp/search.py
Detect shape error of embedding. Close #2997
=> Detect shape error of embedding

api/apps/kb_app.py, api/db/services/knowledgebase_service.py, sdk/python/test/test_frontend_api/test_dataset.py, web/.umirc.ts, web/package-lock.json, web/package.json, web/src/hooks/knowledge-hooks.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/knowledge/index.less, web/src/pages/knowledge/index.tsx
Feat: Scrolling knowledge base list and set the number of entries per page to 30 #3695
=> Feat: Scrolling knowledge base list and set the number of entries per page to 30 #3695 

docker/docker-compose-base.yml, docker/infinity_conf.toml
Added an infinity configuration file to easily customize the settings of Infinity
=> Added an infinity configuration file to easily customize the settings of Infinity

api/utils/file_utils.py
Ensure thumbnail be smaller than 64K. Close #1443
=> Ensure thumbnail be smaller than 64K

api/apps/sdk/session.py
=> Fix image_id absence issue

docker/docker-compose-gpu.yml
=> Fix GPU docker compose file

rag/raptor.py, rag/svr/task_executor.py
=> Fix raptor issue

web/src/locales/zh.ts
Change Traditional Chinese to Simplified Chinese
=> Change Traditional Chinese to Simplified Chinese

rag/llm/chat_model.py
Pass top_p to ollama. Close #1769
=> Pass top_p to ollama

docker/.env, docker/README.md, docs/release_notes.md
=> Added release notes v0.11.0

web/src/components/ui/switch.tsx, web/src/layouts/next.tsx, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/index.tsx, web/src/pages/dataset/sidebar/index.tsx, web/tailwind.config.js, web/tailwind.css
=> Feat: Add DatasetTable #3221

rag/nlp/search.py
=> Weight up title and keywords for chunks in terms of retrieval

api/db/services/llm_service.py
Fixed increase_usage for builtin models. Close #1803
=> Fixed increase_usage for builtin models

web/src/utils/file-util.ts
Feat: Translate comments of file-util.ts to English #3749
=> Feat: Translate comments of file-util.ts to English #3749

web/src/components/delimiter.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
Feat: Add tooltip to delimiter filed #1909
=> Feat: Add tooltip to delimiter filed #1909

api/apps/chunk_app.py, rag/utils/infinity_conn.py
1. Store error type in Infinity
2. position list value read from Infinity isn't correct.
Fix issue: #3729
=> Fix chunk creation using Infinity

api/ragflow_server.py, rag/app/book.py, rag/app/laws.py, rag/app/manual.py, rag/app/naive.py, rag/app/one.py, rag/app/paper.py, rag/app/presentation.py, rag/app/qa.py, rag/settings.py, rag/svr/task_executor.py
=> Update progress info and start welcome info

README_zh.md
=> Update QR code of wechat

rag/svr/task_executor.py
Refine the file parsing progress info
=> Update file parsing progress info

rag/app/naive.py, rag/svr/task_executor.py
=> Refactor parse progress

conf/llm_factories.json, rag/llm/embedding_model.py, rag/llm/rerank_model.py
add new models in jinna connector, to allow use models that support multilingual models
=> add jina new models in jina connector

api/apps/sdk/session.py, deepdoc/parser/pdf_parser.py
=> Fix out of boundary.

api/apps/sdk/chat.py
Fix the bug that prevented modifying `dataset_ids`.
#3772
=> Fix the bug that prevented modifying `dataset_ids`

docker/docker-compose-CN-oc9.yml, docker/docker-compose-gpu-CN-oc9.yml
=> Fix service_conf for oc9 docker compose file.

rag/llm/embedding_model.py
Detect invalid response from api.siliconflow.cn. Close #2643
=> Detect invalid response from api.siliconflow.cn

docker/README.md, docs/references/faq.md
=> Update document: how upload file large than 128MB

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/user-setting/setting-team/hooks.ts, web/src/pages/user-setting/setting-team/tenant-table.tsx
Feat: Quit from jointed team #3759
=> Feat: Quit from jointed team #3759

api/apps/kb_app.py, api/utils/api_utils.py, sdk/python/test/test_frontend_api/test_dataset.py
1. Test not allowed fields of dataset
=> More dataset test cases

docs/guides/deploy_local_llm.mdx
Improved ollama doc. Close #3723
=> Improved ollama doc

web/src/components/editable-cell.tsx, web/src/components/page-rank.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx
Feat: Supports page rank score for different knowledge bases. #3794
=> Feat: Supports page rank score for different knowledge bases. #3794

web/package-lock.json, web/package.json, web/src/components/ui/slider.tsx, web/src/components/ui/textarea.tsx, web/src/pages/dataset/testing/index.tsx, web/src/pages/dataset/testing/testing-form.tsx, web/tailwind.css
=> Feat: Add TestingForm #3221

rag/llm/embedding_model.py
=> Fix voyage embedding.

web/src/components/page-rank.tsx, web/src/pages/add-knowledge/components/knowledge-setting/hooks.ts
Feat: Store the pagerank field at the outermost #3794
=> Feat: Store the pagerank field at the outermost #3794

api/db/services/dialog_service.py, api/db/services/llm_service.py
=> Fix @ in model name issue.

api/apps/chunk_app.py, api/apps/kb_app.py, api/db/db_models.py, api/db/services/knowledgebase_service.py, api/db/services/llm_service.py, api/db/services/task_service.py, conf/infinity_mapping.json, rag/nlp/search.py, rag/svr/task_executor.py, rag/utils/es_conn.py, sdk/python/ragflow_sdk/modules/dataset.py
=> Add pagerank to KB.

agent/canvas.py, conf/llm_factories.json
=> Add more mistral models.

api/db/services/llm_service.py, rag/benchmark.py, rag/llm/embedding_model.py
Refactor embedding batch_size. Close #3657
=> Refactor embedding batch_size

web/src/components/ui/button.tsx, web/src/components/ui/container.tsx, web/src/components/ui/segmented .tsx, web/src/layouts/next-header.tsx, web/src/layouts/next.tsx, web/src/pages/dataset/settings/index.tsx, web/src/pages/home/applications.tsx, web/src/pages/home/datasets.tsx, web/src/pages/home/index.tsx, web/src/routes.ts, web/tailwind.config.js, web/tailwind.css
Feat: Modify the style of the home page in bright mode #3221
=> Feat: Modify the style of the home page in bright mode #3221

deepdoc/parser/json_parser.py, rag/app/naive.py
=> Fix parsing JSON file error

api/apps/canvas_app.py, api/apps/sdk/agent.py, api/apps/sdk/chat.py, api/apps/sdk/session.py, api/db/services/api_service.py, api/db/services/canvas_service.py
Add api for list agents and agent seesions
=> Add api for list agents and agent seesions

rag/llm/chat_model.py, rag/nlp/__init__.py
=> Change default error message to English

api/apps/file_app.py, rag/llm/rerank_model.py
=> Fix preview issue in file manager.

docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/agent.py, sdk/python/ragflow_sdk/modules/session.py, sdk/python/ragflow_sdk/ragflow.py, sdk/python/test/test_sdk_api/t_agent.py, sdk/python/test/test_sdk_api/t_dataset.py, sdk/python/test/test_sdk_api/t_session.py
Add sdk for list agents and sessions
=> Add sdk for list agents and sessions

conf/mapping.json, rag/nlp/query.py
=> Refine synonym query.

web/src/components/knowledge-base-item.tsx, web/src/components/ui/skeleton.tsx, web/src/hooks/knowledge-hooks.ts, web/src/hooks/logic-hooks/navigate-hooks.ts, web/src/layouts/next-header.tsx, web/src/pages/agent/index.tsx, web/src/pages/file-manager/connect-to-knowledge-modal/index.tsx, web/src/pages/flow/canvas/node/retrieval-node.tsx, web/src/pages/home/datasets.tsx, web/src/pages/next-chat/index.tsx, web/src/pages/next-search/index.tsx, web/src/pages/search/index.tsx, web/src/pages/search/sidebar.tsx, web/src/routes.ts
Feat: Bind the route to the navigation bar in the head #3221
=> Feat: Bind the route to the navigation bar in the head #3221

api/apps/sdk/session.py, rag/llm/rerank_model.py
=> Fix open AI compatible rerank issue.

api/apps/chunk_app.py
=> Fix chunk position issue.

web/src/components/edit-tag/index.tsx
Feat: Adjust the input box width of EditTag to 100% #3873
=> Feat: Adjust the input box width of EditTag to 100% #3873

api/apps/chunk_app.py, api/apps/sdk/doc.py, conf/infinity_mapping.json, rag/nlp/query.py, rag/nlp/search.py, rag/svr/task_executor.py, sdk/python/ragflow_sdk/modules/chunk.py, sdk/python/ragflow_sdk/modules/document.py
=> Feat: Add question parameter to edit chunk modal

api/apps/chunk_app.py
=> Fix chunk available issue

web/src/pages/flow/canvas/index.tsx
Reverts infiniflow/ragflow#3878
=> Revert "Feat: Add tooltip to question item of ChunkCreatingModal #3873"

web/src/components/edit-tag/index.less, web/src/components/edit-tag/index.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx, web/src/utils/file-util.ts
Feat: Add tooltip to question item of ChunkCreatingModal  #3873
=> Feat: Add tooltip to question item of ChunkCreatingModal  #3873

poetry.lock, pyproject.toml
=> Add a dependency blincker.

api/apps/llm_app.py
=> Remove token check while adding model.

agent/canvas.py, api/db/services/llm_service.py
Fix: Fixed the issue that the agent list page failed to load #3827
=> Fix: Fixed the issue that the agent list page failed to load #3827

agent/component/base.py
=> Remove vector stored in component output.

.github/workflows/tests.yml, Dockerfile, README.md, README_id.md, README_ja.md, README_ko.md, README_zh.md, docs/guides/develop/launch_ragflow_from_source.md
=> Introduced NEED_MIRROR

docker/docker-compose-CN-oc9.yml, docker/docker-compose-gpu-CN-oc9.yml
Update OC9 docker compose files
issue: #3901
=> Update oc9 docker compose file

.github/workflows/tests.yml, README.md, README_id.md, README_ja.md, README_ko.md, README_zh.md, docker/.env, docker/README.md, docs/configurations.md, docs/guides/develop/build_docker_image.mdx, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, docs/references/faq.md, docs/release_notes.md, helm/values.yaml
=> Obsoleted dev and dev-slim

rag/svr/task_executor.py
=> Fix field missing issue.

Dockerfile, Dockerfile.deps
=> Fixed tmp in Dockerfile

rag/llm/cv_model.py
=> Fix transformers dependencies for slim.

api/apps/document_app.py, api/db/services/canvas_service.py, api/db/services/conversation_service.py
=> Fix error message for image access.

api/apps/sdk/session.py, api/db/services/canvas_service.py, api/db/services/conversation_service.py
=> Fix session API issues.

api/db/services/conversation_service.py
api http  return error when content is not found
=> api http  return error

.github/workflows/tests.yml, api/ragflow_server.py, api/utils/log_utils.py, rag/nlp/__init__.py, rag/svr/task_executor.py
=> Fixed log not displaying

web/src/components/edit-tag/index.tsx
Allows quick entry of entities separated by commas
=> Allows quick entry of entities separated by commas

rag/app/resume.py, rag/nlp/query.py
=> Fix syn error.

api/settings.py
DOC_ENGINE="INFINITY" or "Infinity" or "Elasticsearch" also works
=> Case insensitive when set doc engine

README.md, README_id.md, README_ja.md, README_ko.md, README_zh.md
=> Fixed README

web/src/components/message-item/index.tsx, web/src/pages/chat/utils.ts, web/src/utils/chat.ts
Feat: Exclude reference from the data returned by the conversation/get interface  #3909
=> Feat: Exclude reference from the data returned by the conversation/get interface  #3909

rag/utils/infinity_conn.py
Fixed retrieval TypeError: unhashable type: 'list'
=> Fixed retrieval TypeError: unhashable type: 'list'

agent/__init__.py, api/__init__.py, deepdoc/__init__.py, intergrations/chatgpt-on-wechat/plugins/__init__.py, rag/__init__.py, sdk/python/ragflow_sdk/__init__.py
=> Add back beartype

docs/guides/configure_knowledge_base.md, docs/release_notes.md, web/src/locales/en.ts
=> Added release notes

agent/canvas.py, agent/component/exesql.py
=> Fix exec sql exception issue.

docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Update api documents

web/src/pages/chat/markdown-content/index.tsx, web/src/pages/chat/utils.ts
Fix:  Fixed the issue where two consecutive indexes were displayed incorrectly #3839
=> Fix:  Fixed the issue where two consecutive indexes were displayed incorrectly #3839

agent/canvas.py, agent/component/base.py, agent/component/begin.py, agent/component/generate.py, api/apps/canvas_app.py, api/apps/conversation_app.py, api/apps/document_app.py, rag/svr/task_executor.py
=> Support debug components.

api/apps/chunk_app.py, api/apps/sdk/doc.py, api/db/services/document_service.py, api/db/services/task_service.py, rag/svr/task_executor.py
Replaced md5 with xxhash64 for chunk id
=> Replaced md5 with xxhash64 for chunk id

deepdoc/parser/json_parser.py
=> Fix json file parse

rag/nlp/__init__.py
Fix hierarchical_merge function. From idx vs. actual value to actual value vs. actual value.
Related issue #4003
=> Fix bug in hierarchical_merge function

web/src/hooks/document-hooks.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-file/hooks.ts, web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx
Feat: Reparse a file shall reuse existing chunks if possible #3793
=> Feat: Reparse a file shall reuse existing chunks if possible #3793

rag/svr/task_executor.py
Set task progress on exception
=> Set task progress on exception

rag/svr/task_executor.py
Fix xinfo_groups returns unexpected result. Close #3545
=> Fix xinfo_groups returns unexpected result

api/apps/llm_app.py
=> Fix connection error for adding visual llm.

docs/quickstart.mdx
=> Fixed a display issue

README_zh.md, docs/configurations.md
=> Updated configurations

agent/component/exesql.py
clone https://github.com/infiniflow/ragflow/pull/4023 
improve the information extraction, most llm return results in markdown format  ````sql ___ query `____ ```
=> extraction sqlquery

api/apps/document_app.py, api/db/services/task_service.py
=> Fix chunk number error after re-parsing.

web/src/hooks/chunk-hooks.ts, web/src/pages/add-knowledge/components/knowledge-chunk/components/document-preview/preview.tsx
Fix: Every time you switch the page number of a chunk, the PDF document will be reloaded. #4046
=> Fix: Every time you switch the page number of a chunk, the PDF document will be reloaded. #4046

api/apps/document_app.py, api/db/services/task_service.py, graphrag/claim_extractor.py, graphrag/community_reports_extractor.py, graphrag/description_summary.py, graphrag/entity_resolution.py, graphrag/extractor.py, graphrag/graph_extractor.py, graphrag/mind_map_extractor.py, graphrag/utils.py, rag/raptor.py, rag/svr/task_executor.py
=> Cache the result from llm for graphrag and raptor

web/src/pages/chat/share/large.tsx
Fix: Hide the upload button in the external chat box  #2242
=> Fix: Hide the upload button in the external chat box  #2242

api/apps/system_app.py
=> Compatible with former API keys.

web/src/components/api-service/embed-modal/index.less, web/src/components/api-service/embed-modal/index.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/chat/index.tsx, web/src/pages/flow/header/index.tsx
Feat: Modify the text of the embedded website button #3909
=> Feat: Modify the text of the embedded website button #3909

web/src/components/api-service/embed-modal/index.tsx, web/src/pages/home/datasets.tsx
Feat: Modify the link address of the agent id #3909
=> Feat: Modify the link address of the agent id #3909

api/db/services/document_service.py, api/db/services/task_service.py, graphrag/utils.py
=> Fix raptor resuable issue.

api/apps/kb_app.py, rag/utils/infinity_conn.py
Added pagerank support to infinity
=> Added pagerank support to infinity

api/apps/sdk/chat.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, rag/app/naive.py
Fix rerank_model bug in chat and markdown bug
#4000
#3992
=> Fix rerank_model bug in chat and markdown bug

rag/nlp/search.py
=> Fix position lost issue.

Dockerfile
For the new feature Add mssql support in the Dockerfile, I suggest including support for msodbcsql18 for ARM64.
Based on current testing results (on macOS ARM64 environment), msodbcsql18 needs to be installed.
I hope future Dockerfiles can incorporate a conditional check for this. Specifically:
When $ARCH=arm64 (macOS ARM64 environment), install msodbcsql18.
In other cases (general x86_64 environment), install msodbcsql17.
=> Add Architecture-Specific Logic for msodbcsql in Dockerfile #4036

web/src/pages/dataset/setting/advanced-setting-form.tsx, web/src/pages/dataset/setting/basic-setting-form.tsx, web/src/pages/dataset/setting/index.tsx, web/src/pages/dataset/settings/index.tsx, web/src/pages/dataset/sidebar/hooks.tsx, web/src/pages/dataset/sidebar/index.tsx, web/src/pages/dataset/testing/index.tsx, web/src/routes.ts
Feat: Add AdvancedSettingForm #3221
=> Feat: Add AdvancedSettingForm #3221

web/src/pages/flow/flow-drawer/index.tsx
Fix: The cursor is lost after entering a character in the operator form #4072
=> Fix: The cursor is lost after entering a character in the operator form #4072

web/src/locales/zh.ts
fix chinese warning to update model
=> update chinese model warning message

web/src/components/message-item/group-button.tsx, web/src/components/message-item/index.tsx, web/src/pages/chat/share/large.tsx
Fix:  Fixed the issue with external chat box reporting errors #3909
=> Fix:  Fixed the issue with external chat box reporting errors #3909

poetry.lock, pyproject.toml, sdk/python/ragflow_sdk/modules/session.py
Fix conversation bug in agent session
=> Fix conversation bug in agent session

docs/guides/develop/build_docker_image.mdx
=> Fix arm doc

api/apps/tenant_app.py
=> Fix abnormal user invitaion message.

rag/nlp/rag_tokenizer.py
1. Fix initial build and load trie
2. Update comment
=> Refactor trie load and construct

web/src/pages/user-setting/setting-team/add-user-modal.tsx
Fix: Fixed the issue where the required information in the input box was incorrect when inviting users #2834
=> Fix: Fixed the issue where the required information in the input box was incorrect when inviting users #2834

Dockerfile, download_deps.py
=> Add huqie trie to docker image.

api/apps/tenant_app.py
Refactor inviting team member message.
=> Update team invite message

api/db/services/document_service.py, api/db/services/task_service.py
=> Fix raptor

web/src/locales/vi.ts
=> add typo locale

rag/utils/infinity_conn.py
Fixed infinity exception SCORE() / SCORE_FACTORS() requires Fusion or MATCH TEXT or MATCH TENSOR. Close #4109
=> Fixed infinity exception SCORE() / SCORE_FACTORS() requires Fusion or MATCH TEXT or MATCH TENSOR

docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Separated list_agents() from session management

api/apps/sdk/session.py, sdk/python/ragflow_sdk/modules/session.py
Add parameters for ask_chat and fix bugs in list_sessions
#4105
=> Add parameters for ask_chat and fix bugs in list_sessions

rag/llm/embedding_model.py
=> Make fast embed and default embed mutually exclusive.

conf/llm_factories.json
=> add gemini 2.0

README.md, README_id.md, README_ja.md, README_ko.md, README_zh.md, docs/quickstart.mdx, docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Corrections.

api/utils/__init__.py
=> Mask password in log

graphrag/utils.py
=> Fix redis get error.

docker/.env, rag/utils/infinity_conn.py
=> Fix position_int on infinity

api/apps/sdk/doc.py, rag/utils/infinity_conn.py
Validate returned chunk at list_chunks and add_chunk
=> Validate returned chunk at list_chunks and add_chunk

api/db/services/file_service.py, rag/llm/rerank_model.py
=> Fix Voyage re-rank model. Limit file name length.

api/db/services/dialog_service.py
The refactor in 0.15 contains a small bug that eliminate the classification
=> Fix bug over chunks classification by document in the promp

api/db/services/dialog_service.py, conf/llm_factories.json, deepdoc/vision/recognizer.py, rag/utils/s3_conn.py
=> Add Llama3.3

rag/nlp/search.py, rag/utils/es_conn.py
=> Fetch chunk by batches.

graphrag/leiden.py
=> Fix duplicated communitiy

rag/nlp/search.py
=> Fix raptor bug.

rag/utils/infinity_conn.py
=> Fix score() issue

api/db/services/task_service.py, rag/svr/task_executor.py
Ignore the millisecond and microsecond value.
=> Update progress time info

deepdoc/parser/ppt_parser.py
=> Catch the exception while parsing pptx.

api/apps/sdk/session.py
=> Remove session owner check.

agent/component/base.py
=> Fix interface as input variable for component.

api/apps/sdk/session.py
=> Fix misspell.

pyproject.toml, sdk/python/pyproject.toml
=> Update pyproject.toml to 0.15.1

api/apps/chunk_app.py
=> Fix: Q&A chunk modification

agent/component/base.py
=> Fix component input error.

rag/nlp/rag_tokenizer.py
=> Removing invisible chars before tokenization.

README.md, README_id.md, README_ja.md, README_ko.md, README_zh.md, docker/.env, docker/README.md, docs/configurations.md, docs/guides/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, docs/references/faq.md, helm/values.yaml
=> Update version info

agent/component/invoke.py
to fixed issue https://github.com/infiniflow/ragflow/issues/4236
=> Fixed invoke component parameters #4236

api/apps/llm_app.py, api/utils/api_utils.py
=> Replace image2text model check with internal image.

agent/component/__init__.py, rag/nlp/query.py
=> Clean query.

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/canvas/edge/index.tsx, web/src/pages/flow/canvas/node/iteration-node.tsx, web/src/pages/flow/form/begin-form/paramater-modal.tsx, web/src/pages/flow/form/components/dynamic-input-variable.tsx
Feat: Limit the iteration start node to only be the source node #4242
=> Feat: Limit the iteration start node to only be the source node #4242

docs/references/python_api_reference.md
=> Fix Python SDK example error.

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/flow/form/generate-form/index.tsx
Feat: Translate the system prompt of the generate operator #3993
=>  Feat: Translate the system prompt of the generate operator #3993

api/apps/sdk/session.py
=> Fix agent session list by user_id.

docs/references/python_api_reference.md, sdk/python/ragflow_sdk/ragflow.py
Fix the bug in create_dataset function #4136
=> Fix the bug in create_dataset function

Dockerfile, README.md, README_id.md, README_ja.md, README_ko.md, README_zh.md, docs/guides/develop/launch_ragflow_from_source.md, web/package-lock.json, web/package.json
Fix: After executing npm i --force locally, the login page cannot be opened #4290
=> Fix: After executing npm i --force locally, the login page cannot be opened #4290

api/apps/chunk_app.py, api/apps/sdk/doc.py, docs/references/http_api_reference.md
=> Fix bugs in chunk api

api/apps/canvas_app.py
Update error message for agent name conflict
=> Update error message for agent name conflict

rag/raptor.py, rag/svr/task_executor.py
=> Show the errors out.

web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/force-graph.tsx, web/src/pages/add-knowledge/components/knowledge-chunk/components/knowledge-graph/util.ts
Fix: Fixed the issue that the graph could not display the grouping #4180
=> Fix: Fixed the issue that the graph could not display the grouping #4180

docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/dataset.py, sdk/python/test/test_sdk_api/t_chat.py, sdk/python/test/test_sdk_api/t_chunk.py, sdk/python/test/test_sdk_api/t_document.py, sdk/python/test/test_sdk_api/t_session.py
Update displayed_name to display_name
=> Update displayed_name to display_name

api/db/services/canvas_service.py
=> Fix parameter name error.

agent/component/exesql.py
Update exesql component for agent
=> Update exesql component for agent

agent/templates/customer_service.json, rag/app/knowledge_graph.py, rag/app/manual.py, rag/llm/chat_model.py, rag/llm/tts_model.py, rag/svr/cache_file_svr.py
=> Synchronize with enterprise version

api/apps/sdk/session.py
Fix agent_completion bug  #4320
=> Fix agent_completion bug

deepdoc/vision/t_recognizer.py
=> Fix t_recognizer.py after model updating.

web/src/pages/flow/constant.tsx, web/src/pages/flow/form/exesql-form/index.tsx, web/src/pages/flow/hooks.tsx
Feat: Add model id to ExeSql operator form. #1739
=> Feat: Add model id to ExeSql operator form. #1739

agent/component/crawler.py, api/utils/web_utils.py
Fix potential SSRF attack vulnerability
=> Fix potential SSRF attack vulnerability

web/package-lock.json, web/package.json, web/src/components/confirm-delete-dialog.tsx, web/src/components/ui/alert-dialog.tsx, web/src/components/ui/slider.tsx, web/src/pages/datasets/index.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Add ConfirmDeleteDialog #3221
=> Feat: Add FileUploadDialog #3221 (#4327)

api/db/services/document_service.py
=> Fix total number error.

conf/llm_factories.json
=> Refactor model list.

agent/templates/research_report.json
=> Adds a research report generator.

deepdoc/vision/t_recognizer.py
=> Fix param error.

rag/llm/embedding_model.py
=> Fix gemini embedding error.

docs/guides/start_chat.md, docs/references/agent_component_reference/_category_.json, docs/references/agent_component_reference/begin.mdx, docs/references/faq.md, docs/references/http_api_reference.md, docs/references/python_api_reference.md, docs/references/supported_models.mdx
=> Updated outdated descriptions and added multi-turn optimization

agent/templates/DB Assistant.json
=> Refine DB assistant template.

web/src/components/ui/loading-button.tsx, web/src/hooks/knowledge-hooks.ts, web/src/pages/add-knowledge/components/knowledge-setting/hooks.ts, web/src/pages/add-knowledge/components/knowledge-setting/tag-table/index.tsx, web/src/pages/add-knowledge/components/knowledge-setting/tag-table/rename-dialog/index.tsx
=> Feat: Add LoadingButton #4368

deepdoc/vision/t_recognizer.py
=> Fix t_recognizer issue.

agent/component/generate.py
=> Refine variable display name.

agent/component/invoke.py
fix bug, agent invoke can not get params from begin
=> fix bug, agent invoke can not get params from begin

rag/nlp/search.py
=> Fix page size error.

deepdoc/vision/layout_recognizer.py, deepdoc/vision/t_recognizer.py
[Bug]: layout recognizer failed for wrong boxes class type #4230 (https://github.com/infiniflow/ragflow/issues/4230)
- [✅ ] Bug Fix (non-breaking change which fixes an issue)
=> fix:t_recognizer TypeError: 'super' object is not callable

api/apps/sdk/doc.py
=> Fix API retrieval error.

helm/values.yaml
=> Fix typo in helm charts

agent/component/rewrite.py
=> Remove redundant param of rewrite component.

agent/component/exesql.py
Fixed code error when mssql returns multiple columns
=> Fixed code error when mssql returns multiple columns

api/apps/sdk/session.py
=> Let the agent talk while there's pre-set param.

docs/guides/agent/text2sql_agent.md, docs/references/agent_component_reference/categorize.mdx, docs/references/agent_component_reference/generate.mdx, docs/references/agent_component_reference/retrieval.mdx
=> Added a description of the Categorize agent component

web/src/hooks/knowledge-hooks.ts, web/src/interfaces/database/knowledge.ts, web/src/pages/add-knowledge/components/knowledge-setting/tag-word-cloud.tsx, web/src/pages/add-knowledge/components/knowledge-testing/testing-control/index.tsx, web/src/pages/add-knowledge/components/knowledge-testing/testing-control/label-word-cloud.tsx
Feat: Display tag word cloud on recall test page #4368
=> Feat: Display tag word cloud on recall test page #4368

web/src/locales/vi.ts
=> update res vi

api/apps/chunk_app.py, api/apps/conversation_app.py, api/apps/document_app.py, api/db/db_models.py, api/db/services/dialog_service.py
=> Add doc meta data.

rag/app/tag.py
=> Fix csv for TAG.

api/db/services/dialog_service.py
=> Add meta data while chatting.

web/src/hooks/document-hooks.ts, web/src/interfaces/database/document.ts, web/src/interfaces/request/document.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-file/hooks.ts, web/src/pages/add-knowledge/components/knowledge-file/index.tsx, web/src/pages/add-knowledge/components/knowledge-file/parsing-action-cell/index.tsx, web/src/pages/add-knowledge/components/knowledge-file/set-meta-modal/index.tsx, web/src/services/knowledge-service.ts, web/src/utils/api.ts
Feat: Metadata in documents for improve the prompt #3690
=> Feat: Metadata in documents for improve the prompt #3690

api/apps/document_app.py
=> Check meta data format in json map

api/db/services/document_service.py
=> Recalling the file uploaded while chatting.

api/apps/sdk/dify_retrieval.py, rag/app/manual.py
=> Fix dify retrieval issue.

helm/templates/elasticsearch.yaml, helm/values.yaml
=> Sync prerequisites with Helm Charts

rag/llm/embedding_model.py
=> Truncate text for zhipu embedding.

docker/docker-compose-base.yml, pyproject.toml, uv.lock
Bump infinity to v0.6.0-dev2. Close #4477
=> Bump infinity to v0.6.0-dev2

web/src/pages/knowledge/index.tsx
=> Fix: the Display when the knowledge base empty.

web/src/components/ui/badge.tsx, web/src/components/ui/button.tsx, web/src/components/ui/loading-button.tsx, web/src/hooks/knowledge-hooks.ts, web/src/pages/files/action-cell.tsx, web/src/pages/files/files-table.tsx, web/src/pages/files/hooks.ts, web/src/pages/files/link-to-dataset-dialog.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Add LinkToDatasetDialog #3221
=> Feat: Add LinkToDatasetDialog #3221

rag/llm/rerank_model.py
=> Fix xinference rerank issue.

web/src/pages/flow/constant.tsx, web/src/pages/flow/form/keyword-extract-form/index.tsx, web/src/pages/flow/form/rewrite-question-form/index.tsx
Feat: Add the MessageHistoryWindowSizeItem to RewriteQuestionForm #1739
=> Feat: Add the MessageHistoryWindowSizeItem to RewriteQuestionForm #1739

web/src/components/highlight-markdown/index.tsx, web/src/pages/chat/markdown-content/index.tsx, web/src/utils/chat.ts
[remarkjs/react-markdown/issues/785](https://github.com/remarkjs/react-markdown/issues/785)
Fix: Fixed an issue where math formulas could not be displayed correctly #4405
=> Fix: Fixed an issue where math formulas could not be displayed correctly #4405

docs/references/agent_component_reference/keyword.mdx, docs/references/agent_component_reference/message.mdx, docs/references/agent_component_reference/retrieval.mdx, web/src/locales/en.ts
=> Added descriptions of Message and Keyword agent components

Dockerfile
Change index url per NEED_MIRROR. Close #4507
=> Change index url per NEED_MIRROR

README_tzh.md
=> add file README_tzh.md

api/apps/sdk/doc.py
=> Fix doc progress issue.

pyproject.toml, uv.lock
=> Bump akshare

agent/component/base.py, agent/component/categorize.py
=> Make `Categorize` see more chat hisotry.

docs/references/agent_component_reference/concentrator.mdx, docs/references/agent_component_reference/switch.mdx
=> Added description of the Concentrator component

Dockerfile, docker/docker-compose.yml, docker/entrypoint_task_executor.sh
Added entrypoint for task executor
=> Added entrypoint for task executor

web/src/global.less, web/src/pages/dataset/index.tsx, web/src/pages/dataset/setting/index.tsx, web/src/pages/dataset/testing/index.tsx, web/src/pages/profile-setting/model/index.tsx
Feat: Make the scroll bar of the DatasetSettings page appear inside #3221
=> Feat: Make the scroll bar of the DatasetSettings page appear inside #3221

web/src/locales/config.ts, web/src/locales/en.ts, web/src/locales/es.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
Feat: Support for Portuguese language #4557
=> Feat: Support for Portuguese language #4557

README_pt_br.md
Latest Release button on Portugese Read me is not looking like it shuld
=> Fix Latest Release button on PT README

api/apps/kb_app.py
=> Fix index not found for new user.

rag/app/qa.py
=> Fix pdf applying Q&A issue.

api/db/services/user_service.py
=> Unified user_service.py

web/src/components/knowledge-base-item.tsx, web/src/constants/knowledge.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
Feat: Add keyword item to AssistantSetting #4543
=> Feat: Add keyword item to AssistantSetting #4543

web/tailwind.css
Feat: Set the style of the header tag #3221
=> Feat: Set the style of the header tag #3221

rag/utils/es_conn.py
=> Code format.

deepdoc/vision/ocr.py, deepdoc/vision/recognizer.py
=> deepdoc use GPU if possible

rag/llm/embedding_model.py
=> Fix TogetherAIEmbed.

api/db/services/canvas_service.py, api/db/services/conversation_service.py
=> Add timestamp to messages

deepdoc/vision/__init__.py
=> Fix t_ocr.py for PNG image.

api/apps/sdk/chat.py
=> Fix missplace for vector sim weight and token sim weight.

rag/app/qa.py
=> Fix csv reader exception.

pyproject.toml, uv.lock
=> Fix onnxruntime-gpu marks

rag/utils/infinity_conn.py
=> Make infinity able to cal embedding sim only.

web/src/pages/user-setting/components/setting-title/index.tsx, web/src/pages/user-setting/setting-model/index.tsx
Fixed vertical alignment issues between icons and text in API-Key and System Model Settings buttons. This improves visual consistency across the settings interface.
Before: Icons and text were slightly misaligned vertically
After: Icons and text are now properly centered with consistent spacing
=> refactor: better vertical alignment for icon and text in some setting buttons

docs/references/supported_models.mdx
=> Align table heading with 'System Model Settings'

docs/references/agent_component_reference/concentrator.mdx, docs/references/supported_models.mdx, rag/llm/__init__.py
=> Added GPUStack

rag/nlp/search.py
=> Fix potential error.

rag/app/table.py
=> Fix too long integer for `Table`.

api/apps/kb_app.py, rag/raptor.py, rag/utils/es_conn.py, rag/utils/infinity_conn.py
=> Make infinity adapt to condition `exist`.

docs/references/agent_component_reference/categorize.mdx, docs/references/agent_component_reference/interact.mdx, docs/references/agent_component_reference/iteration.mdx, docs/references/agent_component_reference/template.mdx
=> Added description of the Iteration component

conf/llm_factories.json
=> Refresh deepseek models.

docs/references/agent_component_reference/iteration.mdx, web/src/locales/en.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
Rename from 'Diagonal' to 'Forward slash'
Rename from 'Minus' to 'Dash'
issue: #4655
=> Refactor the delimiter name

conf/infinity_mapping.json, deepdoc/parser/pdf_parser.py, graphrag/utils.py
=> Infinity adapt to graphrag.

conf/infinity_mapping.json
=> Infinity mapping refine.

deepdoc/vision/ocr.py, deepdoc/vision/recognizer.py, pyproject.toml, uv.lock
Fixed GPU detection on CPU only environment. Close #4692
=> Fixed GPU detection on CPU only environment

agent/component/akshare.py
=> Import akshare lazzily.

api/apps/kb_app.py, conf/llm_factories.json
=> Update deepseek model provider info.

graphrag/search.py, rag/utils/infinity_conn.py
=> Fitin for infinity.

deepdoc/vision/ocr.py, deepdoc/vision/recognizer.py, pyproject.toml, uv.lock
=> Added cuda_is_available

web/src/pages/chat/markdown-content/index.tsx
Fix: Chat Assistant page goes blank #4566
=> Fix: Chat Assistant page goes blank #4566

rag/nlp/query.py
=> Fix too long query exception.

agent/component/exesql.py
Avoid misunderstanding LLMs about the numbers value
=> Avoid misunderstanding LLMs about the numbers value

graphrag/general/community_reports_extractor.py, graphrag/general/extractor.py, graphrag/general/graph_extractor.py, graphrag/light/graph_extractor.py
=> Fix too long context issue.

web/src/hooks/logic-hooks.ts, web/src/hooks/user-setting-hooks.tsx, web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
Fix: New user can't accept invite without configuring LLM API #4379
=> Fix: New user can't accept invite without configuring LLM API #4379

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
Feat: Supports docx in the MANUAL chunk method and docx, markdown, and PDF in the Q&A chunk method #3957
=> Feat: Supports docx in the MANUAL chunk method and docx, markdown, and PDF in the Q&A chunk method #3957

agent/templates/research_report.json, docs/guides/accelerate_question_answering.mdx, docs/guides/develop/build_docker_image.mdx, docs/quickstart.mdx, docs/release_notes.md
=> Updated template description

graphrag/general/community_reports_extractor.py, graphrag/search.py, rag/nlp/search.py
=> Robust for abnormal response from LLMs.

conf/llm_factories.json
=> More models for siliconflow.

rag/llm/chat_model.py
=> Fix Gemini chat issue.

conf/llm_factories.json
=> Refresh Gemini model list.

docker/docker-compose-base.yml
=> Add a comment to valkey.

rag/nlp/__init__.py
=> Fix divided by zero issue.

conf/mapping.json
=> Increase ES update script length.

web/src/utils/request.ts
Fix: The requested interface timeout will cause the page to crash #4787
=> Fix: The requested interface timeout will cause the page to crash #4787

agent/component/generate.py, agent/component/template.py, agent/templates/DB Assistant.json, agent/templates/HR_callout_zh.json, agent/templates/customer_service.json, agent/templates/general_chat_bot.json, agent/templates/interpreter.json, agent/templates/investment_advisor.json, agent/templates/medical_consultation.json, agent/templates/research_report.json, agent/templates/seo_blog.json, agent/templates/text2sql.json, agent/templates/websearch_assistant.json
=> Inner prompt parameter setting.

web/src/components/prompt-editor/constant.ts, web/src/components/prompt-editor/index.tsx, web/src/components/prompt-editor/variable-on-change-plugin.tsx, web/src/components/prompt-editor/variable-picker-plugin.tsx, web/src/hooks/flow-hooks.ts, web/src/pages/flow/form/generate-form/index.tsx, web/src/pages/flow/hooks/use-save-graph.ts
Feat: Fixed the issue where the prompt always displayed the initial value when switching between different generate operators #4764
=> Feat: Fixed the issue where the prompt always displayed the initial value when switching between different generate operators #4764

agent/templates/HR_callout_zh.json, agent/templates/customer_service.json, agent/templates/general_chat_bot.json, agent/templates/investment_advisor.json, agent/templates/medical_consultation.json, agent/templates/text2sql.json, agent/templates/websearch_assistant.json
Feat: Remove begin's width from agent templates #4764
=> Feat: Remove begin's width from agent templates #4764

api/db/services/document_service.py
=> Fix KG circle.

web/src/components/message-item/hooks.ts
Fix: Fail to open console with Firefox #4816
=> Fix: Fail to open console with Firefox #4816

api/apps/llm_app.py
=> Reformat error message.

web/src/components/llm-setting-items/index.tsx
Feat: Modify the Preset configurations item style to distinguish it from other fields #4844
=> Feat: Modify the Preset configurations item style to distinguish it from other fields #4844

conf/mapping.json, graphrag/search.py, rag/utils/es_conn.py
=> Make the update script shorter.

agent/component/categorize.py
Fix categorize agent input content not format error
=> fix categorize agent input content not format error

web/src/components/knowledge-base-item.tsx, web/src/pages/next-chats/chat/app-settings.tsx, web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx, web/src/pages/next-chats/chat/app-settings/chat-model-settings.tsx, web/src/pages/next-chats/chat/app-settings/chat-prompt-engine.tsx, web/src/pages/next-chats/chat/app-settings/index.tsx, web/src/pages/next-chats/chat/app-settings/subhead.tsx, web/src/pages/next-chats/chat/app-settings/switch-fom-field.tsx
Feat: Add ChatBasicSetting component #3221
=> Feat: Add ChatBasicSetting component #3221

web/src/pages/knowledge/index.tsx
Fix: Knowledge base page crashes when network connection is lost. #4894
=> Fix: Knowledge base page crashes when network connection is lost. #4894

docker/docker-compose-base.yml, helm/templates/elasticsearch.yaml
Changed elasticsearch image url to speed up image downloading.
=> Changed elasticsearch image url

graphrag/light/graph_extractor.py
=> Fix xinference chat role order issue.

deepdoc/vision/operators.py, rag/llm/chat_model.py
=> Display thinking for deepseek r1

web/src/components/llm-setting-items/next.tsx, web/src/hooks/chat-hooks.ts, web/src/hooks/llm-hooks.tsx, web/src/pages/next-chats/chat/app-settings/chat-model-settings.tsx, web/src/pages/next-chats/chat/app-settings/index.tsx, web/src/pages/next-chats/index.tsx
Feat: Add LlmSettingFieldItems component #3221
=> Feat: Add LlmSettingFieldItems component #3221

web/src/components/llm-select/llm-label.tsx, web/src/components/llm-setting-items/index.tsx, web/src/hooks/chat-hooks.ts, web/src/hooks/llm-hooks.tsx, web/src/utils/llm-util.ts, web/tailwind.css
Fix: After deleting all conversation lists, the chat input box can still be used for input. #4907
=> Fix: After deleting all conversation lists, the chat input box can still be used for input. #4907

conf/llm_factories.json
=> Organized and add a list of large language models of Nvidia.v1.1

web/src/components/chat-input.tsx, web/src/components/ui/textarea.tsx, web/src/pages/next-chats/chat/app-settings/index.tsx, web/src/pages/next-chats/chat/chat-box.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Add ChatInput component #3221
=> Feat: Add ChatInput component #3221

agent/templates/DB Assistant.json
=> Fix DB assistant template error.

web/src/components/message-item/index.less, web/src/pages/chat/markdown-content/index.tsx, web/src/utils/chat.ts
Feat: Display Think for Deepseek R1 model #4903
=> Feat: Display Think for Deepseek R1 model #4903

web/src/pages/dataset/sidebar/hooks.tsx, web/src/routes.ts
Feat: Add an id to the dataset testing route #3221
=> Feat: Add an id to the dataset testing route #3221

api/db/services/llm_service.py
=> Ignore tenant not found error while increasing token usage.

rag/raptor.py
=> Fix hit cache error while raptoring.

agent/component/exesql.py
=> format number float

web/src/hooks/logic-hooks/navigate-hooks.ts, web/src/pages/chunk/chunk-result/index.tsx, web/src/pages/chunk/index.tsx, web/src/pages/chunk/parsed-result/index.tsx, web/src/pages/chunk/result-view/index.tsx, web/src/pages/dataset/dataset/use-dataset-table-columns.tsx, web/src/routes.ts
Feat: Jump from the chunk page to the dataset page #3221
=> Feat: Jump from the chunk page to the dataset page #3221

conf/llm_factories.json
add gemini-2.0-flash-thinking-exp-01-21
=> add  gemini-2.0-flash-thinking-exp-01-21

web/src/hooks/logic-hooks/navigate-hooks.ts, web/src/pages/chunk/chunk-card.tsx, web/src/pages/chunk/chunk-result/index.tsx, web/src/pages/chunk/chunk-toolbar.tsx, web/src/pages/chunk/index.tsx, web/src/pages/chunk/parsed-result-panel.tsx, web/src/pages/chunk/parsed-result/index.tsx
Feat: Add ParsedPageCard component #3221
=> Feat: Add ParsedPageCard component #3221

web/src/components/parse-configuration/graph-rag-items.tsx, web/src/pages/flow/canvas/index.tsx, web/src/pages/flow/hooks/use-open-document.ts
Feat: Add background color to GraphRag configuration #4980
=> Feat: Add background color to GraphRag configuration #4980

docs/guides/develop/build_docker_image.mdx, download_deps.py
Added PEP 723 metadata to download_deps.py
=> Added PEP 723 metadata to download_deps.py

api/db/services/dialog_service.py
=> Fix <think> in keywords or question auto-generations.

api/apps/kb_app.py
Fix knowledge graph node not found (#4968)
=> Fix knowledge graph node not found (#4968)

graphrag/utils.py
=> Fix keyerror issue while rebuilding graph.

api/db/services/dialog_service.py
=> Optimize conversation when uploading attachments

graphrag/utils.py
=> Fix window size of ES issue.

graphrag/general/extractor.py
=> Remove <think> for KG extraction.

web/src/pages/flow/canvas/index.tsx
Fix: Cannot distinguish between export and import icons #5025
=> Fix: Cannot distinguish between export and import icons #5025

api/apps/kb_app.py, rag/utils/es_conn.py
=> Ignore exception of empty index.

api/utils/__init__.py
=> Add another decrypt function.

api/apps/kb_app.py, rag/nlp/search.py
=> Ignore exceptions when no index ahead.

web/src/locales/vi.ts
=> update locale vi

api/db/services/dialog_service.py, api/db/services/llm_service.py
Fix: The max tokens defined by the tenant are not used (#4297) (#2817)
=> Fix: The max tokens defined by the tenant are not used (#4297) (#2817)

web/src/components/api-service/embed-modal/index.less, web/src/components/api-service/embed-modal/index.tsx, web/src/constants/common.ts, web/src/locales/config.ts
Feat: Add LanguageAbbreviation to simplify language resource files. #5065
=> Feat: Add LanguageAbbreviation to simplify language resource files. #5065

web/src/hooks/llm-hooks.tsx
Feat: Extract the common parts of groupImage2TextOptions and groupOptionsByModelType #5063
=> Feat: Extract the common parts of groupImage2TextOptions and groupOptionsByModelType #5063

web/src/components/edit-tag/index.tsx
Fix: Chunk problem tag content cannot be displayed completely. #5076
=> Fix: Chunk problem tag content cannot be displayed completely. #5076

web/src/pages/chunk/chunk-card.tsx, web/src/pages/chunk/chunk-result/index.tsx, web/src/pages/chunk/chunk-toolbar.tsx, web/src/pages/chunk/chunked-result-panel.tsx, web/src/pages/chunk/index.tsx, web/src/pages/chunk/parsed-result-panel.tsx, web/src/pages/chunk/result-view/index.tsx
Feat: Add ChunkedResultPanel #3221
=> Feat: Add ChunkedResultPanel #3221

docs/guides/accelerate_question_answering.mdx, docs/guides/configure_knowledge_base/construct_knowledge_graph.md, docs/references/faq.md, docs/references/http_api_reference.md, docs/references/python_api_reference.md, docs/release_notes.md, web/src/locales/en.ts
=> Added an FAQ

web/src/components/message-item/index.less, web/src/pages/chat/markdown-content/index.less, web/src/pages/chat/markdown-content/index.tsx, web/src/utils/chat.ts
Feat: Write the thinking style in the MarkdownContent layer #4930
=> Feat: Write the thinking style in the MarkdownContent layer #4930

rag/app/naive.py
=> Fix docx table issue.

rag/nlp/query.py, rag/nlp/synonym.py, rag/raptor.py
=> Fix too many clause while searching.

api/apps/sdk/doc.py, api/db/services/document_service.py, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/document.py
add support for update document meta data through  api
=> Feat: Add support for document meta fields update through api

graphrag/general/community_reports_extractor.py
=> Remove redandent code.

web/src/pages/flow/constant.tsx
Feat: Allow the Rewrite operator to connect to the Generate operator #1739
=> Feat: Allow the Rewrite operator to connect to the Generate operator #1739

web/src/pages/document-viewer/index.tsx, web/src/services/file-manager-service.ts, web/src/utils/file-util.ts
Feat: Support preview of HTML files #5096
=> Feat: Support preview of HTML files #5096

README.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md
Docs: Add note about docker volume deletion in README files
refer to this question: https://github.com/infiniflow/ragflow/issues/5132
=> Docs: Add note about docker volume deletion in README files，will be more novice-friendly

web/src/components/prompt-editor/index.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
Feat: Add insert variable icon in the header of prompt editor. #4764
=> Feat: Add insert variable icon in the header of prompt editor. #4764

web/src/components/message-input/index.tsx
just resolve issue： [Improve message input handling with Shift+Enter support](https://github.com/infiniflow/ragflow/issues/5116)
=> Fix: Improve message input handling with Shift+Enter support

web/src/pages/chat/shared-hooks.ts, web/src/pages/flow/header/index.tsx, web/src/pages/flow/hooks/use-get-begin-query.tsx
Right now we cannot embed a chat in website when it has variables in the begin component.
This PR tries to read the variables values from the query string via a data_ prefixed variable.
#5016
=> Iframe should support input variables

web/src/pages/chat/markdown-content/index.less, web/src/pages/chat/markdown-content/index.tsx
Feat: Show formulas when answering, show reference labels in style, remove cursor flashing effect. #5173
=> Feat: Show formulas when answering, show reference labels in style, remove cursor flashing effect. #5173

graphrag/utils.py
=> Fix window size issue of ES.

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/chat/chat-configuration-modal/prompt-engine.tsx
Feat: Add reasoning item to chat configuration modal #5173
=> Feat: Add reasoning item to chat configuration modal #5173

web/src/hooks/logic-hooks/navigate-hooks.ts, web/src/layouts/next-header.tsx, web/src/pages/agent/index.tsx, web/src/pages/agents/agent-card.tsx, web/src/pages/agents/index.tsx, web/src/routes.ts
=> Feat: Add agent page. #3221

web/src/hooks/logic-hooks/navigate-hooks.ts, web/src/layouts/next-header.tsx, web/src/pages/next-search/index.tsx, web/src/pages/next-searches/index.tsx, web/src/pages/next-searches/search-card.tsx, web/src/routes.ts
Feat: Add SearchPage component. #3221
=> Feat: Add SearchPage component. #3221

deepdoc/parser/pdf_parser.py, deepdoc/vision/recognizer.py, deepdoc/vision/table_structure_recognizer.py
Optimized Recognizer.sort_X_firstly and Recognizer.sort_Y_firstly
=> Optimized Recognizer.sort_X_firstly and Recognizer.sort_Y_firstly

api/apps/dialog_app.py, api/db/services/dialog_service.py
=> Support chat solo.

agent/canvas.py, agent/component/base.py, agent/component/categorize.py, agent/component/generate.py, agent/component/template.py
=> Fix spelling errors

rag/nlp/query.py
=> Fix empty question issue.

deepdoc/vision/ocr.py, deepdoc/vision/recognizer.py
Reuse loaded modules if possible
=> Reuse loaded modules if possible

api/db/services/dialog_service.py, rag/nlp/__init__.py, rag/nlp/query.py
=> Refine search query.

rag/utils/infinity_conn.py
=> Fixed similarity on infinity

api/apps/llm_app.py
=> Double check error of adding llm.

web/src/hooks/document-hooks.ts
Partitions the upload of documents in parts of 20 to avoid the size limit error. Allows uploading 100s of documents on a single interaction.
=> Feat: add partition of file uploads

agent/component/exesql.py
=> Refine the error message.

api/apps/llm_app.py
=> Refine error message for re-rank model.

api/apps/sdk/chat.py, rag/raptor.py
=> Let list_chat go without kb checking.

agent/component/generate.py
=> Remove <think> content for `Generate` if it's not stream output.

web/src/pages/dataset/index.tsx, web/src/routes.ts
Feat: Add PageHeader to DatasetWrapper #3221
=> Feat: Add PageHeader to DatasetWrapper #3221

rag/llm/chat_model.py
=> Tongyi adapts deepseek.

web/src/constants/chat.ts, web/src/pages/chat/chat-configuration-modal/model-setting.tsx, web/src/pages/flow/constant.tsx, web/src/pages/flow/hooks.tsx, web/src/utils/chat.ts
Feat: Disable Max_token by default #5283
=> Feat: Disable Max_token by default #5283

docs/guides/configure_knowledge_base/run_retrieval_test.md, docs/guides/develop/build_docker_image.mdx
=> Added a prerequisite for ARM platforms

rag/llm/chat_model.py
=> Fix base url missing for deepseek from Tongyi.

deepdoc/parser/pdf_parser.py, deepdoc/vision/ocr.py, rag/svr/task_executor.py
Introduced OCR.recognize_batch
=> Optimize ocr

web/package-lock.json, web/package.json, web/src/app.tsx, web/src/components/hooks/use-toast.tsx, web/src/components/ui/select.tsx, web/src/components/ui/toast.tsx, web/src/components/ui/toaster.tsx, web/src/constants/common.ts, web/src/pages/agent/hooks/use-export-json.ts, web/src/pages/agent/index.tsx, web/src/pages/agent/upload-agent-dialog/index.tsx, web/src/pages/agent/upload-agent-dialog/upload-agent-form.tsx
=> Feat: Upload agent file #3221

api/db/services/dialog_service.py
=> Refine prompt of agentic search.

graphrag/general/extractor.py
=> Make node merging parallel.

graphrag/general/community_reports_extractor.py
=> More robust community report.

rag/llm/chat_model.py
=> Resolve super class invokation error.

web/src/components/message-item/index.tsx, web/src/interfaces/database/chat.ts, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx, web/src/pages/chat/markdown-content/index.tsx
Feat: Add Tavily Api Key to chat configuration modal. #5198
=> Feat: Add Tavily Api Key to chat configuration modal. #5198

api/db/services/dialog_service.py, rag/llm/rerank_model.py
=> Fix FlagRerank max_length issue.

api/db/services/document_service.py
fix this bug: https://github.com/infiniflow/ragflow/issues/5368
=> Fix：validate knowledge base association before document upload

api/apps/sdk/session.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md
Add OpenAI-compatible http and python api reference
=> DOCS: add OpenAI-compatible http and python api reference

rag/raptor.py
=> Let parallism of RAPTOR controlable.

api/apps/llm_app.py, docs/references/supported_models.mdx
Correct typo in supported_models file
=> FIX: correct typo

api/apps/sdk/session.py
Fixed OpenAI compatibility stream [DONE]
=> Fixed OpenAI compatibility stream [DONE]

api/db/services/conversation_service.py, api/db/services/dialog_service.py, rag/prompts.py
=> Fix issue of `ask` API.

.github/workflows/tests.yml
This patch remove dangerous code that `may expand into attacker-controllable code`
more:
```cli
error[template-injection]: code injection via template expansion
--> /Users/hyi/prs/ragflow/.github/workflows/tests.yml:35:9
|
35 |         - name: Show PR labels
|           ^^^^^^^^^^^^^^^^^^^^ this step
36 |           run: |
|  _________^
37 | |           echo "Workflow triggered by ${{ github.event_name }}"
38 | |           if [[ ${{ github.event_name }} == 'pull_request' ]]; then
39 | |             echo "PR labels: ${{ join(github.event.pull_request.labels.*.name, ', ') }}"
40 | |           fi
| |____________^ github.event.pull_request.labels.*.name may …
```
=> ci: remove may expand into attacker-controllable code

api/apps/sdk/doc.py
=> Fix: issue of no id for /datasets/<dataset_id>/documents

agent/component/exesql.py, api/apps/sdk/doc.py
=> Fix: string format error.

api/apps/llm_app.py, rag/llm/cv_model.py
=> Fix: add image2text issue.

web/src/assets/icon/Icon.tsx, web/src/components/ui/select.tsx, web/src/pages/agent/agent-sidebar.tsx, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form/components/next-dynamic-input-variable.tsx, web/src/pages/agent/form/retrieval-form/next.tsx
Feat: Wrap DynamicVariableForm with Collapsible. #3221
=> Feat: Wrap DynamicVariableForm with Collapsible. #3221

deepdoc/parser/txt_parser.py
Fix special delimiter parsing issue #5382
=> Fix: fix special delimiter parsing issue

api/db/services/dialog_service.py
=> Fix: rm think if stream is Flase.

web/src/components/chunk-method-modal/hooks.ts, web/src/components/chunk-method-modal/index.tsx, web/src/components/parse-configuration/graph-rag-items.tsx, web/src/components/parse-configuration/index.tsx, web/src/constants/knowledge.ts, web/src/pages/add-knowledge/components/knowledge-setting/configuration.tsx
Feat: Modify the parsing method string to an enumeration type. #5467
=> Feat: Modify the parsing method string to an enumeration type. #5467

docs/guides/develop/build_docker_image.mdx
Amend docker image building page and more hints for mac users
=> DOCS: amend docker image building page and more hints for mac users

docker/service_conf.yaml.template, rag/utils/oss_conn.py
Enhance aliyun oss access with adding prefix path.
=> Fix: enhance aliyun oss access with adding prefix path

rag/app/table.py
=> Fix table parser issue.

web/src/components/chunk-method-modal/index.tsx, web/src/components/dataset-configuration-container.tsx
Feat: Wrap MaxTokenNumber with DatasetConfigurationContainer. #5467
=> Feat: Wrap MaxTokenNumber with DatasetConfigurationContainer. #5467

rag/svr/task_executor.py
=> Refine error message while embedding model error,

web/src/hooks/llm-hooks.tsx, web/src/utils/llm-util.ts
Feat: Hide the suffix of the large model name. #5433
=> Feat: Hide the suffix of the large model name. #5433

web/src/components/layout-recognize.tsx
Feat: Add the Experimental text to the option of the large model of the Image2text type of LayoutRecognizeItem
=> Feat: Add the Experimental text to the option of the large model of the Image2text type of LayoutRecognizeItem

api/utils/file_utils.py, deepdoc/parser/pdf_parser.py, deepdoc/vision/__init__.py, rag/svr/task_executor.py
close #5277 by make sure the file close
=> Fix: possible memory leaks close #5277

api/db/services/document_service.py
=> Fix: in case running KG repeatly.

api/db/services/dialog_service.py
=> Optimize prompt.

web/src/components/llm-select/index.tsx, web/src/components/ui/select.tsx, web/src/pages/agent/form/generate-form/index.tsx
Feat: Add NextLLMSelect with shadcn-ui. #3221
=> Feat: Add NextLLMSelect with shadcn-ui. #3221

rag/nlp/rag_tokenizer.py
=> Fix: bad case for tokenizer.

web/src/components/llm-select/index.tsx, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/index.tsx, web/src/pages/agent/operator-icon.tsx
Feat: Combine Select and LlmSettingFieldItems into LLMSelect. #3221
=> Feat: Combine Select and LlmSettingFieldItems into LLMSelect. #3221

web/src/components/message-history-window-size-item.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/rewrite-question-form/index.tsx
Feat: Render RewriteQuestionForm with shadcn-ui #3221
=> Feat: Render RewriteQuestionForm with shadcn-ui #3221

web/src/components/top-n-item.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/akshare-form/index.tsx, web/src/pages/agent/form/baidu-form/index.tsx, web/src/pages/agent/form/duckduckgo-form/index.tsx, web/src/pages/agent/form/keyword-extract-form/index.tsx, web/src/pages/agent/form/wencai-form/index.tsx, web/src/pages/agent/form/wikipedia-form/index.tsx
Feat: Render WikipediaForm and BaiduForm with shadcn-ui. #3221
=> Feat: Render WikipediaForm and BaiduForm with shadcn-ui. #3221

docs/configurations.md, docs/develop/acquire_ragflow_api_key.md, docs/faq.md, docs/guides/chat/start_chat.md, docs/guides/models/deploy_local_llm.mdx, docs/quickstart.mdx, docs/release_notes.md
=> Minor: Fixed broken links

web/src/hooks/llm-hooks.tsx, web/src/pages/user-setting/setting-model/index.tsx
Fix: LLM with ___ return cannot be deleted #5585
=> Fix: LLM with ___ return cannot be deleted #5585

conf/llm_factories.json
=> Perf: update novita.ai LLM library

api/db/services/dialog_service.py
Fix may lose part of information of last stream chunck
=> Fix: fix may lose part of information of last stream chunck

api/apps/sdk/chat.py
=> Fix: remove KB id restriction while creating chat.

graphrag/entity_resolution.py, graphrag/general/extractor.py, graphrag/general/mind_map_extractor.py, rag/svr/task_executor.py
Fix nursery.start_soon. Close #5575
=> Fix nursery.start_soon. Close #5575

docker/launch_backend_service.sh
As title export PYTHONPATH in the shell
=> Fix: better start experience PYTHONPATH in shell

docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Docs: about meta files in API reference.

web/src/layouts/components/right-toolbar/index.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/message-form/index.tsx, web/src/pages/agent/form/pubmed-form/index.tsx
Feat: Render MessageForm with shadcn-ui. #3221
=> Feat: Render MessageForm with shadcn-ui. #3221

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docs/develop/_category_.json, docs/develop/acquire_ragflow_api_key.md, docs/develop/build_docker_image.mdx, docs/develop/launch_ragflow_from_source.md, docs/faq.md, docs/guides/agent/embed_agent_into_webpage.md, docs/guides/agent/general_purpose_chatbot.md, docs/guides/chat/accelerate_question_answering.mdx, docs/guides/chat/start_chat.md, docs/guides/dataset/accelerate_doc_indexing.mdx, docs/guides/dataset/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/models/deploy_local_llm.mdx, docs/references/supported_models.mdx, docs/release_notes.md, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx
=> Added 0.17.0 release notes

api/apps/system_app.py
Fix the issue where, when getting  a user's APIToken, if the user is part of another user's team, it incorrectly gets the Team owner's APIToken instead.
=> Fix：Fix the bug of incorrectly gets the APIToken.

graphrag/entity_resolution.py
=> fix: issue #5600

deepdoc/parser/excel_parser.py, rag/app/table.py
Optimize error handling and support parsing of XLS(EXCEL97—2003) files.
=> Refactor: Optimize error handling and support parsing of XLS(EXCEL97—2003) files.

graphrag/general/extractor.py
=> Fix: parameter error.

api/db/db_models.py, api/db/services/document_service.py, docker/launch_backend_service.sh, graphrag/entity_resolution.py, rag/svr/task_executor.py
Refactored DocumentService.update_progress
=> Refactored DocumentService.update_progress

web/src/pages/add-knowledge/components/knowledge-setting/configuration/book.tsx, web/src/pages/add-knowledge/components/knowledge-setting/configuration/laws.tsx, web/src/pages/add-knowledge/components/knowledge-setting/configuration/manual.tsx, web/src/pages/add-knowledge/components/knowledge-setting/configuration/one.tsx, web/src/pages/add-knowledge/components/knowledge-setting/configuration/paper.tsx, web/src/pages/add-knowledge/components/knowledge-setting/configuration/presentation.tsx
Feat: The parsing method is paper and needs to display Document parser. #5467
=> Feat: The parsing method is paper and needs to display Document parser. #5467

agentic_reasoning/deep_research.py, rag/utils/tavily_conn.py
=> Fix: tavily search error.

api/db/services/dialog_service.py
=> Fix: search citation issue.

api/db/services/llm_service.py, deepdoc/parser/pdf_parser.py, deepdoc/parser/ppt_parser.py, deepdoc/vision/ocr.py, deepdoc/vision/operators.py, deepdoc/vision/postprocess.py, deepdoc/vision/recognizer.py, rag/utils/azure_sas_conn.py, rag/utils/azure_spn_conn.py, rag/utils/minio_conn.py, rag/utils/oss_conn.py, rag/utils/s3_conn.py, sdk/python/ragflow_sdk/modules/base.py
=> refactor: no need to inherit in python3 clean the code

conf/llm_factories.json, rag/llm/__init__.py, rag/llm/rerank_model.py
=> Feat: support huggingface re-rank model.

web/src/pages/user-setting/setting-model/ollama-modal/index.tsx
Feat: Add rerank option to huggingface's model type drop-down box. #5658
=> Feat: Add rerank option to huggingface's model type drop-down box. #5658

web/src/components/parse-configuration/graph-rag-items.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
1. Add the missing translations.  
2. Shorten overly long tips.
=> Minor: improve tips display

rag/llm/chat_model.py
=> Refa: remove max tokens since no one needs it.

web/src/components/llm-setting-items/index.tsx
Fix: Remove the max token parameter. #5640 #5646
=> Fix: Remove the max token parameter. #5640 #5646

docs/references/python_api_reference.md
=> Fix: docs inconsistency.

api/apps/sdk/dataset.py, api/utils/api_utils.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/dataset.py
=> Refa: remove dataset language and validate dataset name length.

api/db/services/document_service.py, graphrag/general/extractor.py
=> Fix: too long context during KG issue.

docs/guides/dataset/run_retrieval_test.md, web/src/locales/en.ts, web/src/locales/es.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
=> Updated instructions in the UI

web/src/pages/add-knowledge/components/knowledge-setting/configuration/index.tsx
Fix: Remove the document language parameter. #5686
=> Fix: Remove the document language parameter. #5640

graphrag/search.py
=> Fix: empty description

web/src/components/file-upload-modal/index.tsx
=> Fix: can not upload file close #5730

agent/component/rewrite.py, rag/prompts.py
=> Refa: make Rewrite component effective to relative data expression.

web/src/components/file-upload-modal/index.tsx, web/src/pages/add-knowledge/components/knowledge-file/hooks.ts
Fix: Fixed the issue that files cannot be uploaded on the file management page. #5730
=> Fix: Fixed the issue that files cannot be uploaded on the file management page. #5730

api/apps/sdk/doc.py
=> Fix: meta fields updata issue,

rag/prompts.py
=> Fix: truncate message issue.

docs/guides/chat/implement_deep_research.md
=> Initial draft of Implemnt deep research

api/apps/sdk/dataset.py
Fixed the issue of "stop deleting when encountering invalid dataset ID"
#5760
=> Fix: bugs mentioned by#5760

conf/llm_factories.json
=> Refa: update mistral model list.

api/apps/llm_app.py
=> Refa: add model.

graphrag/utils.py
=> Refa: reduce default value of MAX_CONCURRENT_CHATS

web/src/components/ui/transfer-list.tsx
Feat: Add TransferList component. #3221
=> Feat: Add TransferList component. #3221

conf/llm_factories.json
=> Refa: SiliconFlow model list refresh.

rag/nlp/query.py
=> Fix: empty query issue.

web/src/components/rerank.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/chat/chat-configuration-modal/prompt-engine.tsx
Feat: When selecting a reordering model, give a prompt that it takes too long. #5834
=> Feat: When selecting a reordering model, give a prompt that it takes too long. #5834

sdk/python/test/test_http_api/test_dataset_mangement/test_list_dataset.py
=> TEST: Added test cases for List Dataset HTTP API

web/src/components/ui/avatar.tsx, web/src/interfaces/database/user-setting.ts
Feat: Add AvatarGroup component. #3221
=> Feat: Add AvatarGroup component. #3221

sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
Update test cases per PR #5755
=> Test: Update test cases per PR #5755

api/apps/sdk/dataset.py
=> Fix: empty dataset parser id.

api/db/services/dialog_service.py
=> Fix: rm <think> for ES sql generation.

sdk/python/test/test_http_api/test_dataset_mangement/test_delete_dataset.py
update test cases per PR https://github.com/infiniflow/ragflow/pull/5778
=> Test: Update test cases per PR #5778

api/apps/sdk/dataset.py
=> Fix: check `desc` parameter value.

docs/develop/build_docker_image.mdx
=> Fix: docs updates.

api/db/services/dialog_service.py
=> Refa: add prompt to empty retrieved answwer.

sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
update test cases per PR #5748 #5878  issue #5709
=> Test: Update test cases per PR #5748 #5878

web/src/locales/en.ts, web/src/locales/id.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
=> UI updates

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docker/.env, docker/README.md, docs/configurations.md, docs/develop/build_docker_image.mdx, docs/faq.md, docs/guides/chat/implement_deep_research.md, docs/guides/dataset/accelerate_doc_indexing.mdx, docs/guides/dataset/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, docs/release_notes.md, helm/values.yaml, pyproject.toml, sdk/python/pyproject.toml, sdk/python/uv.lock, uv.lock
=> Docs: prepare docs for release v0.17.1

docs/faq.md, docs/guides/chat/implement_deep_research.md, docs/guides/dataset/accelerate_doc_indexing.mdx, docs/release_notes.md
=> Reverted some of the version changes

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/question.yml
=> Docs: reformat.

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
=> Docs: updates.

graphrag/entity_resolution.py, graphrag/general/community_reports_extractor.py, graphrag/general/index.py, graphrag/utils.py
=> Optimized graphrag again

sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
cover dataset update endpoints
=> TEST: Added test cases for Update Dataset HTTP API

agent/component/iterationitem.py, agentic_reasoning/prompts.py, api/db/services/dialog_service.py, rag/prompts.py, rag/utils/tavily_conn.py
=> Feat: apply LLM to optimize citations.

api/apps/llm_app.py, api/apps/sdk/session.py
=> Fix: ollama model add error.

api/apps/sdk/dataset.py
=> Fix: empty value updating.

agentic_reasoning/deep_research.py
This commit refactors the deep research module (deep_research.py), with the following major improvements: The complex thinking and retrieval logic has been broken down into multiple independent private methods, enhancing code readability and maintainability. Static methods and class methods have been introduced to simplify the logic for tag processing. The search and reasoning processes have been optimized, increasing the modularity of the code. The flexibility of information retrieval and processing has been improved. The refactored code structure is now clearer, making it easier to understand and extend the functionality of the deep research module.
increase  the modularity of the code
=> Refa: Optimization of the Deep Research Module Code Structure

sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
Remove unstable assertion introduced in PR #5924
=> TEST: Remove unstable assertion introduced in PR #5924

agent/component/retrieval.py
=> Feat: `Retrieval` supports internet search.

web/src/components/tavily-item.tsx, web/src/components/use-knowledge-graph-item.tsx, web/src/pages/chat/chat-configuration-modal/assistant-setting.tsx, web/src/pages/flow/constant.tsx, web/src/pages/flow/form/retrieval-form/index.tsx
Feat: Why can't Retrieval component support internet web search. #5973
=> Feat: Why can't Retrieval component support internet web search. #5973

conf/llm_factories.json, rag/llm/chat_model.py
add qwq model support to Tongyi-Qianwen factory https://github.com/infiniflow/ragflow/issues/5869
=> Feat: Add qwq model support to Tongyi-Qianwen factory

web/src/components/ui/transfer-list.tsx
Feat: Alter Item to TransferListItemType #3221
=> Feat: Alter Item to TransferListItemType #3221

deepdoc/parser/excel_parser.py, rag/app/naive.py
Add CSV file parsing support #4552, #5849, #5870
=> Feat: add CSV file parsing support

rag/llm/chat_model.py
=> Refa: refine the context window size warning.

rag/nlp/__init__.py
=> Fix: encode detect error.

sdk/python/test/test_http_api/test_dataset_mangement/test_list_dataset.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
update test cases per issue #5920 #5923
=> Test: update test cases per issue #5920 #5923

graphrag/utils.py, rag/svr/task_executor.py
Optimize graphrag cache get entity
=> Optimize graphrag cache get entity

docs/guides/agent/agent_component_reference/switch.mdx, docs/release_notes.md, rag/llm/chat_model.py
=> 0.17.1 release notes

web/src/components/max-token-number.tsx
Feat: Set the default value of Chunk token number to 512 #6016
=> Feat: Set the default value of Chunk token number to 512 #6016

api/apps/llm_app.py
=> Fix: empty api-key causes problems.

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docker/.env, docker/README.md, docs/configurations.md, docs/develop/build_docker_image.mdx, docs/faq.md, docs/guides/dataset/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, helm/values.yaml, pyproject.toml, sdk/python/pyproject.toml, sdk/python/uv.lock, uv.lock
=> DOCS: for release.

docs/guides/dataset/configure_knowledge_base.md, docs/release_notes.md
=> Added 0.17.2 release notes

sdk/python/test/libs/utils/__init__.py, sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/conftest.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_download_document.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_upload_documents.py
cover [download docments endpoints](https://ragflow.io/docs/dev/http_api_reference#download-document)
=> Test: Added test cases for Download Documents HTTP API

deepdoc/vision/layout_recognizer.py, rag/app/naive.py
Optimize OCR garbage identification to reduce unnecessary filtering. #5713
=> Fix: optimize OCR garbage identification to reduce unnecessary filtering

api/apps/sdk/session.py
fix chat_completion answer data incorrect
=> Fix: chat_completion answer data incorrect

api/db/init_data.py, api/db/services/llm_service.py, api/settings.py, rag/prompts.py
…ions
This PR fixes an issue where the application was repeatedly reading the llm_factories.json file from disk in multiple places, which could lead to "Too many open files" errors under high load conditions. The fix centralizes the file reading operation in the settings.py module and stores the data in a global variable that can be accessed by other modules.
=> Fix: Reduce excessive IO operations by loading LLM factory configurations

api/apps/sdk/doc.py, api/db/init_data.py
=> Fix: empty doc id validation.

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
Feat: Change “Document parser” to "PDF parser" #6072
=> Feat: Change “Document parser” to "PDF parser" #6072

agent/component/base.py, api/db/services/dialog_service.py
=> Feat: add token comsumption & speed to little lamp.

rag/llm/cv_model.py
=> Refa: remove max toekns for image2txt models.

agent/component/base.py
=> Fix: remove NaN output of components.

rag/svr/task_executor.py
=> Fix executor name

docs/develop/launch_ragflow_from_source.md
=> Doc: update launch from source.

api/apps/sdk/doc.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_upload_documents.py
=>  Fix: check the file name length.

api/apps/__init__.py, docker/nginx/nginx.conf
=> Refa: enlarge default max request body size.

api/db/services/document_service.py
=> Fix: none parse_config updating.

web/src/components/delimiter.tsx, web/src/components/file-upload-modal/index.tsx, web/src/pages/add-knowledge/components/knowledge-file/hooks.ts
Fix: Knowledge base page cannot upload folders #6062
=> Fix: Knowledge base page cannot upload folders #6062

api/db/services/document_service.py, api/db/services/knowledgebase_service.py
Resolve document concurrent upload issue. #6039
=> Fix: fix document concurrent upload issue

docker/.env
=> Refa: enlarge http body size.

rag/nlp/rag_tokenizer.py
=> Fix: limit the depth of DFS

rag/utils/es_conn.py
Regards kb_id at ElasticSearch insert, update, delete. Close #6066
=> Regards kb_id at ElasticSearch insert, update, delete.

rag/nlp/search.py
=> Fix: empty tag field issue.

web/package-lock.json, web/package.json, web/src/components/ui/transfer-list.tsx
Fix: Fixed the issue that events cannot be triggered after the shadcn-ui dialog is closed #3221.
Refer to [Combobox in a form in a dialog isn't working.  #1748](https://github.com/shadcn-ui/ui/issues/1748#issuecomment-2720130543)
=> Fix: Fixed the issue that events cannot be triggered after the shadcn-ui dialog is closed #3221.

web/src/pages/user-setting/setting-model/ollama-modal/index.tsx
Links of [How to integrate with Ollama](https://github.com/infiniflow/ragflow/blob/main/docs/guides/models/deploy_local_llm.mdx) need to be update after #5555 
```
https://github.com/infiniflow/ragflow/blob/main/docs/guides/deploy_local_llm.mdx
->
https://github.com/infiniflow/ragflow/blob/main/docs/guides/models/deploy_local_llm.mdx
```
=> Fix: update link of deploy_local_llm.mdx

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_download_document.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py
cover [update documents endpoints](https://ragflow.io/docs/dev/http_api_reference#update-document)
=> Test: Added test cases for Update Documents HTTP API

sdk/python/test/test_http_api/test_file_management_within_dataset/test_upload_documents.py
update test case per pr #6095 to fix issue #6039
=> Test: update test cases per pr #6095 to fix issue #6039

web/src/pages/flow/canvas/node/retrieval-node.tsx
Limit view with more knowledge when list knowledge so many.
=> Feat: Limit view with more knowledge when list knowledge so many

api/apps/sdk/dataset.py, api/apps/sdk/doc.py, api/utils/api_utils.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
=> Fix: validation of readonly fields.

agent/component/base.py, agent/component/retrieval.py, deepdoc/parser/pdf_parser.py, rag/app/naive.py
=> Fix: retrieval debug mode issue.

api/apps/llm_app.py
=> Refa: refine the error message.

rag/nlp/search.py
=> Refa: fix re-rank scope.

sdk/python/test/test_http_api/test_dataset_mangement/test_list_dataset.py
fix function is_sort() usage error
=> Test: fix expected value validation for list dataset endpoint

sdk/python/test/test_http_api/test_file_management_within_dataset/test_list_document.py
cover [list documents](https://ragflow.io/docs/dev/http_api_reference#list-documents) endpoints
=> Test: Added test cases for List Documents HTTP API
