infiniflow/ragflow

sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
=> Test: update test cases per pr #6144

deepdoc/parser/pdf_parser.py, deepdoc/vision/ocr.py, deepdoc/vision/t_ocr.py, rag/app/naive.py, rag/settings.py, rag/svr/task_executor.py
=> Refa: PARALLEL_DEVICES is a static parameter.

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py
cover [delete documents](https://ragflow.io/docs/dev/http_api_reference#delete-documents) endpoints
=> Test: Added test cases for Delete Documents HTTP API

agent/canvas.py
=> Fix: none item while concating df.

rag/llm/chat_model.py
=> Fix: in case response.choices[0].message.content is None.

agent/canvas.py
=> Fix: NaN data error.

api/apps/sdk/doc.py
=> Fix: doc deletion failure with invalid docid.

docs/references/http_api_reference.md
=> Docs: remove max tokens.

docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py
=> Docs: rm max token

graphrag/search.py, rag/app/qa.py, rag/nlp/search.py, rag/utils/__init__.py, rag/utils/es_conn.py
=> Fix: float transfer exception.

api/apps/sdk/doc.py, rag/llm/chat_model.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py
=> Fix: enable ollama api-key.

api/apps/sdk/doc.py, api/apps/sdk/session.py
=> Fix: miss url path.

web/package-lock.json, web/package.json, web/src/components/ui/accordion.tsx, web/src/components/ui/tree-view.tsx
Feat: Add TreeView component #3221
=> Feat: Add TreeView component #3221

rag/nlp/search.py, rag/utils/__init__.py
=> Fix: rank feat issue.

web/src/components/ui/transfer-list.tsx, web/src/interfaces/database/user-setting.ts
Feat: Alter TransferList props #3221
=> Feat: Alter TransferList props #3221

rag/nlp/__init__.py
=> Feat: text file support position retaining.

agent/component/retrieval.py
=> Fix: empty retrieval kb ids.

sdk/python/test/libs/utils/__init__.py, sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_dataset_mangement/test_delete_dataset.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_parse_documents.py
cover [parse documents](https://ragflow.io/docs/dev/http_api_reference#parse-documents) endpoints
=> Test: Added test cases for Parse Documents HTTP API

agent/canvas.py, agent/component/retrieval.py
=> Fix: Nan issue.

api/utils/api_utils.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
Fix #5719 
Add data type validation for parser_config
=> Fix: #5719 Added type check for parser_config

rag/utils/es_conn.py
=> Fix: tag_feas deletion error.

rag/utils/__init__.py
=> Fix: type violations.

api/apps/sdk/doc.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_parse_documents.py
=> Fix: let parsing continue.

rag/llm/__init__.py, rag/llm/tts_model.py
=> Feat: add TTS support for SILICONFLOW.

agent/component/retrieval.py
=> Fix: Nan response for retrieval component.

api/apps/sdk/dataset.py, api/apps/sdk/doc.py, rag/llm/__init__.py, rag/llm/tts_model.py, sdk/python/test/test_http_api/test_dataset_mangement/test_delete_dataset.py
=> Fix: remove dup ids for APIs.

api/db/db_models.py
=> Fix: long api key issue.

api/apps/canvas_app.py, api/db/db_models.py, api/db/services/user_canvas_version.py, docker/docker-compose.yml, web/src/hooks/flow-hooks.ts, web/src/locales/en.ts, web/src/pages/flow/canvas/index.tsx, web/src/pages/flow/header/index.tsx, web/src/pages/flow/history-version-modal/index.tsx, web/src/services/flow-service.ts, web/src/utils/api.ts
Add history version save
- Allows users to view and download agent files by version revision history
=> Feat: support agent version history.

web/src/components/ui/tree-view.tsx
Feat: Alter TreeView component #3221
=> Feat: Alter TreeView component #3221

agent/component/switch.py
=> Fix: switch follow interact issue.

rag/svr/task_executor.py, rag/utils/redis_conn.py
Fix get_unacked_iterator. Close #6132
=> Fix get_unacked_iterator

docs/guides/dataset/accelerate_doc_indexing.mdx
The word is written incorrectly
=> Docs: Update accelerate_doc_indexing.mdx

web/src/pages/chat/hooks.ts
Fix: In the Agent's workflow, the input content cannot be wrapped, and \n will not work, otherwise an error will be reported #6241
=> Fix: In the Agent's workflow, the input content cannot be wrapped, and \n will not work, otherwise an error will be reported #6241

deepdoc/parser/figure_parser.py, deepdoc/parser/pdf_parser.py, rag/app/naive.py, rag/app/picture.py, rag/prompts.py
Add VLM-boosted PDF parser if VLM is set.
=> Feat: add VLM-boosted PDF parser

rag/app/naive.py
Add fallback for PDF figure parser
=> Feat: add fallback for PDF figure parser

deepdoc/parser/figure_parser.py, rag/app/naive.py
=> Feat: add VLM-boosted DocX parser

sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
Skip unstable 'stop parse documents' test cases
=> Test: Skip unstable 'stop parse documents' test cases

rag/llm/rerank_model.py
=> Fix: rerank with vllm issue.

web/src/pages/flow/form/invoke-form/dynamic-variables.tsx
=> Fix: type import

api/ragflow_server.py, rag/utils/redis_conn.py
=> Fix update_progress

.github/workflows/tests.yml, pyproject.toml
Unify Ruff config and enable async checks (ASYNC, TRIO)
=> Chore: unify Ruff config and enable async checks (ASYNC, TRIO)

api/db/services/common_service.py
Fix: Optimized the get_by_id method to resolve the issue of missing exceptions and improve query performance
Optimized the get_by_id method to resolve the issue of missing exceptions and improve query performance.
Optimization details:
1. The original method used a custom query method that required concatenating SQL, which impacted performance.
2. The query method returned a list, which needed to be accessed by index, posing a risk of index out-of-bounds errors.
3. The original method used except Exception to catch all errors, which is not a best practice in Python programming and may lead to missing exceptions. The get_or_none method accurately catches DoesNotExist errors while allowing other errors to be raised normally.
=> Fix: Optimized the get_by_id method to resolve the issue of missing exceptions and improve query performance

agent/component/template.py
=> Fix: let quot stay.

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/question.yml
=> Refa: refine template.

rag/llm/rerank_model.py, rag/svr/task_executor.py
=> Fix: huggingface rerank model issue.

graphrag/entity_resolution.py
=> Refa: control the simi for entity resolution.

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md
=> Fix broken discord invitation links

api/apps/sdk/doc.py
=> Fix: add_chunk api, empty content issue

web/src/locales/zh.ts
Add the Chinese translation of 'noMoreData' on the flow list page
=> Fix: flow list translate to zh

graphrag/general/extractor.py
=> Fix: miss calculate of token number.

rag/app/naive.py
Adds hierarchical title path tracking for tables in DOCX documents to improve context association. Previously, extracted tables lacked positional context within document structure.
=> Feat:  Adds hierarchical title path tracking for tables in DOCX documents to improve context association

api/apps/sdk/doc.py
=> Fix: add chunk, empty question issue.

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_download_document.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py
cover [add chunk](https://ragflow.io/docs/v0.17.2/http_api_reference#add-chunk) endpoints
=> Test: Added test cases for Add Chunk HTTP API

rag/llm/rerank_model.py
Fix rerank with YoudaoRerank issue，"'YoudaoRerank' object has no attribute '_dynamic_batch_size'"
=> Fix: rerank with YoudaoRerank issue.

rag/app/tag.py, rag/nlp/search.py
=> Fix: point in tag issue.

web/tailwind.css
Feat: Add background-core-standard to tailwind.css #3221
=> Feat: Add background-core-standard to tailwind.css #3221

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_dataset_mangement/test_delete_dataset.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_parse_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
=> Test: Update test cases for PR #6194 #6259 #6376

conf/llm_factories.json, rag/llm/__init__.py, rag/llm/chat_model.py, rag/llm/cv_model.py
=> Refa: update Anthropic models.

sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py
=> Test: Update test case for #6081

api/apps/langfuse_app.py, api/db/db_models.py, api/db/services/dialog_service.py, api/db/services/langfuse_service.py, api/db/services/llm_service.py, pyproject.toml, uv.lock
#6155
Add basic Langfuse support for LLM module.
A trace example:
=> Feat: add basic Langfuse support for LLM module

rag/llm/embedding_model.py, rag/llm/tts_model.py
=> Feat: support api-key for Ollama.

api/apps/langfuse_app.py, api/db/db_models.py, api/db/services/langfuse_service.py
=> Feat: add Langfuse APIs

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/conftest.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/conftest.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py, sdk/python/test/test_http_api/test_dataset_mangement/conftest.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py, sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py, sdk/python/test/test_http_api/test_dataset_mangement/test_list_datasets.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py, sdk/python/test/test_http_api/test_file_management_within_dataset/conftest.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_download_document.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_list_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_parse_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_upload_documents.py
=> Test: Update test cases to reduce execution time

api/apps/conversation_app.py, docs/references/http_api_reference.md
Enhance the prompt of `related_question` API.
=> Refa: enhancement: enhance the prompt of related_question API

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py
Add list chunk checkpoint for the add chunk API
=> Test: Add list chunk checkpoint for the add chunk API

api/apps/langfuse_app.py
Enhance Langfuse API: add project_id and project_name
=> Feat: add project_id and project_name to Langfuse API

rag/llm/chat_model.py
=> Fix: claude max tokens.

api/apps/sdk/chat.py
=> Fix: remove doc status checking while creating an assistant.

rag/llm/rerank_model.py
=> Fix: api-key issue for xinference.

api/apps/sdk/doc.py
=> Fix: img_id errror.

api/db/services/llm_service.py
=> Fix: describe parameter error.

api/apps/file2document_app.py
=> Fix: link to KB from filemanager.

api/apps/llm_app.py
=> Fix: Hunyuan model adding error.

rag/llm/chat_model.py
=> Fix: Bedrock model invocation error.

api/apps/sdk/doc.py
=> Fix: image_id is None.

rag/llm/__init__.py, rag/llm/cv_model.py, rag/nlp/search.py
=> Fix: uploading in chat box issue.

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
cover [update chunk](https://ragflow.io/docs/v0.17.2/http_api_reference#update-chunk) endpoints
=> Test: Added test cases for Update Chunk HTTP API

api/db/db_models.py, conf/llm_factories.json
=> Feat: add "tools" to llm_factories.json

docs/faq.mdx, docs/guides/agent/agent_component_reference/generate.mdx, docs/quickstart.mdx, docs/references/http_api_reference.md
=> AI search vs. chat

api/apps/sdk/session.py, api/db/services/llm_service.py, rag/llm/chat_model.py
Change LLM chat output from full to delta (incremental)
=> Refa: change LLM chat output from full to delta (incremental)

graphrag/general/index.py
=> Rename graphrag task lock

api/db/services/document_service.py
=> Fix: team doc deletion issue.

api/apps/kb_app.py, graphrag/utils.py
Introduced delete_knowledge_graph
=> Introduced delete_knowledge_graph

rag/nlp/query.py, rag/nlp/search.py
=> Refa: token similarity calculations.

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/conftest.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
=> Test: Added test cases for Delete Chunks HTTP API

web/package-lock.json, web/package.json, web/src/components/ui/radio-group.tsx
Feat: Add RadioGroup component #3221
=> Feat: Add RadioGroup component #3221

api/apps/sdk/doc.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
=> Fix: HTTP API delete_chunks issue.

graphrag/general/graph_extractor.py
Fix entity_types. Close #6287 and #6608
=> Fix entity_types. Close #6287 and #6608

docs/references/python_api_reference.md
=> Docs: fix retrieval docs.

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
cover [retrieval chunk](https://ragflow.io/docs/v0.17.2/http_api_reference#retrieve-chunks) endpoints
=> Test: Added test cases for Retrieval Chunks HTTP API

api/db/db_models.py
Fix #6334
Hello, I encountered the same problem in #6334. In the `api/db/db_models.py`, it calls `obj.create_table()` unconditionally in `init_database_tables`, before the `migrate_db()`. Specially for the `permission` field of `user_canvas` table, it has `index=True`, which causes `peewee` to issue a SQL trying to create the index when the field does not exist (the `user_canvas` table already exists), so `psycopg2.errors.UndefinedColumn: column "permission" does not exist` occurred.
I've added a judgement in the code, to only call `create_table()` when the table does not exist, delegate the migration process to `migrate_db()`.
Then another problem occurs: the `migrate_db()` actually does nothing because it failed on the first migration! The `playhouse` blindly issue DDLs without things …
=> Fix table migration on non-exist-yet indexed columns.

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md
=> Update broken discord

agent/component/retrieval.py
=> Refa: add meta data to retrieval.

agent/component/base.py
=> add type canvas

Dockerfile, api/apps/sdk/dataset.py, conf/llm_factories.json, docker/README.md, docs/configurations.md, download_deps.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
=> Refa: remove default build-in rerank model.

rag/llm/__init__.py, rag/llm/chat_model.py, rag/llm/cv_model.py, rag/llm/embedding_model.py, rag/llm/sequence2txt_model.py, rag/llm/tts_model.py
https://github.com/infiniflow/ragflow/issues/6138
This PR is going to support vision llm for gpustack, modify url path from `/v1-openai` to `/v1`
=> Feat: support vision llm for gpustack

docker/.env
=> Refa: docker/.env comment refinement.

agent/component/email.py
=> Fix: `Email` error.

conf/llm_factories.json
=> Feat: add qwq-plus-latest

web/src/components/operate-dropdown/index.tsx, web/src/interfaces/database/knowledge.ts, web/src/interfaces/database/llm.ts, web/src/pages/user-setting/setting-model/system-model-setting-modal/index.tsx
Feat: Allows users to search for models in the model selection drop-down box #3221
=> Feat: Allows users to search for models in the model selection drop-down box #3221

web/src/components/message-input/index.tsx, web/src/hooks/logic-hooks.ts, web/src/pages/chat/chat-container/index.tsx, web/src/pages/chat/hooks.ts, web/src/pages/chat/share/large.tsx, web/src/pages/chat/shared-hooks.ts, web/src/pages/flow/chat/box.tsx, web/src/pages/flow/chat/hooks.ts, web/src/pages/search/hooks.ts, web/src/pages/search/index.less, web/src/pages/search/index.tsx
Feat: Interrupt streaming #6515
=> Feat: Interrupt streaming #6515

web/src/layouts/components/right-toolbar/index.tsx
Feat: Add a notification logic to the team member invite feature #6610
=> Feat: Add a notification logic to the team member invite feature #6610

sdk/python/test/conftest.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
=> Test: Skip test case for PR 6443

web/src/components/chunk-method-modal/index.tsx, web/src/components/parse-configuration/graph-rag-items.tsx, web/src/hooks/knowledge-hooks.ts, web/src/pages/add-knowledge/components/knowledge-graph/index.tsx, web/src/pages/add-knowledge/components/knowledge-graph/use-delete-graph.ts, web/src/services/knowledge-service.ts
Feat: Support deleting knowledge graph #6747
=> Feat: Support deleting knowledge graph #6747

web/src/components/message-input/index.tsx, web/src/pages/chat/markdown-content/index.tsx, web/src/pages/chat/utils.ts
Fix: Using the Enter key does not send a complete message #6754
=> Fix: Using the Enter key does not send a complete message #6754

web/src/hooks/document-hooks.ts
Fix: The file upload prompt indicates "No authorization." #6516
=> Fix: The file upload prompt indicates "No authorization." #6516

web/src/pages/chat/markdown-content/index.tsx
Fix: Issue with Markdown Code Blocks Breaking Frontend Layout #5789
=> Fix: Issue with Markdown Code Blocks Breaking Frontend Layout #5789

graphrag/general/extractor.py, graphrag/general/graph_extractor.py, graphrag/general/index.py, rag/llm/chat_model.py, rag/utils/redis_conn.py
=> Log llm response on exception

sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py
Update test cases for PR #6643 issue #6607
=> Test: Update test cases for PR #6643

docs/references/http_api_reference.md
=> Docs: Fix for issue #6713

conf/llm_factories.json
=> Feat: add gemini-2.5-pro-exp-03-25

graphrag/general/index.py, graphrag/utils.py, rag/utils/redis_conn.py
Fix set_graph on non-existing edge
=> Fix set_graph on non-existing edge

api/db/services/dialog_service.py
=> Refa: copywriting refinement.

sdk/python/test/test_http_api/test_chat_assistant_management/conftest.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_list_chat_assistants.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/conftest.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_parse_documents.py
cover [list chat assistant](https://ragflow.io/docs/v0.17.2/http_api_reference#list-chat-assistants) endpoints
=> Test: Added test cases for List Chat Assistants HTTP API

api/apps/sdk/doc.py
fix issue #6539, refer to pr #6405
=> Fix: update chunk, empty question issue.

web/src/hooks/chat-hooks.ts, web/src/pages/chat/hooks.ts
Feat: Load the dialog page, prohibit calling the dialog/get interface #6798
=> Feat: Load the dialog page, prohibit calling the dialog/get interface #6798

deepdoc/vision/table_structure_recognizer.py
=> Refa:  trival.

sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py
update test case for PR #6800 issue #6539
=> Test: Update test cases for #6800

docs/configurations.md, docs/faq.mdx, docs/guides/agent/agent_component_reference/begin.mdx, docs/guides/chat/start_chat.md, docs/guides/models/deploy_local_llm.mdx, docs/guides/team/join_or_leave_team.md, docs/guides/team/manage_team_members.md, docs/references/http_api_reference.md, web/src/locales/de.ts, web/src/locales/en.ts, web/src/locales/es.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
=> Miscellaneous editorial updates

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md
=> Update broken discord link

graphrag/general/index.py
[When parsing documents with graph, an error occurred:[ERROR][Exception]: 'method']
(https://github.com/infiniflow/ragflow/issues/6835)
Close #6786
=> Fix:When parsing documents with graph, an error occurred:[ERROR][Exception]: 'method'

rag/app/naive.py
=> Fix: docx image exceptions.

sdk/python/test/test_http_api/test_chat_assistant_management/conftest.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py
cover [update chat assistant](https://ragflow.io/docs/v0.17.2/http_api_reference#update-chat-assistant) endpoints
=> Test: Added test cases for Update Chat Assistant HTTP API

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py, sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py
cover [delete chat assistants](https://ragflow.io/docs/dev/http_api_reference#delete-chat-assistants) endpoints
=> Test: Added test cases for Delete Chat Assistants HTTP API

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/conftest.py, sdk/python/test/test_http_api/test_chat_assistant_management/conftest.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_list_chat_assistants.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py, sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py, sdk/python/test/test_http_api/test_dataset_mangement/test_list_datasets.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_download_document.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_list_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_upload_documents.py, sdk/python/test/test_http_api/test_session_management/test_create_session_with_chat_assistant.py
cover [create session with chat assistant](https://ragflow.io/docs/dev/http_api_reference#create-session-with-chat-assistant) endpoints
=> Test: Added test cases for Create Session With Chat Assistant HTTP API

api/apps/sdk/chat.py, api/apps/sdk/session.py
resolve this issue：https://github.com/infiniflow/ragflow/issues/6876
=> Fix delete duplicate assistant

rag/llm/chat_model.py
Fix: local variable referenced before assignment. #6803
=> Fix: local variable referenced before assignment

api/apps/sdk/chat.py, deepdoc/vision/layout_recognizer.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
=> Fix: assistant deleteion issue.

sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
=> Test: Update test cases for PR 6906

web/src/locales/de.ts, web/src/locales/en.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/agent/form/generate-form/index.tsx, web/src/pages/flow/form/generate-form/index.tsx
Feat: Add translation text to the prompt word of the generate operator to distinguish it from the prompt word of the knowledge base #6934
=> Feat: Add translation text to the prompt word of the generate operator to distinguish it from the prompt word of the knowledge base #6934

web/src/components/message-input/index.less, web/src/components/message-input/index.tsx, web/src/locales/en.ts, web/src/pages/chat/chat-configuration-modal/index.tsx
Fix: In the dark night theme, the message input box is not displayed correctly. #6950
=> Fix: In the dark night theme, the message input box is not displayed correctly. #6950

sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py
=> Test: Update test cases for PR 6906 ISSUE 6875

api/db/init_data.py, api/db/services/knowledgebase_service.py
Fix KB update_time changed whenever system relaunched. #6953
=> Fix: KB update_time changed whenever system relaunched

web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
Fix: Fix api page translation issue. #3221
=> Fix: Fix api page translation issue. #3221

api/ragflow_server.py
Fix update_progress issue introduced by #6975
=> Fix update_progress issue

web/src/hooks/document-hooks.ts, web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx
Feat: Remove the rotation state of the button that parses the document #7008
=> Feat: Remove the rotation state of the button that parses the document #7008

conf/llm_factories.json
=> Refa: update llms

helm/templates/ingress.yaml
Fix Helm Ingress template; Trying to access a global variable within a loop 
Fix #6191
=> Fix Helm Ingress template

api/db/services/dialog_service.py, rag/prompts.py
Add fallback for bad citation output. #6948
=> Fix: add fallback for bad citation output

sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_session_management/test_delete_sessions_with_chat_assistant.py
cover [Delete chat assistant's sessions](https://ragflow.io/docs/dev/http_api_reference#delete-chat-assistants-sessions) endpoints
=> Test: Added test cases for Delete Sessions With Chat Assistant HTTP API

docs/references/http_api_reference.md
docs(api): Fix request method in Related Questions example (DELETE→POST)
=> Docs: Change DELETE to POST in Related Questions curl example

web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-file/document-toolbar.tsx, web/src/pages/add-knowledge/components/knowledge-file/hooks.ts, web/src/pages/add-knowledge/components/knowledge-file/index.tsx
Fix: Files being parsed are not allowed to be deleted in batches #7065
=> Fix: Files being parsed are not allowed to be deleted in batches #7065

web/src/components/rerank.tsx, web/src/components/similarity-slider/index.tsx, web/src/components/switch-fom-field.tsx, web/src/components/use-knowledge-graph-item.tsx, web/src/hooks/use-knowledge-request.ts, web/src/interfaces/request/knowledge.ts, web/src/pages/dataset/sidebar/index.tsx, web/src/pages/dataset/testing/testing-form.tsx
=> Feat: Retrieval test #3221

graphrag/general/index.py
https://github.com/infiniflow/ragflow/issues/7053
=> Fix: handle sometimes graph index will miss explanation

rag/app/table.py
… bytes-like object
fix bug #6990 internal server error ehile chunking:expected string or bytes-like object
=> fix bug  chunking:expected string or bytes-like object 

web/src/hooks/use-knowledge-request.ts, web/src/interfaces/database/knowledge.ts, web/src/pages/dataset/testing/index.tsx, web/src/pages/dataset/testing/testing-form.tsx
Feat: Rendering a search test list with real data #3221
=> Feat: Rendering a search test list with real data #3221

agent/component/base.py, agent/component/generate.py, agent/component/retrieval.py
=> Fix: cite disfunction for G component.

docs/guides/mcp.md
=> Docs: MCP server

Dockerfile, docker/.env, docker/docker-compose.yml, docker/entrypoint.sh, mcp/client/client.py, mcp/server/server.py, pyproject.toml, uv.lock
Add MCP support with a client example.
Issue link: #4344
=> Feat: mcp server

docs/develop/mcp.md
Add mcp self-host mode documentation, a complement of #7141.
=> Docs: add mcp self-host mode

docker/docker-compose.yml, docker/entrypoint.sh, mcp/client/client.py, mcp/server/server.py
Add mcp self-host mode, a complement of #7084.
=> Feat: add mcp self-host mode

web/src/components/ui/dropdown-menu.tsx, web/src/hooks/knowledge-hooks.ts, web/src/pages/datasets/dataset-creating-dialog.tsx, web/src/pages/datasets/dataset-dropdown.tsx, web/src/pages/datasets/hooks.ts, web/src/pages/datasets/index.tsx, web/src/pages/datasets/use-rename-dataset.ts, web/tailwind.config.js, web/tailwind.css
=> Feat: Rename a dataset #3221

graphrag/search.py
=> Fix: KG search issue.

web/src/components/api-service/chat-overview-modal/api-content.tsx, web/src/components/api-service/chat-overview-modal/markdown-toc.tsx, web/src/pages/user-setting/setting-model/index.tsx
Feat: Move langfuse configuration to api page #6155
=> Feat: Move langfuse configuration to api page #6155

rag/nlp/search.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
Fix retrieval testing wrong pagination. #7171
=> Fix: fix retrieval tesing wrong pagination

web/src/components/chunk-method-modal/index.tsx, web/src/interfaces/database/knowledge.ts
Fix: Knowledge Graph Extraction Conflict Between Dataset-Level and File-Specific Configurations #7198
=> Fix: Knowledge Graph Extraction Conflict Between Dataset-Level and File-Specific Configurations #7198

web/src/pages/add-knowledge/components/knowledge-setting/configuration/common-item.tsx
Feat: Even if the knowledge base has slices, the chunk method can be changed  #7115
=> Feat: Even if the knowledge base has slices, the chunk method can be changed  #7115

web/src/pages/datasets/index.tsx, web/src/pages/datasets/use-display-owner.ts
Feat: Show the owner of this knowledge base on the list card. #3221
=> Feat: Show the owner of this knowledge base on the list card. #3221

api/apps/kb_app.py, api/db/services/knowledgebase_service.py, sdk/python/test/test_frontend_api/common.py
Enhance capability of `list_kbs`.
Breaking change: change method from `GET` to `POST`.
=> [BREAKING CHANGE] GET to POST: enhance kb list capability

docs/guides/dataset/construct_knowledge_graph.md, docs/guides/dataset/enable_raptor.md
=> Added a RAPTOR guide

web/src/components/confirm-delete-dialog.tsx, web/src/components/file-upload-dialog/index.tsx, web/src/components/list-filter-bar.tsx, web/src/hooks/use-document-request.ts, web/src/hooks/use-file-request.ts, web/src/pages/dataset/dataset/hooks.ts, web/src/pages/dataset/dataset/index.tsx, web/src/pages/dataset/dataset/use-upload-document.ts, web/src/pages/datasets/dataset-card.tsx, web/src/pages/datasets/dataset-dropdown.tsx, web/src/pages/datasets/index.tsx, web/src/pages/files/hooks.ts, web/src/pages/files/index.tsx, web/src/pages/files/use-upload-file.ts, web/src/pages/home/datasets.tsx
=> Feat: Upload document #3221

docs/guides/dataset/enable_raptor.md, docs/release_notes.md
=> v0.18.0 release notes

docs/develop/mcp.md, docs/guides/agent/agent_component_reference/begin.mdx, docs/release_notes.md
=> Updated v0.18.0 release notes

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docker/.env, docker/README.md, docs/configurations.md, docs/develop/build_docker_image.mdx, docs/develop/mcp.md, docs/faq.mdx, docs/guides/chat/start_chat.md, docs/guides/dataset/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, helm/values.yaml, pyproject.toml, sdk/python/pyproject.toml, sdk/python/uv.lock, uv.lock
=> Docs: update for v0.18.0

web/src/components/list-filter-bar.tsx, web/src/components/ui/single-tree-select.tsx, web/src/hooks/logic-hooks/navigate-hooks.ts, web/src/hooks/use-file-request.ts, web/src/pages/agents/index.tsx, web/src/pages/dataset/dataset/index.tsx, web/src/pages/datasets/index.tsx, web/src/pages/files/action-cell.tsx, web/src/pages/files/create-folder-dialog/create-folder-form.tsx, web/src/pages/files/create-folder-dialog/index.tsx, web/src/pages/files/file-breadcrumb.tsx, web/src/pages/files/files-table.tsx, web/src/pages/files/hooks.ts, web/src/pages/files/index.tsx, web/src/pages/files/move-dialog.tsx, web/src/pages/files/use-create-folder.ts, web/src/pages/files/use-move-file.ts, web/src/pages/files/use-navigate-to-folder.ts, web/src/pages/next-chats/index.tsx, web/src/pages/next-searches/index.tsx
=> Feat: Create a folder #3221

web/src/components/bulk-operate-bar.tsx, web/src/components/confirm-delete-dialog.tsx, web/src/hooks/use-file-request.ts, web/src/interfaces/database/file-manager.ts, web/src/pages/dataset/dataset/index.tsx, web/src/pages/dataset/dataset/use-bulk-operate-dataset.tsx, web/src/pages/datasets/index.tsx, web/src/pages/files/action-cell.tsx, web/src/pages/files/files-table.tsx, web/src/pages/files/hooks.ts, web/src/pages/files/index.tsx, web/src/pages/files/use-bulk-operate-file.tsx, web/src/pages/files/use-delete-file.ts, web/src/pages/files/use-move-file.ts
Feat: Deleting files in batches. #3221
=> Feat: Deleting files in batches. #3221

.pre-commit-config.yaml, README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md
Sometimes after we commit the code and open the PR the CI pipeline fails in Ruff checks. Including a pre-commit we can identify this problem early and avoid time loss.
=> chore: adds pre-commit

agent/component/exesql.py, agent/component/generate.py, agent/component/keyword.py, agentic_reasoning/deep_research.py, api/db/services/dialog_service.py, graphrag/general/extractor.py, rag/prompts.py, rag/raptor.py
Some models force thinking, resulting in the absence of the think tag in the returned content
=> <think> tag is missing.

rag/svr/task_executor.py
The lock is not released correctly when task_exectuor is abnormal
=> fix: task_executor bug fix

web/package-lock.json, web/package.json, web/src/components/confirm-delete-dialog.tsx, web/src/components/ui/hover-card.tsx, web/src/hooks/use-document-request.ts, web/src/pages/dataset/dataset/constant.ts, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/dataset/hooks.ts, web/src/pages/dataset/dataset/index.tsx, web/src/pages/dataset/dataset/parsing-card.tsx, web/src/pages/dataset/dataset/parsing-status-cell.tsx, web/src/pages/dataset/dataset/use-dataset-table-columns.tsx, web/src/pages/dataset/dataset/use-run-document.ts, web/src/pages/dataset/dataset/utils.ts
Feat: Display document parsing status #3221
=> Feat: Display document parsing status #3221

web/src/components/rename-dialog/index.tsx, web/src/components/rename-dialog/rename-form.tsx, web/src/hooks/use-document-request.ts, web/src/pages/dataset/dataset/dataset-action-cell.tsx, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/dataset/hooks.ts, web/src/pages/dataset/dataset/parsing-status-cell.tsx, web/src/pages/dataset/dataset/use-dataset-table-columns.tsx, web/src/pages/dataset/dataset/use-rename-document.ts
Feat: Delete and rename files in the knowledge base #3221
=> Feat: Delete and rename files in the knowledge base #3221

rag/llm/chat_model.py
Fix Qwen-vl-* url error. #7277
=> Fix: Qwen-vl-plus url error

docker/.env, docs/guides/team/join_or_leave_team.md, docs/guides/team/manage_team_members.md, docs/guides/team/share_agents.md, docs/guides/team/share_knowledge_bases.md, docs/guides/team/share_model.md, docs/release_notes.md
=> Doc: Updated sharing behavior in the open-source editions.

web/src/components/auto-keywords-form-field.tsx, web/src/components/chunk-method-dialog/index.tsx, web/src/components/delimiter-form-field.tsx, web/src/components/entity-types-form-field.tsx, web/src/components/excel-to-html-form-field.tsx, web/src/components/layout-recognize-form-field.tsx, web/src/components/max-token-number-from-field.tsx, web/src/components/parse-configuration/graph-rag-form-fields.tsx, web/src/components/parse-configuration/raptor-form-fields.tsx, web/src/components/slider-input-form-field.tsx, web/src/components/ui/select.tsx, web/src/hooks/use-document-request.ts, web/src/hooks/use-knowledge-request.ts, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/dataset/hooks.ts, web/src/pages/dataset/dataset/parsing-status-cell.tsx, web/src/pages/dataset/dataset/use-change-document-parser.ts, web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
Feat: Display the document configuration dialog with shadcn #3221
=> Feat: Display the document configuration dialog with shadcn #3221

rag/prompts.py
=> Fix: LLM generated tag issue.

web/src/components/chunk-method-dialog/dynamic-page-range.tsx, web/src/components/chunk-method-dialog/index.tsx, web/src/components/chunk-method-dialog/use-default-parser-values.ts, web/src/components/delimiter-form-field.tsx, web/src/components/file-upload-dialog/index.tsx, web/src/components/parse-configuration/raptor-form-fields.tsx, web/src/pages/dataset/dataset/parsing-status-cell.tsx, web/src/pages/dataset/dataset/use-change-document-parser.ts, web/src/pages/dataset/dataset/use-dataset-table-columns.tsx
Feat: Save the configuration information of the knowledge base document #3221
=> Feat: Save the configuration information of the knowledge base document #3221

web/src/components/chunk-method-dialog/index.tsx, web/src/hooks/use-document-request.ts, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/dataset/parsing-status-cell.tsx, web/src/pages/dataset/dataset/set-meta-dialog.tsx, web/src/pages/dataset/dataset/use-dataset-table-columns.tsx, web/src/pages/dataset/dataset/use-save-meta.ts, web/src/pages/dataset/sidebar/index.tsx
Feat: Save document metadata #3221
=> Feat: Save document metadata #3221

web/src/components/chunk-method-dialog/index.tsx, web/src/components/list-filter-bar/filter-popover.tsx, web/src/components/list-filter-bar/index.tsx, web/src/components/list-filter-bar/interface.ts, web/src/components/list-filter-bar/use-handle-filter-submit.ts, web/src/components/parse-configuration/raptor-form-fields.tsx, web/src/hooks/document-hooks.ts, web/src/hooks/use-document-request.ts, web/src/hooks/use-knowledge-request.ts, web/src/interfaces/request/knowledge.ts, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/dataset/index.tsx, web/src/pages/dataset/dataset/use-select-filters.ts, web/src/pages/datasets/index.tsx, web/src/pages/datasets/use-select-owners.ts, web/src/services/knowledge-service.ts, web/src/utils/dataset-util.ts
Feat: Filter document by running status and file type. #3221
=> Feat: Filter document by running status and file type. #3221

web/src/components/rename-dialog/index.tsx, web/src/hooks/use-document-request.ts, web/src/pages/dataset/dataset/dataset-action-cell.tsx, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/dataset/hooks.ts, web/src/pages/dataset/dataset/index.tsx, web/src/pages/dataset/dataset/use-create-empty-document.ts, web/src/pages/dataset/dataset/use-dataset-table-columns.tsx, web/src/pages/dataset/sidebar/index.tsx, web/tailwind.css
Feat: Create empty document. #3221
=> Feat: Create empty document. #3221

api/apps/api_app.py, api/apps/document_app.py, api/db/__init__.py, api/db/services/document_service.py, api/db/services/knowledgebase_service.py, sdk/python/test/test_frontend_api/common.py
Enhance capability of `list_docs`.
Breaking change: change method from `GET` to `POST`.
=> [BREAKING CHANGE] GET to POST: enhance document list capability

web/src/pages/files/action-cell.tsx, web/src/pages/files/files-table.tsx, web/src/pages/files/knowledge-cell.tsx, web/src/pages/files/util.ts
=> Feat: Preview the file #3221

rag/app/picture.py
https://github.com/infiniflow/ragflow/issues/7362
append title_tks
=> Fix: Add title_tks for Pictures

docs/references/http_api_reference.md, docs/references/python_api_reference.md
=> Knowledge graph no longer exists as a chunking method

rag/nlp/query.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py
=> Refa: similarity calculations.

web/src/components/list-filter-bar/index.tsx, web/src/components/table-skeleton.tsx, web/src/components/ui/async-tree-select.tsx, web/src/components/ui/ragflow-pagination.tsx, web/src/components/ui/tooltip.tsx, web/src/hooks/logic-hooks/use-row-selection.ts, web/src/hooks/use-agent-request.ts, web/src/interfaces/database/flow.ts, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/dataset/index.tsx, web/src/pages/dataset/dataset/use-dataset-table-columns.tsx, web/src/pages/dataset/sidebar/index.tsx, web/src/pages/datasets/dataset-card.tsx, web/src/pages/datasets/index.tsx, web/src/pages/files/action-cell.tsx, web/src/pages/files/files-table.tsx, web/src/pages/files/index.tsx, web/src/pages/files/link-to-dataset-dialog.tsx, web/src/pages/files/use-bulk-operate-file.tsx, web/src/pages/files/use-move-file.ts, web/src/pages/home/agent-list.tsx, web/src/pages/home/application-card.tsx, web/src/pages/home/applications.tsx, web/src/pages/home/datasets.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Bind data to the agent module of the home page #3221
=> Feat: Bind data to the agent module of the home page #3221

agent/component/keyword.py
fixed missing list input ref in query
=> fixed missing list input ref in query

web/src/layouts/next-header.tsx, web/src/pages/datasets/dataset-card.tsx, web/src/pages/home/applications.tsx, web/src/pages/home/banner.tsx, web/src/pages/home/chat-list.tsx, web/src/pages/home/datasets.tsx, web/src/pages/home/index.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Adjust the style of the home page #3321
=> Feat: Adjust the style of the home page #3221

.github/workflows/tests.yml, api/apps/sdk/dataset.py, api/utils/api_utils.py, api/utils/validation_utils.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/pyproject.toml, sdk/python/ragflow_sdk/ragflow.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py, sdk/python/test/test_sdk_api/t_dataset.py, sdk/python/uv.lock
This PR introduces Pydantic-based validation for the create dataset HTTP API, improving code clarity and robustness. Key changes include:
1. Pydantic Validation
2. ​​Error Handling
3. Test Updates
4. Documentation
=> Refa: http API create dataset and test cases

web/src/components/ui/segmented.tsx, web/src/layouts/next-header.tsx, web/src/pages/datasets/dataset-card.tsx, web/src/pages/datasets/index.tsx, web/src/pages/home/applications.tsx, web/src/pages/home/banner.tsx, web/src/pages/home/datasets.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Modify the segmented component style #3221
=> Feat: Modify the segmented component style #3221

web/src/pages/add-knowledge/components/knowledge-file/index.tsx
https://github.com/infiniflow/ragflow/issues/5931
=> feat: dataset filter by parsing status

web/src/layouts/next-header.tsx, web/src/pages/add-knowledge/components/knowledge-file/index.tsx
Feat: Add a language switch drop-down box to the top navigation bar #3221
=> Feat: Add a language switch drop-down box to the top navigation bar #3221

conf/llm_factories.json
Qwen3 and more LLMs.
Close #7296
=> Feat: add Qwen3 and OpenAI o series

web/src/components/ragflow-avatar.tsx, web/src/components/ui/card.tsx, web/src/layouts/next-header.tsx, web/src/pages/add-knowledge/components/knowledge-file/index.tsx, web/src/pages/datasets/dataset-card.tsx, web/src/pages/home/application-card.tsx, web/src/pages/home/applications.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Modify background color of Card #3221
=> Feat: Modify background color of Card #3221

web/src/locales/de.ts, web/src/locales/en.ts, web/src/locales/es.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
=> DOC: Added a UI tip for document parsing

web/src/components/prompt-editor/variable-picker-plugin.tsx
filler list by user change input
=> Feat: filler list by user change input

api/db/services/llm_service.py
https://github.com/infiniflow/ragflow/issues/7407
Based on this context, I think there should be some reasons that let some LLMs have a mismatch (add the wrong "@xxx"),
So I think when use fid can not fetch llm then tried to just use name should can fetch it.
=> Fix: Tried to fix the fid mis match under some cases 

docs/faq.mdx, docs/guides/agent/agent_component_reference/generate.mdx
=> Built-in reranker models have been removed from official deliveries.

web/src/components/list-filter-bar/filter-popover.tsx, web/src/components/list-filter-bar/index.tsx, web/src/components/ui/button.tsx, web/src/components/ui/input.tsx, web/src/components/ui/pagination.tsx, web/src/components/ui/ragflow-pagination.tsx, web/src/components/ui/select.tsx, web/src/layouts/next-header.tsx, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/dataset/index.tsx, web/src/pages/datasets/dataset-creating-dialog.tsx, web/src/pages/datasets/index.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Modify the dataset list page style #3221
=> Feat: Modify the dataset list page style #3221

web/src/app.tsx, web/src/components/icon-font.tsx, web/src/components/ragflow-avatar.tsx, web/src/components/ui/switch.tsx, web/src/components/ui/table.tsx, web/src/constants/file.ts, web/src/global.less, web/src/interfaces/database/knowledge.ts, web/src/pages/dataset/dataset/dataset-table.tsx, web/src/pages/dataset/dataset/index.tsx, web/src/pages/dataset/dataset/use-dataset-table-columns.tsx, web/src/pages/dataset/sidebar/index.tsx, web/src/pages/files/files-table.tsx, web/src/pages/files/index.tsx, web/tailwind.config.js, web/tailwind.css
Feat:  Modify the style of the dataset page #3221
=> Feat:  Modify the style of the dataset page #3221

api/apps/document_app.py, api/db/services/document_service.py, api/db/services/knowledgebase_service.py
Fix `filed_map` was incorrectly persisted. #7412
=> Fix: filed_map was incorrectly persisted

docs/guides/models/deploy_local_llm.mdx
1. Use `host.docker.internal` as base URL
2. Fix numbers in list
3. Make clear what is the console input and what is the output
=> Fix instructions for Ollama

docs/guides/models/deploy_local_llm.mdx
=> Fix Ollama instructions

rag/llm/embedding_model.py
https://github.com/infiniflow/ragflow/issues/7420
=> Fix:Set CUDA_VISIBLE_DEVICES In DefaultEmbedding

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docker/launch_backend_service.sh, download_deps.py
Fix https://github.com/infiniflow/ragflow/issues/7224 and https://github.com/infiniflow/ragflow/issues/6793
=> fix(deps): incorrect nltk download dir

agent/component/base.py
fixed errror when vars of cnt begin  declare with key contain "begin"
=> fixed errror when vars of cnt begin  declare with key contain "begin"

api/apps/sdk/dataset.py, api/settings.py, api/utils/api_utils.py, api/utils/validation_utils.py, sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py
Optimize dataset validation and add function docs
=> refa: Optimize create dataset validation

deepdoc/parser/figure_parser.py
https://github.com/infiniflow/ragflow/issues/7466
I think due to some times we can not get position
=> Fix: Sometimes VisionFigureParser.figures may is tuple

api/db/services/dialog_service.py
=> Fix: chat solo issue.

docs/develop/mcp.md
=> docs: add API key instructions for MCP host mode

docs/develop/launch_mcp_server.md
=> Docs: minor format updates

agent/component/retrieval.py
=> Fix: retrieval component for shared KB issue.

docs/references/http_api_reference.md
Correct wrong URL for related_questions HTTP API. #7282
=> Docs: correct wrong URL for related_questions HTTP API

api/apps/api_app.py
https://github.com/infiniflow/ragflow/issues/7519
=> Feat: Add API to support get chunk by id

deepdoc/parser/pdf_parser.py
=> Refa: text order be robuster.

.github/workflows/tests.yml, sdk/python/pyproject.toml, sdk/python/test/conftest.py, sdk/python/test/test_http_api/conftest.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_list_chat_assistants.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py, sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py, sdk/python/test/test_http_api/test_dataset_mangement/test_list_datasets.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_delete_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_download_document.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_list_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_parse_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_upload_documents.py, sdk/python/test/test_http_api/test_session_management/test_create_session_with_chat_assistant.py, sdk/python/test/test_http_api/test_session_management/test_delete_sessions_with_chat_assistant.py, sdk/python/test/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py, sdk/python/test/test_http_api/test_session_management/test_update_session_with_chat_assistant.py
Configure test case priorities to reduce CI execution time
=> Test: Configure test case priorities to reduce CI execution time

docs/develop/launch_mcp_server.md, docs/release_notes.md
=> Updated MCP

web/src/locales/de.ts, web/src/locales/en.ts, web/src/locales/es.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
=> Docs: UI updates

web/src/components/chunk-method-dialog/index.tsx, web/src/components/file-upload-dialog/index.tsx, web/src/components/rename-dialog/index.tsx, web/src/components/ui/button.tsx, web/src/pages/dataset/dataset/set-meta-dialog.tsx, web/src/pages/files/link-to-dataset-dialog.tsx, web/src/pages/files/move-dialog.tsx
Feat: Replace the submit form button with ButtonLoading #3221
=> Feat: Replace the submit form button with ButtonLoading #3221

.github/workflows/tests.yml
Add scheduled workflow for daily HTTP API full tests
Configure cron job to trigger at 16:00:00Z(00:00:00+08:00)
=> CI: add daily test

api/apps/kb_app.py, api/db/services/document_service.py
Kb detail supports return document total size now.
=> Feat: KB detail supports document total size

api/apps/sdk/doc.py
=> Feat: add document enabled

web/src/components/cross-language-item.tsx, web/src/components/language-item.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/add-knowledge/components/knowledge-testing/testing-control/index.tsx, web/src/pages/chat/chat-configuration-modal/prompt-engine.tsx
Feat: Cross-language query #7376 #4503  #5710 #7470
=> Feat: Cross-language query #7376 #4503  #5710 #7470

rag/llm/chat_model.py, rag/llm/cv_model.py
=> Refa: remove ollama keep alive.

api/apps/sdk/dataset.py, api/utils/api_utils.py, api/utils/validation_utils.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/ragflow.py, sdk/python/test/libs/utils/hypothesis_utils.py, sdk/python/test/test_http_api/common.py, sdk/python/test/test_http_api/test_dataset_mangement/conftest.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
This PR introduces Pydantic-based validation for the update dataset HTTP API, improving code clarity and robustness. Key changes include:
1. Pydantic Validation
2. ​​Error Handling
3. Test Updates
4. Documentation Updates
5. fix bug: #5915
=> Refa: HTTP API update dataset / test cases / docs

sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py
Skip unstable test cases to ensure daily testing stability
=> Test: skip unstable test cases

docs/develop/mcp/_category_.json, docs/develop/mcp/launch_mcp_server.md, docs/develop/mcp/mcp_client_example.md, docs/develop/mcp/mcp_tools.md, docs/guides/dataset/construct_knowledge_graph.md, docs/release_notes.md
=> Docs: Restructured MCP-specific documents

docs/guides/tracing.mdx
As RAGFlow has an integration with Langfuse, this docs page shows how to configure Langfuse tracing.
=> docs: add langfuse documentation

api/apps/sdk/doc.py, sdk/python/ragflow_sdk/modules/document.py
=> Fix:Discrepancy between Document.list_chunks() API documentation and implementation

docs/develop/mcp/launch_mcp_server.md, docs/guides/agent/text2sql_agent.md, docs/guides/tracing.mdx
=> Docs:Updated langfuse guide

web/src/pages/flow/list/index.tsx
https://github.com/infiniflow/ragflow/issues/7538
=> Fix: InfiniteScroll sometimes can not fetch next page

conf/llm_factories.json
Adds support for the GPT-4.1 series from OpenAI.
=> Feat: add support for OpenAi gpt 4.1 series

api/apps/sdk/dataset.py, api/utils/validation_utils.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
Fix  HTTP API Create/Update dataset parser config default value error
=> Fix(api): correct default value handling in dataset parser config

web/src/components/chunk-method-dialog/dynamic-page-range.tsx, web/src/components/chunk-method-dialog/index.tsx, web/src/components/form-container.tsx, web/src/components/slider-input-form-field.tsx, web/src/components/ui/dual-range-slider.tsx, web/src/components/ui/form.tsx
Feat: Add FormContainer component #3221
=> Feat: Add FormContainer component #3221

conf/infinity_mapping.json, rag/app/manual.py, rag/app/picture.py, rag/app/presentation.py, rag/app/qa.py, rag/nlp/__init__.py, rag/nlp/search.py
=> Feat: add image preview to retrieval test.

docs/develop/mcp/launch_mcp_server.md, docs/guides/chat/best_practices/_category_.json, docs/guides/chat/best_practices/accelerate_question_answering.mdx, docs/guides/dataset/best_practices/_category_.json, docs/guides/dataset/best_practices/accelerate_doc_indexing.mdx, docs/guides/dataset/enable_excel2html.md
=> Docs: Restructured docs

web/src/components/chunk-method-dialog/dynamic-page-range.tsx, web/src/components/confirm-delete-dialog.tsx, web/src/hooks/use-chat-request.ts, web/src/pages/home/chat-list.tsx
Feat: Fixed the issue where the chat page would jump after entering the homepage #3221
=> Feat: Fixed the issue where the chat page would jump after entering the homepage #3221

agent/component/retrieval.py, api/apps/conversation_app.py, rag/prompts.py
=> Feat: let image citation being shown.

web/src/pages/chat/markdown-content/index.less, web/src/pages/chat/markdown-content/index.tsx
Feat: Show images in reply messages #7608
=> Feat: Show images in reply messages #7608

api/db/services/file_service.py
=> Fix: file name length limit mismtach

web/src/pages/knowledge/index.tsx
as https://github.com/infiniflow/ragflow/issues/7538
and https://github.com/infiniflow/ragflow/pull/7550
=> FIX:  knowledge will not render a paginator when count is greater than 30

rag/app/naive.py, rag/prompts.py
=> Fix: docx get image exception.

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md
=> Docs: update 7 readme

web/src/components/page-rank-form-field.tsx, web/src/components/parse-configuration/graph-rag-form-fields.tsx, web/src/pages/dataset/setting/category-panel.tsx, web/src/pages/dataset/setting/chunk-method-form.tsx, web/src/pages/dataset/setting/configuration/audio.tsx, web/src/pages/dataset/setting/configuration/book.tsx, web/src/pages/dataset/setting/configuration/common-item.tsx, web/src/pages/dataset/setting/configuration/email.tsx, web/src/pages/dataset/setting/configuration/knowledge-graph.tsx, web/src/pages/dataset/setting/configuration/laws.tsx, web/src/pages/dataset/setting/configuration/manual.tsx, web/src/pages/dataset/setting/configuration/naive.tsx, web/src/pages/dataset/setting/configuration/one.tsx, web/src/pages/dataset/setting/configuration/paper.tsx, web/src/pages/dataset/setting/configuration/picture.tsx, web/src/pages/dataset/setting/configuration/presentation.tsx, web/src/pages/dataset/setting/configuration/qa.tsx, web/src/pages/dataset/setting/configuration/resume.tsx, web/src/pages/dataset/setting/configuration/table.tsx, web/src/pages/dataset/setting/configuration/tag.tsx, web/src/pages/dataset/setting/general-form.tsx, web/src/pages/dataset/setting/hooks.ts, web/src/pages/dataset/setting/index.tsx, web/src/pages/dataset/setting/tag-item.tsx, web/src/pages/dataset/setting/tag-table/index.tsx, web/src/pages/dataset/setting/tag-table/rename-dialog/index.tsx, web/src/pages/dataset/setting/tag-table/rename-dialog/rename-form.tsx, web/src/pages/dataset/setting/tag-tabs.tsx, web/src/pages/dataset/setting/tag-word-cloud.tsx
Feat: Add data set configuration form #3221
=> Feat: Add data set configuration form #3221

docs/release_notes.md, web/src/locales/de.ts, web/src/locales/en.ts, web/src/locales/es.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
=> Docs: Chat assistant relative time expressions were enabled in 0.17.1.

web/src/pages/profile-setting/profile/index.tsx
Remove PII from webapp profile page input defaults
=> Fix: Anonymize profile input defaults

api/apps/chunk_app.py
When Delete Chunk Will Also Delete Chunk Related Image
=> Feat: When Delete Chunk Will Also Delete Chunk Related Image

docs/guides/ai_search.md
=> Docs: Added a guide on AI search

web/src/pages/chat/markdown-content/index.tsx
Fix: Use DOMPurify to filter out dangerous HTML #7668
=> Fix: Use DOMPurify to filter out dangerous HTML #7668

agent/component/__init__.py, agent/component/code.py
Add code agent component.
#4977
=> Feat: add code agent component

api/apps/sdk/session.py
Close #7655
Based on the codes atthe  api_app, I think the reference is one-to-one with the message
`
def fillin_conv(ans):
nonlocal conv, message_id
if not conv.reference:
conv.reference.append(ans["reference"])
else:
conv.reference[-1] = ans["reference"]
conv.message[-1] = {"role": "assistant", "content": ans["answer"], "id": message_id}
ans["id"] = message_id
`
=> Fix:Fail to get list_sessions

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, api/settings.py, docker/.env, docker/docker-compose-base.yml
Launch sandbox from docker-compose.
#4977
=> Feat: launch sandbox from docker-compose

web/src/pages/chat/share/index.less
Fix: Fixed the issue where the height of the chat page shared externally did not fill the window #7460
=> Fix: Fixed the issue where the height of the chat page shared externally did not fill the window #7460

api/apps/auth/README.md, conf/service_conf.yaml, docker/README.md, docker/service_conf.yaml.template, docs/configurations.md
Improve oauth configuration documentation and examples.
- Related pull requests: 
- #7379
- #7553
- #7587
- Related issues:
-  #3495
=> Docs: Improve oauth configuration documentation and examples

.github/workflows/tests.yml, sdk/python/test/test_http_api/conftest.py
change variable for ZHIPU_AI_API_KEY
=> Test: change variable for ZHIPU_AI_API_KEY

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docs/contribution/_category_.json, docs/contribution/contributing.md, docs/quickstart.mdx
=> Docs: Added contribution guidelines and sandbox-related tips

web/src/pages/chat/markdown-content/index.tsx
Fix: Fixed the issue where message references could not be displayed
=> Fix: Fixed the issue where message references could not be displayed

web/src/components/list-filter-bar/index.tsx, web/src/components/rerank.tsx, web/src/components/similarity-slider/index.tsx, web/src/components/slider-input-form-field.tsx, web/src/hooks/use-knowledge-request.ts, web/src/pages/chat/markdown-content/index.tsx, web/src/pages/dataset/dataset-title.tsx, web/src/pages/dataset/setting/index.tsx, web/src/pages/dataset/testing/index.tsx, web/src/pages/dataset/testing/testing-form.tsx
Feat: Rendering recall test page #3221
=> Feat: Rendering recall test page #3221

docs/develop/acquire_ragflow_api_key.md, docs/develop/mcp/_category_.json, docs/develop/switch_doc_engine.md, docs/guides/team/join_or_leave_team.md, docs/guides/team/manage_team_members.md, docs/guides/team/share_agents.md, docs/guides/team/share_chat_assistant.md, docs/guides/team/share_knowledge_bases.md, docs/guides/team/share_model.md
=> Docs: Added a guide on switching document engine

.github/workflows/tests.yml, Dockerfile, api/apps/document_app.py, api/db/services/file_service.py, api/utils/file_utils.py
Try the best to repair corrupted PDF files on upload automatically.
=> Feat: repair corrupted PDF files on upload automatically

api/db/services/dialog_service.py
More fallbacks for bad citation format
=> Refa: more fallbacks for bad citation format

web/src/constants/agent.ts, web/src/hooks/use-knowledge-request.ts, web/src/pages/dataset/testing/index.tsx, web/src/pages/dataset/testing/testing-result.tsx, web/src/pages/flow/form/code-form/index.tsx
Feat: Modify the Python language template code of the code operator #4977
=> Feat: Modify the Python language template code of the code operator #4977

api/apps/sdk/dataset.py, api/utils/api_utils.py, api/utils/validation_utils.py, sdk/python/test/test_http_api/test_dataset_mangement/test_create_dataset.py, sdk/python/test/test_http_api/test_dataset_mangement/test_delete_datasets.py, sdk/python/test/test_http_api/test_dataset_mangement/test_list_datasets.py, sdk/python/test/test_http_api/test_dataset_mangement/test_update_dataset.py
This PR introduces Pydantic-based validation for the list datasets HTTP API, improving code clarity and robustness. Key changes include:
Pydantic Validation
Error Handling
Test Updates
Documentation Updates
=> Refa: HTTP API list datasets / test cases / docs

web/src/pages/agent/constant.tsx, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/code-form/dynamic-input-variable.tsx, web/src/pages/agent/form/code-form/index.tsx, web/src/pages/agent/hooks.tsx
Feat: Migrate the code operator to the new agent. #3221
=> Feat: Migrate the code operator to the new agent. #3221

docker/.env, docker/docker-compose-base.yml
1. Add sandbox options for max memory and timeout.
2. ​Malicious code detection for Python only.​​
=> Feat: sandox enhancement

api/db/services/dialog_service.py
=> Fix: wrong type hint

web/src/hooks/use-agent-request.ts, web/src/pages/agents/agent-card.tsx, web/src/pages/agents/agent-dropdown.tsx, web/src/pages/agents/index.tsx, web/src/pages/agents/use-rename-agent.ts
=> Feat: Rename agent #3221

docs/develop/mcp/launch_mcp_server.md, docs/develop/switch_doc_engine.md, docs/guides/ai_search.md, docs/guides/dataset/configure_knowledge_base.md, docs/guides/dataset/select_pdf_parser.md, docs/guides/dataset/set_metadata.md, web/src/locales/de.ts, web/src/locales/es.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts
=> 0519 pdfparser

rag/svr/task_executor.py
delete useless image blobs when the task executor meets edge cases
=> Feat: delete useless image blobs when task executor meet edge cases

web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/code-form/index.tsx, web/src/pages/agent/form/code-form/next-variable.tsx, web/src/pages/agent/hooks.tsx
Feat: Fixed the issue where the page would refresh continuously when opening the sheet on the right side of the canvas #3221
=> Feat: Fixed the issue where the page would refresh continuously when opening the sheet on the right side of the canvas #3221

web/src/pages/agent/canvas/node/note-node.tsx, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/code-form/index.tsx, web/src/pages/agent/form/code-form/next-variable.tsx, web/src/pages/agent/hooks.tsx, web/src/pages/agent/hooks/use-watch-form-change.ts
Feat: Switching the programming language of the code operator will switch the corresponding language template #3221
=> Feat: Switching the programming language of the code operator will switch the corresponding language template #3221

web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/code-form/index.tsx, web/src/pages/agent/form/code-form/next-variable.tsx
Feat: Add return value widget  to CodeForm #3221
=> Feat: Add return value widget  to CodeForm #3221

rag/svr/task_executor.py
https://github.com/infiniflow/ragflow/issues/7761
but it may be difficult to achieve 0 delay (which need to pass the cancel token to all parts)
Another solution is just 0 delay effect at UI.
And task will stop latter
=> Fix: improve task cancel lag

api/apps/sdk/chat.py, api/apps/user_app.py, api/settings.py, conf/llm_factories.json, sdk/python/test/conftest.py, sdk/python/test/test_http_api/conftest.py, sdk/python/test/test_sdk_api/t_chat.py
change default models to buildin models https://github.com/infiniflow/ragflow/issues/7774
=> Feat: change default models

web/src/components/ui/button.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/begin-form/index.tsx, web/src/pages/agent/form/begin-form/paramater-dialog.tsx, web/src/utils/common-util.ts, web/tailwind.config.js, web/tailwind.css
Feat: Verify the parameters of the begin operator #3221
=> Feat: Verify the parameters of the begin operator #3221

api/db/services/dialog_service.py
Add more robust fallbacks for citations
=> Feat: more robust fallbacks for citations

agent/component/baidu.py
=> Fix baidu request error

web/src/pages/agent/form/begin-form/index.tsx, web/src/pages/agent/form/begin-form/query-table.tsx
Feat: Reconstruct the QueryTable of BeginForm using shandcn #3221
=> Feat: Reconstruct the QueryTable of BeginForm using shandcn #3221

conf/llm_factories.json
=> Feat: add claude4 models

docs/guides/chat/start_chat.md, docs/guides/dataset/configure_knowledge_base.md, docs/guides/dataset/run_retrieval_test.md, docs/quickstart.mdx, docs/references/glossary.mdx, docs/references/http_api_reference.md, docs/references/python_api_reference.md, docs/references/supported_models.mdx
=> Docs: Added instructions on cross-language search

rag/nlp/__init__.py
https://github.com/infiniflow/ragflow/issues/7790
=> Fix: Improve First Chunk Size

docs/guides/chat/start_chat.md, docs/guides/dataset/configure_knowledge_base.md, docs/guides/dataset/run_retrieval_test.md, docs/quickstart.mdx, docs/references/glossary.mdx, docs/references/http_api_reference.md, docs/references/python_api_reference.md, docs/references/supported_models.mdx
=> Docs: Added instructions on cross-language search (#7812)

docs/release_notes.md
=> Docs: Added v0.19.0 release notes

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md, docker/.env, docker/README.md, docs/configurations.md, docs/develop/build_docker_image.mdx, docs/faq.mdx, docs/guides/chat/start_chat.md, docs/guides/dataset/configure_knowledge_base.md, docs/guides/manage_files.md, docs/guides/tracing.mdx, docs/guides/upgrade_ragflow.mdx, docs/quickstart.mdx, docs/release_notes.md, helm/values.yaml, pyproject.toml, sdk/python/pyproject.toml, sdk/python/uv.lock, uv.lock
=> Docs: update for v0.19.0

docs/guides/agent/agent_component_reference/code.mdx, docs/guides/agent/agent_component_reference/note.mdx, docs/release_notes.md
=> Docs: Added code component reference

web/src/components/prompt-editor/index.tsx, web/src/locales/en.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/begin-form/begin-dynamic-options.tsx, web/src/pages/agent/form/code-form/dynamic-input-variable.tsx, web/src/pages/agent/form/code-form/next-variable.tsx, web/src/pages/agent/form/message-form/index.tsx
Feat: Refactor the MessageForm with shadcn #3221
=> Feat: Refactor the MessageForm with shadcn #3221

conf/llm_factories.json
=> Refa: update gemini2.5

agent/component/code.py
Catch non-begin component output
=> Fix: catch non-begin component output

api/apps/sdk/session.py
=> Fix: list out of boundary

rag/svr/task_executor.py
=> Fix: restore task limiter.

web/src/pages/agent/agent-sidebar.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/begin-form/query-table.tsx, web/src/pages/agent/form/waiting-dialogue-form/index.tsx, web/src/pages/agent/hooks/use-watch-form-change.ts
Feat: Add the WaitingDialogue operator. #3221
=> Feat: Add the WaitingDialogue operator. #3221

rag/svr/task_executor.py
=> Fix: task limiter issue.

api/db/services/__init__.py
[Regular Expression Injection leading to Denial of Service (ReDoS)](https://github.com/infiniflow/ragflow/security/advisories/GHSA-wqq6-x8g9-f7mh)
=> Fix: patch regex vulnerability in filename handling

rag/svr/task_executor.py
reduce upload_to_minio limter scope
=> Perf: reduce upload to minio limiter scope

web/src/components/large-model-form-field.tsx, web/src/components/llm-select/index.tsx, web/src/components/llm-select/next.tsx, web/src/components/llm-setting-items/next.tsx, web/src/components/llm-setting-items/slider.tsx, web/src/components/originui/select-with-search.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/categorize-form/index.tsx, web/src/pages/agent/form/generate-form/index.tsx, web/src/pages/agent/form/keyword-extract-form/index.tsx, web/src/pages/agent/form/rewrite-question-form/index.tsx, web/src/utils/file-util.ts
Feat: Add the SelectWithSearch component #3221
=> Feat: Add the SelectWithSearch component #3221

graphrag/general/index.py
Close #7879
I checked the current master code, the kb_parser_config is join from knowledge table, so I think should be some edge cases due to history data
=> Fix: KeyError: 'method' when build run_graphrag

agent/component/template.py
[[Critical] RagFlow has a SSTI, which can lead to Remote Code Execution (RCE).](https://github.com/infiniflow/ragflow/security/advisories/GHSA-mrf5-7w8r-8x88#event-463508)
=> Fix: patch SSTI vulnerability in template rendering

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md
=> Docs: about latest updates

docs/references/http_api_reference.md
conversation change to sessions
related_question interface has wrong uri in HTTP API doc
=> doc related_question path changed

web/src/pages/chat/utils.ts
Fix: Display bug in the early stage of conversation chat #7904
=> Fix: Display bug in the early stage of conversation chat #7904

api/db/services/dialog_service.py, rag/nlp/search.py, rag/prompts.py
Change citation mark as [ID:n], it's easier for LLMs to follow the instruction :) #7904
=> Refa: change citation mark as [ID:n]

rag/nlp/__init__.py
Add advanced delimiter detection for naive merge. #7824
=> Fix: add advanced delimiter detection for naive merge

agent/component/base.py, agent/component/code.py
Fix code component debug issue. #7908.
I delete the additions in #7933, there is no semantic meaning `output` for `parameters`.
=> Fix: code debug

web/src/components/message-history-window-size-item.tsx, web/src/components/originui/select-with-search.tsx, web/src/components/ui/input.tsx, web/src/components/ui/textarea.tsx, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/categorize-form/dynamic-categorize.tsx, web/src/pages/agent/form/categorize-form/index.tsx, web/src/pages/agent/form/code-form/next-variable.tsx, web/src/pages/agent/hooks/use-watch-form-change.ts, web/src/pages/demo.tsx
Feat: Add InnerBlurInput component to avoid frequent updates of zustand causing the input box to lose focus #3221
=> Feat: Add InnerBlurInput component to avoid frequent updates of zustand causing the input box to lose focus #3221

web/package-lock.json, web/package.json, web/src/app.tsx, web/src/components/ui/form.tsx, web/src/components/ui/input.tsx, web/src/pages/agent/form/categorize-form/dynamic-categorize.tsx
Feat: Install why-did-you-render to detect component updates #3221
=> Feat: Install why-did-you-render to detect component updates #3221

api/apps/sdk/dify_retrieval.py
When performing the dify_retrieval, the metadata of the document was empty.
=> Fix Bug: When performing the dify_retrieval, the metadata of the document was empty.

rag/llm/chat_model.py, rag/llm/cv_model.py, rag/llm/embedding_model.py, rag/llm/rerank_model.py
=> Fix: url path join issue.

pyproject.toml, uv.lock
sync test group from sdk/python/pyproject.toml to top pyproject.toml
=> Feat: sync test group to top pyproject.toml

web/src/components/rerank.tsx, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agent/form/categorize-form/dynamic-example.tsx, web/src/pages/agent/form/categorize-form/index.tsx, web/src/pages/agent/form/components/query-variable.tsx, web/src/pages/agent/form/retrieval-form/next.tsx
Feat: Construct RetrievalForm with original fields #3221
=> Feat: Construct RetrievalForm with original fields #3221

api/apps/dialog_app.py
=> Fix: no kb selected for an assistant.

api/apps/conversation_app.py
=> Fix: /v1/conversation/completion KeyError: 'conversation_id'

sdk/python/ragflow_sdk/ragflow.py
Fix parser_config=None handling in create_dataset
=> Fix: Allow None value for parser_config in create_dataset SDK method

web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/chat/chat-sheet.tsx, web/src/pages/agent/debug-content/index.tsx, web/src/pages/agent/debug-content/popover-form.tsx, web/src/pages/agent/index.tsx, web/src/pages/agent/run-sheet/index.tsx
Feat: Add RunSheet component #3221
=> Feat: Add RunSheet component #3221

docker/docker-compose.yml
=> Fix: data missing after upgrading.

api/apps/sdk/dataset.py, sdk/python/ragflow_sdk/modules/base.py, sdk/python/ragflow_sdk/modules/dataset.py
=> Fix: DataSet.update() now refreshes object data

test/testcases/test_http_api/test_dataset_mangement/test_delete_datasets.py, test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py, test/testcases/test_sdk_api/common.py, test/testcases/test_sdk_api/conftest.py, test/testcases/test_sdk_api/test_dataset_mangement/conftest.py, test/testcases/test_sdk_api/test_dataset_mangement/test_create_dataset.py, test/testcases/test_sdk_api/test_dataset_mangement/test_delete_datasets.py, test/testcases/test_sdk_api/test_dataset_mangement/test_list_datasets.py, test/testcases/test_sdk_api/test_dataset_mangement/test_update_dataset.py
=> Test: add sdk Dataset test cases

web/src/pages/agent/form/begin-form/index.tsx, web/src/pages/agent/form/begin-form/use-edit-query.ts, web/src/pages/agent/form/begin-form/use-values.ts
Feat: Solved the problem that BeginForm would get stuck when modifying data #3221
=> Feat: Solved the problem that BeginForm would get stuck when modifying data #3221

api/db/services/conversation_service.py
https://github.com/infiniflow/ragflow/issues/8070
=> Fix:when stream=false，new message without sessionid does no 

sdk/python/ragflow_sdk/modules/dataset.py
Added name filtering capability for Dataset.list_documents()
=> Fix(python-sdk): Add name filtering support to Dataset.list_documents()

sdk/python/ragflow_sdk/modules/document.py, test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py, test/testcases/test_http_api/test_dataset_mangement/test_delete_datasets.py, test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py, test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py, test/testcases/test_http_api/test_file_management_within_dataset/conftest.py, test/testcases/test_http_api/test_file_management_within_dataset/test_delete_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_list_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_upload_documents.py, test/testcases/test_sdk_api/common.py, test/testcases/test_sdk_api/conftest.py, test/testcases/test_sdk_api/test_file_management_within_dataset/conftest.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_delete_documents.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_download_document.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_list_documents.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_parse_documents.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_stop_parse_documents.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_update_document.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_upload_documents.py
=> Test: add sdk Document test cases

docs/develop/mcp/launch_mcp_server.md
=> Docs: Updated server launching code

deepdoc/parser/ppt_parser.py
=> Fix:Unimplemented function in ppt_parser

rag/svr/task_executor.py
Back port PR #7330  to 0.19 branch
=> task_limiter with trio.Semaphore

web/src/hooks/use-send-message.ts, web/src/pages/agent/chat/box.tsx, web/src/pages/agent/chat/chat-sheet.tsx, web/src/pages/agent/chat/hooks.ts, web/src/pages/agent/form-sheet/next.tsx
Feat: Receive reply messages of different event types from the agent #3221
=> Feat: Receive reply messages of different event types from the agent #3221

web/src/components/llm-setting-items/use-watch-change.ts, web/src/pages/agent/canvas/edge/index.tsx, web/src/pages/agent/canvas/node/popover.tsx, web/src/pages/agent/chat/box.tsx, web/src/pages/agent/chat/hooks.ts, web/src/pages/agent/constant.tsx, web/src/pages/agent/context.ts, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form/agent-form/dynamic-prompt.tsx, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/form/begin-form/use-values.ts, web/src/pages/agent/form/begin-form/utils.ts, web/src/pages/agent/form/components/output.tsx, web/src/pages/agent/form/components/prompt-editor/constant.ts, web/src/pages/agent/form/components/prompt-editor/index.css, web/src/pages/agent/form/components/prompt-editor/index.tsx, web/src/pages/agent/form/components/prompt-editor/theme.ts, web/src/pages/agent/form/components/prompt-editor/variable-node.tsx, web/src/pages/agent/form/components/prompt-editor/variable-on-change-plugin.tsx, web/src/pages/agent/form/components/prompt-editor/variable-picker-plugin.tsx, web/src/pages/agent/form/generate-form/index.tsx, web/src/pages/agent/form/message-form/index.tsx, web/src/pages/agent/form/template-form/index.tsx, web/src/pages/agent/hooks/use-build-dsl.ts, web/src/pages/agent/hooks/use-export-json.ts, web/src/pages/agent/hooks/use-fetch-data.ts, web/src/pages/agent/hooks/use-get-begin-query.tsx, web/src/pages/agent/hooks/use-save-graph.ts, web/tailwind.config.js, web/tailwind.css
Feat: Enables the message operator form to reference the data defined by the begin operator #3221
=> Feat: Enables the message operator form to reference the data defined by the begin operator #3221

test/testcases/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py, test/testcases/test_http_api/test_dataset_mangement/test_create_dataset.py, test/testcases/test_http_api/test_dataset_mangement/test_delete_datasets.py, test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py, test/testcases/test_http_api/test_dataset_mangement/test_update_dataset.py, test/testcases/test_http_api/test_file_management_within_dataset/test_delete_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_list_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_upload_documents.py, test/testcases/test_sdk_api/common.py, test/testcases/test_sdk_api/conftest.py, test/testcases/test_sdk_api/test_chunk_management_within_dataset/conftest.py, test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_add_chunk.py, test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_delete_chunks.py, test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_list_chunks.py, test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_retrieval_chunks.py, test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_update_chunk.py
- Improve concurrent test cases by using as_completed for better reliability
- Rename variables for clarity (chunk_num -> count)
- Add new SDK API test suite for chunk management operations
- Update HTTP API tests with consistent concurrency patterns
=> Test: Refactor test concurrency handling and add SDK chunk management tests

rag/raptor.py
=> Fix task_limiter in raptor.py

graphrag/general/index.py, graphrag/utils.py
Support passing the attribute check when the upstream has already made sure it.
=> Perf: pass useless check for tidy graph

api/apps/sdk/dataset.py
- Consolidate database operations within single try-except blocks in the methods
=> Refa: dataset operations to simplify error handling

rag/app/presentation.py
=> Fix: presentation of PDF using vlm.

web/src/pages/agent/chat/hooks.ts, web/src/pages/agent/form/agent-form/constant.ts, web/src/pages/agent/form/agent-form/dynamic-prompt.tsx, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/form/agent-form/use-values.ts, web/src/pages/agent/form/agent-form/use-watch-change.ts, web/src/pages/agent/hooks/use-get-begin-query.tsx
Feat: Convert the prompt field of the agent operator to an array #3221
=> Feat: Convert the prompt field of the agent operator to an array #3221

web/src/pages/agent/chat/hooks.ts, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/retrieval-form/next.tsx, web/src/pages/agent/form/retrieval-form/use-values.ts, web/src/pages/agent/hooks/use-get-begin-query.tsx
Feat: Display chat content on the agent page #3221
=> Feat: Display chat content on the agent page #3221

test/testcases/test_http_api/conftest.py, test/testcases/test_http_api/test_chat_assistant_management/conftest.py, test/testcases/test_http_api/test_chunk_management_within_dataset/conftest.py, test/testcases/test_http_api/test_file_management_within_dataset/conftest.py, test/testcases/test_http_api/test_session_management/conftest.py, test/testcases/test_http_api/test_session_management/test_create_session_with_chat_assistant.py, test/testcases/test_http_api/test_session_management/test_delete_sessions_with_chat_assistant.py, test/testcases/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py, test/testcases/test_http_api/test_session_management/test_update_session_with_chat_assistant.py, test/testcases/test_sdk_api/common.py, test/testcases/test_sdk_api/conftest.py, test/testcases/test_sdk_api/test_chat_assistant_management/conftest.py, test/testcases/test_sdk_api/test_chunk_management_within_dataset/conftest.py, test/testcases/test_sdk_api/test_session_management/conftest.py, test/testcases/test_sdk_api/test_session_management/test_create_session_with_chat_assistant.py, test/testcases/test_sdk_api/test_session_management/test_delete_sessions_with_chat_assistant.py, test/testcases/test_sdk_api/test_session_management/test_list_sessions_with_chat_assistant.py, test/testcases/test_sdk_api/test_session_management/test_update_session_with_chat_assistant.py
- Consolidate HTTP API test fixtures using batch operations (batch_add_chunks, batch_create_chat_assistants)
- Fix fixture initialization order in clear_session_with_chat_assistants
- Add new SDK API test suite for session management (create/delete/list/update)
=> Test: Refactor test fixtures and add SDK session management tests

web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/canvas/node/agent-node.tsx, web/src/pages/agent/context.ts, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/hooks.tsx, web/src/pages/agent/hooks/use-add-node.ts
Feat: Add agent operator node from agent form #3221
=> Feat: Add agent operator node from agent form #3221

web/src/components/originui/select-with-search.tsx, web/src/interfaces/database/flow.ts, web/src/pages/agent/canvas/edge/index.tsx, web/src/pages/agent/canvas/node/agent-node.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/components/query-variable.tsx, web/src/pages/agent/hooks/use-add-node.ts
Feat: Constructing query parameter options for the Retrieval operator #3221
=> Feat: Constructing query parameter options for the Retrieval operator #3221

.github/workflows/tests.yml
- Replace manual venv activation with `uv run` for pytest commands
- Add dynamic test level (p2/p3) based on GitHub event type
- Simplify test commands by removing redundant directory changes
=> Test: Migrate test workflow to use top-level test directory

deepdoc/vision/ocr.py
Enhanced the image rotation handling by evaluating the original orientation, clockwise 90°, and counter-clockwise 90° rotations. The image with the highest text recognition score is now selected, improving accuracy for text detection in images with aspect ratios >= 1.5.
#8166
=> Improve image rotation logic for text recognition

web/src/components/originui/timeline.tsx, web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/chat/chat-sheet.tsx, web/src/pages/agent/log-sheet/data.ts, web/src/pages/agent/log-sheet/index.tsx
Feat: Display the agent node running timeline #3221
=> Feat: Display the agent node running timeline #3221

rag/llm/chat_model.py
Fix auto-keyword and auto-question fail with qwq model. #8189
=> Fix: auto-keyword and auto-question fail with qwq model

rag/llm/chat_model.py, rag/prompts.py
=> Refa: chat with tools.

web/src/custom.d.ts
https://github.com/infiniflow/ragflow/issues/8157
The current master code should work fine, but hI ave some warnings, so I added a declare to improve the warning
=> Fix: Improve TS Warning For http_api_reference.md

test/testcases/test_http_api/common.py, test/testcases/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py, test/testcases/test_http_api/test_chat_assistant_management/test_delete_chat_assistants.py, test/testcases/test_http_api/test_chat_assistant_management/test_list_chat_assistants.py, test/testcases/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_add_chunk.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_delete_chunks.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_retrieval_chunks.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_update_chunk.py, test/testcases/test_http_api/test_dataset_mangement/test_delete_datasets.py, test/testcases/test_http_api/test_dataset_mangement/test_list_datasets.py, test/testcases/test_http_api/test_file_management_within_dataset/test_delete_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_download_document.py, test/testcases/test_http_api/test_file_management_within_dataset/test_list_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py, test/testcases/test_http_api/test_file_management_within_dataset/test_upload_documents.py, test/testcases/test_http_api/test_session_management/test_create_session_with_chat_assistant.py, test/testcases/test_http_api/test_session_management/test_delete_sessions_with_chat_assistant.py, test/testcases/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py, test/testcases/test_http_api/test_session_management/test_update_session_with_chat_assistant.py
- Move common constants (HOST_ADDRESS, INVALID_API_TOKEN, etc.) to configs.py
- Update test imports to use centralized configs
- Clean up duplicate constant definitions across test files
This improves maintainability by centralizing configuration.
=> Refa: Test configs

web/src/interfaces/database/agent.ts, web/src/interfaces/database/flow.ts, web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/canvas/node/switch-node.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/switch-form/index.tsx, web/src/pages/agent/form/switch-form/use-values.ts, web/src/pages/agent/hooks.tsx, web/src/pages/agent/hooks/use-add-node.ts, web/src/pages/agent/hooks/use-get-begin-query.tsx, web/src/pages/agent/store.ts
Feat: Connect conditional operators to other operators #3221
=> Feat: Connect conditional operators to other operators #3221

docs/guides/dataset/autokeyword_autoquestion.mdx, docs/guides/dataset/use_tag_sets.md, docs/references/http_api_reference.md
=> Docs: Miscellaneous editorial updates

agent/templates/customer_service.json
The issue of reporting the 「Can't inference the where the component input is. Please identify whose output is this component's input」error when creating an Agent using the Customer service template has been resolved.
=> Fix: Update customer_service.json

rag/llm/__init__.py, rag/llm/embedding_model.py, rag/llm/rerank_model.py
=> Feat: implement novitaAI embedding and reranking.

web/src/components/xyflow/base-node.tsx, web/src/components/xyflow/tooltip-node.tsx, web/src/pages/agent/canvas/node/agent-node.tsx, web/src/pages/agent/canvas/node/hooks.ts, web/src/pages/agent/canvas/node/node-header.tsx, web/src/pages/agent/canvas/node/switch-node.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/switch-form/index.tsx, web/src/pages/agent/operator-icon.tsx
Feat: Add canvas node toolbar #3221
=> Feat: Add canvas node toolbar #3221

agent/templates/customer_service.json
- Add query references to "RewriteQuestion:AllNightsSniff" in multiple components
- Set "selected" to false for retrieval node
=> Fix: Update customer service template with query references to RewriteQuestion

api/db/services/task_service.py
Progress is only updated if it's valid and not regressive.
=> Fix: incorrect progress updating

test/utils/file_utils.py
Update all test file creation functions to use English text instead of Chinese for consistency with the project's language standards. This includes DOCX, Excel, PPT, PDF, TXT, MD, JSON, EML, and HTML test file generators.
=> Refa: Translate test file content from Chinese to English in file_utils.py

api/apps/document_app.py, api/db/services/document_service.py
=> Feat: Let number of task ahead be visible.

web/src/components/llm-setting-items/index.tsx, web/src/constants/knowledge.ts, web/src/utils/chat.ts
Feat: Reset the default values ​​of large model parameters
=> Feat: Reset the default values ​​of large model parameters

sdk/python/ragflow_sdk/modules/session.py
=> Refa: Structure Ask Message

docs/develop/mcp/mcp_client_example.md
Add documentation of authorization header for MCP server based on OAuth 2.1
=> Docs: add authorization header for MCP server based on OAuth 2.1

web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/interface.ts
Feat: Use the node ID as the key to destroy different types of form components to switch the form values ​​of the same type of operators #3221
=> Feat: Use the node ID as the key to destroy different types of form components to switch the form values ​​of the same type of operators #3221

web/src/pages/agent/canvas/node/categorize-node.tsx, web/src/pages/agent/canvas/node/node-wrapper.tsx, web/src/pages/agent/canvas/node/switch-node.tsx, web/src/pages/agent/canvas/node/use-build-categorize-handle-positions.ts, web/src/pages/agent/canvas/node/use-build-switch-handle-positions.ts, web/src/pages/agent/form/switch-form/index.tsx, web/src/pages/agent/form/switch-form/use-watch-change.ts
Feat: Modify the anchor point positioning of the classification operator node #3221
=> Feat: Modify the anchor point positioning of the classification operator node #3221

web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/canvas/node/agent-node.tsx, web/src/pages/agent/canvas/node/begin-node.tsx, web/src/pages/agent/canvas/node/categorize-node.tsx, web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/canvas/node/handle.tsx, web/src/pages/agent/canvas/node/index.tsx, web/src/pages/agent/canvas/node/logic-node.tsx, web/src/pages/agent/canvas/node/message-node.tsx, web/src/pages/agent/canvas/node/retrieval-node.tsx, web/src/pages/agent/canvas/node/switch-node.tsx, web/src/pages/agent/context.ts, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/hooks/use-add-node.ts
Feat: Add a child operator node by clicking the operator node anchor point #3221
=> Feat: Add a child operator node by clicking the operator node anchor point #3221

web/src/pages/agent/canvas/node/agent-node.tsx, web/src/pages/agent/canvas/node/begin-node.tsx, web/src/pages/agent/canvas/node/categorize-node.tsx, web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/canvas/node/index.tsx, web/src/pages/agent/canvas/node/message-node.tsx, web/src/pages/agent/canvas/node/retrieval-node.tsx, web/src/pages/agent/canvas/node/switch-node.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/hooks/use-add-node.ts
Feat: Add child nodes and their connecting lines by clicking #3221
=> Feat: Add child nodes and their connecting lines by clicking #3221

web/src/interfaces/database/agent.ts, web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/canvas/node/tool-node.tsx, web/src/pages/agent/form/agent-form/dynamic-tool.tsx, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/form/agent-form/tool-popover/index.tsx, web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx, web/src/pages/agent/form/agent-form/use-values.ts
Feat: Add tool nodes and tool drop-down menu #3221
=> Feat: Add tool nodes and tool drop-down menu #3221

agent/component/template.py
Fix illegal variable name in Jinja2. #8316.
=> Fix: illegal variable name in Jinja2

deepdoc/vision/recognizer.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py, sdk/python/test/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py, test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py, test/testcases/test_http_api/test_session_management/test_list_sessions_with_chat_assistant.py, test/testcases/test_sdk_api/test_session_management/test_list_sessions_with_chat_assistant.py
1. rename var
2. update if statement
=> Refactor code

rag/llm/chat_model.py
https://github.com/infiniflow/ragflow/issues/8324
=> Fix: Raptor: [Bug]: **ERROR**: Unknown field for GenerationConfig: max_tokens

api/apps/search_app.py, api/db/db_models.py, api/db/services/dialog_service.py, api/db/services/search_service.py
=> Feat: wrap search app

rag/svr/task_executor.py
=> Fix: duplicated task

api/apps/document_app.py
- Correct boolean parsing for 'desc' parameter in document_app.py to properly handle string values
=> Fix: desc parameter parsing

web/src/pages/agent/form/components/output.tsx, web/src/pages/agent/form/tavily-form/dynamic-domain.tsx, web/src/pages/agent/form/tavily-form/index.tsx, web/src/pages/agent/form/tavily-form/use-values.ts, web/src/pages/agent/form/tavily-form/use-watch-change.ts
Feat: Improve the tavily form #3221
=> Feat: Improve the tavily form #3221

web/src/hooks/logic-hooks/navigate-hooks.ts, web/src/hooks/use-chunk-request.ts, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-card/index.less, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-card/index.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/tag-feature-item.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/checkbox-sets.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/index.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-toolbar/index.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/document-header.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/hooks.ts, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/index.less, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/document-preview/preview.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/constant.ts, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/hooks.ts, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.less, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/index.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/utils.ts, web/src/pages/chunk/parsed-result/add-knowledge/constant.ts, web/src/pages/chunk/parsed-result/add-knowledge/index.less, web/src/pages/chunk/parsed-result/add-knowledge/index.tsx, web/src/routes.ts
Refactor Pdf 2 Slices page to new style
=> Refa: Pdf 2 Slices page to new style

web/src/components/edit-tag/index.tsx
Fix: Fixed the issue where tag content would overflow the container #8392
=> Fix: Fixed the issue where tag content would overflow the container #8392

web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/agent-form/agent-tools.tsx, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/form/tavily-form/index.tsx, web/src/pages/agent/form/tavily-form/use-values.ts, web/src/pages/agent/form/tavily-form/use-watch-change.ts, web/src/pages/agent/form/tool-form/constant.ts, web/src/pages/agent/form/tool-form/tavily-form/index.tsx, web/src/pages/agent/form/tool-form/use-values.ts, web/src/pages/agent/form/tool-form/use-watch-change.ts, web/src/pages/agent/hooks.tsx, web/src/pages/agent/hooks/use-add-node.ts
Feat: Add Tavily operator #3221
=> Feat: Add Tavily operator #3221

rag/prompts.py
=> Fix: rank feature score should be greater than 0.

web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/canvas/node/handle.tsx, web/src/pages/agent/canvas/node/message-node.tsx
Feat: Solved the conflict between the Handle click and drag events of the canvas node #3221
=> Feat: Solved the conflict between the Handle click and drag events of the canvas node #3221

rag/nlp/search.py
=> Fix: doc_aggs issue.

rag/utils/opendal_conn.py
**Context and Purpose:**
This PR automatically remediates a security vulnerability:
- **Description:** Detected possible formatted SQL query. Use parameterized queries instead.
- **Rule ID:** python.lang.security.audit.formatted-sql-query.formatted-sql-query
- **Severity:** HIGH
- **File:** rag/utils/opendal_conn.py
- **Lines Affected:** 98 - 98
This change is necessary to protect the application from potential security risks associated with this vulnerability.
**Solution Implemented:**
The automated remediation process has applied the necessary changes to the affected code in `rag/utils/opendal_conn.py` to resolve the identified issue.
Please review the changes to ensure they are correct and integrate as expected.
=> Fix: Database Query Vulnerable to Injection Attacks in rag/utils/opendal_conn.py

web/src/pages/agent/canvas/edge/index.tsx, web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/canvas/node/toolbar.tsx, web/src/pages/agent/hooks.tsx, web/src/pages/agent/store.ts, web/src/pages/agent/utils.ts
Feat: The delete button is displayed only when the cursor is hovered over the connection line #3221
=> Feat: The delete button is displayed only when the cursor is hovered over the connection line #3221

docker/README.md, docker/nginx/ragflow.https.conf
Adds  HTTPS/SSL configuration guide/example to enable secure RAGFlow deployments with proper certificate management.
- New HTTPS Setup Section: Step-by-step guide for SSL certificate configuration
- Let's Encrypt Integration: Complete Certbot setup instructions
- Docker Configuration: Volume mapping examples for certificates
- Prerequisites checklist
- Docker Compose configuration examples
- Support for both Let's Encrypt and existing certificates
- `README.md`
- `ragflow.https.conf` (new file)
=> Feat: Add HTTPS setup instructions and configuration for Nginx

rag/llm/chat_model.py
- Simplify AzureChat constructor by passing base_url directly
- Clean up spacing and formatting in chat_model.py
- Remove redundant parentheses and improve code consistency
- #8423
=> Fix: AzureChat model code

docker/.env
Update .env ,Defaults to the v0.19.1-slim edition
=> Update .env ,Defaults to the v0.19.1-slim edition

web/src/hooks/logic-hooks.ts, web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/chat/hooks.ts, web/src/pages/agent/constant.tsx, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx, web/src/pages/agent/form/tool-form/constant.ts, web/src/pages/agent/hooks.tsx, web/src/pages/agent/hooks/use-add-node.ts, web/src/pages/agent/utils.ts
Feat: Use the message_id returned by the interface as the id of the reply message #3221
=> Feat: Use the message_id returned by the interface as the id of the reply message #3221

docs/guides/dataset/construct_knowledge_graph.md, docs/references/http_api_reference.md
=> Docs: exporting created knowledge graphs is not supported

mcp/client/streamable_http_client.py, mcp/server/server.py
Add MCP treamable-http transport.
=> Feat: add MCP treamable-http transport

helm/templates/env.yaml, helm/templates/ragflow.yaml, helm/templates/ragflow_config.yaml, helm/values.yaml
OIDC configuration  add to the helm values.
=> helm add oidc  configuration

graphrag/entity_resolution.py, rag/nlp/__init__.py
Improve GraphRAG similarity sensitivity to numeric differences. #8444.
=> Refa: improve GraphRAG similarity sensitivity to numeric differences

web/src/components/originui/select-with-search.tsx, web/src/pages/agent/canvas/node/agent-node.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form-sheet/use-form-config-map.tsx, web/src/pages/agent/form/begin-form/use-edit-query.ts, web/src/pages/agent/form/components/query-variable.tsx, web/src/pages/agent/form/iteration-form/index.tsx, web/src/pages/agent/hooks/use-add-node.ts, web/src/pages/agent/hooks/use-get-begin-query.tsx, web/src/pages/agent/hooks/use-show-drawer.tsx, web/src/pages/agent/store.ts, web/src/pages/flow/constant.tsx, web/src/pages/flow/form/iteration-start-from/index.tsx
Feat: Filter the query variable drop-down box options by type #3221
=> Feat: Filter the query variable drop-down box options by type #3221

sdk/python/ragflow_sdk/modules/chunk.py
This PR adds fields to the `Chunk` class to store retrieval results like similarity scores, term similarity, vector similarity, positions, and document type. This allows the chunk object to hold all the information needed when returning search results from the vector database.
=> Adds retrieval result fields to Chunk

api/apps/mcp_server_app.py, api/ragflow_server.py, api/utils/web_utils.py, mcp_client/mcp_tool_call.py
Add MCP dashboard functionalities list_tools and test_tool.
=> Feat: add MCP dashboard functionalities list_tools and test_tool

api/apps/chunk_app.py
- Include optional `tag_feas` field if present in request
- Add input validation for `important_kwd` and `question_kwd` to ensure they are lists
- #8462
=> Fix: Add input validation to chunk creation endpoint

api/apps/mcp_server_app.py
Allow users to choose which MCP tools are enabled.
=> Feat: allow users to choose which MCP tools are enabled

web/package-lock.json, web/package.json, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/components/prompt-editor/variable-picker-plugin.tsx, web/src/pages/agent/form/string-transform-form/use-values.ts, web/tailwind.config.js
Feat: Fixed the issue where the prompt menu content was hidden #3221
=> Feat: Fixed the issue where the prompt menu content was hidden #3221

web/src/hooks/use-send-message.ts, web/src/pages/agent/chat/hooks.ts, web/src/pages/agent/constant.tsx, web/src/pages/agent/debug-content/index.tsx, web/src/pages/agent/form/components/query-variable.tsx, web/src/pages/agent/run-sheet/index.tsx
Feat: Fixed the issue where the begin operator parameters could not be submitted during debugging #3221
=> Feat: Fixed the issue where the begin operator parameters could not be submitted during debugging #3221

rag/llm/chat_model.py, rag/raptor.py
=> Refa: limit embedding concurrency and fix `chat_with_tool`

web/src/components/next-message-item/index.tsx, web/src/hooks/logic-hooks.ts, web/src/hooks/use-send-message.ts, web/src/interfaces/database/chat.ts, web/src/pages/agent/canvas/node/begin-node.tsx, web/src/pages/agent/chat/box.tsx, web/src/pages/agent/chat/hooks.ts, web/src/pages/agent/chat/input-form.tsx, web/src/pages/agent/form/begin-form/use-edit-query.ts, web/src/pages/agent/form/begin-form/use-watch-change.ts, web/src/pages/agent/form/iteration-form/use-watch-form-change.ts, web/src/pages/agent/form/user-fill-up-form/use-watch-change.ts
Feat: Allow users to enter text in the middle of a chat #3221
=> Feat: Allow users to enter text in the middle of a chat #3221

web/src/app.tsx, web/src/pages/agent/canvas/index.less, web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/index.tsx
Feat: Fixed the issue that the top toolbar disappears when opening the agent operator form #3221
=> Feat: Fixed the issue that the top toolbar disappears when opening the agent operator form #3221

web/src/pages/agent/chat/box.tsx, web/src/pages/agent/chat/hooks.ts, web/src/pages/agent/debug-content/index.tsx, web/src/pages/agent/run-sheet/index.tsx, web/src/pages/agent/utils.ts
Feat: In a dialog message, users can enter different types of data #3221
=> Feat: In a dialog message, users can enter different types of data #3221

Dockerfile, Dockerfile.scratch.oc9, api/apps/mcp_server_app.py, api/ragflow_server.py, mcp_client/__init__.py, rag/utils/mcp_tool_call_conn.py
Change mcp_client module to rag/utils/conn.
=> Refa: change mcp_client module to rag/utils/conn

docs/references/http_api_reference.md, docs/references/python_api_reference.md
https://github.com/infiniflow/ragflow/issues/8556
=> doc: change to chunk_token num

api/apps/sdk/files.py
Add file management HTTP_API for operating files
=> Feat: Add file management HTTP_API

web/src/interfaces/database/agent.ts, web/src/pages/agent/store.ts, web/src/pages/agent/utils.ts
Feat: Construct the to field of the classification operator when saving data #3221
=> Feat: Construct the to field of the classification operator when saving data #3221

helm/templates/ragflow.yaml, helm/templates/ragflow_config.yaml, helm/values.yaml
=> Add service_conf and llm_factories options to Helm chart

download_deps.py
Update Chrome download URL in use_china_mirrors configuration
=> Update Chrome download URL in use_china_mirrors configuration

web/src/hooks/use-send-message.ts, web/src/pages/agent/log-sheet/index.tsx
Feat: Combine the output logs of the same operator together #3221
=> Feat: Combine the output logs of the same operator together #3221

web/src/components/xyflow/tooltip-node.tsx, web/src/pages/agent/canvas/node/iteration-node.tsx, web/src/pages/agent/constant.tsx
Feat: Display the iteration operator toolbar #3221
=> Feat: Display the iteration operator toolbar #3221

web/src/interfaces/database/agent.ts, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/code-form/index.tsx, web/src/pages/agent/form/code-form/next-variable.tsx, web/src/pages/agent/form/code-form/schema.ts, web/src/pages/agent/form/code-form/use-values.ts, web/src/pages/agent/form/code-form/use-watch-change.ts, web/src/pages/agent/utils/build-output-list.ts
Feat: Edit the output data of the code operator #3221
=> Feat: Edit the output data of the code operator #3221

rag/llm/__init__.py, rag/llm/chat_model.py, rag/llm/cv_model.py, rag/llm/embedding_model.py, rag/llm/rerank_model.py, rag/llm/sequence2txt_model.py, rag/llm/tts_model.py
Support automatic LLMs registration.
=> Refa: automatic LLMs registration

web/src/pages/agent/debug-content/index.tsx
Fix: Fixed the issue where the debug form Switch component had no default value #3221
=> Fix: Fixed the issue where the debug form Switch component had no default value #3221

rag/svr/task_executor.py
https://github.com/infiniflow/ragflow/issues/8656
=> Fix: The data set created by API call failed to parse after uploading the file.

download_deps.py
Resolves ambiguity and potential MITM attacks by using official channel for chromedriver-linux in download_deps.py
=> feat: use official sources for chromedriver-linux in download_deps.py

web/src/pages/chat/markdown-content/index.tsx, web/src/pages/chat/utils.ts
Fix: Wrong Citation Display #8594 #8474
=> Fix: Wrong Citation Display #8594 #8474

rag/prompts.py
Fix a small typo in count of used fragments.
=> Fix a small typo in count of used fragments

rag/utils/es_conn.py
=> Fix: add ES re-connect once request timeout.

api/db/services/task_service.py
Fix the case where pages variable might be None
=> fix task_service.py

web/src/components/file-upload.tsx, web/src/hooks/use-agent-request.ts, web/src/pages/agent/chat/box.tsx, web/src/pages/agent/debug-content/index.tsx, web/src/pages/agent/debug-content/uploader.tsx, web/src/pages/agent/utils.ts, web/src/pages/agent/utils/chat.ts, web/src/services/flow-service.ts, web/src/utils/api.ts
Feat: Support uploading files when running agent #3221
=> Feat: Support uploading files when running agent #3221

api/apps/document_app.py, api/apps/sdk/doc.py, api/db/db_models.py, api/db/services/document_service.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/document.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_parse_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py, sdk/python/test/test_http_api/test_file_management_within_dataset/test_update_document.py, test/testcases/test_http_api/test_file_management_within_dataset/test_parse_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_stop_parse_documents.py, test/testcases/test_http_api/test_file_management_within_dataset/test_update_document.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_parse_documents.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_stop_parse_documents.py, test/testcases/test_sdk_api/test_file_management_within_dataset/test_update_document.py, test/testcases/test_web_api/test_document_app/test_paser_documents.py, web/src/interfaces/database/document.ts, web/src/interfaces/database/knowledge.ts, web/src/pages/add-knowledge/components/knowledge-file/parsing-status-cell/index.tsx, web/src/pages/dataset/dataset/parsing-card.tsx
=> Fix: typo process_duration

rag/llm/embedding_model.py
https://github.com/infiniflow/ragflow/issues/8567
=> Fix:disallowed special token while embedding

rag/nlp/__init__.py
https://github.com/infiniflow/ragflow/issues/8719
=> Fix:use the same logic to handle pos in tokenize_chunks_with_images

api/apps/api_app.py, api/apps/document_app.py, api/apps/file2document_app.py, api/db/db_models.py, api/db/services/document_service.py, api/db/services/file_service.py
=> Feat: add advanced document filter

web/src/components/bulk-operate-bar.tsx, web/src/hooks/use-mcp-request.ts, web/src/pages/agent/chat/hooks.ts, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/message-form/use-values.ts, web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx, web/src/pages/profile-setting/mcp/edit-mcp-form.tsx, web/src/pages/profile-setting/mcp/index.tsx, web/src/pages/profile-setting/mcp/mcp-card.tsx, web/src/pages/profile-setting/mcp/use-bulk-operate-mcp.tsx, web/src/pages/profile-setting/mcp/use-edit-mcp.ts, web/src/utils/request.ts
Feat: Display MCP multiple selection bar #3221
=> Feat: Display MCP multiple selection bar #3221

rag/llm/embedding_model.py
https://github.com/infiniflow/ragflow/issues/8733
=> Fix: Change Ollama Embedding Keep Alive

docs/guides/upgrade_ragflow.mdx
=> Docs: Updated upgrading guide

web/src/hooks/use-mcp-request.ts, web/src/interfaces/database/mcp.ts, web/src/interfaces/request/mcp.ts, web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx, web/src/pages/profile-setting/mcp/edit-mcp-form.tsx, web/src/pages/profile-setting/mcp/mcp-card.tsx, web/src/pages/profile-setting/mcp/tool-card.tsx
=> Feat: Test MCP server #3221

web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/hooks/use-show-drawer.tsx, web/src/pages/agent/log-sheet/index.tsx
Feat: Avoid the form sheet covering the chat sheet #3221
=> Feat: Avoid the form sheet covering the chat sheet #3221

web/src/hooks/use-mcp-request.ts, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/hooks/use-add-node.ts, web/src/pages/profile-setting/mcp/mcp-card.tsx, web/src/pages/profile-setting/mcp/mcp-dropdown.tsx, web/src/pages/profile-setting/mcp/use-bulk-operate-mcp.tsx
=> Feat: Delete MCP server #3221

rag/llm/chat_model.py
=> Refa: refine retry gap.

api/apps/conversation_app.py
Fixes a function name typo for the `/list` route in `api/apps/conversation_app.py`.
=> Fix: Resolve typo in /list route function

web/src/interfaces/database/agent.ts, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form/agent-form/tool-popover/use-update-tools.ts, web/src/pages/agent/hooks.tsx, web/src/pages/agent/hooks/use-change-node-name.ts
Feat: Modify the agent tool name #3221
=> Feat: Modify the agent tool name #3221

web/src/components/collapse.tsx, web/src/hooks/use-mcp-request.ts, web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx, web/src/pages/profile-setting/mcp/edit-mcp-form.tsx, web/src/pages/profile-setting/mcp/index.tsx, web/src/pages/profile-setting/mcp/mcp-card.tsx, web/src/pages/profile-setting/mcp/mcp-dropdown.tsx, web/src/pages/profile-setting/mcp/use-edit-mcp.ts, web/src/services/mcp-server-service.ts
=> Feat: Edit MCP server #3221

conf/llm_factories.json, docs/references/supported_models.mdx, rag/llm/chat_model.py, rag/llm/cv_model.py
Add xAI provider (experimental feature, requires user feedback).
=> Feat: add xAI provider

api/apps/document_app.py
Change document status in bulk.
=> Feat: change document status in bulk

rag/app/presentation.py
https://github.com/infiniflow/ragflow/issues/8791
=> Fix: Improve Memory Usage For Presentation

rag/nlp/__init__.py
https://github.com/infiniflow/ragflow/issues/8719#issuecomment-3055883271
=> Fix: better_handle_different_types

api/apps/document_app.py, api/apps/file_app.py, api/utils/web_utils.py
Better uniform MIME content type.
=> Refa: better MIME content type

web/src/pages/document-viewer/index.tsx, web/src/pages/document-viewer/md/index.tsx, web/src/pages/document-viewer/text/index.tsx
Add document viewers for text and markdown files
=> Feat: Add text and markdown file view

web/src/hooks/use-mcp-request.ts, web/src/locales/en.ts, web/src/pages/profile-setting/mcp/edit-mcp-dialog.tsx, web/src/pages/profile-setting/mcp/edit-mcp-form.tsx, web/src/pages/profile-setting/mcp/index.tsx, web/src/pages/profile-setting/mcp/use-edit-mcp.ts, web/src/services/mcp-server-service.ts
Feat: Filter MCP server list by text. #3221
=> Feat: Filter MCP server list by text. #3221

rag/llm/embedding_model.py
FlagModel internal support returns as numpy
=> Perf:Remove Useless Convert When BGE Embedding

api/apps/mcp_server_app.py, api/utils/mcp_server.py
Refine MCP dashboard create and list operations.
=> Feat: refine create and list operations for MCP dashboard

web/src/hooks/use-mcp-request.ts, web/src/interfaces/database/mcp.ts, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form/tool-form/index.tsx, web/src/pages/agent/form/tool-form/mcp-form/index.tsx, web/src/pages/agent/form/tool-form/mcp-form/mcp-card.tsx, web/src/pages/agent/form/tool-form/mcp-form/use-values.ts, web/src/pages/agent/form/tool-form/mcp-form/use-watch-change.ts, web/src/pages/agent/utils.ts, web/src/services/mcp-server-service.ts
Feat: Synchronize MCP data to agent #3221
=> Feat: Synchronize MCP data to agent #3221

rag/nlp/__init__.py
Fixes no chunks parsed out for Law. #5113
=> Fix: no chunks parsed out for Law

api/utils/api_utils.py, rag/raptor.py, rag/svr/task_executor.py
=> Perf: make `do_cancel` quicker.

api/apps/document_app.py, api/db/services/task_service.py, rag/svr/task_executor.py
=> Pref: use redis to check if canceled.

rag/app/presentation.py, rag/svr/task_executor.py
Fixed invalid save() arguments for slide thumbnails.
=> Fix: fixed invalid save() arguments for slide thumbnails

web/src/components/originui/select-with-search.tsx, web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/crawler-form/index.tsx, web/src/pages/agent/hooks/use-watch-form-change.ts
Feat: Add CrawlerForm component #3221
=> Feat: Add CrawlerForm component #3221

api/db/db_models.py, graphrag/general/extractor.py
=> Perf: retryable mysql connection.

web/src/pages/agent/form/crawler-form/index.tsx, web/src/pages/agent/form/tool-form/constant.tsx, web/src/pages/agent/form/tool-form/crawler-form/index.tsx
Feat: Add agent tool CrawlerForm #3221
=> Feat: Add agent tool CrawlerForm #3221

graphrag/general/index.py, graphrag/utils.py, rag/svr/task_executor.py
=> Perf: set timeout of some steps in KG.

conf/llm_factories.json
Add Kimi model series support.
=> Feat: add Kimi model series support

web/src/hooks/use-agent-request.ts, web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/agent-form/tool-popover/use-update-tools.ts, web/src/pages/agent/form/components/form-wrapper.tsx, web/src/pages/agent/form/exesql-form/index.tsx, web/src/pages/agent/form/exesql-form/use-submit-form.ts, web/src/pages/agent/form/tool-form/constant.tsx, web/src/pages/agent/form/tool-form/crawler-form/index.tsx, web/src/pages/agent/form/tool-form/exesql-form/index.tsx, web/src/pages/agent/form/tool-form/use-values.ts, web/src/pages/agent/hooks/use-add-node.ts, web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
=> Feat: Add sql form #3221

graphrag/utils.py
=> Perf: add limit to embedding druing KG.

rag/llm/rerank_model.py
1. bug when re-try, we need to reset i.
2. remove useless convert
=> Refa: Remove useless conver and fix a bug for DefaultRerank

web/src/components/llm-select/next.tsx, web/src/components/originui/select-with-search.tsx, web/src/hooks/use-send-message.ts, web/src/pages/agent/chat/hooks.ts
Feat: Display the thinking process according to the start_to_think flag of the message #3221
=> Feat: Display the thinking process according to the start_to_think flag of the message #3221

rag/utils/s3_conn.py
when``` if 'signature_version' in self.s3_config:``` and ```if 'addressing_style' in self.s3_config:``` both true.
the config init is error, will be overwrite by last one. 
this pr is for fix that case.
=> fix s3 init config .

web/package-lock.json, web/src/pages/add-knowledge/components/knowledge-graph/util.ts
Fix: Fixed the issue that the knowledge graph could not be displayed #8890
=> Fix: Fixed the issue that the knowledge graph could not be displayed #8890

api/utils/api_utils.py, deepdoc/parser/figure_parser.py, graphrag/general/index.py, rag/svr/task_executor.py
=> Perf: test llm before RAPTOR.

web/src/components/highlight-markdown/index.tsx, web/src/components/ui/dialog.tsx, web/src/pages/agent/embed-dialog/index.tsx, web/src/pages/agent/index.tsx
Feat: Adjust the EmbedDialog style #3221
=> Feat: Adjust the EmbedDialog style #3221

rag/app/naive.py
https://github.com/infiniflow/ragflow/issues/8902
=> Fix: when parse markdown support extract image at local

docs/quickstart.mdx, docs/references/http_api_reference.md
=> Docs: Updated knowledge graph-specific APIs

rag/llm/rerank_model.py
Use the normalize method directly
=> Refactor improve codes for ranker

web/src/hooks/use-agent-request.ts, web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/canvas/node/switch-node.tsx, web/src/pages/agent/index.tsx, web/src/pages/agent/version-dialog/index.tsx, web/tailwind.css
Feat: Display agent history versions #3221
=> Feat: Display agent history versions #3221

api/apps/sdk/doc.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, graphrag/general/extractor.py, graphrag/general/graph_extractor.py, graphrag/light/graph_extractor.py, sdk/python/ragflow_sdk/ragflow.py
=> Fix: support cross language for API.

api/apps/llm_app.py, web/src/hooks/llm-hooks.tsx, web/src/locales/de.ts, web/src/locales/en.ts, web/src/locales/es.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/vi.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/user-setting/setting-model/api-key-modal/index.tsx, web/src/pages/user-setting/setting-model/hooks.ts, web/src/pages/user-setting/setting-model/index.tsx, web/src/pages/user-setting/setting-model/ollama-modal/index.tsx
Add edit button for local LLM models
=> Feat: Add model editing functionality with improved UI labels

rag/llm/rerank_model.py
https://github.com/infiniflow/ragflow/issues/8915
=> Fix:Improve float operation when rerank

web/src/pages/agent/form/begin-form/use-edit-query.ts
Fix: Fixed the issue that the key parameter duplication check of the begin operator was incorrect #3221
=> Fix: Fixed the issue that the key parameter duplication check of the begin operator was incorrect #3221

api/apps/document_app.py
=> Fix: correct cancel logic error

sandbox/README.md, sandbox/executor_manager/api/handlers.py, sandbox/executor_manager/api/routes.py, sandbox/executor_manager/core/container.py, sandbox/executor_manager/services/execution.py
Improve usability of Node.js/JavaScript code executor.
=> Refa: improve usability of Node.js/JavaScript code executor

graphrag/entity_resolution.py, graphrag/general/community_reports_extractor.py, graphrag/general/graph_extractor.py, graphrag/general/mind_map_extractor.py, graphrag/search.py, rag/raptor.py, rag/svr/task_executor.py
=> Refa: remove temperature since some  LLMs fail to support.

web/src/constants/agent.ts, web/src/hooks/use-agent-request.ts, web/src/pages/agent/form/agent-form/index.tsx, web/src/services/agent-service.ts, web/src/utils/api.ts, web/src/utils/next-request.ts, web/src/utils/register-server.ts
Fix: Fixed the issue where the error prompt box on the Agent page would be covered #3221
=> Fix: Fixed the issue where the error prompt box on the Agent page would be covered #3221

api/apps/sdk/session.py, docs/references/python_api_reference.md
OpenAI-compatible-API supports references.
=> Feat: OpenAI-compatible-API supports references

web/src/components/collapse.tsx, web/src/components/cross-language-form-field.tsx, web/src/components/page-header.tsx, web/src/components/ui/sheet.tsx, web/src/pages/agent/canvas/node/node-wrapper.tsx, web/src/pages/agent/canvas/node/note-node/index.tsx, web/src/pages/agent/canvas/node/note-node/use-watch-change.ts, web/src/pages/agent/chat/box.tsx, web/src/pages/agent/components/background.tsx, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form/retrieval-form/next.tsx, web/src/pages/agents/index.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Modify the background color of the agent canvas #3221
=> Feat: Modify the background color of the agent canvas #3221

web/src/components/originui/select-with-search.tsx, web/src/components/ui/multi-select.tsx, web/src/pages/agent/canvas/node/switch-node.tsx, web/src/pages/agent/canvas/node/use-build-switch-handle-positions.ts, web/src/pages/agent/form-sheet/form-config-map.tsx, web/src/pages/agent/form/string-transform-form/index.tsx, web/src/pages/agent/form/switch-form/index.tsx, web/src/pages/agents/agent-card.tsx
Feat: Allows users to delete a condition of a conditional operator #3221
=> Feat: Allows users to delete a condition of a conditional operator #3221

web/package-lock.json, web/src/components/message-input/next.tsx, web/src/hooks/use-agent-request.ts, web/src/locales/pt-br.ts, web/src/pages/agent/canvas/node/index.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/user-fill-up-form/index.tsx, web/src/pages/agent/form/user-fill-up-form/use-watch-change.ts
Feat: Downstream operators can get the variables defined by the user input operator #3221
=> Feat: Downstream operators can get the variables defined by the user input operator #3221

api/apps/sdk/chat.py
https://github.com/infiniflow/ragflow/issues/9034
=> Feature: Support set chats kbs to empty

deepdoc/parser/docx_parser.py, deepdoc/parser/excel_parser.py, deepdoc/parser/html_parser.py
=> Refactor parser code

rag/llm/cv_model.py, rag/llm/embedding_model.py
=> get keep alive from env

api/db/db_models.py
Suppress DB migration error logs.
=> Refa: suppress DB migration error logs

web/src/pages/agent/form/retrieval-form/next.tsx, web/src/pages/agent/form/switch-form/index.tsx, web/src/pages/agent/form/tool-form/retrieval-form/index.tsx
Feat: The operator is displayed only when the number of conditions is greater than 1 #3221
=> Feat: The operator is displayed only when the number of conditions is greater than 1 #3221

api/apps/kb_app.py, conf/infinity_mapping.json, docker/docker-compose-base.yml, docker/infinity_conf.toml, helm/values.yaml, rag/nlp/query.py, rag/nlp/search.py, rag/utils/infinity_conn.py, sdk/python/test/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py, test/testcases/test_http_api/test_chunk_management_within_dataset/test_list_chunks.py, test/testcases/test_sdk_api/test_chunk_management_within_dataset/test_list_chunks.py, test/testcases/test_web_api/test_chunk_app/test_list_chunks.py
Added infinity rank_feature support
=> Added infinity rank_feature support

web/src/components/next-message-item/index.tsx, web/src/components/next-message-item/uploaded-message-files.tsx, web/src/interfaces/database/chat.ts, web/src/pages/agent/chat/box.tsx, web/src/pages/agent/chat/use-send-agent-message.ts, web/src/pages/next-chats/share/index.tsx
Feat: Render the uploaded agent message file #3221
=> Feat: Render the uploaded agent message file #3221

web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/code-form/index.tsx, web/src/pages/agent/form/components/api-key-field.tsx, web/src/pages/agent/form/google-form/index.tsx, web/src/pages/agent/form/tavily-extract-form/index.tsx, web/src/pages/agent/form/tavily-form/index.tsx, web/src/pages/agent/form/tool-form/constant.tsx, web/src/pages/agent/form/tool-form/tavily-form/index.tsx, web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Feat: Add Google operator #3221
=> Feat: Add Google operator #3221

web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/tool-form/constant.tsx, web/src/pages/agent/form/tool-form/yahoo-finance-form/index.tsx, web/src/pages/agent/form/yahoo-finance-form/index.tsx, web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Feat: Add Yahoo Finance Operator #3221
=> Feat: Add Yahoo Finance Operator #3221

web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/canvas/node/tool-node.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/agent-form/agent-tools.tsx, web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx, web/src/pages/agent/form/arxiv-form/index.tsx, web/src/pages/agent/form/duckduckgo-form/index.tsx, web/src/pages/agent/form/email-form/index.tsx, web/src/pages/agent/form/google-form/index.tsx, web/src/pages/agent/form/google-scholar-form/index.tsx, web/src/pages/agent/form/tool-form/arxiv-form/index.tsx, web/src/pages/agent/form/tool-form/constant.tsx, web/src/pages/agent/form/tool-form/google-form/index.tsx, web/src/pages/agent/form/tool-form/google-scholar-form/index.tsx, web/src/pages/agent/form/wikipedia-form/index.tsx, web/src/pages/agent/form/yahoo-finance-form/index.tsx, web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Feat: Add Arxiv GoogleScholar operator #3221
=> Feat: Add Arxiv GoogleScholar operator #3221

api/utils/file_utils.py, deepdoc/parser/json_parser.py, rag/app/naive.py
Supports jsonl or ldjson format. Feature request from [discussion](https://github.com/orgs/infiniflow/discussions/8774).
=> Feat: parsing supports jsonl or ldjson format

web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/agent-form/tool-popover/tool-command.tsx, web/src/pages/agent/form/tool-form/constant.tsx, web/src/pages/agent/form/tool-form/wencai-form/index.tsx, web/src/pages/agent/form/wencai-form/index.tsx, web/src/pages/agent/hooks/use-agent-tool-initial-values.ts
Feat: Add wencai operator #3221
=> Feat: Add wencai operator #3221

web/src/components/llm-select/llm-label.tsx, web/src/components/message-input/next.tsx, web/src/hooks/use-agent-request.ts, web/src/pages/agent/chat/use-send-agent-message.ts, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/exesql-form/index.tsx, web/src/pages/agent/index.tsx, web/src/pages/next-chats/hooks/use-send-shared-message.ts, web/src/pages/next-chats/share/index.tsx, web/src/pages/next-chats/share/parameter-dialog.tsx, web/src/services/agent-service.ts, web/src/utils/api.ts
Feat: Make the agent dialog window exposed to the outside world fill in the begin form #3221
=> Feat: Make the agent dialog window exposed to the outside world fill in the begin form #3221

api/db/services/llm_service.py
- Add Generator return type annotation for tts method
- Import typing.Generator for type hints
=> Rafe: Update LLMService type hints

conf/llm_factories.json
add Kimi-K2-Instruct from Tongyi-Qianwen API
=> add Kimi-K2-Instruct from Tongyi-Qianwen API

web/src/hooks/use-send-message.ts, web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/canvas/node/begin-node.tsx, web/src/pages/agent/canvas/node/note-node/index.tsx, web/src/pages/agent/chat/box.tsx, web/src/pages/agent/chat/use-send-agent-message.ts, web/src/pages/agent/hooks/use-show-drawer.tsx, web/src/pages/agent/operator-icon.tsx
Feat: Delete the operator node and hide the corresponding sheet #3221
=> Feat: Delete the operator node and hide the corresponding sheet #3221

rag/nlp/__init__.py
https://github.com/infiniflow/ragflow/issues/9149
=> Fix:Repeated images when parsing markdown files with images

api/settings.py, api/utils/api_utils.py
https://github.com/infiniflow/ragflow/issues/9189#issuecomment-3148920950
=> Refactor: support config strong test

api/db/services/dialog_service.py, api/db/services/llm_service.py
Fix:
```bash
'Langfuse' object has no attribute 'trace'
```
=> Fix: migrate deprecated Langfuse API from v2 to v3

api/apps/sdk/dify_retrieval.py
fix #8424 NPE in dify_retrieval.py, add log exception
=> fix #8424 NPE in dify_retrieval.py, add log exception

api/apps/document_app.py, api/apps/sdk/doc.py, docs/references/http_api_reference.md, docs/references/python_api_reference.md, sdk/python/ragflow_sdk/modules/dataset.py
list_document supports range filtering.
=> Feat: list documents supports range filtering

docs/release_notes.md
=> v0.20.0 release notes

web/src/hooks/logic-hooks.ts, web/src/pages/agent/chat/box.tsx, web/src/pages/agent/chat/use-send-agent-message.ts, web/src/pages/chat/chat-container/index.tsx, web/src/pages/chat/hooks.ts, web/src/pages/next-chats/share/index.tsx
Fix: Fixed the issue where the agent's chat box could not automatically scroll to the bottom #3221
=> Fix: Fixed the issue where the agent's chat box could not automatically scroll to the bottom #3221

api/apps/sdk/dify_retrieval.py, api/db/services/canvas_service.py, api/db/services/llm_service.py, rag/utils/s3_conn.py
=> Fix: self-deployed LLM error,

rag/utils/redis_conn.py
Ensure Redis queue could be created properly.
=> Refa: ensure Redis stream queue could be created properly

docs/guides/agent/agent_component_reference/agent.mdx, docs/release_notes.md
=> Docs: Updated tips for max rounds

rag/llm/cv_model.py
Improve the chat stream logic for NvidiaCV
=> Refactor:Improve the chat stream logic for NvidiaCV

rag/nlp/__init__.py
https://github.com/infiniflow/ragflow/issues/9149#issuecomment-3157129587
=> Fix:remove a img close which can not operate

api/apps/llm_app.py, rag/svr/task_executor.py, rag/utils/s3_conn.py
=> Refa: add provider info while adding model.

web/src/components/ui/modal/modal-manage.tsx, web/src/components/ui/modal/modal.tsx, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agents/agent-log-detail-modal.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-creating-modal/index.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/index.tsx, web/src/pages/dataset/setting/index.tsx, web/src/pages/next-chats/share/parameter-dialog.tsx, web/src/pages/next-searches/index.tsx, web/src/pages/next-searches/search-card.tsx
fix: Optimized popups and the search page #3221 
- Added a new PortalModal component
- Refactored the Modal component, adding show and hide methods to support popups
- Updated the search page, adding a new query function and optimizing the search card style
- Localized, added search-related translations
=> fix: Optimized popups and the search page

web/src/hooks/use-chat-request.ts, web/src/pages/next-chats/chat-card.tsx, web/src/pages/next-chats/chat/app-settings/chat-settings-sheet.tsx, web/src/pages/next-chats/chat/app-settings/chat-settings.tsx, web/src/pages/next-chats/chat/chat-box.tsx, web/src/pages/next-chats/chat/index.tsx, web/src/pages/next-chats/chat/sessions.tsx, web/src/pages/next-chats/hooks/use-button-disabled.tsx, web/src/pages/next-chats/hooks/use-click-card.ts, web/src/pages/next-chats/hooks/use-create-conversation.ts, web/src/pages/next-chats/hooks/use-select-conversation-list.ts, web/src/pages/next-chats/hooks/use-send-chat-message.ts
=> Feat: Render chat page #3221

rag/nlp/__init__.py
naive_merge_with_images close useless images
=> Refactor:naive_merge_with_images close useless images

api/apps/document_app.py
Fix virtual file cannot be displayed in KB. #9265
=> Fix: virtual file cannot be displayed in KB

web/src/components/edit-tag/index.tsx, web/src/components/next-message-item/index.tsx, web/src/components/ui/badge.tsx, web/src/components/ui/button.tsx, web/src/components/ui/card.tsx, web/src/components/ui/table.tsx, web/src/locales/en.ts, web/src/pages/agent/canvas/node/agent-node.tsx, web/src/pages/agent/canvas/node/categorize-node.tsx, web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/embed-dialog/index.tsx, web/src/pages/agent/form/agent-form/agent-tools.tsx, web/src/pages/agent/form/switch-form/index.tsx, web/src/pages/agent/log-sheet/toolTimelineItem.tsx, web/src/pages/agent/log-sheet/workFlowTimeline.tsx, web/src/pages/chunk/parsed-result/add-knowledge/components/knowledge-chunk/components/chunk-result-bar/index.tsx, web/src/pages/dataset/sidebar/index.tsx, web/src/pages/next-chats/chat/sessions.tsx, web/tailwind.config.js, web/tailwind.css
Feat: Configure colors according to the design draft#3221
=> Feat: Configure colors according to the design draft#3221

api/settings.py, rag/llm/cv_model.py, rag/utils/s3_conn.py
=> Fix: bytes style image issue.

agent/tools/retrieval.py, api/db/services/llm_service.py
=> Fix: model type error.

api/apps/sdk/session.py, api/db/services/canvas_service.py
Update broken agent completion due to v0.20.0 changes. #9199
=> Fix: update broken agent completion due to v0.20.0 changes

api/db/services/llm_service.py
=> fix model type

web/src/pages/agent/setting-dialog/setting-form.tsx
Feat: Set the description of the agent, which can be null #3221
=> Feat: Set the description of the agent, which can be null #3221

api/apps/canvas_app.py, api/apps/sdk/session.py, api/db/services/canvas_service.py, api/db/services/llm_service.py
=> Fix: add prologue to api.

docs/guides/agent/agent_component_reference/agent.mdx, docs/release_notes.md
=> Docs: v0.20.1 release notes

api/apps/canvas_app.py, api/db/services/canvas_service.py
=> Fix: canvas sharing bug.

api/apps/canvas_app.py
=> Refa: code format.

rag/svr/task_executor.py
fix "broken data stream when writing image file", just log warning and ignore
Close #8379
=> Fix broken data stream when writing image file

agent/component/invoke.py
https://github.com/infiniflow/ragflow/issues/9385
Based on my understanding, I think checking empty string is fine
=> Fix:HTTP request component failed to retrieve the corresponding value

api/db/services/llm_service.py
https://github.com/infiniflow/ragflow/issues/9351
Support filter argument before invoking
=> Fix:TypeError: OllamaCV.chat() got an unexpected keyword argument 'stop'

rag/llm/chat_model.py
=> Fix: Patch LiteLLM

api/db/services/document_service.py
=> Fix: remove doc error.

api/apps/user_app.py, api/db/init_data.py, api/settings.py, conf/service_conf.yaml
Allows set multiple types of default models in service config.
=> Feat: allows setting multiple types of default models in service config

api/db/services/dialog_service.py, web/src/components/llm-setting-items/next.tsx, web/src/components/llm-setting-items/slider.tsx, web/src/components/llm-setting-items/use-watch-change.ts, web/src/components/rerank.tsx, web/src/components/similarity-slider/index.tsx, web/src/components/slider-input-form-field.tsx, web/src/components/top-n-item.tsx, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/next-chats/chat/app-settings/chat-model-settings.tsx, web/src/pages/next-chats/chat/app-settings/chat-prompt-engine.tsx, web/src/pages/next-chats/chat/app-settings/chat-settings.tsx, web/src/pages/next-chats/chat/app-settings/dynamic-variable.tsx, web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx, web/src/pages/next-chats/chat/sessions.tsx
Feat: Fixed the issue where some fields in the chat configuration could not be displayed #3221
=> Feat: Fixed the issue where some fields in the chat configuration could not be displayed #3221

rag/llm/rerank_model.py
Improve the float compare for LocalAIRerank
=> Refactor:Improve the float compare for LocalAIRerank

agent/templates/sql_assistant.json, api/apps/sdk/chat.py, api/db/db_models.py, docs/references/http_api_reference.md, sdk/python/ragflow_sdk/modules/chat.py, sdk/python/ragflow_sdk/ragflow.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py, sdk/python/test/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py, test/testcases/test_http_api/test_chat_assistant_management/test_create_chat_assistant.py, test/testcases/test_http_api/test_chat_assistant_management/test_update_chat_assistant.py, test/testcases/test_sdk_api/test_chat_assistant_management/test_create_chat_assistant.py, test/testcases/test_sdk_api/test_chat_assistant_management/test_update_chat_assistant.py, web/src/locales/en.ts, web/src/pages/agent/constant.tsx, web/src/pages/flow/constant.tsx
=> Docs: Deprecated 'Create session with agent'

web/src/hooks/logic-hooks.ts, web/src/interfaces/database/chat.ts, web/src/locales/zh.ts, web/src/pages/agent/form/components/prompt-editor/index.tsx, web/src/pages/agent/form/retrieval-form/next.tsx, web/src/pages/next-chats/chat/chat-box/multiple-chat-box.tsx, web/src/pages/next-chats/hooks/use-build-form-refs.ts, web/src/pages/next-chats/hooks/use-send-multiple-message.ts
Feat: Send data to compare the performance of different models' answers #3221
=> Feat: Send data to compare the performance of different models' answers #3221

web/src/hooks/logic-hooks.ts, web/src/hooks/use-chat-request.ts, web/src/pages/agent/constant.tsx, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/next-chats/chat/chat-box/multiple-chat-box.tsx, web/src/pages/next-chats/chat/chat-box/single-chat-box.tsx, web/src/pages/next-chats/chat/index.tsx, web/src/pages/next-chats/hooks/use-send-chat-message.ts, web/src/pages/next-chats/hooks/use-send-multiple-message.ts, web/src/pages/next-chats/hooks/use-upload-file.ts, web/src/services/next-chat-service.ts
Feat: Upload files in the chat box #3221
=> Feat: Upload files in the chat box #3221

agent/component/agent_with_tools.py, agent/component/llm.py, graphrag/entity_resolution.py, graphrag/general/community_reports_extractor.py, graphrag/general/index.py, rag/svr/task_executor.py
=> Feat: add citation option to agent and enlarge the timeouts.

web/src/hooks/logic-hooks/use-change-search.ts, web/src/hooks/use-chat-request.ts, web/src/pages/next-chats/chat/app-settings/chat-settings.tsx, web/src/pages/next-chats/chat/conversation-dropdown.tsx, web/src/pages/next-chats/chat/index.tsx, web/src/pages/next-chats/chat/llm-select-form.tsx, web/src/pages/next-chats/chat/sessions.tsx, web/src/pages/next-chats/hooks/use-select-conversation-list.ts
Feat: Delete or filter conversations #3221
=> Feat: Delete or filter conversations #3221

deepdoc/parser/excel_parser.py, rag/app/naive.py
Handle unexpected truncated Excel files.
=> Fix: unexpected truncated Excel files

api/apps/conversation_app.py, api/db/db_models.py, api/db/services/dialog_service.py
Conversation completion can specify different model
=> Feat: conversation completion can specify different model

api/apps/conversation_app.py, api/apps/sdk/session.py, api/db/db_models.py, api/db/services/dialog_service.py
=> Refa: refine search app

web/src/interfaces/request/chat.ts, web/src/layouts/next-header.tsx, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/log-sheet/tool-timeline-item.tsx, web/src/pages/agent/log-sheet/workflow-timeline.tsx, web/src/pages/next-search/embed-app-modal.tsx, web/src/pages/next-search/hooks.ts, web/src/pages/next-search/index.tsx, web/src/pages/next-search/markdown-content/index.tsx, web/src/pages/next-search/mindmap-drawer.tsx, web/src/pages/next-search/search-home.tsx, web/src/pages/next-search/search-setting.tsx, web/src/pages/next-search/search-view.tsx, web/src/pages/next-search/share/index.tsx, web/src/pages/next-searches/hooks.ts, web/src/pages/search/hooks.ts
feat(search): Optimized search functionality and user interface #3221
- Added similarity threshold adjustment function
- Optimized mind map display logic
- Adjusted search settings interface layout
- Fixed related search and document viewing functions
- Optimized time display and node selection logic
=> feat(search): Optimized search functionality and user interface #3221

web/src/components/large-model-form-field.tsx, web/src/components/llm-select/next.tsx, web/src/components/message-item/index.less, web/src/components/message-item/index.tsx, web/src/hooks/logic-hooks.ts, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/next-chats/chat/app-settings/chat-settings.tsx, web/src/pages/next-chats/chat/chat-box/single-chat-box.tsx, web/src/pages/next-chats/chat/index.tsx, web/src/pages/next-chats/chat/sessions.tsx
Feat: Allow agent operators to select speech-to-text models #3221
=> Feat: Allow agent operators to select speech-to-text models #3221

rag/llm/rerank_model.py
Improve VoyageRerank not texts handling
=> Refactor:Improve VoyageRerank not texts handling

docs/release_notes.md
=> Docs: Updated v0.20.2 release notes

api/apps/dialog_app.py, conf/llm_factories.json, rag/app/audio.py, rag/llm/sequence2txt_model.py
Refactor OpenAI to enable audio parsing.
=> Refa: OpenAI whisper-1

web/src/components/metadata-filter/index.tsx, web/src/components/metadata-filter/metadata-filter-conditions.tsx, web/src/constants/chat.ts, web/src/layouts/next-header.tsx, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agent/form/exesql-form/use-submit-form.ts, web/src/pages/agent/form/tool-form/exesql-form/index.tsx, web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx, web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx, web/src/pages/next-chats/hooks/use-build-form-refs.ts, web/src/pages/next-chats/hooks/use-rename-chat.ts, web/src/pages/next-search/search-setting.tsx, web/src/pages/next-searches/hooks.ts
Fix: Fixed the issue where clicking the SQL tool test button did not request the interface #9541
=> Fix: Fixed the issue where clicking the SQL tool test button did not request the interface #9541

docs/references/http_api_reference.md
=> Docs: Updated workarounds for uploading file to an agent

api/apps/dialog_app.py
Create new name for duplicated dialog name.
=> Refa: create new name for duplicated dialog name

api/apps/chunk_app.py, api/apps/conversation_app.py, api/db/services/dialog_service.py
=> Fix: no effect on retrieval_test in term of metadata filter.

web/src/hooks/logic-hooks/navigate-hooks.ts, web/src/locales/zh.ts, web/src/pages/agents/agent-card.tsx, web/src/pages/datasets/dataset-card.tsx, web/src/pages/home/search-list.tsx, web/src/pages/next-chats/chat-card.tsx, web/src/pages/next-searches/index.tsx, web/src/pages/next-searches/search-card.tsx
Fix home card not responding to click events
=> Fix dataset card not responding to click events

docs/release_notes.md
=> Docs: Updated v0.20.3 release notes

api/db/services/canvas_service.py
Reverts infiniflow/ragflow#9582
=> Revert "Feat: reference should also be list after 0.20.x"

agent/canvas.py
https://github.com/infiniflow/ragflow/issues/9545
add backward compatible logics
=> Fix:KeyError: 'globals' KeyError： 'globals'

rag/app/naive.py, rag/raptor.py
=> Fix: enlarge raptor timeout limits.

web/src/app.tsx, web/src/components/file-upload-dialog/index.tsx, web/src/components/file-uploader.tsx, web/src/components/ui/multi-select.tsx, web/src/pages/agent/upload-agent-dialog/upload-agent-form.tsx, web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx, web/src/pages/profile-setting/mcp/import-mcp-dialog/import-mcp-form.tsx
Fix: Remove the file size and quantity restrictions of the upload control #9613 #9598
=> Fix: Remove the file size and quantity restrictions of the upload control #9613 #9598

web/src/components/file-upload-dialog/index.tsx, web/src/hooks/use-document-request.ts, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/dataset/dataset/index.tsx, web/src/pages/dataset/dataset/use-upload-document.ts, web/src/pages/datasets/dataset-creating-dialog.tsx, web/src/pages/files/use-upload-file.ts
Feat: Allow users to parse documents directly after uploading files #3221
=> Feat: Allow users to parse documents directly after uploading files #3221

web/src/components/home-card.tsx, web/src/components/ragflow-form.tsx, web/src/components/shared-badge.tsx, web/src/constants/permission.ts, web/src/pages/dataset/setting/general-form.tsx, web/src/pages/dataset/setting/index.tsx, web/src/pages/datasets/dataset-card.tsx
Fix: Fixed an issue where knowledge base could not be shared #9634
=> Fix: Fixed an issue where knowledge base could not be shared #9634

api/apps/sdk/dify_retrieval.py
=> fix(sdk): add default empty dict for metadata_condition

web/src/hooks/use-llm-request.ts, web/src/hooks/use-user-setting-request.tsx, web/src/pages/next-chats/chat/chat-box/multiple-chat-box.tsx, web/src/pages/next-chats/chat/chat-box/single-chat-box.tsx, web/src/pages/next-chats/chat/index.tsx, web/src/pages/next-chats/hooks/use-rename-chat.ts, web/src/pages/next-chats/hooks/use-send-multiple-message.ts
Fix: Document Previewer is not working #9606
=> Fix: Document Previewer is not working #9606

agent/tools/code_exec.py, sandbox/executor_manager/core/config.py
=> Fix: code executor timeout

rag/llm/chat_model.py
Remove unexpected LLM parameters.
=> Fix: unexpected LLM parameters

api/apps/conversation_app.py, graphrag/general/index.py, rag/prompts/prompts.py
=> Fix: meta data error.

web/src/pages/agent/index.tsx
The VersionDialog component was not receiving the correct context for dropdown handling, causing improper behavior in its interactions.
This PR wraps VersionDialog in DropdownProvider to ensure it gets the proper context and functions as expected.
=> Fix: Wrap VersionDialog in DropdownProvider for proper context

api/apps/sdk/session.py
When create conversation,the prologue hasn't save in conversation.
=> fix: Create conversation sessions will lost prologue

rag/llm/__init__.py, rag/llm/chat_model.py
replace Chat Ollama implementation with LiteLLM.
=> Refa: replace Chat Ollama implementation with LiteLLM

api/db/services/dialog_service.py, api/utils/api_utils.py, graphrag/entity_resolution.py, graphrag/general/community_reports_extractor.py, graphrag/general/index.py, graphrag/utils.py, rag/svr/task_executor.py
=> Fix: meta data filter with AND logic operations.

web/src/components/message-input/next.tsx, web/src/hooks/use-agent-request.ts, web/src/hooks/use-chat-request.ts, web/src/pages/next-chats/chat/chat-box/single-chat-box.tsx, web/src/pages/next-chats/hooks/use-send-chat-message.ts, web/src/pages/next-chats/hooks/use-upload-file.ts
Fix: Delete the uploaded file in the chat input box, the corresponding file ID is not deleted #9701
=> Fix: Delete the uploaded file in the chat input box, the corresponding file ID is not deleted #9701

rag/llm/rerank_model.py
for total_token_count method use if to check first, to improve the performance when we need to handle exception cases
=> Refactor: for total_token_count method use if to check first.

web/src/pages/dataset/dataset/parsing-status-cell.tsx
Fix: Chunk error when re-parsing created file
=> Fix: Chunk error when re-parsing created file #9665

conf/llm_factories.json
Add Zhipu GLM-4.5 model series. #9708.
=> Feat: add Zhipu GLM-4.5 model series

web/src/hooks/auth-hooks.ts, web/src/routes.ts
Fix: Try to fix the issue of not being able to log in through Oauth2 #9601
=> Fix: Try to fix the issue of not being able to log in through Oauth2 #9601

deepdoc/parser/html_parser.py, rag/app/naive.py
=> Feat: Upgrade html parser

rag/svr/task_executor.py
Improve the try logic for upload_to_minio
=> Refactor: Improve the try logic for upload_to_minio

web/src/pages/user-setting/setting-locale/index.tsx
=> add Russian in translation table index.tsx

agent/templates/ecommerce_customer_service_workflow.json, agent/templates/trip_planner.json
=> Fix: agent template error.

api/apps/sdk/session.py, api/db/services/canvas_service.py, docs/references/http_api_reference.md
Unify reference format of agent completion and OpenAI-compatible completion API.
=> Refa: unify reference format of agent completion and OpenAI-compatible completion API

web/src/components/llm-setting-items/next.tsx, web/src/components/message-item/index.less, web/src/interfaces/database/chat.ts, web/src/pages/next-chats/chat/app-settings/chat-basic-settings.tsx, web/src/pages/next-chats/chat/app-settings/chat-prompt-engine.tsx, web/src/pages/next-chats/chat/app-settings/chat-settings.tsx, web/src/pages/next-chats/chat/app-settings/dynamic-variable.tsx, web/src/pages/next-chats/chat/app-settings/use-chat-setting-schema.tsx, web/src/pages/next-chats/chat/sessions.tsx
Fix: Fixed the issue where the thinking mode on the chat page could not be turned off #9789
=> Fix: Fixed the issue where the thinking mode on the chat page could not be turned off #9789

agent/component/llm.py
=> Fix: agent second round issue.

web/src/pages/home/agent-list.tsx, web/src/pages/home/application-card.tsx, web/src/pages/home/chat-list.tsx
Fix: Fixed the issue where the agent and chat cards on the home page could not be deleted #3221
=> Fix: Fixed the issue where the agent and chat cards on the home page could not be deleted #3221

web/src/hooks/route-hook.ts, web/src/pages/next-searches/hooks.ts, web/src/pages/next-searches/index.tsx
Feat: By default, 50 records are displayed per page. #3221
=> Feat: By default, 50 records are displayed per page. #3221

README.md, README_id.md, README_ja.md, README_ko.md, README_pt_br.md, README_tzh.md, README_zh.md
Add jemalloc install instruction for mac
=> Add jemalloc install instruction for mac

web/src/constants/agent.ts, web/src/pages/agent/canvas/index.tsx, web/src/pages/agent/canvas/node/dropdown/next-step-dropdown.tsx, web/src/pages/agent/constant.tsx
Fix: The operator added by clicking the plus sign will overlap with the original operator. #9886
=> Fix: The operator added by clicking the plus sign will overlap with the original operator. #9886

docs/guides/agent/agent_component_reference/code.mdx, docs/guides/agent/agent_component_reference/retrieval.mdx
=> Docs: Updated the Code component reference

api/apps/canvas_app.py, api/db/__init__.py, api/db/db_models.py, api/db/services/canvas_service.py
Add `canvas_category` field for UserCanvas and CanvasTemplate.
=> Feat: add `canvas_category` field for UserCanvas and CanvasTemplate

docs/guides/agent/agent_component_reference/code.mdx
=> Docs: Updated instructions on importing third-party packages to Sandbox

web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agent/form/exesql-form/index.tsx
Feat: Allow users to enter SQL in the SQL operator #9897
=> Feat: Allow users to enter SQL in the SQL operator #9897

api/db/services/dialog_service.py
During the chat, the assistant's response cited documents outside the current knowledge base。
=> During the chat, the assistant's response cited documents outside current chat's kbs

web/.eslintrc.js, web/.storybook/preview.ts, web/src/stories/avatar-upload.stories.ts, web/src/stories/ragflow-avatar.stories.ts, web/src/stories/ragflow-form.stories.tsx, web/src/stories/ragflow-pagination.stories.ts, web/src/stories/skeleton-card.stories.ts
Feat: Display AvatarUpload and RAGFlowAvatar in Storybook #9914
=> Feat: Display AvatarUpload and RAGFlowAvatar in Storybook #9914

.github/workflows/tests.yml
Fix the issue in ci.
[ci err](https://github.com/infiniflow/ragflow/actions/runs/17452439789/job/49559702590?pr=9894)
```
Container ragflow-redis  Error response from daemon: Conflict. The container name "/ragflow-redis" is already in use by container "b6cbde4d186ffba701f6e2a85f37e1d053d7197adb2938547f1df08cfcadf355". You have to remove (or rename) that container to be able to reuse that name.
Error response from daemon: Conflict. The container name "/ragflow-redis" is already in use by container "b6cbde4d186ffba701f6e2a85f37e1d053d7197adb2938547f1df08cfcadf355". You have to remove (or rename) that container to be able to reuse that name.
Error: Process …
```
=> before docker-compose up, first down it,and cleans.

deepdoc/parser/excel_parser.py
=> fix xss in excel_parser

rag/nlp/term_weight.py
Use re compile for the weight method
=> Refactor: Use re compile for weight method

web/src/hooks/use-agent-request.ts, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/form/agent-form/use-build-prompt-options.ts, web/src/pages/agent/form/components/prompt-editor/index.tsx, web/src/pages/agent/form/components/prompt-editor/variable-node.tsx, web/src/pages/agent/form/components/prompt-editor/variable-on-change-plugin.tsx, web/src/pages/agent/form/components/prompt-editor/variable-picker-plugin.tsx, web/src/services/agent-service.ts, web/src/utils/api.ts
Feat: Allow users to select prompt word templates in agent operators. #9935
=> Feat: Allow users to select prompt word templates in agent operators. #9935

web/src/components/ui/message.ts, web/src/hooks/file-manager-hooks.ts, web/src/hooks/login-hooks.ts, web/src/hooks/use-document-request.ts, web/src/hooks/use-file-request.ts, web/src/hooks/user-setting-hooks.tsx, web/src/pages/agent/form-sheet/next.tsx, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/hooks/use-calculate-sheet-right.ts, web/src/pages/agent/log-sheet/index.tsx
Feat: Use sonner to replace the requested prompt message component #3221
=> Feat: Use sonner to replace the requested prompt message component #3221

rag/llm/chat_model.py
The total token was incorrectly accumulated when using the OpenAI-API-Compatible api.
=> Fix miscalculated token count

api/apps/sdk/dify_retrieval.py, api/apps/sdk/doc.py, api/db/services/dialog_service.py
=> Refa: import issue.

conf/llm_factories.json
=> add model: qwen3-max-preview

agent/component/llm.py, api/utils/api_utils.py
=> Fix: re sub error.

web/src/interfaces/request/knowledge.ts, web/src/pages/dataset/testing/testing-form.tsx
Fix: Issue of ineffective weight adjustment for retrieval_test API-related functions #9854
=> Fix: Issue of ineffective weight adjustment for retrieval_test API-related functions #9854

web/src/components/llm-setting-items/next.tsx, web/src/interfaces/database/agent.ts, web/src/pages/agent/canvas/edge/index.tsx, web/src/pages/agent/share/index.tsx, web/src/pages/next-search/search-setting-aisummery-config.tsx
Fix: Highlight the edges after running #9538
=> Fix: Highlight the edges after running #9538

web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/agent/form/agent-form/use-build-prompt-options.ts, web/src/pages/agent/utils.ts, web/src/pages/agents/agent-card.tsx
Feat: The prompt words "plan" are displayed only when the agent operator has sub-agent operators or sub-tool operators. . #10000
=> Feat: The prompt words "plan" are displayed only when the agent operator has sub-agent operators or sub-tool operators. #10000

docs/guides/agent/agent_component_reference/agent.mdx
=> Docs: v0.20.5 - Added Framework prompt block documentation for the Agent component

web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agent/form/agent-form/index.tsx, web/src/pages/next-chats/chat/app-settings/dynamic-variable.tsx, web/src/pages/next-chats/hooks/use-rename-chat.ts
Feat: Translate the maxRounds field of the chat settings #3221
=> Feat: Translate the maxRounds field of the chat settings #3221

rag/prompts/next_step.md, rag/prompts/prompts.py
=> Fix: typo.

docs/release_notes.md
=> Docs: Added v0.20.5 release notes.

rag/flow/parser/parser.py, rag/flow/tests/dsl_examples/general_pdf_all.json
=> Feat: dataflow supports markdown

web/src/components/ragflow-form.tsx, web/src/components/ui/dialog.tsx, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agents/agent-templates.tsx, web/src/pages/agents/create-agent-dialog.tsx, web/src/pages/agents/create-agent-form.tsx, web/src/pages/agents/index.tsx
Feat: Add type card to create agent dialog #9869
=> Feat: Add type card to create agent dialog #9869

web/src/components/llm-setting-items/llm-form-field.tsx, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/data-flow/constant.tsx, web/src/pages/data-flow/form/parser-form/common-form-fields.tsx, web/src/pages/data-flow/form/parser-form/email-form-fields.tsx, web/src/pages/data-flow/form/parser-form/index.tsx, web/src/pages/data-flow/form/parser-form/pdf-form-fields.tsx
Feat: Translate the fields of the parsing operator #9869
=> Feat: Translate the fields of the parsing operator #9869

deepdoc/vision/ocr.py, deepdoc/vision/recognizer.py
judge not empty before delete session.
=> Fix: judge not empty before delete

web/src/pages/data-flow/canvas/index.tsx, web/src/pages/data-flow/constant.tsx, web/src/pages/data-flow/form-sheet/form-config-map.tsx, web/src/pages/data-flow/form/hierarchical-merger-form/index.tsx, web/src/pages/data-flow/form/splitter-form/index.tsx
=> Feat: Add splitter form #9869

agent/tools/code_exec.py, api/apps/HEALTHCHECK_TESTING.md, api/apps/system_app.py, api/utils/health.py, rag/app/naive.py
Support image recognition with image links in markdown files, solved issue: #8755
Fixed log info error in code_exec, solved issue: #10064
=> Support image recognition for url links in Markdown file, fix log error in code_exec

api/apps/kb_app.py, api/db/services/document_service.py
Add support for KB document basic info
=> Feat: add support for KB document basic info

web/src/components/ragflow-form.tsx, web/src/hooks/use-agent-request.ts, web/src/pages/agent/debug-content/uploader.tsx, web/src/pages/agent/run-sheet/index.tsx, web/src/pages/data-flow/form/hierarchical-merger-form/index.tsx, web/src/pages/data-flow/hooks/use-run-dataflow.ts, web/src/pages/data-flow/hooks/use-save-graph.ts, web/src/pages/data-flow/run-sheet/index.tsx, web/src/pages/data-flow/run-sheet/uploader.tsx
Feat: Upload files on the data flow page #9869
=> Feat: Upload files on the data flow page #9869

rag/llm/__init__.py, rag/llm/chat_model.py
Migrate OpenAI-compatible chats to LiteLLM.
=> Feat: migrate OpenAI-compatible chats to LiteLLM

intergrations/firecrawl/INSTALLATION.md, intergrations/firecrawl/README.md, intergrations/firecrawl/__init__.py, intergrations/firecrawl/example_usage.py, intergrations/firecrawl/firecrawl_config.py, intergrations/firecrawl/firecrawl_connector.py, intergrations/firecrawl/firecrawl_processor.py, intergrations/firecrawl/firecrawl_ui.py, intergrations/firecrawl/integration.py, intergrations/firecrawl/ragflow_integration.py, intergrations/firecrawl/requirements.txt
=> Add Firecrawl integration for RAGFlow

api/apps/sdk/files.py
Add file convert to document API just like file2document_app.py
=> Feat: Add file convert to document API just like file2document_app.py

api/db/services/file_service.py, api/utils/file_utils.py, pyproject.toml, rag/app/email.py, rag/flow/parser/parser.py, rag/flow/tests/dsl_examples/general_pdf_all.json, uv.lock
- Dataflow support email.
- Fix old email parser.
- Add new depends to parse msg file.
=> Feat: parse email

chat_demo/index.html, chat_demo/widget_demo.html, web/src/components/embed-dialog/index.tsx, web/src/components/floating-chat-widget.tsx, web/src/pages/next-chats/widget/index.tsx, web/src/routes.ts
Add a chat widget. I'll probably need some assistance to get this ready for merge!
=> Chat Widget

web/src/components/delimiter-form-field.tsx, web/src/pages/data-flow/constant.tsx, web/src/pages/data-flow/form/hierarchical-merger-form/index.tsx, web/src/pages/data-flow/log-sheet/dataflow-timeline.tsx, web/src/pages/data-flow/log-sheet/index.tsx, web/src/pages/data-flow/utils.ts
Feat: Add suffix field to all operators #9869
=> Feat: Add suffix field to all operators #9869

rag/llm/chat_model.py, rag/llm/embedding_model.py, rag/llm/rerank_model.py, rag/utils/__init__.py
use the same implement for total token count from res
=> Refactor: use the same implement for total token count from res

web/src/pages/data-flow/hooks/use-download-output.ts, web/src/pages/data-flow/log-sheet/dataflow-timeline.tsx, web/src/pages/data-flow/log-sheet/index.tsx
Feat: Exporting the results of data flow tests #9869
=> Feat: Exporting the results of data flow tests #9869

rag/llm/chat_model.py
https://github.com/infiniflow/ragflow/issues/10235
=> Fix:max_tokens must be at least 1, got -950, BadRequestError

web/src/locales/config.ts
=> Fix: Russian language config.ts

conf/llm_factories.json
=> add Qwen models

api/apps/kb_app.py, api/db/services/document_service.py, api/db/services/pipeline_operation_log_service.py, api/db/services/task_service.py, api/utils/api_utils.py, rag/svr/task_executor.py
=> Refa: fake doc ID.

agent/component/agent_with_tools.py, agent/component/base.py, agent/component/invoke.py, agent/component/llm.py, agent/component/message.py, agent/component/switch.py, agent/tools/code_exec.py, agent/tools/exesql.py, api/apps/canvas_app.py, pyproject.toml, rag/flow/base.py, uv.lock, web/src/pages/agent/options.ts, web/src/pages/data-flow/options.ts, web/src/pages/flow/constant.tsx
issue：#5617
change：add IBM DB2 support in ExeSQL
=> feat: add IBM DB2 support

web/src/less/mixins.less, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agents/hooks/use-create-agent.ts, web/src/pages/agents/index.tsx, web/src/pages/data-flow/constant.tsx, web/src/pages/data-flow/hooks/use-run-dataflow.ts, web/src/pages/data-flow/index.tsx, web/src/pages/data-flow/utils.ts
Feat: Bring the parser operator when creating a new data flow #9869
=> Feat: Bring the parser operator when creating a new data flow #9869

api/apps/user_app.py
https://github.com/infiniflow/ragflow/issues/10293
=> Fix:After setting user's is_active to 0, the user can still log in to RAGFlow.

agent/tools/exesql.py, pyproject.toml, uv.lock
issue： 
#10326
change：
remove ibm-db dependency and refactor import order
=> fix: remove ibm-db dependency and refactor import order

web/src/pages/add-knowledge/components/knowledge-graph/index.tsx, web/src/pages/add-knowledge/components/knowledge-graph/use-delete-graph.ts, web/src/pages/dataset/knowledge-graph/index.tsx, web/src/pages/dataset/knowledge-graph/use-delete-graph.ts
Fix: The dataset uses the new id to obtain the knowledge graph #10333
=> Fix: The dataset uses the new id to obtain the knowledge graph #10333

web/src/components/data-pipeline-select/index.tsx, web/src/constants/agent.ts, web/src/hooks/use-agent-request.ts, web/src/hooks/use-knowledge-request.ts, web/src/interfaces/database/agent.ts, web/src/pages/agent/constant.tsx, web/src/pages/agents/agent-card.tsx, web/src/pages/agents/hooks/use-create-agent.ts, web/src/pages/agents/hooks/use-selelct-filters.ts, web/src/pages/agents/index.tsx, web/src/pages/datasets/use-select-owners.ts, web/src/services/agent-service.ts, web/src/utils/api.ts, web/src/utils/dataset-util.ts, web/src/utils/list-filter-util.ts
Feat: Filter the agent list by owner and category #9869
=> Feat: Filter the agent list by owner and category #9869

web/src/hooks/use-agent-request.ts, web/src/locales/en.ts, web/src/pages/agent/log-sheet/workflow-timeline.tsx, web/src/pages/data-flow/form/tokenizer-form/index.tsx, web/src/pages/data-flow/hooks/use-cancel-dataflow.ts, web/src/pages/data-flow/hooks/use-fetch-log.ts, web/src/pages/data-flow/index.tsx, web/src/pages/data-flow/log-sheet/dataflow-timeline.tsx, web/src/pages/data-flow/log-sheet/index.tsx
Feat: Displays the loading status of the data flow log #9869
=> Feat: Displays the loading status of the data flow log #9869

api/apps/file_app.py
Fix unexpected operation of file management.
=> Fix: unexpected operation of file management

rag/llm/chat_model.py, web/src/locales/de.ts, web/src/locales/en.ts, web/src/locales/es.ts, web/src/locales/fr.ts, web/src/locales/id.ts, web/src/locales/ja.ts, web/src/locales/pt-br.ts, web/src/locales/ru.ts, web/src/locales/zh-traditional.ts, web/src/locales/zh.ts, web/src/pages/user-setting/setting-model/api-key-modal/index.tsx
Add support for international Dashscope service. #10340
=> Feat: add support for international Dashscope service

api/apps/canvas_app.py, api/apps/kb_app.py, api/db/services/pipeline_operation_log_service.py, deepdoc/parser/pdf_parser.py, rag/flow/extractor/extractor.py, rag/flow/parser/parser.py, rag/flow/splitter/splitter.py, rag/llm/embedding_model.py, rag/svr/task_executor.py
=> Fix: debug PDF positions..

conf/llm_factories.json
Add support for LongCat-Flash-Thinking and Claude Sonnet 4.5.
=> Feat: add support for LongCat-Flash-Thinking and Claude Sonnet 4.5

agent/component/agent_with_tools.py
=> Fix: reset tools in/out-put.

rag/flow/parser/parser.py
=> Fix: input

web/src/hooks/use-chunk-request.ts, web/src/locales/en.ts, web/src/locales/zh.ts, web/src/pages/agents/create-agent-dialog.tsx, web/src/pages/agents/create-agent-form.tsx, web/src/pages/agents/name-form-field.tsx, web/src/pages/data-flow/context.ts, web/src/pages/data-flow/hooks/use-run-dataflow.ts, web/src/pages/data-flow/index.tsx, web/src/pages/data-flow/log-sheet/index.tsx, web/src/pages/dataflow-result/components/document-preview/hooks.ts, web/src/pages/dataflow-result/constant.ts, web/src/pages/dataflow-result/hooks.ts, web/src/pages/dataflow-result/index.tsx, web/src/pages/dataflow-result/interface.ts, web/src/utils/api.ts
Feat: View data flow test results #9869
=> Feat: View data flow test results #9869

docs/develop/mcp/launch_mcp_server.md
=> Doc: Fixed a typo

.github/workflows/release.yml, .github/workflows/tests.yml
=> Fix MY_GITHUB_TOKEN
